### ISSUE TITLE
Time coord dtype problem

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#1036]
When a time coord whose units' calendar is not one of "gregorian" or "standard" is converted the dtype of the coord's points is forced to `float64`. This is evidenced below:

``` python
>>> print cubes
0: air_temperature / (K)               (time: 5)
1: air_temperature / (K)               (time: 5)
>>> print repr(cubes[1].coord('time').units)
Unit('hours since 1970-01-02 00:00:00', calendar='360_day')
>>> print cubes[1].coord('time').points.dtype
float32
>>> iris.util.unify_time_units(cubes)
>>> print repr(cubes[1].coord('time').units)
Unit('hours since 1970-01-01 00:00:00', calendar='360_day')
>>> print cubes[1].coord('time').points.dtype
float64
```

In converting the time unit of `cubes[1]` to be the same as that of `cubes[0]` using `iris.util.unify_time_units` the dtype of the coord's points is being forced to `float64`. The direct impact of this is that these two cubes, which are otherwise compatible for concatenation, can not be concatenated on account of this differing dtype.

**Comment by rcomer** [comment]
Looks like this has been fixed at some point.  With Iris2.4, if I do
```python
tcoord = iris.coords.DimCoord(np.arange(5, dtype=np.float32), standard_name='time', units=cf_units.Unit('days since 1970-01-01', calendar='360_day'))
print(tcoord.points.dtype)
tcoord.convert_units(cf_units.Unit('days since 1971-01-01', calendar='360_day'))
print(tcoord.points.dtype)
```

I get

```
float32
float32
```
