### ISSUE TITLE
Feature request: reading little-endian pp files in Iris

### ISSUE THREAD

**Issue by theabro** [SciTools/iris#1165]
Iris 1.6.1 can read UM fieldsfiles, but when these are converted to pp format using ff2pp on a little endian machine (ARCHER) Iris has the following error:

ValueError: PP file ['/scratch/nla27/xjgpya.pyt9c10.pp'] contains little-endian data, please convert to big-endian with command line utility "bigend".

Is it possible to allow Iris to read little-endian files?

**Comment by marqh** [comment]
closed (finally) by #1965
