### ISSUE TITLE
ENH: make time interpolation work on datetime objects

### ISSUE THREAD

**Issue by andreas-h** [SciTools/iris#1174]
currently, when performing interpolation (at least via iris.analysis.interpolation.linear), the interpolation works on the _points_ of the coords, not on the actual datetime objects.  this is a source of confusion for the user, and makes things complicated and ugly when dealing with cubes from different origin.  So I propose to have the interpolation routines handle the date2num conversion when interpolating on a time axis and sample_points are composed of datetime objects.

**Comment by rcomer** [comment]
Looks like this was implemented at #1234.
