### ISSUE TITLE
saving cube to netcdf doesn't preserve circular longitudes

### ISSUE THREAD

**Issue by andreas-h** [SciTools/iris#1181]
When saving a cube with a circular `x` coordinate to netCDF4, the `x` coordinate will not be circular after a save/load cycle:

```
In [5]: cube_circular.coord(axis="x").circular
Out[5]: True

In [6]: iris.save(cube_circular, "test.nc")

In [7]: cube_loaded = iris.load("test.nc")[0]

In [8]: cube_loaded.coord(axis="x").circular
Out[8]: False

In [10]: iris.__version__
Out[10]: '1.6.1'
```

**Comment by cpelley** [comment]
> I presume you already know that 'circular' is only possible when the unit is modular ?

This occurs for me with coordinates where the units have modulus also:
http://nbviewer.ipython.org/gist/cpelley/4d2d5ae39a52ad8ab1ff

**Comment by PAGWatson** [comment]
I just ran into this problem (in Iris 1.9.2). It happens for me even when the coordinate in question (longitude) has circular bounds. Is it still being looked at? Is it not possible for iris.save to look at the coordinate's circular attribute and set the attribute in the NetCDF file appropriately, without needing to look at the points or bounds values?
