### ISSUE TITLE
Add tests for ugrid integration

### ISSUE THREAD

**Issue by benjwadams** [SciTools/iris#1232]
Add some tests for NetCDF files implementing ugrid conventions.  I will add a PR with a couple test cases once ugrid compliant NetCDF file is present in the iris test data.

**Comment by rcomer** [comment]
Is this closed by #4058 and #4074?

**Comment by trexfeathers** [comment]
>Is this closed by #4058 and #4074?

@rcomer in theory yes, however that functionality is still in a feature branch, so I wouldn't consider the matter actually closed until [`mesh-data-model`](https://github.com/SciTools/iris/tree/mesh-data-model) is merged to `master`.

**Comment by rcomer** [comment]
So is this closed by #4313? 😇
