### ISSUE TITLE
Iris has turned very slow for reading 4D data from ocean datasets

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#1287]
I'm not sure when it happened, but Iris has turned very slow for reading 4D data from ocean model datasets.   I used to run a demo showing Iris loading sea surface temperature from a variety of models to illustrate the power C Conventions in Iris,  but now it takes so long I can no longer run it.   I'm not sure what version this happened at.  If anybody has an older version, perhaps they can try this out:
```
url='http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his_Best/ESPRESSO_Real-Time_v2_History_Best_Available_best.ncd'
var='sea_water_potential_temperature'
cube = iris.load_cube(url,var)
```

This used to take about 10 seconds, but now it takes 120 seconds or more.    If you do just a load_raw, it takes a few seconds.  

And using netcdf4, I can load a layer of a 4D variable (e.g. temperature) along with lon and lat coordinates and plot it up in about 3 seconds.  

Here's a Wakari bundle as proof:  https://www.wakari.io/sharing/bundle/rsignell/iris_test_v1.7.1

My best guess is that Iris is loading a bunch of coordinate data -- perhaps the z coordinates for all time steps?    
And it would make sense that ocean models with more time steps are either timing out or giving memory issues, as in  #1280.   

I really hope this issue can be resolved soon -- it has effectively broken many of our workflows.

**Comment by rsignell-usgs** [comment]
This got closed automatically (but mistakenly) by a conda-recipes PR, so reopening here.
@ocefpaf, it seems if perhaps you can help address the small questions from the Iris team at
https://github.com/SciTools/iris/pull/1502
perhaps we can get this closed for real!  
I'd love to be using a "genuine" Iris build instead of our hacked version!

**Comment by ajdawson** [comment]
Did #1560 fix this issue?

**Comment by rsignell-usgs** [comment]
Yes, I'd say the issue is fixed.  It no longer takes several minutes: the times in 1.8.1 are now again what they were in 1.6.1. 

iris.load_cube:  14.6 seconds
iris.load_raw: 11.5 seconds
netcdf4_read: 3.9 seconds

See this notebook:

http://nbviewer.ipython.org/gist/rsignell-usgs/39facf7957ed65d663aa

**Comment by ajdawson** [comment]
Thanks @rsignell-usgs, I'll close this issue now then.
