### ISSUE TITLE
Cube with unit Celsius multiplied by scalar has incorrect units

### ISSUE THREAD

**Issue by ajdawson** [SciTools/iris#1327]
As reported on [Google Groups](https://groups.google.com/forum/#!topic/scitools-iris/rj65m9Nac6k).

Consider the following example code:

``` python
from iris.cube import Cube

cube = Cube(25., standard_name='air_temperature', units='Celsius')
print cube
print cube.data
result = cube * 1.
print result
print result.data
```

which gives the following result:

```
air_temperature / (Celsius)         (scalar cube)
25.0
unknown / (kelvin)                  (scalar cube)
25.0
```

The units have changed to kelvin from Celsius, but the data values did not change, leading to an inconsistency. This should either be 25 Celsius or 298.15 kelvin I think, assuming we are working with absolutes. I know that assumption may not always be true, but in this use case it is.

I can't tell if this is a bug in udunits2 or something wrong with the way iris is using udunits2, or something else.

**Comment by nhsavage** [comment]
I can reproduce this with Iris. 2.2.0 although the example with iris.unit has to be rewritten:

>>> import cf_units
>>> u = cf_units.Unit('celsius')
>>> u*1
Unit('K')

**Comment by rcomer** [comment]
This has just come up again, reported on Met Office Yammer.  With latest `cf-units` we have:

```python
In [1]: import cf_units

In [2]: cf_units.__version__
Out[2]: '3.0.1.post0'

In [3]: u = cf_units.Unit('Celsius')

In [4]: u * 1
Out[4]: Unit('K')
```

Both @esc24 above and @ajdawson on the Google Group suggested that the problem could be in `udunits2`.  Does anyone have the time and skills to check whether that is the case?  I found on their issue tracker, which seems related but is specifically about powers: https://github.com/Unidata/UDUNITS-2/issues/82.

**Comment by trexfeathers** [comment]
This is controversial throughout the community, and certainly isn't something that can/should be solved within Iris. If we were to 'fix' anywhere within SciTools, we would be diverging from UDUNITS and CF conventions, which would be a big decision.

So I'm closing. If anyone in the future is concerned about this, please raise on cf-units.
