### ISSUE TITLE
single cube slice not working on Windows 64bit

### ISSUE THREAD

**Issue by ColinTalbert** [SciTools/iris#1339]
I get an error when I try to slice a cube with a single value.  

I found that if I change https://github.com/SciTools/iris/blob/master/lib/iris/_constraints.py#L367 
from:
result[dim] = where_true[0]  
to
result[dim] = int(where_true[0])
then everything starts working.

without this change where_true[0] resolves to a numpy.int64 which must get caught is some type check latter on.

Thanks,
Colin

**Comment by rsignell-usgs** [comment]
Here's @ocefpaf example of the same bug raising it's ugly head (from closed duplicate issue #1568):
http://nbviewer.ipython.org/gist/ocefpaf/e27255a5a8c5a1d6415c

**Comment by ocefpaf** [comment]
Just for future reference.  I updated that gist and it shows our workaround the bug.  This one shows the bug:

http://nbviewer.ipython.org/gist/ocefpaf/01e1a94710c01cfd3f52

**Comment by ocefpaf** [comment]
I knew I saw this [before](https://github.com/SciTools/biggus/pull/65#issuecomment-39713879)!  Thanks to @rhattersley I learned that (sometimes):

```python
key = np.int64(0)
isinstance(key, int)
False
```

and the solution is,
```python
isinstance(key, (int, np.integer))
True
```

PR #1571 should fix this.
