### ISSUE TITLE
Unexpected datetimes obtained when producing monthly mean climatology data 

### ISSUE THREAD

**Issue by rockdoc** [SciTools/iris#1422]
Hi

I'm producing a cube of monthly mean climatology data from a multi-year time-series of monthly mean data values (ozone, as it happens). My sample netcdf dataset spans the 20 years 1990-01-16 to 2010-12-16. In reality the actual dataset will likely span >100 years.

I'm using `iris.coord_categorisation` to add a month number auxiliary coordinate. And then I'm calling `cube.aggregated_by` to aggregate across that coordinate, thus producing a resultant cube which contains 12 time coords, one for each month of the year. (The other dimensions of my data are latitude and height, but for the purposes of this issue I guess they could equally be some other axes.)

Now, if the time span of my sample data covers an _odd_ number of years, then the dates written to the aggregated cube are as expected, e.g. YYYY-01-16, YYYY-02-16, …, YYYY-12-16, where YYYY is the mid-year of the input time-series.

But if the time span of my sample data covers an _even_ number of years, then the dates written to the aggregated cube are rotated by 6 months, e.g. YYYY-07-16, YYYY-08-16, etc.  Assuming that the cube data was written in this same order, I was sorting it to get it into the normal CF climatology order of Jan to Dec.  However, it would appear that the data is in fact in the desired Jan-Dec order, but that the rotated datetimes are incorrect.

An examination of the time bounds (in the aggregated cube) would seem to corroborate this observation as they too run from Jan to Dec (although the upper bounds are not quite right, they should be one month later than the lower bound).

I have put together a small bit of test code (see [this gist](https://gist.github.com/rockdoc/e3a55de71e94377c7f1e)) which hopefully illustrates the scenario described above.

Phil

**Comment by larsbarring** [comment]
I just ran into the same behaviour as described in the initial post (luckily I remembered reading this issue). Now, with the improved handling of climatologies in Iris, it would be good to bounce up this and make Iris produce a climatological time coordinate, as per CF section 7.4.
