### ISSUE TITLE
Loading of Cell Methods for Climatological statistics.

### ISSUE THREAD

**Issue by esc24** [SciTools/iris#1438]
According to the cf spec, climatologies (data that has been aggregated over a period of time over a series of years) can be represented using time coordinates and cell methods (see http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#climatological-statistics for details and examples). Putting aside the handling of the time coordinate, and focussing purely on the cell methods, this might involve something like:

```
time: minimum within years
time: mean over years
```

At the moment these cell methods can be added to a cube (see #1436) and saved. However, on load the `within years` and the `over years` bits are discarded. This is due to the behaviour of the regular expression parsing in https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L799-L807

(pyparsing might be useful here)

I'd like to be able to load cf-netcf files with these cell methods and retain the details that are currently lost.

**Comment by esc24** [comment]
@rockdoc - I just put up a PR to do this. It's suffering from the same travis issue as your PR, but allows you to load more complex cell methods like `time: mean over years`.

**Comment by rockdoc** [comment]
@esc24 - thanks, I'll try this with some of my sample files.

**Comment by rcomer** [comment]
Looks like this was addressed at #1513, and the associated issue for climatological bounds was addressed more recently at  #3395.
