### ISSUE TITLE
problem with travis?

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#1509]
I'm getting this weird message about not being able to clone the repository to test it
https://travis-ci.org/niallrobinson/iris/builds/45550198

**Comment by pelson** [comment]
Looks like a travis problem. have you tried re-starting the build?

**Comment by niallrobinson** [comment]
I've restarted it about 5 times now, over that last three days, but it failed again just now.

**Comment by niallrobinson** [comment]
sorry - wrong button

**Comment by rhattersley** [comment]
Looks like you've created your branch from an old version ... this was fixed in #1113.

**Comment by niallrobinson** [comment]
wow - that is old...thanks
