### ISSUE TITLE
BLD: Bad ref to dependencies

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1514]
Currently the only manner in which to determine which dependencies to build to get **master** up and running is by looking at the conda build recipes.  The **INSTALL** should be updated to reflect the version requirements of packages.

As a result of https://github.com/SciTools/iris/pull/1424/files, iris master actually requires a version of biggus greater than 0.7 (it requires a version which includes the commit makes API changes to biggus.save https://github.com/SciTools/biggus/commit/89ced476848882cb84616b7d9c2ce2959d7ae294).

I propose that we make a new tag release of biggus and then update the INSTALL to reflect this requirement.

Biggus issue: https://github.com/SciTools/biggus/issues/114

**Comment by rhattersley** [comment]
> The INSTALL should be updated to reflect the version requirements of packages.

:+1: Ideally that should have been done in #1424.

> I propose that we make a new tag release of biggus and then update the INSTALL to reflect this requirement.

With biggus we are in the lucky position of having control of its release cycle, so this can easily be made to work. For other dependencies we're going to have to be very careful of constraining the Iris release cycle!
