### ISSUE TITLE
MAINT: Natural Earth data

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1518]
I propose we create an abstraction layer between where the Natural Earth data lives and iris, by way of redirection through our http://scitools.org.uk.

This way, if the natural earth site yet again changes the location of its data, we can at least fix it for our users by simply updating our website to point to the correct data.  Our users would then no longer need to wait for a speedy release of iris.

**Comment by rhattersley** [comment]
Thanks for the proposal, but I'm :-1: for a couple of main reasons:
 1. Obtaining a rapid fix for Natural Earth is mostly an issue for our continuous integration - not for normal users who will normally already have the relevant data cached.
 2. Natural Earth no longer intend to provide ZIP files in github so we wouldn't have an easy backup source anyway.

**Comment by cpelley** [comment]
> Obtaining a rapid fix for Natural Earth is mostly an issue for our continuous integration - not for normal users who will normally already have the relevant data cached.

Fair enough, thanks for sharing your insights.
