### ISSUE TITLE
Fast-FF loading handles realisation wrong

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#1525]
Results from loading data with ensemble numbers are different from standard.

As internal bug report (cf. internal issue EPM-636) :

Compared results for fast- and normal-loaded data.

> "Dimensions issue in new fast structured FF loading"
> 
> ```
> >> import iris
> >> from iris.experimental.fieldsfile import load as ff_load
> >> load_cubes = iris.load('akzmgo.da67bl0')
> >> fast_cubes = ff_load('akzmgo.da67bl0')
> >> load_cube = load_cubes[65]
> >> fast_cube = fast_cubes[18]
> >> 
> >> print load_cube
> baroclinic_northward_sea_water_velocity / (cm s-1) (depth: 40; latitude: 216; longitude: 362)
>      Dimension coordinates:
>           depth                                          x             -               -
>           latitude                                       -             x               -
>           longitude                                      -             -               x
>      Scalar coordinates:
>           model_level_number: 0
>           time: 3667-11-21 00:00:00
>      Attributes:
>           STASH: m02s00i122
>           source: Data from Met Office Unified Model
>           um_version: 6.6
> 
> >> 
> >> print fast_cube
> baroclinic_northward_sea_water_velocity / (cm s-1) (depth: 40; latitude: 216; longitude: 362)
>      Dimension coordinates:
>           depth                                          x             -               -
>           latitude                                       -             x               -
>           longitude                                      -             -               x
>      Auxiliary coordinates:
>           model_level_number                             x             -               -
>      Scalar coordinates:
>           time: 3667-11-21 00:00:00
>      Attributes:
>           STASH: m02s00i122
>           source: Data from Met Office Unified Model
>           um_version: 6.6
> >> 
> >> print fast_cube.coord('model_level_number')
> AuxCoord(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), standard_name='model_level_number', units=Unit('1'))
> ```

**The key problem is that the fast-loaded 'ensemble' coordinate is an auxiliary, not scalar as it 'ought' to be.**

**Comment by pp-mo** [comment]
In essence, the problem with this is that an 'ensemble number' is not treated like the other scalar metadata values.
**N.B. this also applies to 'pseudo-level'**

Initially, ensemble (and pseudo-level)  were to be included in the 'vectorisable' coordinates, but this was not implemented.  However, they are not handled like the other 'scalar' ones, either. 
See code in https://github.com/SciTools/iris/blob/master/lib/iris/experimental/fieldsfile.py : 
 * [normal scalar coordinates](https://github.com/SciTools/iris/blob/master/lib/iris/experimental/fieldsfile.py#L169)
 * [ensemble values](https://github.com/SciTools/iris/blob/master/lib/iris/experimental/fieldsfile.py#L229)
 * [pseudo-levels](https://github.com/SciTools/iris/blob/master/lib/iris/experimental/fieldsfile.py#L233)

Potentially, all we need to do is move the translation code calls for 'ensemble' + 'pseudo-level' to just after the other-scalars call, and before the vectorised parts.  Note though that this will *not* enable these to appear as dimensions -- they are "assumed" to be all-the-same (like other non-vectorisable ones).

**Comment by pelson** [comment]
@pp-mo - is this a quick win, or do we need to move this out of the 2.0.0 release?

**Comment by pp-mo** [comment]
> @pelson is this a quick win, or do we need to move this out of the 2.0.0 release?

Let's put this off. It's tricky code to grasp, and at least 2 people need time to get heads round it.
