### ISSUE TITLE
Load and merge may be highly inefficient with lots of small files

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#1526]
A problem arises when a lot of small-ish files on a common grid are to be loaded:  Memory can get filled by all the coordinate arrays, although they are mostly just endless identical copies.

For example, single field ORCA2 files can often have more coordinate data than phenomenon data (as the 2D lat+lon coordinates are typically double floats, and the data may only be single).
(N.B. large testdata examples attached to internal issue : EPM-691)

This could be avoided by implementing deferred data loading for coordinate arrays, and making the merge process more memory-aware (i.e. you don't need to load all coordinate arrays simultaneously to see that they are all equal).

**Comment by rockdoc** [comment]
@pp-mo 

Just to lend some weight to this particular issue, a while back I was working with some high-resolution (25m) raster data over the UK. For convenience, the data was supplied as 13 files, each with shape (x=28000, y=4000), and of size c. 108 MB. The projected X and Y coordinates together occupied a fairly lean 130 KB of storage per file.

I did some back-of-an-envelope calculations and worked out that to add 64-bit, 2D latitude and longitude coordinates and cell bounds to each file (in an effort to generate CF-compliant data) would increase the size of each file by c. 9 GB (yes, that's gigabytes). Over the full dataset that's a coordinate storage overhead of almost 120 GB.

Unsurprisingly we elected not to go down that particular route!

We're finding that we're working with this kind of data with increasing frequency. So, yes, I'd agree that we need to find smarter, more efficient ways of handling this kind of coordinate (meta)data.

**Comment by pelson** [comment]
**Update: ** In Iris 2 we have lazy Aux data, which covers the case for the dense multi-dimensional coordinates. To my knowledge, we have not updated merge to preserve the lazy data though.

Would be interested to see a specific usecase that we want to address, as the lazy coords is a really big step forwards, and as a result one might consider this issue obsolete.
