### ISSUE TITLE
Consider making `iris.unit` submodule its own module.

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/iris#1563]
Hello!  This is more a request than an issue.

There are some projects that do not need all of iris, but would be greatly improved with some of iris parts.  one of them is `iris.unit`.  There is some ongoing discussion on using it [here](https://github.com/ioos/compliance-checker/issues/81), but having iris as a dependency is not an option for most projects.

**Comment by pelson** [comment]
:+1: - I'd find this a most welcome improvement.
Is this something you'd be interested in taking a look at @ocefpaf?

Thanks for the heads up!

**Comment by rhattersley** [comment]
> some of iris parts. one of them is iris.unit

Out of interest, what are the other parts?

**Comment by ocefpaf** [comment]
> Is this something you'd be interested in taking a look at @ocefpaf?

Yes.  I will try (and cry for help if I crash and burn).  Wait for something next week...

@rhattersley I know that the "cf interpretation" that iris does is of great interest to people like @rsignell-usgs.

On the top of my head I think that splitting the `fileformats` (netcdf, pp, grib, etc) would make  iris installation easier and lighter for people using just one format.  (I only use netcdf for example.)
Something like what [pydap](https://pypi.python.org/pypi?%3Aaction=search&term=pydap&submit=search) does for the handlers and responses.

(Although, iris installation became much easier lately that this is not a big issue anymore.)

**Comment by pelson** [comment]
> On the top of my head I think that splitting the fileformats

Agreed. On my radar in the short-ish term is the Unified Model type files such as Fieldsfiles and PP.

>  Wait for something next week...

Cool. Keep us in the loop, I'd be happy to help if you hit any blockers.

**Comment by ocefpaf** [comment]
Thanks to iris high quality code it was easy to hack (and slash) the code and get a units module.  I have a prototype working:

http://nbviewer.ipython.org/gist/ocefpaf/ba386349d035edd15dcf

I still need to:
- import all the tests from iris
- prepare an iris PR that removes all `units` code and imports this instead

But before I do that I have a few questions.  Should I create a GitHub repository using my account with this prototype?  Is that OK with iris license?

(Once this is done, and if there is interested, we'll move it to Scitools of course.)

PS: @rhattersley While working on this I found out about `symbols.py`, and that is another good candidate to be a stand-alone module :wink:

**Comment by QuLogic** [comment]
> Should I create a GitHub repository using my account with this prototype? Is that OK with iris license?

The ToS of GitHub allow you to fork and do edits at will. But license-wise, that is the point of the (L)GPL. The code (that was obtained under the terms of the LGPL) will _always_ be free.

**Comment by ocefpaf** [comment]
It is not really a fork in the GitHub sense of "forks."  Although I could fork, rename, and remove everything non-units from the repository, but that sounds like an overkill.

I will start a repository with the same licenses and later on, if this takes flight, you'll decide where it should live.

**Comment by ocefpaf** [comment]
Done: https://github.com/ocefpaf/units

**Comment by ChrisBarker-NOAA** [comment]
@ocefpaf : very cool!

Pardon my ignorance, but will this work all on its own -- i.e. not requiring udnitspy (though probably requiring udunits itself)

**Comment by QuLogic** [comment]
Just as an aside, there already appears to be a [Python package named "units"](https://pypi.python.org/pypi/units), so you may wish to choose an alternate name. While that package is quite old, it might be a bit confusing.

**Comment by ocefpaf** [comment]
@QuLogic yes, i just realized that :disappointed: Suggestions? `iris_units`?

**Comment by ocefpaf** [comment]
> Pardon my ignorance, but will this work all on its own -- i.e. not requiring udnitspy (though probably requiring udunits itself)

Correct @ChrisBarker-NOAA.  It is substitute for `udnitspy` :smiley: , but still dependent on `udunits2` :unamused: 

See: http://nbviewer.ipython.org/gist/ocefpaf/60ecac928612f5ae8fed

**Comment by ChrisBarker-NOAA** [comment]
Maybe "cf_units" it's all about CF, but theoretically only used by Iris, rather than the other way around. But I don't care, really. Good to have "units" in the name, so people will find it.

@ocefpaf : maybe udinits2 could be built-in, rather then kept as a separate package. It would make it harder to build, but then it would be only one package to manage.

-CHB

**Comment by pelson** [comment]
We did this. Yay to cf-units! https://github.com/SciTools/cf_units/.
