### ISSUE TITLE
slice a cube on Windows 64 

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/iris#1568]
I found a weird bug when trying to slice cubes on Windows 64 machine.  If I use numpy's int64 it fails, but any other int it works:

http://nbviewer.ipython.org/gist/ocefpaf/e27255a5a8c5a1d6415c

Not sure if the bug is on iris, numpy or the conda package.  Just wanted to report so others do not waste a whole afternoon on it like I did :sob: 

@rsignell-usgs  I am adding a work around in our package to circumvent this.

**Comment by ajdawson** [comment]
Related to #1339 perhaps, or even the same?

**Comment by ocefpaf** [comment]
Yep, the same.  Closing this to avoid duplication.
