### ISSUE TITLE
Allow users to set `missing_value` attribute

### ISSUE THREAD

**Issue by ajdawson** [SciTools/iris#1588]
Currently users are prevented from setting an attribute named `missing_value` on their cubes. However, since Iris will never automatically create one, this means there is no way to save a cube to a netCDF file and include a `missing_value` attribute.

For indicating missing values iris will always save to netCDF with a `_FillValue` attribute. The CF conventions recommend that if both `_FillValue` and `missing_value` attributes are used then they should have the same value (sensible), but do not prohibit them from being different. Therefore I propose that `missing_value` becomes an attribute that is allowed to be set on cubes, since the effects of doing so do not conflict with CF conventions.

**Comment by ajdawson** [comment]
Relevant discussion on google groups: https://groups.google.com/forum/?fromgroups=#!topic/scitools-iris/_9aFHObEJOE

**Comment by ajdawson** [comment]
It may be enough to simply remove `'missing_value' from this tuple: https://github.com/SciTools/iris/blob/master/lib/iris/_cube_coord_common.py#L32

**Comment by djkirkham** [comment]
@ajdawson I don't think so, that would make is a global attribute in the file in a lot of cases - see my comment in the google groups discussion.

**Comment by zklaus** [comment]
Since we have the same problem in a project here, I compounded the suggestion from @ajdawson with a change to iris.fileformats.netcdf to address @djkirkham 's concern and created pr #2866 . What do you think?
