### ISSUE TITLE
Cube method and method argument deprecations

### ISSUE THREAD

**Issue by ajdawson** [SciTools/iris#1592]
These items should be considered for deletion in 1.8. The following are marked as deprecated in 1.6:
- `name` and `coord` keywords of `Cube.coords`
- `name` and `coord` keywords of `Cube.coord`
- method `Cube.add_history`

In addition:
- method `Cube.assert_valid` appears to have been deprecated since the initial commit so should probably be deleted now

Finally, there is https://github.com/SciTools/iris/blob/master/lib/iris/cube.py#L1035. If anyone knows anything about this please comment here (git blame is suggesting @niallrobinson added the warning in January 2014, the comment above was added by @esc24).

**Comment by niallrobinson** [comment]
If I remember correctly, these are depreciated because I replaced them with a "catch-both" name_or_coord type argument i.e. you could pass either a coord name or a coord instace to the same argument. There was some reason why this was a good idea at the time.

**Comment by pelson** [comment]
I'd love to simplify/reduce the whole set of kwargs to ``coords`` and replace them with a function (to be clear, I'd keep the common kwargs). That is definitely in scope for v2.0 IMHO.

**Comment by rhattersley** [comment]
Thanks for the link ... should we just change this issue to the v1.9 milestone?

**Comment by rhattersley** [comment]
> Thanks for the link ... should we just change this issue to the v1.9 milestone?

Sorry ... brain-fail. It needs to stay as v2.0 because actually removing stuff is a backwards incompatible change. :expressionless:

**Comment by ajdawson** [comment]
Closed by #1595
