### ISSUE TITLE
%matplotlib magic breaks iris import

### ISSUE THREAD

**Issue by andreas-h** [SciTools/iris#1605]
I'm running into a strange issue when using the `%matplotlib` magic.  My system is as follows:

```
In [1]: import os; os.environ.get("UDUNITS2_XML_PATH")

In [2]: import matplotlib; matplotlib.__version__
Out[2]: '1.4.3'

In [3]: import iris; iris.__version__
Out[3]: '1.8.0-dev'

In [4]: import IPython; IPython.__version__
Out[4]: '3.0.0'
```

When I first import Iris and then use the `%matplotlib` magic, everything's fine:

```
In [1]: import iris

In [2]: %matplotlib 
Using matplotlib backend: Qt4Agg

In [3]: 
```

However, when I try to import Iris _after_ using the `%matplotlib` magic, I get an error regarding the `UDUNITS2_XML_PATH`:

```
In [1]: %matplotlib
Using matplotlib backend: Qt4Agg

In [2]: import iris
[...]
OSError: [UT_PARSE] Failed to open UDUNITS-2 XML unit database 
```

Any clue what's going on here?

**Comment by pelson** [comment]
Are your environment variables being preserved?

**Comment by andreas-h** [comment]
In [1]: import os; os.environ.get("UDUNITS2_XML_PATH")
    
    In [2]: import iris
    
    In [3]: import os; os.environ.get("UDUNITS2_XML_PATH")
    
    In [4]: %matplotlib
    Using matplotlib backend: Qt4Agg

but

    In [1]: import os; os.environ.get("UDUNITS2_XML_PATH")
    
    In [2]: %matplotlib
    Using matplotlib backend: Qt4Agg
    
    In [3]: import os; os.environ.get("UDUNITS2_XML_PATH")
    
    In [4]: import iris
    [...]
    OSError: [UT_PARSE] Failed to open UDUNITS-2 XML unit database

**Comment by pelson** [comment]
@takluyver - who knows most about the ``%matplotlib`` magic? There are several technologies in play here, so I'm wondering if something is fiddling with LD_LIBRARY_PATH etc.

**Comment by takluyver** [comment]
I don't think we mess around with anything like that. You can see the code run by `%matplotlib` in these places:

https://github.com/ipython/ipython/blob/rel-3.0.0/IPython/core/interactiveshell.py#L3064
https://github.com/ipython/ipython/blob/rel-3.0.0/IPython/core/pylabtools.py
