### ISSUE TITLE
Test failures with matplotlib 1.4.3

### ISSUE THREAD

**Issue by QuLogic** [SciTools/iris#1661]
Many image plots are failing with matplotlib 1.4.3. I'm not sure what's going on; it seems like everything within the axes is shifted a little bit. Not every test is affected, so here is a list of the problems. Hopefully one of you can spot some commonality between them. I have also included one example of the plots where it's pretty clear that things are shifted a bit. Most of the others are similar.
- test_COP_maps.TestCOPMaps.test_cop_maps.0.png
- test_analysis.TestRotatedPole.test_all.0.png
- test_global_map.TestGlobalMap.test_global_map.0.png
  ![index](https://cloud.githubusercontent.com/assets/302469/7551927/468ebc8c-f669-11e4-9224-a521d35277a3.png)
- test_grib_load.TestGribLoad.test_ij_directions.0.png
- test_grib_load.TestGribLoad.test_y_fastest.0.png
- test_lagged_ensemble.TestLaggedEnsemble.test_lagged_ensemble.0.png
- test_mapping.TestBoundedCube.test_grid.0.png
- test_mapping.TestBoundedCube.test_pcolormesh.0.png
- test_mapping.TestLimitedAreaCube.test_grid.0.png
- test_mapping.TestLimitedAreaCube.test_outline.0.png
- test_mapping.TestLimitedAreaCube.test_scatter.0.png
- test_mapping.TestLowLevel.test_keywords.0.png
- test_mapping.TestLowLevel.test_params.0.png
- test_plot.TestHybridHeight.test_orography.0.png
- test_plot.TestMissingCS.test_missing_cs.0.png
- test_plot.TestPlotCoordinatesGiven.test_tx.4.png
- test_plot.TestPlotCoordinatesGiven.test_yx.5.png
- test_projections_and_annotations.TestProjectionsAndAnnotations.test_projections_and_annotations.0.png (I believe this one is a [matplotlib bug](https://github.com/matplotlib/matplotlib/issues/4139))
- test_quickplot.TestLabels.test_alignment.0.png
- test_quickplot.TestQuickplotCoordinatesGiven.test_tx.4.png
- test_quickplot.TestQuickplotCoordinatesGiven.test_yx.5.png
- test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid.test_circular_subset.0.png
- test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid.test_global_data_increase_res.0.png
- test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid.test_global_data_reduce_res.0.png
- test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid.test_global_data_same_res.0.png
- test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid.test_global_data_subset.0.png
- test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid.test_non_circular_subset.0.png
- test_regridding.TestGlobalSubsample.test_linear.0.png
- test_regridding.TestGlobalSubsample.test_nearest.0.png
- test_rotated_pole_mapping.TestRotatedPoleMapping.test_rotated_pole_mapping.2.png

**Comment by pelson** [comment]
Thanks @QuLogic - these are generally changes that all need eyeballing and accepting. It isn't pretty, but every version change of mpl since v1.1 has resulted in image changes (typically pixel diffs).

**Comment by QuLogic** [comment]
Odd, [we](http://www.obspy.org/) have not seen such large changes going from 1.3.1 to 1.4.3. There's usually text that wobbles around and something about axes corners, but the basemap doesn't shift like that.

**Comment by pelson** [comment]
Closing due to the version now being obsolete. We are likely to jump for mpl v2.x in the iris 2.x series (but not for 2.0.0).
