### ISSUE TITLE
log-linear interpolation

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#1694]
Hi Iris - I'm back!

I'm trying to interpolate from log spaced model levels to linearly spaced ones, which is described [here](http://scitools.org.uk/iris/docs/latest/userguide/interpolation_and_regridding.html). However, as far as I can see, this isn't correct - half way between a level at 1m and 100m should be 10m but the linear interpolation described would return 50.5m. (Let me know if I've got that wrong)

We should have a log-linear interpolator that people can choose when interpolating across log spaced levels.

Before I start hacking code - can I canvas people for the best way of doing it? I could add another class to `analysis.__init__.py` or I could potentially add a log key to the `EXTRAPOLATION_MODES` global. Any feedback would be appreciated - I'd like to get this done ASAP so I can use it!

**Comment by niallrobinson** [comment]
on second thought - its probably easier to get round this by adding an aux coord of log_height and doing a linear interp on that? In which case, I guess the example needs correcting.

**Comment by ajdawson** [comment]
Are you referring to this example: http://scitools.org.uk/iris/docs/latest/userguide/interpolation_and_regridding.html#interpolating-non-horizontal-coordinates?

If so, I think this does interpolation from one set of altitudes (in metres) to another specified set of altitudes (in metres), via the existing `altitude` coordinate. I'm not sure there is any issue with this is there?

**Comment by ajdawson** [comment]
Ah wait, do you mean the other coordinates on the cube get interpolated incorrectly? I was only thinking about the altitude-based result, and not considering what happens to the sigma and hybrid height coordinates.

**Comment by niallrobinson** [comment]
no - I mean that the interpolation from altitude to altitude is incorrect. It's doing a linear interpolation on a field which is log spaced. However, the log of the log spaced altitude coordinate is linearly spaced, and therefore suitable for linear interpolation...let me know if I've got that wrong! I'm 95% sure that's right though.

**Comment by rhattersley** [comment]
1. The linear interpolator does just that ... linear interpolation. It's up to the user to choose whether it is appropriate.
2. :+1: for having a "log-linear" interpolator.

**Comment by rhattersley** [comment]
> the interpolation from altitude to altitude is incorrect

I don't see how you can use the word "incorrect" to describe an approximation to a sampled phenomenon - it's just not a binary yes/no issue. It might not be a particularly strong approximation in general, but in that specific example I can't see that log-linear would be much of an improvement. The sample data are highly non-linear and highly non-log-linear.

**Comment by niallrobinson** [comment]
I hadn't realised that the altitude wasn't strictly log spaced - I eyeballed it and assumed - sorry, my fault. However, altitude is traditionally log spaced, and its looks closer to log spaced than linear (with the exception of the lowers few levels). But I guess it probably doesn't make that much difference in the end. Would it still be a useful feature to have, even if this example doesn't strictly need it. 
![figure_1](https://cloud.githubusercontent.com/assets/2979205/9004016/94fe7a32-376a-11e5-886c-19545561ed44.png)

**Comment by rhattersley** [comment]
(I'm not sure it matters, but I wasn't trying to make a case that the altitudes aren't log spaced. I was trying to point out that the air potential temperature wasn't linearly proportional to log-altitude.)

I'm still :+1: for having a log-linear interpolator.
