### ISSUE TITLE
Problems with newer versions of mock

### ISSUE THREAD

**Issue by ajdawson** [SciTools/iris#1724]
It looks like there is an issue with the newer 1.1 versions of mock released recently. The test suite will report internal mock failures because it can't find certain attributes/methods of the mock objects. See https://travis-ci.org/SciTools/iris/jobs/71156177 for an example.

Given impending Python3 compatibility (where there is a `unittest.mock` module) perhaps we should think about fixing this properly instead of holding back the version of mock we use on Travis CI.

**Comment by QuLogic** [comment]
Might be a problem in the backport testing-cabal/mock#283, or possibly 3.5. I don't see any issues with 3.4.

**Comment by QuLogic** [comment]
So it might be the case that these are typos and are in fact not asserting anything.

**Comment by ajdawson** [comment]
Well, that isn't good!

**Comment by ajdawson** [comment]
@QuLogic - If you understand this issue properly, would you mind wiriting a description of what exactly is happening, why the tests previously (appeared?) to pass and what happens with the new version. I think I don't quite understand properly (but I gather we have to make some changes)

**Comment by QuLogic** [comment]
It stems from [this patch](https://bugs.python.org/issue21238) being backported wherein calls to `assert*` that are not defined will raise an error. Previously, they were treated like any other `MagicMock` property and simply mocked into existence at that point.

**Comment by ajdawson** [comment]
OK, thanks for the link. So we need to replace the uses of the following with the appropriate *real* method call:

* `assertCalledOnceWith`
* `assert_called`
* `assert_has_call`

**Comment by ajdawson** [comment]
* `assertCalledOnceWith` -> `assert_called_once_with`
* `assert_has_call` -> `assert_has_calls`?
* `assert_called` -> ?

**Comment by QuLogic** [comment]
I think `assert_called` should be `assert_called_with` or `assert_called_once_with`, since it seems like all of them have some parameters.

**Comment by rhattersley** [comment]
Are either of you (@QuLogic/@ajdawson) working on this? If not, I'll see if I can get someone (possibly, me) to take a look.

**Comment by ajdawson** [comment]
No I'm not.

**Comment by QuLogic** [comment]
Not at this moment.

**Comment by rhattersley** [comment]
OK - thanks chaps.
