### ISSUE TITLE
Broken link in http://scitools.org.uk/iris/docs/latest/iris/iris/fileformats/netcdf.html

### ISSUE THREAD

**Issue by jprb-walton** [SciTools/iris#1743]
On this page (and probably elsewhere in iris documentation), there's a link to 

http://www.cdc.noaa.gov/cdc/conventions/cdc_netcdf_standard.shtml

which is broken.  It seems to have been moved to

http://www.esrl.noaa.gov/psd/data/gridded/conventions/cdc_netcdf_standard.shtml

**Comment by pelson** [comment]
Thanks Jeremy.

@scmc72 - this would be a nice simple PR to put together. Looks like you need to change:
 * https://github.com/SciTools/iris/blob/00a168f5260c7ac765e0e307655d88cc218b2799/lib/iris/fileformats/netcdf.py#L717
 * https://github.com/SciTools/iris/blob/00a168f5260c7ac765e0e307655d88cc218b2799/lib/iris/fileformats/netcdf.py#L717

**Comment by scmc72** [comment]
Just submitted a pull request for the netcdf.py file... 

Those links are the same Phil - did you mean to link a different one?

**Comment by pelson** [comment]
Woops. Yes I did. Richard pointed to the correct location in #1749.
Thanks for raising this @jprb-walton - the link will be fixed in the next release's documentation.
