### ISSUE TITLE
Preserve lazy data in cube math operations

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#1744]
Cube mathematics operations do not preserve lazy data on either the resultant cube or any input cubes to the mathematics :cry: 

To demonstrate this:

``` python
>>> a1b = iris.load_cube(iris.sample_data_path('A1B_north_america.nc'))
>>> a1b.has_lazy_data()
True
>>> e1 = iris.load_cube(iris.sample_data_path('E1_north_america.nc'))
>>> e1.has_lazy_data()
True
>>> scenario_difference = a1b - e1
>>> print scenario_difference.has_lazy_data()
False
>>> print a1b.has_lazy_data()
False
>>> print e1.has_lazy_data()
False
```

**Comment by pelson** [comment]
With the recent versions of biggus, this is a nice small, self contained problem. @scmc72 might be interested in taking this on (ping @bjlittle).

**Comment by pelson** [comment]
A big amount of this got done. Use of biggus and then subsequently dask really helped with its implementation.
