### ISSUE TITLE
ENH: Iris area weighted regrid

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1752]
Currently, iris masks those grid cells which lie beyond the source extend (even if they only partly go beyond the extent).  This means that the area weighted regridder is actually not conservative.
I propose being able to treat these cells in the same way as missing data (i.e. accounting for partial coverage - whatever is within the src extent).

This is a simple change within `iris.experimental.regrid._within_bounds`.
See the following diff:

``` Python
-    return (((lower <= max_bound) * (lower >= min_bound)) *
+    return (((lower <= max_bound) * (lower >= min_bound)) |
             ((upper <= max_bound) * (upper >= min_bound)))
```

In my opinion, modifying the behaviour of area weighted regrid stops this information loss and maintains conservative regridding while the existing behaviour looses information.  A user wanting the existing behaviour can achieve the same thing as an additional stage after regrid.  For this reason, I see no reason in supporting both behaviours via the regridding API, we should simply switch to the new behaviour.

Based on this, are people happy for me to make the requested alteration and put up a PR?

**Comment by cpelley** [comment]
I think you will be interested in this @jkettleb as it will likely effect cases where the source grid is the same size or smaller than the target grid.

**Comment by rhattersley** [comment]
> I see no reason in supporting both behaviours via the regridding API, we should simply switch to the new behaviour.

Thanks to #1178 the `AreaWeighted` regridder has been in the public API since 1.7.0, so any changes to the behaviour need to be carefully managed. Particularly as your proposed change is not a bug fix (which you've reflected in the "ENH" prefix you chose for your issue).

In other words, we *would* need to support both behaviours.

**Comment by cpelley** [comment]
> Thanks to #1178 the AreaWeighted regridder has been in the public API since 1.7.0, so any changes to the behaviour need to be carefully managed. Particularly as your proposed change is not a bug fix (which you've reflected in the "ENH" prefix you chose for your issue).

>In other words, we would need to support both behaviours.

Thank you @rhattersley for your comments.  I agree, I think the current behaviour though not technically conservative is likely a common approach (for example ESMF) and so not a bug.
Sounds like you are happy for the API to be extended.

How about via an `extrapolation_mode` keyword argument just like with the Linear approach?

```Python
iris.analysis.AreaWeighted(mdtol=1, extrapolation_mode='mask')
```

i.e.
```
‘mask’ - Target cells which like beyond the source extent will be masked.

'extrapolate' - Target cells which lie beyond the source extent will take into account partial coverage 
within the extent.
```

**Comment by rhattersley** [comment]
> How about via an extrapolation_mode keyword argument

That sounds like a sensible approach - thank you. :+1:

If any other interested parties agree, then we can move on to discussion of the details of the keyword name, allowed keyword values, corresponding behaviours, and what we do about the default needs to be clarified.

**Comment by cpelley** [comment]
> ...keyword name, allowed keyword values, corresponding behaviours, ...

So long as the name is specific enough then it should not preclude alternative future behavioural switches (i.e. my `extrapolate` name is probably too non-specific??).

> ...and what we do about the default needs to be clarified.

Do you mean, whether the default behaviour gets changed to an alternative approach?  Or do you mean to simply document the current behaviour in better detail?

Thanks for your interest in this @rhattersley

**Comment by rhattersley** [comment]
> my `extrapolate` name is probably too non-specific??

From the perspective of, "What mode of operation do you want when outside the source extent?" it seems fine. Another perspective would be, "What fraction of out-of-source-extent contribution do you tolerate before you mask the result?". Similarly to the existing `mdtol`, this could use a keyword like `extrap_tol`.

> Do you mean, whether the default behaviour gets changed to an alternative approach? Or do you mean to simply document the current behaviour in better detail?

I mean whether we plan to change the default.

**Comment by cpelley** [comment]
> Another perspective would be, "What fraction of out-of-source-extent contribution do you tolerate before you mask the result?". Similarly to the existing mdtol, this could use a keyword like extrap_tol.

Ah OK, yes that's more general (I like your idea).  Would you be in favour of constraining acceptable values to 0 and 1 for now?  This would limit the required number of initial code changes, especially when it comes to testing :)  We could then later extend this to the more general case?

**Comment by cpelley** [comment]
> I mean whether we plan to change the default.

Hmm, I think we will find it difficult to get a definitive answer to this, especially as people's expectations might be based on the type of data their used to dealing with (global vs regional) or perhaps the type of tools their used to using (ESMF vs IDL).
I can try post something on the google groups as a first step?

**Comment by cpelley** [comment]
Hi @rhattersley, this has become lower on our priority list due to how two datasets get merged (essentially overriding the edges).
However, I thought it worth enquiring what you felt was the best way to get to the bottom of this API.  Happy to go down the google groups route and timebox it for feedback perhaps?

**Comment by cpelley** [comment]
Is there any interest at all in this enhancement? :)

**Comment by cpelley** [comment]
I'm going to propose putting up a PR which provides the first stage of the proposed extrapolation control to area weighted regridding in iris.  I'm hopping to get this into the v1.9.0 release if possible

This would not provide control via `extrap_tol` but does not preclude it.  I would advise that we add this capability in a future PR.

```Python
`iris.analysis.AreaWeighted(mdtol=1, extrapolation_mode='mask')`
```

Where initial extrapolation modes include:
 1. Mask
 2. NAN

In a future PR, I would then propose extending the capability further by the addition of yet another keyword argument (`extrap_tol`).  The effect of this first PR will not change any behaviour, it simply distinguishes between masked elements and those outside extend via NAN assignment.  In affect, this initial PR would be like assigning an `extrap_tol = 0.0`.

**Comment by dkillick** [comment]
> I'm hopping to get this into the v1.9.0 release if possible

For reference, Iris v1.9.0 is pretty much a done deal - any enhancement in this space won't go into Iris v1.9.x. You would be better off targetting enhancements at master and trying to get them approved for a following release (Iris v1.10 is being planned for early next year).

**Comment by cpelley** [comment]
> For reference, Iris v1.9.0 is pretty much a done deal

Thanks @dkillick.  I see, in that case, we will have to make the changes available to our by wrapping the capability of the iris AreaWeighted regridder
