### ISSUE TITLE
Indexing of cubes is not clear in documentation

### ISSUE THREAD

**Issue by mo-g** [SciTools/iris#1756]
A user had an interesting issue with slicing a cube loaded from NetCDF.

With a cube of lets say.. 4x5, the user was trying to run:

```
slice = cube[ [0, 2] ]
```

Which would only work if they forced iris to pull the data into a NumPy array beforehand with `cube.data`. Because the cube is loaded into Biggus with an OrthoArrayAdapter, the Biggus array did not support the NumPy fancy indexing they were using. The solution was to use the following:

```
slice = cube[(0, 2), :]
```

I don't think there is clarity in the Iris documentation on exactly what indexing can be used, and in what cases. There is some detail in the Biggus documentation, but this is obviously obfuscated from an Iris user.

Thoughts?

**Comment by pelson** [comment]
Perhaps we can reference the biggus docs in ``Cube.__getitem__``. The complexity is that we don't document ``Cube.__getitem__`` as it is a special method - we should fix that.

**Comment by mo-g** [comment]
So, with Biggus no longer being used - I guess I should test this again!

**Comment by rcomer** [comment]
Under Iris 2.4, this works fine:

```python
fname = iris.sample_data_path('air_temp.pp')
temperature = iris.load_cube(fname)
print(temperature)
sub = temperature[[0,2]]
print(sub)
```
