### ISSUE TITLE
Text formatting loss

### ISSUE THREAD

**Issue by isedwards** [SciTools/iris#176]
Text formatting is lost when Iris plots over an existing figure

```
import matplotlib.pyplot as plt
import iris
import iris.plot as iplt

cube = iris.load_cube(iris.sample_data_path('air_temp.pp'))

plt.subplot(121)
plt.title('Large red title',fontsize=20,color='r')
iplt.contourf(cube)

plt.subplot(122)
iplt.contourf(cube)
plt.title('Large red title',fontsize=20,color='r')

plt.show()
```

**Comment by dkillick** [comment]
You know, in all the time this has been open, I don't think there have been _any_ support requests about this issue.

Also, it has the simplest fix ever: set the title **after** creating the Cartopy geoaxes. That's certainly what I'd tell anyone who came knocking with a support request about this to do...
