### ISSUE TITLE
Backport 8c952371 into v1.8.x and release 1.8.2

### ISSUE THREAD

**Issue by ajdawson** [SciTools/iris#1763]
New versions of netCDF4 have removed `date2num` from the `netcdftime` module. A fix was put onto the Iris master branch, but this is not in a released version yet. I suggest we backport 8c9523715492db7af5bccd31858df47daa611874 into v1.8.x and do a quick release of 1.8.2 to allow iris to be compatible with newer netCDF4 versions.

FYI @shoyer

**Comment by pelson** [comment]
Seems reasonable provided we can keep the scope of v1.8.2 down to a minimum.

**Comment by ajdawson** [comment]
I was imagining the scope of the release being just this commit + a what's new entry describing which bug it fixes.

**Comment by ajdawson** [comment]
There never was a v1.8.2 release. This ticket is now obsolete with v1.9.2 released and v1.10 incoming.
