### ISSUE TITLE
documentation links broken

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#1768]
Going here:
http://scitools.org.uk/iris/docs/latest/examples/General/polar_stereo.html#polar-stereo
and clicking on "source code" leads http://scitools.org.uk/iris/docs/example_code/General/polar_stereo.py, which gives a 404.

**Comment by rhattersley** [comment]
It's not a one-off - tt affects the other examples too. The links to the source code are missing the `latest` component.

The links to the images are also broken.

**Comment by pelson** [comment]
The site is on github under https://github.com/SciTools/scitools.org.uk.
In particular the [polar stereo example is here](https://github.com/SciTools/scitools.org.uk/blob/gh-pages/iris/docs/v1.8.1/examples/General/polar_stereo.html).

The ["source code" link](https://github.com/SciTools/scitools.org.uk/blob/gh-pages/iris/docs/v1.8.1/examples/General/polar_stereo.html#L138) references ``../../../example_code/General/polar_stereo.py`` which is outside of the document root - looks like when being built, Sphinx is referencing code outside of the source tree and not copying over the appropriate content.

Looks like a bit of trial and error with Sphinx will be needed... :disappointed:

**Comment by pelson** [comment]
This should now be fixed.

Thanks @rsignell-usgs
