### ISSUE TITLE
Features in setup.py deprecated

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#1818]
Apparently:

DeprecationWarning: Features are deprecated and will be removed in a future version. See http://bitbucket.org/pypa/setuptools/issues/65.

We use them https://github.com/SciTools/iris/blob/master/setup.py#L213-L226

**Comment by rhattersley** [comment]
Once pp_packing has been removed (in favour of mo_pack) the need for this would go away anyway. A lazy option would be to ignore for now and just throw it all away in Iris 2.0.

**Comment by pelson** [comment]
:+1:

**Comment by pelson** [comment]
Yay to iris 2. We removed this in https://github.com/SciTools/iris/pull/2689/files#diff-2eeaed663bd0d25b7e608891384b7298L213
