### ISSUE TITLE
Issue a warning for loading certain UM files with non-standard LBCODE values

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#1851]
#1535 attempted to address this, but that was sidelined owing to a lack of clarity over what values we are liable to misinterpret.

Following discussion of @dkillick and @pelson with concerned parties, it was decided that this should go into 1.9 if at all possible.

**Comment by pp-mo** [comment]
The scope of this isn't too clear.
There is certainly some disagreement about the exact interpretation of the existing format spec.
It isn't yet clear whether we have enough information to identify which files warrant a warning ?

**Comment by marqh** [comment]
i'm moving this out of the 1.9n milestone; I think a fix for some of this is on master
#1893 

please close this issue if it is no longer needed
