### ISSUE TITLE
Difference between SUM and MEAN treatment of weights

### ISSUE THREAD

**Issue by mo-g** [SciTools/iris#1859]
When using iris.analysis.MEAN, the code calls numpy.ma.average - which normalizes the weights before the operation. When using iris.analysis.SUM, the code uses the private function _sum which doesn't normalize the weights. This means that the functions respond very differently when given normalized or not-normalized weights:

```
weights sum:     100.0
SUM aggregator
orig weights data sum:   180.713
normed weights data sum: 1.80708
MEAN aggregator
orig weights data sum:   0.488625122311
normed weights data sum: 0.488625114254
```

Is this intentional? I'm afraid I don't quite understand the target usage..

**Comment by ajdawson** [comment]
Yes it is intentional. The `SUM` aggregator is designed to be used for things like integration or filtering where the for each weight the magnitude as well as the relative fraction is important.

**Comment by ajdawson** [comment]
See #626 for background.

**Comment by mo-g** [comment]
Thanks AJ, that's very informative.
