### ISSUE TITLE
BUG: Travis continuous integration does not test raster import

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1884]
Gdal is installed as part of the travis build, [see](https://github.com/SciTools/iris/blob/1ba7405ad86e5d8d2ea65b5f9a6510802775045d/minimal-conda-requirements.txt#L24).

However, tests are skipped:

```
test_masked (iris.tests.experimental.test_raster.TestGeoTiffExport) ... SKIP: Test requires 'gdal'.
test_unmasked (iris.tests.experimental.test_raster.TestGeoTiffExport) ... SKIP: Test requires 'gdal'.
```

On closer inspection, gdal fetched through conda has a broken dependency with the hdf shared object version installed via conda:

```
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carwyn/miniconda/envs/ants_env/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/carwyn/miniconda/envs/ants_env/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libhdf5_hl.so.10: cannot open shared object file: No such file or directory
```

**Workaround:**

My own workaround is to simply downgrade to gdal v1.10.1

**Proposed changes:**
1. Utilising specifically gdal v1.10.1 on travis to enable the running of raster import tests.
2. Iris should differentiate between different messages returned by ImportError (i.e. 'No module names <module_name>'  vs other).

**Comment by cpelley** [comment]
Possibly related:

https://github.com/conda/conda/issues/1915

**Comment by ocefpaf** [comment]
@cpelley I have an alternative `gdal 1.11.3` [here](https://github.com/ioos/conda-recipes/tree/master/gdal), if that works I can send that recipe to `conda-recipes-scitools`.

**Comment by cpelley** [comment]
Thanks @ocefpaf, I'll give it a go.

**Comment by pp-mo** [comment]
> Iris should differentiate between different messages returned by ImportError (i.e. 'No module names ' vs other).

:+1: for that.
I think we should simply change : [this code](https://github.com/SciTools/iris/blob/master/lib/iris/tests/__init__.py#L79)
from
```
except ImportError:
    GDAL_AVAILABLE = False
```
to
```
except ImportError as e:
    if e.message.startswith('No module named'):
        GDAL_AVAILABLE = False
    else:
        raise
```

It would be good to do the other skip-tests too.
I want to wait until you have a testable solution to the actual issue here..

**Comment by cpelley** [comment]
> @cpelley I have an alternative gdal 1.11.3 here, if that works I can send that recipe to conda-recipes-scitools.

Tried building with your recipe under the environment that I had a working iris build but to no avail I'm afraid :(

**Comment by cpelley** [comment]
I think the problem with gdal is perhaps that it is built against whichever shared object of hdf is available at that time.  So as conda updates hdf to satisfy dependencies of other packages/upgrades, this breaks dependency with gdal.  Of course I could be wrong...  I have not had the time to experiment yet.

**Comment by cpelley** [comment]
Made redundant by #2952
