### ISSUE TITLE
GRIB derived keys

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#1889]
The GRIB loader uses 

```
gribapi.grib_skip_computed(keys_itr)
```

https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/grib/_message.py#L295

at grib api version 12 this also returned computed keys, which are then used in GDT40
- https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/grib/_load_convert.py#L902
- https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/grib/_load_convert.py#L971

This 'bug' has been fixed, so the code used for GDT40 no longer runs, as the keys are not available

We need to decide whether to relax the constraint on using computed keys or refactor the relevant code to not use them

which approach is preferred?
mark

**Comment by marqh** [comment]
@ajdawson we discussed this issue before, from a slightly different perspective.

Please may you consider and share your views with us?
thank you

**Comment by rhattersley** [comment]
As mentioned in the comments in those two functions, the use of computed keys is a pragmatic compromise. Unless it's a lot of work to cleanly(*1) expose the derived latitude & longitude values the grounds for that compromise aren't substantially altered by the bug fix, so I'd stick with the "relaxed" approach.

*1) I don't think we should just get rid of `grib_skip_computed` - it's still desirable to limit ourselves to coded keys so we don't accidentally start using them. Instead, how about we extend the `_RawGribMessage` & `_GribMessage` classes to add explicit support for derived latitude & longitude values?

**Comment by ajdawson** [comment]
I don't think we should limit ourselves to coded keys blindly, as in cases like the GDT40 translation is it beneficial to take advantage of the relevant computed keys rather than reimplementing a whole lot of code that already exists in gribapi. I'm not opposed to limiting what we can access as a kind of safety measure to prevent using computed keys that are not necessary (or are unwise to use in some way), but let's not make it impossible to use computed keys.

**Comment by pp-mo** [comment]
> I don't think we should limit ourselves to coded keys blindly

IIRC the key reason is that we got burnt in the past by the definitions of computed keys changing (or vanishing) with gribapi version changes, so we took a solemn oath not to use them...
For instance, we  had things change return type at one point : [old issue comment](https://github.com/SciTools/iris/pull/452#discussion_r3954403)
Does that  sound at all  familiar @rhattersley @marqh, or I am out of order ?

**Comment by rhattersley** [comment]
Yes, that's how I remember it too ... although I seem to recall signing a document with blood rather than swearing an oath. :stuck_out_tongue_winking_eye:

**Comment by ajdawson** [comment]
Well, that seems reasonable... until it isn't. I think GDT40 provides a strong motivation to be a little more relaxed about this restriction. My view is that coded keys can be used wherever possible as the first port of call, but if excessive complication is required in order to do so then alternatives may be considered.

**Comment by rhattersley** [comment]
> My view is that coded keys can be used wherever possible as the first port of call, but if excessive complication is required in order to do so then alternatives may be considered.

Yes - that's how I see it too. Hopefully you realised I was joking about the blood thing :wink:.

It's about being pragmatic, e.g. the cost of re-implementing functionality vs. the cost of dealing with changing computed key definitions.

**Comment by ajdawson** [comment]
>Hopefully you realised I was joking about the blood thing

All fancy and modern with your non-blood signed contracts! That's not how we do it in Oxford...

I was replying more to @pp-mo's comment. I'm happy even to say that coded keys are the rule and computed keys the exception, and perhaps we can treat GDT40 as the model for such exceptions, where we clearly document the use of a computed key and outline an exit strategy in case we need to switch to coded keys in future.

**Comment by marqh** [comment]
Based on comments to date, I think it's worthwhile removing the 
gribapi.grib_skip_computed(keys_itr)
call and enforcing the preference for coded keys by convention.

I have done this on:
https://github.com/marqh/iris/pull/8
to illustrate its simplicity and effectiveness.

This doesn't enable us to move to GRIB API 1.14 on its own, but it gets us pretty close:
https://github.com/marqh/iris/pull/8

We could explicitly code up a different path for the special cases that we know about, but it is more work, so I'd like a steer on whether people would accept the simpler approach before trying to code up the more complicated one

many thanks
mark

**Comment by pp-mo** [comment]
> Based on comments to date, I think it's worthwhile removing the
gribapi.grib_skip_computed(keys_itr)

I think in this case we really need to sort out the purpose of _GribMessage and _RawGribMessage and the distinction between them.
It isn't clear (to me!) on a quick glance whether we ever really intended to ring-fence the computed keys approach, and if that was really the *only* reason to define _RawGribMessage as a separate class ?
At present, it seems to replace usage of an *actual* grib message with a property-based interface, and some caching, but there isn't much more in _GribMessage anyway, so I suspect the  distinction  may no be longer needed.

This is already pretty confused as the comments are unhelpful and presumably wrong, in particular ...
```
class _GribMessage(object):
    """
    Lightweight GRIB message wrapper, containing **only** the coded keys and
    data attribute of the input GRIB message.

    """
...
class _RawGribMessage(object):
    """
    Lightweight GRIB message wrapper, containing **only** the coded keys
    of the input GRIB message.

    """
...

```

I don't have time right now to tease all this out, but either something subtle is going on, or that distinction is unnecessary and obsolete (the comments likewise).
I hope a trawl into the history can cast some light.

**Comment by dkillick** [comment]
I think this was completed by #1913. In any case the code to which this refers no longer resides in Iris, so I think we can safely close this issue now.
