### ISSUE TITLE
Importing iris shouldn't result in a subprocess.check_call

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#1899]
https://github.com/SciTools/iris/pull/1266 introduced an automatic check_call to identify the dot executable. Because of our import machinery, this ends up getting done when ```import iris``` is run. Clearly that is not desirable - ideally it should only run when we actually *want* dot to work.

**Comment by pelson** [comment]
Raised in https://groups.google.com/forum/#!topic/scitools-iris/CYOywlwSr6Q

**Comment by rhattersley** [comment]
How about #1900?

**Comment by QuLogic** [comment]
I think there might be a bug there, too; I'm not sure why it's raising `subprocess.CalledProcessError`. Maybe it's calling a different `dot`, or maybe it's too old?

**Comment by QuLogic** [comment]
Oh, I guess from the thread, the `dot` command is available but broken; we should probably catch `subprocess.CalledProcessError` there too.
