### ISSUE TITLE
1.9.2

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#1909]
A number of commits have been merged onto v1.9.x since v1.9.1

https://github.com/SciTools/iris/compare/v1.9.1...v1.9.x

I think this deserves a v1.9.2

I will aim to organise this next week (perhaps Tuesday), with the current commits and an update to the what's new

Please add any other relevant issues to the v1.9.2 milestone so that they get captured

thank you
mark

**Comment by QuLogic** [comment]
The release has been made.
