### ISSUE TITLE
Cube intersection transparency

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1919]
I have a use case where I would like to use intersection to extract the region of a target to regrid which covers the source.  In this case, the target is defined within ~[350-370] but the source is within an extent of [-180, 180].  Obviously the target is entirely within the source, since the source has global coverage, however in this particular case, I don't want intersection to wrap the resulting coordinates.

In the more general case what intersection has done is lost on returning the cube.

I'm going to propose that rather than having a hook which allows the coordinates to be preserved (which can only work for a subset of cases), instead, intersection should have the ability to return a list of 'subsets' objects (corresponding to each specified coordinate extract).

**Comment by cpelley** [comment]
One possible UI:

```Python
x_ext = iris.coords.CoordExtent(source_x, ..., ...)
y_ext = iris.coords.CoordExtent(source_y,  ..., ...)
overlap = source.intersection(x_ext, y_ext, out_subsets=subsets)
```
This follows UI common to numpy functions ([see](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.take.html))

`subsets` is then populated with the subsets determined by intersection which should have length corresponding to the number of coordinates extracted.

**Comment by cpelley** [comment]
@jkettleb you might be interested in this one.

**Comment by pelson** [comment]
@cpelley, maybe a picture would help describe what you mean. I'm not 100% certain we don't already have such a capability in http://scitools.org.uk/iris/docs/latest/iris/iris/analysis/maths.html#iris.analysis.maths.intersection_of_cubes.

**Comment by cpelley** [comment]
Thanks for your comment @pelson.  We must cater for different coordinate systems cases as well as same coordinate system cases so I think that takes `intersection_of_cubes` out.  Sometimes the resulting extracted cube needs to retain its original range whilst other cases are more flexible.  This is because we generate data on specific grids.  Altering the definition of this grid (even if its simply a wrap), could cause reconfiguration to fall over.

I'll post some details on my two unittests tomorrow.

P.S. I have made a workaround for our project which re-wraps the coordinates of the extracted cube to match the original range (when that's possible).  Not pretty but it means this is not time pressing.

Cheers.

**Comment by cpelley** [comment]
Going to close this for now.
