### ISSUE TITLE
BUG: Anonymous concatenation bug

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1938]
See the following gist:
https://gist.github.com/cpelley/cfadb311350935a2d312

We can see that concatenation without the anonymous dimension works as expected, however, when we try to concatenate with the addition of an anonymous dimension (with auxiliary coordinate present), an exception is raised:

```Python
...
/home/carwyn/git/iris/lib/iris/cube.pyc in _add_unique_dim_coord(self, dim_coord, data_dim)
   1025             raise ValueError(msg.format(data_dim, self.shape[data_dim],
   1026                                         dim_coord.name(),
-> 1027                                         len(dim_coord.points)))
   1028 
   1029         self._dim_coords_and_dims.append([dim_coord, int(data_dim)])

ValueError: Unequal lengths. Cube dimension 0 => 2; coord 'latitude' => 6.
```

**Comment by marqh** [comment]
I don't think this is a bug.

the change in #1915 enabled the concatenation of cubes which have anonymous dimensions, as long as those dimensions are not being concatenated over.

Concatenating by combining coordinates describing an anonymous dimensions is not supported, this is a harder problem to solve.

`Concatenate can work across anonymous dimensions, but not along them`

If the docs in #1915 don't make this clear, I would be happy to adjust them, to make this point explicit.

The capability you are describing, of concatenating along an anonymous dimension, is a feature request. Some extending logic is required to handle this effectively within concatenate

**Comment by cpelley** [comment]
Thanks for your clarification and interest @marqh.

> If the docs in #1915 don't make this clear, I would be happy to adjust them, to make this point explicit.

No that's OK, makes sense now that you mention it.

Thanks @marqh, I'll close this for now.
