### ISSUE TITLE
Problem loading cube from this UGRID dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#1940]
@ocefpaf updated our UGRID water level interoperability demo to use Iris:
https://github.com/pyugrid/pyugrid/blob/master/notebook_examples/COMT_example.ipynb
and although 2 of the 3 ocean model datasets load okay (see cells [9] and [10]), the 3rd is not loading as a cube, giving:
```
ConstraintMismatchError: no cubes found
```
This duplicates the problem:
```
url = 'http://comt.sura.org/thredds/dodsC/data/comt_1_archive/inundation_tropical/USF_FVCOM/Hurricane_Rita_2D_final_run_without_waves'
variable = 'sea_surface_height_above_geoid'
cube = iris.load_cube(url, variable)
```
yeilding
```
---------------------------------------------------------------------------
ConstraintMismatchError                   Traceback (most recent call last)
<ipython-input-1-8ec6bcb2d48e> in <module>()
      2 url = 'http://comt.sura.org/thredds/dodsC/data/comt_1_archive/inundation_tropical/USF_FVCOM/Hurricane_Rita_2D_final_run_without_waves'
      3 variable = 'sea_surface_height_above_geoid'
----> 4 cube = iris.load_cube(url, variable)

C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\IOOS\lib\site-packages\iris\__init__.pyc in load_cube(uris, constraint, callback)
    341         raise iris.exceptions.ConstraintMismatchError(str(e))
    342     except ValueError:
--> 343         raise iris.exceptions.ConstraintMismatchError('no cubes found')
    344 
    345     return cube

ConstraintMismatchError: no cubes found
```
A quick glance at the OPeNDAP Data Form: 
http://comt.sura.org/thredds/dodsC/data/comt_1_archive/inundation_tropical/USF_FVCOM/Hurricane_Rita_2D_final_run_without_waves.html
doesn't show anything obvious problem:   there is a variable `zeta` that has `standard_name='sea_surface_height_above_geoid` and everything else looks in order. 

Any idea what the problem is here?

**Comment by ajdawson** [comment]
This works if you set `iris.FUTURE.netcdf_promote = True`. There is a warning issued when you load the data set, but your notebook will hide them because you filter them out.

**Comment by ocefpaf** [comment]
I thought that was the default behavior in iris 1.9.0!  Sorry for the rookie mistake...  I am re-running them to confirm.

BTW we suppress warnings because of the verbosity level of iris when parsing netCDF files.  It is really too much! In some cases this renders the notebooks unreadable.

(Maybe that should be in another issue. Some sort of verbosity level setting. Don't really know how to address that.)

**Comment by ajdawson** [comment]
I think suppressing warnings is fine for prodcution stuff and examples in particular, but they sure help when debugging issues like this.

**Comment by ocefpaf** [comment]
> but they sure help when debugging issues like this.

Definitely!  I was just wondering if there are verbosity levels to python warnings. For example: non-compliant units warnings should be a "level 2," while the more important warnings, like the one I missed, should be a "level 1."

Anyway. I don't think that is too important I am digressing here... Thanks for the save! And feel free to close this issue.

**Comment by rsignell-usgs** [comment]
Okay, closing here.
