### ISSUE TITLE
404 error for mailing list in developer's guide

### ISSUE THREAD

**Issue by BHFock** [SciTools/iris#1954]
The mailing list in the [developer guide](http://scitools.org.uk/iris/docs/latest/developers_guide/gitwash/patching.html) points to an missing link.

**Comment by pelson** [comment]
@corinnebosley - you might be interested in taking a quick look at fixing this here: https://github.com/SciTools/iris/blob/master/docs/iris/src/developers_guide/gitwash/patching.rst

For the already built documentation, maybe just search and replace in https://github.com/scitools/scitools.org.uk...

**Comment by BHFock** [comment]
In order to correct this bug in the developer guide I would need to know if this mailing list exists and if so where.

**Comment by pelson** [comment]
@BHFock - https://groups.google.com/forum/#!forum/scitools-iris

**Comment by ajdawson** [comment]
This has been fixed in #1957 for future releases, but will still be incorrect in the live version.

**Comment by pelson** [comment]
https://github.com/SciTools/scitools.org.uk/pull/122
