### ISSUE TITLE
quickplot (x,y) orientation

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#202]
_quickplot_ does not choose a sensible orientation when plotting _("x","y")_ cubes.
It plots _y_ along the bottom. We have to specify the coords manually.

I believe it should automatically choose the obvious orientation.
I have found this to be an issue when plotting fields from several different NIMROD sources.

**Update:**
_If neither of the dimension coordinates have a recognisable axis (e.g. via standard_name) then  the trailing dimension would be horizontal for 2D cubes._

**Comment by rcomer** [comment]
#2899 claimed to have closed this.
