### ISSUE TITLE
BUG: Unexpected concatenate failure

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2021]
```Python
>>> import iris
>>> import iris.tests.stock
>>> cube = iris.tests.stock.lat_lon_cube()[:, 1:]
>>> cube.coord(axis='x').points = [360., 350., 10.]
>>> iris.cube.CubeList([cube[:, 2:], cube[:, :2]]).concatenate_cube()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../git/iris/lib/iris/cube.py", line 487, in concatenate_cube
    res = iris._concatenate.concatenate(self, error_on_mismatch=True)
  File ".../git/iris/lib/iris/_concatenate.py", line 291, in concatenate
    concatenated_cubes.append(proto_cube.concatenate())
  File ".../git/iris/lib/iris/_concatenate.py", line 653, in concatenate
    dim_coords_and_dims = self._build_dim_coordinates()
  File ".../git/iris/lib/iris/_concatenate.py", line 851, in _build_dim_coordinates
    dim_coord = iris.coords.DimCoord(points, bounds=bounds, **kwargs)
  File ".../git/iris/lib/iris/coords.py", line 1390, in __init__
    coord_system=coord_system)
  File ".../git/iris/lib/iris/coords.py", line 445, in __init__
    self.points = points
  File ".../cpelley/git/iris/lib/iris/coords.py", line 1464, in points
    raise ValueError('The points array must be strictly monotonic.')
ValueError: The points array must be strictly monotonic.
>>> iris.cube.CubeList([cube[:, :2], cube[:, 2:]]).concatenate_cube()
<iris 'Cube' of unknown / (unknown) (latitude: 3; longitude: 3)>
```

As you can see, concatenation succeeds when the cubelist has a different order.

**Comment by ajdawson** [comment]
Is this so unexpected? With the first order the longitudes are [[10], [360, 350]] which do not join (in the order specified) to form a monotonic coordinate. In the second case the longitudes are [[360, 350], [10]] which form a monotonically decreasing sequence.

**Comment by cpelley** [comment]
> Is this so unexpected? With the first order the longitudes are [[10], [360, 350]] which do not join (in the order specified) to form a monotonic coordinate.

Yes.  That is not how concatenate is documented to behave and this behaviour is not consistent in any case.  See:

```Python
>>> cube = iris.tests.stock.lat_lon_cube()       
>>> iris.cube.CubeList([cube[:, 1:], cube[:, :1]]).concatenate_cube()
<iris 'Cube' of unknown / (unknown) (latitude: 3; longitude: 4)>
>>> iris.cube.CubeList([cube[:, 1:], cube[:, :1]]).concatenate_cube()
<iris 'Cube' of unknown / (unknown) (latitude: 3; longitude: 4)>
>>> cube = iris.tests.stock.lat_lon_cube()
>>> cubes = [cube[:, :2], cube[:, 2:]]
>>> cubes = iris.cube.CubeList([cube[:, :2], cube[:, 2:]])
>>> cubes.concatenate_cube()
<iris 'Cube' of unknown / (unknown) (latitude: 3; longitude: 4)>
>>> cubes[::-1].concatenate_cube()
<iris 'Cube' of unknown / (unknown) (latitude: 3; longitude: 4)>
```

**Comment by ajdawson** [comment]
I'm not sure I'm following you precisely.

>Yes this certainly is unexpected behaviour (and not consistent with my use of concatenation since it came into existence)

Are you saying this is a regression then? If so, which version did it work in?

I appreciate that in the first example you posted there is an error with one order and not another, and in this one there isn't, which seems buggy, but have you been able to nail this down to a particular feature of the inputs?

**Comment by ajdawson** [comment]
Seems like the coordinate having only one point may be a factor?

**Comment by cpelley** [comment]
> Are you saying this is a regression then? If so, which version did it work in?

Sorry no I meant that concatenation as never been order sensitive to my knowledge and I believe that in this case the order only changes the conditions somehow that then don't give rise to the problem.

> Seems like the coordinate having only one point may be a factor?

Thanks for your interest @ajdawson.  Possibly yes, just like order and direction, they all change the conditions so this problem no longer presents itself.

When I have time I'll debug and keep you posted when I find something.

Cheers

**Comment by ajdawson** [comment]
I've been having a quick look into it. Looks like the sorting in `iris._concatenate._ProtoCube.concatenate` could be problematic for this case. I'm unfamiliar with this area of iris so I haven't figured out exactly what should be happening and what is going wrong. Do let me know if you figure something out.

**Comment by ajdawson** [comment]
OK I think I figured out the problem! The `_ProtoCube` is created from the first cube, which has a 1 element longitude coordinate, and when the dimension order (`_DECREASING`, `_INCREASING` or `_CONSTANT`) is determined, it comes back as `_CONSTANT`. When it comes to concatenating the `_ProtoCube`, the input skeletons are sorted and put in the correct order according to the dimension ordering, which come out as `_CONSTANT` in this case but it should really be `_DECREASING`. If I change the sort instruction from:

```python
skeletons.sort(key=key_func,
               reverse=(order == _DECREASING))
```

to

```python
skeletons.sort(key=key_func,
               reverse=(order == _DECREASING or order == _CONSTANT))
```

we now don't have a problem. Of course this is not a general solution, it'll just break the opposite case, but it shows that the determination of dimension order that is the problem.

I'm not exactly sure how this should be approached. It seems we may need to inspect each cube to determine the dimension order for the `_ProtoCube` rather than just taking the first. If the first cube has dimension order `_CONSTANT` we keep looking until we find one that is either `_INCREASING` or `_DECREASING` and use that instead.

**Comment by cpelley** [comment]
> ...It seems we may need to inspect each cube to determine the dimension order for the _ProtoCube rather than just taking the first....

Thanks @ajdawson, that's great!  Sounds sensible to me.  I'll take a look and have a think.

**Comment by ajdawson** [comment]
I think I have something, just need to test it.
