### ISSUE TITLE
Auxcoord vs DimCoord vs cube auxcoords vs cube dimcoords

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2024]
I understand why we differentiate between dimcoords and auxcoords on the cube (for reasons of CF), however having `DimCoord` or `AuxCoord` objects seems unnecessarily confusing for end-users.

Can we not dispense with the `DimCoord` vs `AuxCoord` classes? (Just a `Coord` class) and just keep the concept at the cube level only?
Is there really enough behavior specific to a `DimCoord` to warrant its existence?

I know this is not a trivial change, and there is not burning demand here but I think its worth sharing these recurring issues from end-users.

**Comment by pelson** [comment]
I think there is a justification for the difference (i.e. the fact that one is numeric, monotonic, 1d etc.). Whether we actually need them to be classes, or just special behaviour inside the Coord implementation is another question. For now, I'm fairly content with the setup, and nothing is on the cards that would fundamentally change the data model in this area just yet...

**Comment by cpelley** [comment]
Thanks for your response @pelson
