### ISSUE TITLE
Citing Iris

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#2025]
Is [this citation](http://scitools.org.uk/iris/docs/latest/userguide/citation.html#bibtex-entry) the best for citing Iris? As a suggestion, can Iris releases be uploaded to Zenodo? I think it provides a convenient way of citing software (example for [matplotlib](https://zenodo.org/record/44579?ln=en)).

**Comment by rhattersley** [comment]
> Is this citation the best for citing Iris?

That was our best understanding at the time, and I believe it has successfully been used already. But thanks for the nudge to improve things.

> can Iris releases be uploaded to Zenodo?

Which release do you have an interest in? I've done [v1.9.2](http://dx.doi.org/10.5281/zenodo.51860).

@SciTools/iris-devs - I've turned on the webhook to Zenodo so future releases will automatically create a DOI. Any objections? If not, we should probably do the same with cartopy, biggus, etc.

**Comment by dennissergeev** [comment]
Thanks!
> I've done v1.9.2.

Could you please add a badge to the README file? And perhaps to the docs?

**Comment by QuLogic** [comment]
Careful though; if you add a badge, then it won't be up-to-date using the automatic DOI creation.

**Comment by ajdawson** [comment]
I've stuck a badge in the README in #2031, with this caveat noted. Needs thought.
