### ISSUE TITLE
Corrupted fill_value when using cube.slices_over()

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2042]
Hello :)

Please see this [IPython notebook](http://nbviewer.jupyter.org/gist/ehogan/0f92da63876625a6b9df6d61398d8328), which shows an issue I discovered while trying to update the `fill_value` on a cube slice (created using `cube.slices_over()`).

The `fill_value` of the slice has a type of `numpy.ndarray` rather than `numpy.float32`, which prevents me from updating the `fill_value` of the slice (note that I can successfully update the `fill_value` of the original cube).

I pinpointed the problem to [this line](https://github.com/SciTools/iris/blob/master/lib/iris/cube.py#L2184).

If I replace this line with:

```
orig_fill_value = data.fill_value
data._fill_value = None
data = copy.deepcopy(data)
data.set_fill_value(orig_fill_value)
```

the result is [as I expect](http://nbviewer.jupyter.org/gist/ehogan/dd832ef357922b6c930276bce5f00fdd).

The act of deepcopying a `MaskedArray` is somehow corrupting the `fill_value`. This issue does not appear to be present if the data is a `biggus` array (i.e., with lazy data). The code I provided above only works when the data is a `MaskedArray` (which has the `fill_value` and `set_fill_value` attributes). 

I'm not sure why this is happening; the [`__deepcopy__`](https://github.com/numpy/numpy/blob/v1.8.2/numpy/ma/core.py#L5539) method of the `MaskedArray` class doesn't look unreasonable.

Any ideas on the best way to resolve this issue?

**Comment by ehogan** [comment]
This issue is resolved if I use a later version of NumPy (I tried 1.11.0).

**Comment by marqh** [comment]
> This issue is resolved if I use a later version of NumPy (I tried 1.11.0).

interesting, and a neat illuystration of a fix as well; thank you for sharing.  

Moving our dependency to a newer version of numpy is plausible; although it'll take a little work, it should not be a lot (famous optimism bias).

We should consider/evaluate this for v1.10

i'll try to take your example and make a test and an updated requirements and see what effect it has and report back

**Comment by pelson** [comment]
Closing as fixed upstream.
