### ISSUE TITLE
Is it necessary to demote to scalar coordinates?

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2048]
When I loop over slices of a cube using `for time_slice in cube.slices_over(time_coord):`, the time coordinate is demoted to a scalar coordinate (since the time coordinate now only contains one point). This also sometimes happens (depending on the input data) if I use a time constraint when loading. Unfortunately, I require time to be a dimension coordinate (more specifically, I require that the data of the cube contain a dimension corresponding to the time coordinate), so I use `iris.util.new_axis` to restore the time coordinate to a dimension coordinate, but this has the unfortunate side effect of loading the data.

Would it be possible to not demote coordinates containing a single point in these cases? If it's possible to create a scalar coordinate while keeping the data lazy, wouldn't it be better for the user to do this themselves rather than having to load the data to restore the dimension coordinate?

**Comment by ajdawson** [comment]
Can I ask why you need the leading time dimension? The more details the better.

This comes up periodically and most times there is a good way to work with the scalar coordinates and achieve the desired results without needing the extra dimension.

**Comment by ehogan** [comment]
In the slicing case, I am working on code that produces MIP-compliant netCDF files for CMIP6. To do this, [CMOR](https://pcmdi.github.io/cmor-site/) is used to write the output netCDF files using MIP tables (containing MIP-specific metadata), which control what is written to the output netCDF files. If a MIP table has defined the dimensions of a variable to be `time`, `latitude` and `longitude`, CMOR will fail unless I provide it with data (which I take from the cube) with these dimensions.

In the time constraint case, the loaded (merged) cubes won't concatenate if the time coordinate is a scalar, so I need to restore the time coordinate to a dimension coordinate. However, this prevents me from processing a large amount of data (which is required for CMIP6), since the data is loaded.

I hope that helps? If you need any more details, just let me know :)

**Comment by ajdawson** [comment]
Thanks for the information. I doubt it matters that data is loaded when you use `iris.utilnew_axis` if you are passing things onto CMOR as I'm guessing you'll end up loading the data anyway. For the case of concatenation, it depends on exactly what you want to do. If it is combine a bunch of cubes that all have scalar time coordinates you should use merge to combine them, which works by combining scalar coordinates to form a new dimension coordinate. If what you want is to stick a cube with a scalar time coordinate onto a cube with a time dimension coordinate then I appreciate this is inconvenient to load the data.

I rather like that we end up with scalar coordinates when using slices etc, but I see this can sometimes be inconvenient. I think a great feature would be to promote a scalar coordinate to a dimension coordinate without loading data. This could be enough to keep everyone content.

**Comment by ehogan** [comment]
> I doubt it matters that data is loaded when you use `iris.util.new_axis` if you are passing things onto CMOR as I'm guessing you'll end up loading the data anyway

True, and I've just realised that this slicing behaviour is consistent with the way NumPy works, so I shouldn't complain ;)

> If it is combine a bunch of cubes that all have scalar time coordinates you should use merge to combine them, which works by combining scalar coordinates to form a new dimension coordinate. If what you want is to stick a cube with a scalar time coordinate onto a cube with a time dimension coordinate then I appreciate this is inconvenient to load the data.

Normally, when I load the data in question (a years worth of monthly data containing a single time point) for a particular variable using `iris.load`, I end up with 12 cubes where time is a dimension coordinate. These cubes don't merge because the `comment` and `history` are different (this is what `iris.load_cube` tells me). I can concatenate these cubes without issue. However, if I load the data for a particular variable using `iris.load` and a time constraint, I end up with 12 cubes again (as expected, since the cubes won't merge), except now time is a scalar coordinate. I can't concatenate these cubes without promoting the time coordinate to a dimension coordinate.

> I think a great feature would be to promote a scalar coordinate to a dimension coordinate without loading data.

This sounds like a good solution to me :) Would it be possible to implement something like this?

**Comment by ajdawson** [comment]
>I end up with 12 cubes again (as expected, since the cubes won't merge), except now time is a scalar coordinate. I can't concatenate these cubes without promoting the time coordinate to a dimension coordinate.

What I really mean is that you could fix the problem by removing the clashing metadata and merge manually yourself (or use a load callback to make sure they merge on load). Promoting a scalar coordinate to a singleton dimension on a whole set of cubes then concatenating them is an anti-pattern, merge (http://scitools.org.uk/iris/docs/latest/iris/iris/cube.html#iris.cube.CubeList.merge, rather than concatenate) is the tool for the job when you have lots of cubes all with scalar coordinates to combine along.

**Comment by ajdawson** [comment]
I've opened SciTools/biggus#179 to discuss the possibility of adding singleton dimensions to deferred arrays.

**Comment by ehogan** [comment]
> I've opened SciTools/biggus#179 to discuss the possibility of adding singleton dimensions to deferred arrays.

Great, thank you!

> What I really mean is that you could fix the problem by removing the clashing metadata and merge manually yourself (or use a load callback to make sure they merge on load).

Ok, I've just written a callback to delete the `comment` and `history` attributes and in my first case, `iris.load_cube` tells me that the time coordinates differ (the time coordinates are dimension coordinates), which is what I expect and I can concatenate these as before. However, in my second case I get an exception `ValueError: Unequal lengths. Cube dimension 0 => 3; metadata u'area of T grid cells' dimension 0 => 1020.`. In this case I am using a time constraint, which selects 3 months of the monthly data (cube dimension 0) and the `area of T grid cells` is the long name of the variable that is specified in the `cell_measures` attribute of the data variable in the netCDF file I am trying to load. Is this a bug in the way `cell_measures` works? Should I move this issue to another ticket?

**Comment by ehogan** [comment]
I noticed #2051 has been merged; thank you very much! :) Did you want me to move the other issue to another ticket?

**Comment by ajdawson** [comment]
I'm not actually sure I understand the other issue. It'd be great if you could explain it in more detail, but probably better in another ticket or perhaps the [Google Group](https://groups.google.com/forum/?fromgroups#!forum/scitools-iris), particularly if you aren't sure if there is a bug or not.

**Comment by ehogan** [comment]
No problem, I'll open a new issue with more details (I'm pretty sure it's a bug) :) Thank you!
