### ISSUE TITLE
Would it be possible to enable multiple points in slices from slices_over?

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2050]
I was wondering whether it would be possible to enable something like `for slice in cube.slices_over(coord, 10):` such that `slice` is a cube containing 10 points from `coord`?

**Comment by bjlittle** [comment]
@ehogan Why don't you just constrain the cube beforehand to contain those 10 points that you want, and then slice over it?

That would be my recommendation.

**Comment by ehogan** [comment]
Ah, I didn't think about that! If I constrain the cube beforehand then I don't need to slice over it :) Thank you!

**Comment by bjlittle** [comment]
:+1: Glad to help!
