### ISSUE TITLE
pp.asfields() on a cube with a single longitude point results in incorrect lbnpt

### ISSUE THREAD

**Issue by hdyson** [SciTools/iris#2054]
I've encountered another unexpected behaviour in the pp_save_rules.  I'm not sure if this one is  intentional so I thought I'd confirm before preparing a fix.  

Saving a cube with a single longitude point, e.g. zonal mean data, as a pp file results in lbnpt (number of longitude points) being incorrectly set to 0 rather than 1 (Note this example isn't on the save function directly, but is on the function that [save calls](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L2281) to set up the fields prior to writing to disc):

```
import iris
from iris.coords import DimCoord
import numpy as np

def create_cube(longitude_points):
    cube = iris.cube.Cube(np.zeros((longitude_points, 2)))
    xcoord = DimCoord(np.arange(longitude_points),
                      standard_name='longitude',
                      units='degrees')
    ycoord = DimCoord(points=np.arange(2))
    cube.add_dim_coord(xcoord, 0)
    cube.add_dim_coord(ycoord, 1)
    return cube

cube1 = create_cube(1)
fields1 = list(iris.fileformats.pp.as_fields(cube1))
fields1[0].lbnpt
#[Out]# 0
# Incorrect result: should be 1

cube2 = create_cube(2)
fields2 = list(iris.fileformats.pp.as_fields(cube2))
fields2[0].lbnpt
#[Out]# 2
# Correct result
```

Digging into this, it looks like the culprit is in the pp_save_rules requiring longitude to be a vector coordinate [here](https://github.com/SciTools/iris/blob/master/lib/iris/etc/pp_save_rules.txt#L332).  Is there a reason to constrain to a vector coordinate?

**Comment by hdyson** [comment]
An answer to whether this is intended behaviour or not would be appreciated.  I'm happy to provide a fix if it's not intended.

**Comment by hdyson** [comment]
There's a similar issue for BDX too: it's not set for zonal mean data, but it should be set to 360.0 (for a fixed resolution lat/lon grid).

**Comment by cpelley** [comment]
ping

**Comment by djkirkham** [comment]
It doesn't look like intended behaviour, but looking at the code I'm wondering how easy it will be to fix and maintain current behaviour: currently Iris saves vector coordinates of length 1 as scalars in pp files. So, for example, a cube of shape (1, 10, 20) can be saved in pp format (though it will load as a cube of shape (10, 20)). The function [`scalar_coord`](https://github.com/SciTools/iris/blob/2ac14cb01e771aa2fdc04ebbbdf9a2aec60aa558/lib/iris/fileformats/rules.py#L682), used in the pp rules, will detect 1D vector coordinates of length 1, whereas `vector_coord` won't. Attempting to treat them as either scalars or vectors may lead to difficulties.

**Comment by hdyson** [comment]
Thanks, that's interesting info.  I don't know that area of the code well enough to have a good grasp of how easy it will be to fix, but I think the fastest way to find out will be to take a stab at it and see where the difficulties lie.  I'm going to assume that preserving current behaviour for the (1, 10, 20) shape cube is required.

Just a heads up that it's unlikely that a PR will be in the next couple of weeks, I don't have a great deal of time to devote to this just now.
