### ISSUE TITLE
Consider dtype promotion for analysis routines

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2069]
This is more of an open question rather than a concrete issue ... but it does arise from using Iris with Numpy `v1.8.2` and calculating a mean over a **large** data sample e.g.

``` python
>>> import numpy as np
>>> np.__version__
'1.8.2'
>>> a = np.empty(10000000, dtype=np.float32)
>>> a.fill(290.1234)
>>> a.mean()
272.76416
```

This Numpy `v1.8.2` behaviour can be circumvented using `a.mean(dtype=np.float64)` e.g.

``` python
>>> a.mean(dtype=np.float64)
290.1234130859375
```

It is also a non-issue from Numpy `v1.9.0` onwards e.g.

``` python
>>> import numpy as np
>>> np.__version__
'1.9.0'
>>> a = np.empty(10000000, dtype=np.float32)
>>> a.fill(290.1234)
>>> a.mean()
290.12482
```

This matters because this `v1.8.2` behaviour is mirrored in Biggus and thus Iris e.g. when using `cube.collapsed`, so there is the potential to get an incorrect result from Iris given the underlying software stack. Although, you can also dodge that bullet by promoting the dtype lazily in Iris as follows:

``` python
data = cube.lazy_data()
cube.lazy_data(data.astype(np.float64))
```

So there is a workaround, but you need to explicitly take it (and know about it!)...

In general, moving northwards of Numpy `v1.8.2` resolves the whole issue. Great.

That aside, it seems worthwhile to pause, draw breath and simply ask the question as to whether there is appetite and/or benefit in general for Iris to automatically promote the "accumulator/cumulation" dtype for all such analysis operations in order to maintain precision, independent of Numpy pre-`v1.8.2` behaviour?

**Comment by rcomer** [comment]
I'm gonna stick my neck out and say I don't think this is worth doing...!

**Comment by pp-mo** [comment]
Well done for re-raising @rcomer .
Three years old .. I think this has had its day don't you ?
