### ISSUE TITLE
Using np.ma.where on lazy data

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2078]
To replace values in the data of my cube that are less than a particular value with zero, I use `cube.data = np.ma.where(cube.data < value, 0, cube.data)`. However, this command loads the data. In researching whether it was possible to do this without loading the data, I found [this Google groups post](https://groups.google.com/d/msg/scitools-iris/vl9E6CK_yeA/XbBgjXtqAAAJ). So I tried using the following lazy function: `replace_less_than_value = partial(np.ma.where, cube.data < value, 0)`. (I couldn't use `partial(np.ma.where, cube.data < value, 0, cube.data)` because biggus fails with a `TypeError: where() takes at most 3 arguments (4 given)`). However, if I slice the cube and then load the data, I have problems due to the fact that there is a mismatch in the shapes of the data and the metadata, presumably because the lazy function refers to the data in the cube rather than the data in the slice. I tried `cube.lazy_data()` instead of `cube.data` in the lazy function but I had similar problems (biggus fails with a `ValueError: The new_axes must have length 5 but was actually length 3.`). Is there a way to define a lazy function so that it works with sliced data?

**Comment by ajdawson** [comment]
I think there is some confusion about how the example referred to actually works. You are fixing the whole array within the partially applied function, but really you should pass in an array instead, this way it will work on any slice.

You could use the private biggus function `_dual_input_fn_wrapper` (again with all the caveats using part of the private API may bring, e.g. it might disappear without warning in a future version!) with a `lambda` that calls `ma.where` correctly when provided with 2 arguments.

```python
import biggus
import iris
import numpy.ma as ma

# Function that accepts an array and a value as input, and returns an array the same
# shape as the input array, whose elements are replaced by 0 if they are less than the
# given value:
lt_value = lambda d, v: ma.where(d < v, 0, d)

# Wrap this up so biggus can use it to operate on lazy data:
zeroit = biggus._dual_input_fn_wrapper('zero_less_than_value', lt_value, lt_value)

# Apply the function:
filename = iris.sample_data_path('uk_hires.pp')
pt = iris.load_cube(filename, 'air_potential_temperature')
pt.lazy_data(zeroit(pt.lazy_data(), 294))
print(pt.has_lazy_data())
```

This example lazily sets all values less than 294 in the cube pt to zero. Once again, this uses part of the biggus private API, so has no guarantee of working with biggus versions other than 0.13.

**Comment by ehogan** [comment]
Thanks @ajdawson, I figured I was doing something stupid (I'll blame it on the fact that it was Friday) ;) However, when I apply this to my code, an exception is raised when I try and use `iris.util.new_axis` and I can't seem to reproduce the problem by extending your example to use my own data and the following code:

```
time_coord = pt.coord('time')
for time_slice in pt.slices_over(time_coord):
    coord = time_slice.coord('time')
    time_slice = iris.util.new_axis(time_slice, coord)
```

:(

```
Traceback (most recent call last):
  File <my_code>
    time_slice = iris.util.new_axis(time_slice, coord)
  File "/home/h01/ehogan/software/iris/lib/iris/util.py", line 1089, in new_axis
    new_cube = iris.cube.Cube(src_cube.lazy_data()[None])
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 548, in __getitem__
    indexed_array = array[keys]
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 868, in __getitem__
    new_axes)
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 768, in __init__
    len(new_axes)))
ValueError: The new_axes must have length 5 but was actually length 3.
```
This is the same error I was getting before.

Can you give me any hints as to what to look for in my code that might be causing this problem?

**Comment by ajdawson** [comment]
Hard to say without seeing the rest of your code. This discussion might be more appropriate on the mailing list since it does not seem to involve a problem with iris itself.

**Comment by ehogan** [comment]
After further investigation, I discovered that the problem is not due to the lazy function; it appears to be related to the use of ancillary files. To reproduce the problem, I have to multiply (or divide) two cubes, one of which contains data from an ancillary file (I tried various arithmetic with other cubes, but this seemed to be the only combination that causes the problem), then I need to slice over the cube (such that the slice contains different data to the original cube) and load the data. I have a test that does all of the above except for the fact that the cube contains a single time slice (so the slice and the cube contain the same data), and the test passes. Also, if I load the data before slicing over the cube I have no problems.

Here's how to reproduce the problem:
```
In [1]: import iris

In [2]: filenames = ['/project/cdds/testdata/diagnostics/input/ajnjg/apm/ajnjga.pmm1jan.pp',
   ...:              '/project/cdds/testdata/diagnostics/input/ajnjg/apm/ajnjga.pmm1feb.pp',
   ...:              '/project/cdds/etc/um_ancil/HadGEM2-ES/mask_frac_l32161_n96_ref.pp']

In [3]: constraint1 = iris.AttributeConstraint(STASH='m01s19i013')

In [4]: cube1 = iris.load_cube(filenames, constraint1).extract(iris.Constraint(pseudo_level=3))

In [5]: constraint2 = iris.AttributeConstraint(STASH='m01s00i505')  # from the ancillary file.

In [6]: cube2 = iris.load_cube(filenames, constraint2)

In [7]: cube = cube1 * cube2

In [8]: for time_slice in cube.slices_over(cube.coord('time')):
   ...:     print time_slice.data
   ...:     
Exception in thread <biggus.ProducerNode object at 0x4c98710>:
Traceback (most recent call last):
  File "/usr/local/sci/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/sci/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 217, in run
    data = self.array[key].masked_array()
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 1126, in masked_array
    ma = super(BroadcastArray, self).masked_array()
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 742, in masked_array
    return self.array.masked_array()
  File "/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py", line 1786, in masked_array
    fill_value=self.fill_value)
  File "/usr/local/sci/lib/python2.7/site-packages/numpy/ma/core.py", line 7223, in __call__
    result = self._func.__call__(a, *args, **params).view(MaskedArray)
MemoryError

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-8-9764bb0b8a3a> in <module>()
      1 for time_slice in cube.slices_over(cube.coord('time')):
----> 2     print time_slice.data
      3 

/home/h01/ehogan/software/iris/lib/iris/cube.pyc in data(self)
   1681         if not isinstance(data, np.ndarray):
   1682             try:
-> 1683                 data = data.masked_array()
   1684             except MemoryError:
   1685                 msg = "Failed to create the cube's data as there was not" \

/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py in masked_array(self)
   2940             raise TypeError('No {} operation defined for masked arrays.'
   2941                             ''.format(self._numpy_op.__name__))
-> 2942         ma_operands = masked_arrays(self.sources)
   2943         result = self._ma_op(*ma_operands)
   2944         return result

/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py in masked_arrays(arrays)
   2052 
   2053     """
-> 2054     return engine.masked_arrays(*arrays)
   2055 
   2056 

/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py in masked_arrays(self, *arrays)
    463 
    464     def masked_arrays(self, *arrays):
--> 465         return self._evaluate(arrays, True)
    466 
    467     def ndarrays(self, *arrays):

/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py in _evaluate(self, arrays, masked)
    457         all_results = [None] * len(arrays)
    458         for group in groups:
--> 459             ndarrays = group.evaluate(masked)
    460             for i, ndarray in zip(group.indices, ndarrays):
    461                 all_results[i] = ndarray

/opt/ukmo/iris/default/linux64/site-packages/biggus/__init__.py in evaluate(self, masked)
    443             results = [node.result for node in result_nodes]
    444             if any(result is None for result in results):
--> 445                 raise Exception('error during evaluation')
    446             return results
    447 

Exception: error during evaluation

In [9]: print cube.has_lazy_data()
True

In [10]: print cube.data
[[[0.0 0.0 0.0 ..., 0.0 0.0 0.0]
  [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
  [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
  ..., 
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]]

 [[0.0 0.0 0.0 ..., 0.0 0.0 0.0]
  [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
  [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
  ..., 
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]]]

In [11]: print cube.has_lazy_data()
False

In [12]: for time_slice in cube.slices_over(cube.coord('time')):
   ....:     print time_slice.data
   ....:     
[[0.0 0.0 0.0 ..., 0.0 0.0 0.0]
 [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
 [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
 ..., 
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]]
[[0.0 0.0 0.0 ..., 0.0 0.0 0.0]
 [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
 [0.0 0.0 0.0 ..., 0.0 0.0 0.0]
 ..., 
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]]
```
The exception I got from my code is different because the data were being loaded indirectly.

Do I win the prize for finding the most obscure bug in Iris / biggus? ;)

**Comment by rcomer** [comment]
So I just tried this with recent Iris.  With Iris2.4, you can't multiply `cube1` and `cube2` because "ValueError: This operation cannot be performed as there are differing coordinates (forecast_period) remaining which cannot be ignored."!  With `master`, the slicing all works fine with no `MemoryError`, but `cube.has_lazy_data()` returns `False` after the slicing.  This is not the case if you just set up some dummy cube with lazy data:

```python
import iris
import dask.array as da
cube = iris.cube.Cube(da.array(range(5)))
cube.add_dim_coord(iris.coords.DimCoord(range(5), long_name='foo'), 0)
for subcube in cube.slices_over('foo'):
    print(subcube.data)
print(cube.has_lazy_data())
```
```
0
1
2
3
4
True
```
