### ISSUE TITLE
Make structured FF loading public

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2083]
This is currently stuck in iris.experimental.fieldsfile, but we want to produce a public version in due course.
It may be differently structured by then, and may also rely on 'mule'.
See #2082 "Refactor iris.fileformats.um to use mule"

**Comment by hdyson** [comment]
Hi @pp-mo 

Is the plan to replace the existing FF loader, or complement it?  The reason I ask is that we have a use case that requires the current loaders behaviour of calling the callback after **each** field, rather than the structured loaders calling of the callback once after **all** fields have been read in.

**Comment by pp-mo** [comment]
> @hdyson Is the plan to replace the existing FF loader, or complement it? 

This functionality will still be distinct from "ordinary" loading.
The only immediate desire is to provide a proper 'mainstream' form with a supported API, as internal uses (StaGE) are now requiring it.

There is an important technical reason for keeping it separate, because the existing structured load can not cope with arbitrary **un**-structured input files.  I have previously speculated whether we may eventually remove those restrictions and use "structured" loading wherever possible ...
Your usecase demonstrates how that is not always desirable, which is a valuable observation.

This implies that any future integrated scheme may need to make special allowance for callbacks.
On the other hand, whatever the future API, it should still be possible to replicate the existing mechanism:
 * PP and Fieldsfile loading is essentially a combination of ```iris.load_raw``` and ```CubeList.merge``` ...
 * ... so you can simply do that explicitly.
 * This is explained at http://scitools.org.uk/iris/docs/latest/whitepapers/um_files_loading.html?highlight=load_raw#overview-of-loading-process
 * I'm very aware that this relationship between loading and merging is currently **not** clearly explained in the UserGuide where, arguably, it should be :  However, there is a problem doing that because the process is fileformat-dependent : while grib loading works the same way, other formats (e.g. netcdf) don't have separate 2d 'fields', so they obviously do not.

**Comment by hdyson** [comment]
Thanks for the thorough answer @pp-mo, that's cleared things up nicely.  Good to know that there's no need for us to panic!

**Comment by pp-mo** [comment]
This is done ! cf. #2441

**Comment by QuLogic** [comment]
Don't understand what that PR (adopt conda-forge) has to do with this issue?

**Comment by pp-mo** [comment]
Fniger trouble.
That should be #2241
