### ISSUE TITLE
Missing FUTURES hook for pp data API change

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2100]
Relating to changes introduced in #1926.  I think a FUTURES hook should have been in-place due to the API change that resulted.
I think it would be a good idea to do this before tagging a release.

**Comment by cpelley** [comment]
I propose that this issue be added to the v1.10 milestone.  I mentioned it some time ago on #1926 but I don't think it got noticed.

**Comment by marqh** [comment]
I am wary of introducing another future switch for this behaviour

The #1926 change is adding metadata and removing a bug which could exhibit itself with certain input data sets.

This is not an API change.

I would need more justification for how this is a major behavioural change before I would support a  future option.
This level of change, subtly reinterpreting metadata on load, is a common pattern for changes and enhancements and does not fall into the future switch category, I feel.

**Comment by cpelley** [comment]
Our code was dependent on the fact that there was a time coordinate when there is now not one (month_number instead).  Iris has a public UI not just for function/class/module calls but also of how data is represented (perhaps UI is not the right term, but the principle/risk is the same).

I think this could be high risk with iris end users who rightly assume they still have a time coordinate but are not aware of the subtle change that has taken place here.

**Comment by hdyson** [comment]
To expand on @cpelley's comment, we had workaround code that specifically checked for invalid years on a cube prior to saving, which then "fixed" the year prior to saving.  Year 0 to mean any year is a common convention in ancillary files, so we've hit this problem a lot.  The #1926 change broke our check for whether a file was a year < 1 or not - so was, to us, an unexpected behaviour change that we then had to account for.

It's great that you're trying to handle data with a year of 0 in a better way (and your fix is better than our workaround one), but I'd suggest it's only courteous that when you change behaviour in a way that may impact downstream code, you give people fair warning.

**Comment by marqh** [comment]
> It's great that you're trying to handle data with a year of 0 in a better way (and your fix is better than our workaround one), but I'd suggest it's only courteous that when you change behaviour in a way that may impact downstream code, you give people fair warning.

We have attempted to give fair warning, by providing a what's new entry and (soon) by providing a release candidate.

The addition of a 'future' flag for a particular case is a value judgement based on the size of the change.  In this case, my view is that the change is not large enough to warrant the complication of a future flag.  The removal of the erroneous time coordinate is more in the realms of a bug fix than anything else.

**Comment by hdyson** [comment]
Thanks for that @marqh.  You're right, it is a value judgement of whether or not something justifies the use of a FUTURE flag, and ultimately it's your call, so I'm not going to push this any further.  I've explained our position, and you've listened, so I'm content.  

I suspect our view may be different from yours because we deal with ancillaries so have hit this problem so often: to us, year zero is a problem for the vast majority of files we see, while to you, it's a tiny fraction.  Different perspective, leading to different opinions.
