### ISSUE TITLE
Make nc_time_axis an optional dependency

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2113]
For a library with such a specific purpose, it is a surprise to find that `nc_time_axis` is now a first-class Iris dependency. At the very least `nc_time_axis` should be only a deferred load (i.e. only when necessary) within `iris.plot`, but even this will still mean that we cannot build the documentation without nc_time_axis. This clearly is not a desirable situation to be in.

An ideal solution to this would be that `nc_time_axis` behaves like `iris_grib`; that is that it is a plugin module for Iris that relies on Iris, rather than being a library that Iris relies on.

**Comment by QuLogic** [comment]
I think this is done.
