### ISSUE TITLE
Modules export only intended public elements

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2122]
- Consider all public names
- Avoid sub-module imports
  - some existing ones may be wanted : e.g. iris.cube, iris.coords
  - most are "accidental" and should be avoided :  like #2121
- Don't export the module's own imports (sys, six, numpy, netcdf4 ...)
  - can be done with widespread renames adding underscores
  - Alternatively, much less fiddly to use "__all__", but it's not clear how universally respected the '__all__' convention is ?
  - see : https://github.com/SciTools/iris/pull/1999#issuecomment-216841149

**Comment by pelson** [comment]
The only tangible benefit we can come up with for this is to avoid things like ```iris.logging``` where `logging` is imported in ``iris/__init__.py``. 

I notice that packages like ```matplotlib``` haven't solved this one either: ```>>> plt.np``` is completely valid...


For me, this doesn't feel like a huge win, nor particularly urgent, so I'll close this. Would probably merge a PR that addressed this though...
