### ISSUE TITLE
BUG: Cube equality with annonymous dimensions

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2123]
``` Python
>>> import iris
>>> import numpy as np

>>> data = np.zeros((2, 2, 2))
>>> source = iris.cube.Cube(data)
>>> source.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='bing'), 1)
>>> source.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='flop'), 2)
>>> print source.summary(True)
unknown / (unknown)                 (-- : 2; bing: 2; flop: 2)

>>> data = np.zeros((1, 2, 2, 2))
>>> source2 = iris.cube.Cube(data)
>>> source2.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='bing'), 1)
>>> source2.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='flop'), 2)
>>> print source2.summary(True)
unknown / (unknown)                 (-- : 1; bing: 2; flop: 2; -- : 2)

>>> source == source2
True
```

Iris cube equality is not checking that the coordinates which are present are mapped to the same dimensions or even that the cube has the same shape.  I think this has not been caught before because the numpy equality by substitution will work for most cases.  here it doesn't because of numpy broadcasting rules and a coincidental all zeros difference between the arrays (in the example above, this is because both arrays are filled with zeros but this doesn't have to be the case).  A false Positive is then returned.

**Comment by cpelley** [comment]
I have added this to the v1.13 milestone because it's a BAD bug (causing problems which go unnoticed for end users).  I'll happily commit to putting up a PR to fix this there is interest?

**Comment by pelson** [comment]
Thanks for making it easy to reproduce @cpelley. I'm not as convinced that the *actual answer* isn't correct... CF has an interesting relationship with regards to length 1 dimensions and might actually consider the two equal. That said, I'm confident that what has been implemented isn't what was intended by the developer, so can see why you'd call it a bug (for example, is a transposed cube equal to the non-transposed one?).

**Comment by cpelley** [comment]
Thanks for your input Phil.

It's possible that I didn't explain myself well enough with only a single example and that my description doesn't stand on it's own.  Being of dimension length 1 isn't a characteristic of the problem.

Make source2 of shape 2, 2, 2, 2 and the two cubes will still return a True for equality:
(also note that both sources have bing and flop mapped to 1 and 2!

```Python
>>> import iris
>>> import numpy as np

>>> data = np.zeros((2, 2, 2))
>>> source = iris.cube.Cube(data)
>>> source.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='bing'), 1)
>>> source.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='flop'), 2)
>>> print source.summary(True)
unknown / (unknown)                 (-- : 2; bing: 2; flop: 2)

>>> data = np.zeros((2, 2, 2, 2))
>>> source2 = iris.cube.Cube(data)
>>> source2.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='bing'), 1)
>>> source2.add_dim_coord(iris.coords.DimCoord([0, 1], long_name='flop'), 2)
>>> print source2.summary(True)
unknown / (unknown)                 (-- : 1; bing: 2; flop: 2; -- : 2)

>>> source == source2
True
```

Fundamentally, my issue is that cubes are not numpy arrays and current equality feels wrong.  One can easily imagine that coincidental positives could exist even for non-zero arrays too.
As for transposed data, I think a case could be made for a positive result between a cube and a suspected transpose of that cube, but doing so would require using the metadata in a way that it does not current (also hence the issues presented above).

Sorry Phil, I hope this helps a little.

Cheers

**Comment by pelson** [comment]
It sure does. I agree - this is a pretty ugly bug.
