### ISSUE TITLE
Contour labels cause latitudinal lines to be drawn

### ISSUE THREAD

**Issue by nltyrrell** [SciTools/iris#2129]
When adding inline labels to a contour plot made with iris.plot latitudinal lines are drawn across the plots. I wasn't sure if this should be a Cartopy bug, but it seems true for different projections. There's a very easy work around, just use inline=0, i.e. `plt.clabel(c1, inline=0)`, but it makes it harder to read the labels!

In the example below, you can see the lines correspond to the colors of the contours.

```
import matplotlib.pyplot as plt
import iris as iris
import iris.plot as iplt
import iris.quickplot as qplt
import cartopy.crs as ccrs

fname = iris.sample_data_path('air_temp.pp')
data = iris.load_cube(fname)

NPS_proj = ccrs.NorthPolarStereo()
PC_proj = ccrs.PlateCarree()

fig = plt.figure(figsize=(10,12))

ax = fig.add_subplot(2,1,1) 
c1 = iplt.contour(data) #,colors='k') 
plt.clabel(c1)

ax = fig.add_subplot(2,1,2,projection=NPS_proj)
ax.set_extent((-180, 180, 0, 90),crs=PC_proj)
c2 = iplt.contour(data) #,colors='k') 
plt.clabel(c2)
```

![image](https://cloud.githubusercontent.com/assets/8508770/18267473/e6eb403c-7427-11e6-91ab-6e64d2399ae9.png)

**Comment by marqh** [comment]
Hi @nltyrrell 

thank you for the update about this bug, I think it's a bug somewhere, a\nd code to illustrate its behaviour.

I'll try and write a test for this and find a way to chase it down.  I will update you via this ticket

mark
