### ISSUE TITLE
netcdftime.num2date() rounding issues

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2138]
When [unpinning Matplotlib](https://github.com/SciTools/iris/pull/2124) it was discovered that there are rounding issues with `netcdftime.num2date()` now that it implements microsecond precision. This issue likely affects many other areas of the code. For instance, coordinate categorisation: https://github.com/SciTools/iris/pull/2137

**Comment by marqh** [comment]
I think this issue has now been addressed.  @djkirkham please may you check and close this issue or update it with more details, based on what you find

thank you
mark

**Comment by djkirkham** [comment]
It's not fixed in the `iris.unit` module, which is deprecated. Does anything need to be done about that?

**Comment by djkirkham** [comment]
`iris.unit` has been removed.
