### ISSUE TITLE
check sha1

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#2163]
```
======================================================================

ERROR: test_keywords (iris.tests.test_mapping.TestLowLevel)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.11.0.dev0-py3.4-linux-x86_64.egg/iris/tests/test_mapping.py", line 180, in test_keywords

    self.check_graphic()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.11.0.dev0-py3.4-linux-x86_64.egg/iris/tests/__init__.py", line 730, in check_graphic

    ' Message: {}'.format(emsg))

ValueError: Image comparison failed. Message: Actual SHA1 a49153fde62c8e7c33a4de4675bdecfb6745da5b not in expected ['35df96c086fb2fd3d9caf6fb83f4d60ec374d911'] for test iris.tests.test_mapping.TestLowLevel.test_keywords.0.


```

but this disappears on a rerun

the particular test is not important, it can happen on various tests and test matrix configuration.

is there some instability in how matplotlib save and the file hash calculation process?

**Comment by bjlittle** [comment]
Slightly disturbing, but I'm not surprised.

Using a cryptographic hash gives no tolerance to any change ... imagehashing my be our friend here, but I'd love to understand what the heck is at the root of the difference.

The fact that it's behaviour is somewhat random is pretty unfortunate and most likely difficult to diagnose :disappointed:

**Comment by bjlittle** [comment]
@marqh Have you seen this behaviour when you run the tests locally i.e. taking travis out of the equation?

That would be really good to know.

**Comment by marqh** [comment]
> Have you seen this behaviour when you run the tests locally i.e. taking travis out of the equation?
> 
> That would be really good to know.

i have not seen it, but i have no evidence of absence

**Comment by QuLogic** [comment]
Is there any reason why the failed images are not printed at the end?

**Comment by pelson** [comment]
Haven't seen this for quite some time. Closing for now.
