### ISSUE TITLE
iris.tests.test_trajectory.TestTrajectory.test_tri_polar

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2168]
The "integration" test `iris.tests.test_trajectory.TestTrajectory.test_tri_polar` is chronically s--l--o--w.

It's interpolating a 90 point trajectory over the following cube ...

```
sea_water_potential_temperature / (degC) (time: 1; depth: 31; -- : 148; -- : 180)
     Dimension coordinates:
          time                                x         -        -         -
          depth                               -         x        -         -
     Auxiliary coordinates:
          latitude                            -         -        x         x
          longitude                           -         -        x         x
```

... using `iris.analysis.trajectory.interpolate` to do all the hard work.

We should investigate to diagnose the bottleneck. 

I'd be pretty interested in user feedback on their experience of using `iris.analysis.trajectory.interpolate` and whether it's performance is fit for purpose (within the context of its use).

**Comment by ajdawson** [comment]
#1767 has details and links to user stories regarding this, seems like an issue for others too.
