### ISSUE TITLE
Subplots not lining up with matplotlib 1.5

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2171]
We have an outstanding problem with the positioning of multiple subplots, that appeared when we unpinned matplotlib (mpl 1.3 --> 1.5.1).

Issue is captured here : https://github.com/SciTools/iris/pull/2169#discussion_r82399049
"Eventually this may need raising as a matplotlib issue, or possibly we can add a workaround in Iris."

There is a result image demonstrating this  problem here : https://scitools.github.io/test-images-scitools/image_files/8f68ed33e818f4cde38bc94c755e2a98b58016fe.png
 : The subplot edges don't all line up nicely

( Compare this with an older version from mpl=1.3 : https://github.com/SciTools/iris/blob/v1.10.0/lib/iris/tests/results/visual_tests/test_lagged_ensemble.TestLaggedEnsemble.test_lagged_ensemble.0.png
for a hint as to where the problems are )

**Comment by QuLogic** [comment]
Maybe the example should be changed to use `plt.subplots` instead of `plt.subplot`? And maybe stop using `plt.gcf` so much...

**Comment by QuLogic** [comment]
This might be related to matplotlib/matplotlib#5370, so apparently you should bug @pelson about it.
