### ISSUE TITLE
mpl scatter markers not lining up with mpl 1.5+

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2172]
There is an issue with `matplotlib.pyplot.scatter` consistent from versons `1.4.0` thru to `1.5.3` where the scatter markers do not align.

See [comment](https://github.com/SciTools/iris/pull/2169#discussion_r82386404) on PR #2169 

Relevant images that highlight this issue are [mpl 1.3.1](https://scitools.github.io/test-images-scitools/image_files/66ed0f9d1ef83b714fda7299264e6c420ca04159.png) and [mpl 1.5.1](https://scitools.github.io/test-images-scitools/image_files/c007fa9d002b911e9868cb11474b827959bc70b7.png)

Note that, link [mpl 1.5.1](https://scitools.github.io/test-images-scitools/image_files/c007fa9d002b911e9868cb11474b827959bc70b7.png) will **404** unless PR https://github.com/SciTools/test-images-scitools/pull/5 is merged.

**Comment by pelson** [comment]
The code below:

```
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

x, y = np.meshgrid(np.arange(0, 5, 0.5),
                   np.arange(0, 100, 10))

ax = plt.axes([0, 0, 1, 1])
ax.grid(True)

ax.scatter(x, y)

plt.savefig('scatter.{}.png'.format(matplotlib.__version__))

plt.show()
```

Can be used to produce the following images on 1.3.1 and 1.5.3:

![scatter 1 3 1](https://cloud.githubusercontent.com/assets/810663/19265362/cb0e2da8-8f9c-11e6-904d-966ded449968.png)
![scatter 1 5 3](https://cloud.githubusercontent.com/assets/810663/19265363/cb12c7dc-8f9c-11e6-88d9-8bbca9307f83.png)

We can clearly see that the location of the markers **has** changed. By eye, the incorrect markers are those in v1.3.1, and they appear much better in v1.5.3 (as we would expect).

The images that you link @bjlittle are showing a similar pattern. The only difference is that we have lost the **ordering** of the scatter drawing process - in v1.3 it looks like the order resulted in pretty scatter markers when they were too close together, in v1.5 it looks like these are now in an unpredictable (repeatable?) order.

**Comment by bjlittle** [comment]
@pelson The scatter images in mpl v1.3 and v1.5 are repeatable, given the same input data.

**Comment by pelson** [comment]
> @pelson The scatter images in mpl v1.3 and v1.5 are repeatable, given the same input data.

Confirmed. The ordering is not having an impact at all - it is consistent. Looks like there may be some snapping that needs investigating, but given we can already see that scatter markers *have* moved for the better, it may be there isn't anything wrong with the image we are seeing. I'll dig into the actual data that we are seeing this problem for (I'll be looking out for floating point tolerances, if there is anything wrong at all).

**Comment by pelson** [comment]
xref: https://github.com/matplotlib/matplotlib/issues/7262
