### ISSUE TITLE
Multi-graphic-check test cases

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2176]
There are several graphical test cases that perform more than one `iris.tests.IrisTest.check_graphic` call.

We should enforce that each such graphical test only performs **one** call to `check_graphic` in order to simplify the new test image workflow; otherwise a developer requires to run the tests several times (e.g. #2175 required 6 re-runs) to ensure that all graphics tests are exercised, as a test case stops at the first point of failure

**Comment by pp-mo** [comment]
Reviewing this ...
Scanned + found there *are* still some testcases making multiple `check_graphic` calls :
  * `iris.tests.experimental.test_animate.IntegrationTest.test_cube_animation`
  * `iris.tests.integration.test_mapping.TestLowLevel`
    * `test_params`, `test_keywords`
  *  `iris.tests.integration.test_plot`
    *  `TestMissingCoord`
      * (all 3)
    *  `TestHybridHeight`
      * (all 3)
    * `TestPlotCoordinatesGiven`
      * `test_yx`, `test_zx`, `test_tx`, `test_x`, `test_y`
    * `TestPlotDimAndAuxCoordsKwarg`
      * `test_coords`,  `test_coord_names`, `test_yx_order`
    * `test_quickplot`
      * `TestLabels`
        * `test_contour`, `test_contourf`
