### ISSUE TITLE
iris test runner missing tests

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#2202]
iris test runner inside travis is not running all available iris tests

I have been chasing
`
iris.tests.unit.analysis.cartography.test_project.TestAll
`
which does not get run by travis, but a 
`
python -s -m unittest discover -v -s iris.tests
`
does run it

I suspect this is not the only one, but I have not conducted a gap analysis

**Comment by pelson** [comment]
cc: @pp-mo: This came up for you yesterday.

**Comment by pp-mo** [comment]
This problem keeps shifting.

Chased down this by date.
There is no appearance of "cartography.test_project" in the log for ...
 * this commit .. https://travis-ci.org/SciTools/iris/jobs/168880885
 * in [the python2.7 'default' Travis test]()
