### ISSUE TITLE
Outstanding review comments from #2206

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2210]
I believe that #2206 was merged a little hastily, and I have made extra comments on the PR post-merge. To try and prevent these extra comments from getting lost, here's an issue that references them.

Ping @bjlittle

**Comment by QuLogic** [comment]
I believe these were addressed by #2215 and #2218. Please re-open if I'm incorrect.

**Comment by dkillick** [comment]
Good spot @QuLogic - many thanks.
