### ISSUE TITLE
Tests using nc-time-axis are not skipped if not installed

### ISSUE THREAD

**Issue by QuLogic** [SciTools/iris#2219]
I'm testing out the rc, and tests that use nc-time-axis are not skipped even when I don't have it installed. Additionally, this dependency is not listed in the `INSTALL` file.

**Comment by QuLogic** [comment]
I just realized that these are the example tests, so maybe this might be a bit difficult to do. I guess I might have to finish up packaging nc-time-axis...

**Comment by dkillick** [comment]
It would be _really nice_ if you didn't have to... IMO `nc-time-axis` should be a proper optional dependency so that Iris will just work properly if it's not available.

**Comment by pp-mo** [comment]
>  IMO nc-time-axis should be a proper optional dependency 

I believe it is all ok + as it should be :
It is only imported when you invoke functionality that requires it.
The main code imports it in only one place, and [that is a "lazy" import ...](https://github.com/SciTools/iris/blob/v1.10.0/lib/iris/plot.py#L415)
In the 'normal'  tests, every use is guarded with a skip.

My understanding is that **example** tests may assume the presence of "any" optional dependencies, which has seemed reasonable so far.
At any rate, we don't want to clutter the example _code_ with conditionals.
But.. the example _tests_ are independently written (not automatic), so I guess we could easily add @skip_xx wrappers into those, if that were useful to anyone ?
Travis runs the example tests when not "TEST_MINIMAL".

**Comment by rcomer** [comment]
The `INSTALL` file is no more.  The current yml files list `nc-time-axis` as an optional dependency.  `iris-sample-data` is also an optional dependency and the gallery tests won't get far without that!  I just tried running the gallery tests without `nc-time-axis`, and the error message telling me to install it was pretty idiot-proof.  So I think the risks of not addressing this issue are very minimal and it can be closed.  Obviously any core dev who disagrees is welcome to re-open it.
