### ISSUE TITLE
Test failures with builtin grib support

### ISSUE THREAD

**Issue by QuLogic** [SciTools/iris#2226]
I haven't got iris-grib packaged yet (because it seems to have a circular dependency?), so I'm still running tests with the internal support. I've still got 35 failures, and I think most of them have grib in the name, so I think it's related to using the internal support. It doesn't look like Travis tests out this combination, so it may have broken.

I haven't been able to reproduce in a conda environment (as opposed to rpm) because `python-ecmwf_grib` is broken on conda-forge, somehow...

**Comment by QuLogic** [comment]
I think [this build](https://travis-ci.org/QuLogic/iris/jobs/171930832) shows the relevant failures.

**Comment by rcomer** [comment]
Given that `iris.fileformats.grib` was removed at v2.0, I’m betting this is no longer a problem!
