### ISSUE TITLE
Slow TEST_TARGET=default on travis-ci

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2229]
Investigate the step change slowness of the `TEST_TARGET=default` on travis-ci, see this [job](https://travis-ci.org/SciTools/iris/builds/172012307) as a typical example.

May be due to the recent nose timeout change and/or the locking serialisation of graphical tests.

**Comment by ajdawson** [comment]
Comment from @marqh in #2231:

>```
>...
>test_hybrid_height (iris.tests.test_trajectory.TestTrajectory) ... ok
>test_trajectory_definition (iris.tests.test_trajectory.TestTrajectory) ... ok
>test_trajectory_extraction (iris.tests.test_trajectory.TestTrajectory) ... ok
>test_tri_polar (iris.tests.test_trajectory.TestTrajectory) ... ok
>test_pcolor (iris.tests.test_mapping.TestBasic) ... ok
>...
>```
>
>take ages to run
>always...

**Comment by QuLogic** [comment]
Maybe SciTools/cartopy#772?

**Comment by dkillick** [comment]
Maybe this issue is addressed by #2240?

**Comment by QuLogic** [comment]
It appears there might not be any missing tests, so maybe? Or it could just be killing the processes earlier?
