### ISSUE TITLE
Export matplotlib collections to vector filetypes

### ISSUE THREAD

**Issue by isedwards** [SciTools/iris#223]
Export contour information to vector file formats, e.g. shapefile / WKT (possibly GML...)

Where style information exists (e.g. linestyle / polygon fill colour) create a corresponding SLD (Styled Layer Descriptor) for use in GIS packages and software such as GeoServer.

**Comment by bjlittle** [comment]
@isedwards Not much actively has happen on this issue in the last 8 years, so I'm going to close this issue.

Reopen this issue if you want to push this forwards. Thanks.

**Comment by isedwards** [comment]
Bit late in the year for a spring clean?

I'm happy for these to close
