### ISSUE TITLE
Differences between xarray and Iris

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2244]
I wanted somewhere to keep track of some of the differences between xarray and Iris so that we can continue to evaluate how the two packages can be more closely aligned. This is not intended as a criticism of either library, and it most certainly isn't a race 😄 !

Features/positives that aren't part of the other library:

## xarray

- [x] - a pandas-like API
- [x] - a representation of a dataset (collection of variables) where coordinates are shared
- [x] - has the ability to represent any netcdf data

## iris

- [x] - a representation of bounded quantities
- [x] - full support for non-standard calendars (e.g 360 day, noleap etc.)
- [x] - interpolation and regridding
- [x] - supports the use and creation of standards (CF) compliant data

-----

**NOTE**: I will attempt to keep this list up-to-date based on comments in the issue. Additionally, if pros/features become functionality in both packages, I will remove the tick (and annotate with a version number).

Ultimately, it would be interesting to see how easy it would be to build Iris on top of xarray so that AOS folk can have xarray's benefits without losing the domain specific capabilties of Iris'.

Ping @shoyer.

**Comment by ocefpaf** [comment]
One important difference for my workflows if the CF model in `iris`. It allows for some automation like, finding valid sea water temperature `standard_names` in a dataset (possible in `xarray` now with the `filter_by_attrs`.)

We also use `iris` as a CF compliance checker and file writer. That is probably the best and worst thing about iris at the same time.

**Comment by pelson** [comment]
Thanks @ocefpaf - I added this as a pro to both 😄

**Comment by niallrobinson** [comment]
👍 glad someone is thinking about this stuff
