### ISSUE TITLE
Polygonal extraction

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#227]
Users of satellite products would like to extract data using custom geographic polygons, from which a time-series of area-averages will be generated.

It might look something like this:
```
# Create 1D time series from an xyt cube.
mean1 = cube.extract(polygon1).collapsed([latitude", "longitude"], MEAN)
mean2 = cube.extract(polygon2).collapsed([latitude", "longitude"], MEAN)
qplt.plot(mean1)
qplt.plot(mean2)
qplt.legend()
plt.show()
```

**Comment by isedwards** [comment]
@esc24 - Suggest closing this ticket since this functionality is provided by [geometry_area_weights](http://scitools.org.uk/iris/docs/v1.7/iris/iris/analysis/geometry.html#iris.analysis.geometry.geometry_area_weights)
