### ISSUE TITLE
Move to a single stably-named folder for "whatsnew contributions".

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2289]
See problem here : #2288 

> Actually, I think it would be better if we did ***not*** include the version in the name of the contributions directory, but just had a fixed name for it. Then we wouldn't need to destroy + recreate it either.

To do this, need to :
 * Fix behaviour of [```docs/iris/src/whatsnew/aggregate_directory.py```](https://github.com/SciTools/iris/blob/master/docs/iris/src/whatsnew/aggregate_directory.py)
 * Fix help text in same
 * adjust documentation in [```docs/iris/src/developers_guide/documenting/whats_new_contributions.rst```](https://github.com/SciTools/iris/blob/master/docs/iris/src/developers_guide/documenting/whats_new_contributions.rst)

**Comment by rcomer** [comment]
I reckon this was covered by #3769.
