### ISSUE TITLE
Investigate use of dask in Iris

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2300]
Has a project board : https://github.com/SciTools/iris/projects/1

**Feature branch for this development :** https://github.com/SciTools/iris/tree/dask
Please target all PRs against that.
We can be then slightly more permissive with merging to there, rather than master.
However, bear in mind that ultimate quality + confidence must permit merging back to master !

**Comment by pp-mo** [comment]
Current key "best ideas" so far :
 * right now, biggus doesn't do a whole lot that dask cannot do, and it remains a niche product while dask is growing fast
 * Iris' current use of biggus is ***very*** limited:
   * lazy loading of PP, netcdf and Grib data: biggus.OrthoArrayAdapter / biggus.NumpyArrayAdapter
   * lazy indexing of deferred data content : biggus.Array.__getitem__
   * lazy merging of multiple data sources, via biggus.ArrayStack
   * lazy calculation of 3 statistics only : MEAN, STD + VAR
 * so here we investigate **replacing** biggus with dask
   * aim for **no** API changes, and minimal functional changes (like small calculation result differences)

**Comment by niallrobinson** [comment]
:+1:

**Comment by mrocklin** [comment]
Please let me know if you run into issues with dask.array while pursuing this.

**Comment by pp-mo** [comment]
Hi @mrocklin apologies missed this somehow !
Thanks for your interest, we are going on ok so far.
I do have one outstanding query (#2385) but I think it may be a bit of an academic argument.
I should really write that up as an issue on Dask...

**Comment by pp-mo** [comment]
> I should really write that up as an issue on Dask...

At last, I did it !
Enjoy : https://github.com/dask/dask/issues/1988

**Comment by marqh** [comment]
> Please let me know if you run into issues with dask.array while pursuing this.

Hello @mrocklin 

I have a couple of questions:

1. Where a dask array is wrapping another array-like object, how stable is the interface to access that underlying object?  For example, if I have a dask array resulting from a `da.stack` which contains 2 array-like objects, I could write some simple code to hunt through the `mydaskarray.dask` dictionary and pick out references.  Is this a reasonable approach or is it unstable?

```
        def get_something_useful(data, useful_attr='something_useful'):
            useful_collection = set()
            for dkey in data.dask.keys():
                if (isinstance(dkey, six.string_types) and
                   dkey.startswith('array-original-')):
                    if hasattr(data.dask.get(dkey), useful_attr):
                        useful_collection.add(data.dask.get(dkey).something_useful)
            return useful_collection
```

2. Does a dask array attempt to manage any data caching, for example: if an array-like object is wrapping a file access object that has a `__getitem__` call which opens a file; will dask always call `open` by simply calling `__getitem__`?

many thanks for your interest
mark

**Comment by mrocklin** [comment]
1.  It is rare to investigate the graph to get back other objects.  Typically you would just depend on Dask.array to gather data as necessary.  It will only touch the necessary objects.
2.  The single machine scheduler has an optional opportunistic caching system (see http://dask.pydata.org/en/latest/caching.html).  For general use I recommend using `persist` to explicitly keep high priority data in RAM.  http://distributed.readthedocs.io/en/latest/manage-computation.html#client-persist .  On released versions this is only available for the distributed scheduler, but will become a top level function and method in the next dask release (currently available in git-master)

**Comment by marqh** [comment]
Hi @mrocklin 

> 1. It is rare to investigate the graph to get back other objects. Typically you would just depend on Dask.array to gather data as necessary. It will only touch the necessary objects.

I would like to investigate some semantics with you, if I may?

you use 'rare' and 'Typically' but you did not pick up on the terms I enquired about 'stable' and 'unstable'

If I had a use case which I considered gave me strong cause to ask questions about the object the dask array is wrapping, is there a public interface which would be considered 'stable' from the dask library perspective?
Clearly I can obtain references, but the method I sketched out with `dkey.startswith('array-original-')` seems to me the kind of thing which could be changed in a point version release, due to an implementation detail

what do you think?

**Comment by mrocklin** [comment]
Right, so I wouldn't trust the name `'array-original'` to stick around long term.  Generally speaking no effort is made to ensure that the dask graphs are friendly for introspection.  

There *will* be a graph, it will be a Mapping, and it will follow the [spec](http://dask.pydata.org/en/latest/spec.html), but conventions about naming and such are considered developer details and may change over time without warning.

**Comment by marqh** [comment]
https://github.com/dask/dask/issues/1996 is following up on some interesting referencing

**Comment by pelson** [comment]
We now have iris master using ```dask>=0.16``` (w. heavy use of masked arrays). Iris v2.0.0 will include this change, and we are currently targeting 2017/10/27 as a date to cut the release candidate.

🎉  - huge thanks to all involved!

**Comment by mrocklin** [comment]
I'm quite glad to see this.  Please be vocal with issues in the future (as I'm sure they'll pop up).
