### ISSUE TITLE
Check full scope of Iris' usage of biggus (lazy operations)

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2302]
From [original comment in #2300](https://github.com/SciTools/iris/issues/2300#issuecomment-272910898)
> *  Iris' current use of biggus is ***very*** limited:
>     * lazy loading of PP, netcdf and Grib data: biggus.OrthoArrayAdapter / biggus.NumpyArrayAdapter
>     * lazy indexing of deferred data content : biggus.Array.__getitem__
>     * lazy merging of multiple data sources, via biggus.ArrayStack
>     * lazy calculation of 3 statistics only : MEAN, STD + VAR

**Comment by pp-mo** [comment]
**STOP PRESS**
The above list missed cube arithmetic, which adds a significant work item to the above list.

**Comment by pp-mo** [comment]
Results of a trawl through Iris code,
listing all the places biggus gets used
```
analysis
    MEAN, STD_DEV, VARIANCE
    maths
        _assert_compatible : broadcast_arrays
        _binary_op_common : broadcast_arrays
fileformats
    _pyke_rules."fc_rules_cf.krb"
        build_auxiliary_coordinate : OrthoArrayAdapter
        build_cell_measures : OrthoArrayAdapter
    netcdf
        _load_cube() : OrthoArrayAdapter
        Saver._create_cf_data_variable : save
    grib
        GribWrapper((deprecated)) : NumpyArrayAdapter
        .message.GribMessage.data : NumpyArrayAdapter
    pp
        PPField.data : (isinstance) Array
        PPField.__eq__ : (isinstance) NumpyArrayAdapter
        _create_field_data : NumpyArrayAdapter
_merge
    ProtoCube.merge : NumpyArrayAdapter, ArrayStack
coords
    AuxCoord.points(get) : (isinstance) Array
    AuxCoord.points(set) : (isinstance) Array, ConstantArray
    AuxCoord.bounds(get) : (isinstance) Array
    AuxCoord.bounds(set) : (isinstance) Array, ConstantArray
    CellMeasure.data(get) : (isinstance) Array, ndarray
cube
    Cube.__init__ : (isinstance) Array
    Cube.lazy_data() : (isinstance) Array, NumpyArrayAdapter
    Cube.has_lazy_data() : (isinstance) Array
    Cube.__getitem__ : (isinstance) Array
    Cube._intersect : LinearMosaic
    Cube._deepcopy : (isinstance) Array
```

**Comment by pp-mo** [comment]
Why don't we see concatenate in the above list of affected code areas ?

**Comment by ajdawson** [comment]
I don't know, it is right here: https://github.com/SciTools/iris/blob/master/lib/iris/_concatenate.py#L845

**Comment by pp-mo** [comment]
> @ajdawson  I don't know, it is right here ...

Right, I see that now !
I'll review the search I did as something obviously went wrong.

FYI many of these tickets will shortly be re-written or replaced with newer ones, as we will are re-evaluating the whole scope.
I'm re-planning this like mad now, in advance of a devs meeting tomorrow, as we'll be working on this over the next 2 weeks (Mon 13 - Fri 24).

**Comment by pp-mo** [comment]
It's here now : #2345
