### ISSUE TITLE
'other' cube support

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2309]
complete the refactor of any other cube.Cube code

**Comment by pp-mo** [comment]
Includes deepcopy, which is currently biggus-aware
**Relevant code sections**
(from https://github.com/SciTools/iris/issues/2302#issuecomment-273061295)
```
cube
    Cube._deepcopy : (isinstance) Array
```

**Comment by marqh** [comment]
some of this is addressed in #2369 

this tssue isn't adding to the project any more
