### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2313]
(i.e. aggregators, where lazy = min/std/var)

**Comment by pp-mo** [comment]
**Relevant code sections**
(from https://github.com/SciTools/iris/issues/2302#issuecomment-273061295)
```
analysis
    MEAN, STD_DEV, VARIANCE
    ((and various support routines))
```

**Comment by corinnebosley** [comment]
Tests skipped:
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py Test.test_mdtol
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py Test.test_common_mask_simple
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py Test.test_common_mask_broadcast

**Comment by corinnebosley** [comment]
https://github.com/SciTools/iris/pull/2402

**Comment by pp-mo** [comment]
Dask Aggregators PR : #2406 

This fixes the above test_VARIANCE.
The others appear to have since been fixed by addition of masked-data handling.
Will check + post another PR if required (i.e. not already done elsewhere).
