### ISSUE TITLE
cube arithmetic

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2314]

**Comment by corinnebosley** [comment]
Tests skipped:
- lib/iris/tests/unit/analysis/maths/__init__.py CubeArithmeticMaskingTestMixin.test_partial_mask_in_place
- lib/iris/tests/unit/analysis/maths/__init__.py CubeArithmeticMaskingTestMixin.test_partial_mask_not_in_place
- lib/iris/tests/unit/analysis/maths/test_divide.py TestMasking.test_masked_div_zero
- lib/iris/tests/unit/analysis/test_COUNT.py Test_masked
- lib/iris/tests/unit/analysis/test_PROPORTION.py Test_masked
- lib/iris/tests/unit/analysis/test_VARIANCE.py Test_masked

**Comment by pp-mo** [comment]
* lib/iris/tests/unit/analysis/test_COUNT.py Test_masked
  * lib/iris/tests/unit/analysis/test_PROPORTION.py Test_masked
  * lib/iris/tests/unit/analysis/test_VARIANCE.py Test_masked

Shurely those are statistics rather than cube arithmetic ?
Or is it somehow about both ?

**Comment by corinnebosley** [comment]
https://github.com/SciTools/iris/pull/2402
