### ISSUE TITLE
cube intersection

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2315]
Currently uses biggus.LinearMosaic

**Comment by pp-mo** [comment]
**Relevant code sections**
(from https://github.com/SciTools/iris/issues/2302#issuecomment-273061295)
```
cube
    Cube._intersect : LinearMosaic
```

**Comment by corinnebosley** [comment]
Note: May be able to replace current implementation with 'dask.array.concatenate'.  May even be able to simplify the code a little.

**Comment by corinnebosley** [comment]
https://github.com/SciTools/iris/pull/2409

**Comment by corinnebosley** [comment]
I believe that we can make more changes to this PR to fix intersection and embetter it, but this is a start.

**Comment by corinnebosley** [comment]
Py27 default tests timed out.

**Comment by corinnebosley** [comment]
Tests passing.

**Comment by lbdreyer** [comment]
Can this be closed?

**Comment by corinnebosley** [comment]
I think this can be closed now.  Any potential further improvements to this code section are not vital to this ticket.
