### ISSUE TITLE
Prototype solutions for mask-aware operations

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2316]
Enough to know how much work it would be to get Iris using dask for masked calculations 

As dask.array does not support masked arrays.

**Comment by pp-mo** [comment]
Code ideas (untested !!) for doing masked stats calculations *without* available masked operations
```
import numpy as np
import numpy.ma as ma


def ma_masked_mean(a, axis=axis):
    return ma.mean(a, axis=axis)

def masked_mean(a, axis=axis):
    a = a[:]
    a = ma.masked_array(a)
    a, m = a.data, ma.getmaskarray(a)
    a[~m] = 0.0
    counts = np.count_nonzero(m, axis)
    validmask = m & counts > 0
    fixedcounts = counts[:]
    fixedcounts[~validmask] = 1
    return np.ma.masked_array(np.sum(a, axis=axis) / fixedcounts,
                              mask=validmask)

def masked_var(a, axis=axis, ddof=0):
    a = a[:]
    a = ma.masked_array(a)
    a, m = a.data, ma.getmaskarray(a)
    a[~m] = 0.0
    counts = np.count_nonzero(m, axis=axis)
    fixedcounts = counts[:] - ddof
    validmask = m & fixedcounts > 0
    fixedcounts[~validmask] = 1
    means = np.sum(a, axis=axis) / fixedcounts
    deviations = a - means
    sqdevs = deviations * deviations
    results = np.sum(deviations, axis=axis) / fixedcounts
    return results
```

**Comment by ajdawson** [comment]
Also worth bearing in mind the discussion on whether to use masked arrays at all, or just use `nan` to represent missing values in normal arrays (like xarray).

**Comment by pp-mo** [comment]
>  just use  nan  to represent missing values

That might work, but it's not clear to me whether it can be relied on for any particular statistics function I want.
Do you have some idea that there is a standard handling of NaNs in numpy statistics functions, and even that it is mirrored in dask ?

\<RANT/>
The real problem with this stuff is that the support for masked operations is so poorly documented in numpy, especially for statistics calculations, so it needs sorting on a case-by-case basis, and you wind up "trying" things to see what works (!)
So it seems I have no real way of trusting whether NaNs will solve a problem in numpy, let alone dask, or whether the resulting solution will keep working in future.
Likewise, it seems that dask itself makes no explicit mention of masked arrays, but just throws weird errors if you try it.  For example:
```
>>> dask.array.from_array(np.ma.array([1,2], mask=False), 1e6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/dask/array/core.py", line 1806, in from_array
    token = tokenize(x, chunks)
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/dask/base.py", line 368, in tokenize
    return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/dask/utils.py", line 558, in __call__
    return self(arg)  # recurse
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/dask/utils.py", line 563, in __call__
    return lk[cls](arg)
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/dask/base.py", line 350, in normalize_array
    data = md5(x.copy().ravel().view('i1').data).hexdigest()
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/numpy/ma/core.py", line 3047, in view
    output = ndarray.view(self, dtype)
  File "/data/local/itpp/miniconda/envs/iris_dask/lib/python2.7/site-packages/numpy/ma/core.py", line 3236, in __setattr__
    self._mask.shape = self.shape
ValueError: total size of new array must be unchanged
>>> 
```
This makes me uncomfortable !!
\</RANT>

**Comment by pp-mo** [comment]
P.S.
>  whether to use masked arrays at all

Well that decision is pretty much made for iris, though I suppose we could review.
I think the oceans people are needing it, and of course matplotlib likes it.
The numpy 'separate mask array' solution has a more reliable interpretation than the alternatives. and of course it's the only completely flexible solution for integral types.
It does surprise me though that so much of the rest of the community is maybe not that bothered, hence no support in pandas or dask, even though they are explicitly based on numpy.

**Comment by pp-mo** [comment]
>  just use  nan  to represent missing values

Doesn't actually seem to work, at least  in the most obvious way ?
```
>>> nanarray = np.array([1.0, 1.0, np.nan])
>>> nanarray 
array([  1.,   1.,  nan])
>>> dan = dask.array.from_array(nanarray, 1e6)
>>> dan.compute()
array([  1.,   1.,  nan])
>>> nanarray.std()
nan
>>> nanarray.mean()
nan
>>> dan.mean().compute()
nan
>>> dan.std().compute()
nan
>>> 
```

**Comment by ajdawson** [comment]
You'd want to use `nanmean`, `nanstd` etc.

**Comment by pp-mo** [comment]
Excuse my ignorance.
I see what you mean now ...
```
>>> da.nanmean(dan).compute()
1.5
>>> da.nanstd(dan).compute()
0.5
>>> da.sum(~da.isnan(dan)).compute()
2
```

**Comment by pp-mo** [comment]
This: #2323 dips a toe in the waters of a more radical approach ...

**Comment by pp-mo** [comment]
**NOTE**: there is more to this than just stats
E.G. cube arithmetic also uses masks.

**Comment by pelson** [comment]
dask has masks... yay!
