### ISSUE TITLE
Make example code importable

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris#233]
See #98 for previous attempt.

**Comment by tkknight** [comment]
This can be closed now.  The docs have had an overhaul including the gallery (I think that was what `example_code` was quite a while ago).

Current folders:

- [docs/iris/gallery_code](https://github.com/SciTools/iris/tree/master/docs/iris/gallery_code) Python code that creates the gallery.  The code can be downloaded form the docs and run locally.
- [docs/iris/gallery_tests](https://github.com/SciTools/iris/tree/master/docs/iris/gallery_tests).  Tests for the gallery entries.

You can view the gallery here: https://scitools-iris.readthedocs.io/en/latest/generated/gallery/index.html

Each gallery entry has the code to view and downloaded, for example: https://scitools-iris.readthedocs.io/en/latest/generated/gallery/general/plot_cross_section.html#sphx-glr-generated-gallery-general-plot-cross-section-py.

If you think this is not resolved, please reopen the issue @rhattersley .
