### ISSUE TITLE
Design a testing strategy

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2338]
For managing tests during iterative development (towards: dask replaces biggus)

**Comment by pp-mo** [comment]
Ideas:
 * when refactoring some parts, unit tests will be broken : **Don't** fix/rewrite these **until** the implementation is agreed (and then **do**)
 * when you replace biggus with dask in one area, various things will break :  because effectively they then depend on both biggus *and* dask usage in Iris
  * skip out ("@skip_biggus") the tests that this breaks in other areas
  * at some point these become available for fixing : it isn't clear exactly when
    * in some cases, old-style unit tests may be too much trouble to rewrite + should be *replaced** or **ditched** -- latter case, if other areas give reasonable testing anyway

**Comment by pp-mo** [comment]
We will produce a test skip decorator "@skip_biggus", which turns off tests that break during changes.
Periodically, we should re-test with biggus "turned on" to check what is still failing.

**Comment by pp-mo** [comment]
Ideas:
 * when refactoring some parts, unit tests will be broken : within the dev process
    * skip
    * **Don't** fix/rewrite these **until** the implementation is agreed (and then **do**)
 * when you replace biggus with dask in one area, various things will break :  because effectively they then depend on both biggus *and* dask usage in Iris
   * skip out ("@skip_biggus") the tests that this breaks in other areas
   * at some point these become available for fixing : it isn't clear exactly when
   * in some cases, old-style unit tests may be too much trouble to rewrite + should be replaced or **ditched** -- the latter, if other areas give reasonable testing anyway
 * in many cases, we may feel that existing testing is inadequate for testing a refactor.  Then we should just produce some more sensible tests in advance
    * that includes when existing tests are just too closely tied to the existing implementation.
    * the changes must be developed and tested with "normal" Iris, rather than the "iris-dask" feature branch :
      1. branch from Iris upstream/master ; add new test code
      1. PR targets "upstream/master" ; review + merge there
      1. rebase iris_dask feature branch onto this + force to GitHub
      1. other outstanding PRs may then need to be rebased

**Comment by pelson** [comment]
Closed as obsolete.
