### ISSUE TITLE
Investigate option : masked arrays in dask

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2339]
Enough to know how much work it would be 
 * to get masked array support (like biggus') *into* dask.
 * to get Iris using this

**Accept:**
 * some improved certainty on likelihood this can be done ..
 * .. and an estimate of effort required
 * .. and when we might get it by ?

**Comment by pp-mo** [comment]
@bjlittle already opened a discussion on this.
See : https://github.com/dask/dask/issues/1928

**Comment by pelson** [comment]
Yay! This got done 🎉
