### ISSUE TITLE
Decide on basis of masking support

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2340]
Choose between #2357, #2358 and #2339 solutions.

So we can then implement other aspects accordingly, e.g. #2314 and #2313

**Comment by corinnebosley** [comment]
Tests skipped:
- lib/iris/tests/test_abf.py TestAbfLoad.test_load
- lib/iris/tests/test_aggregate_by.py TestAggregateBy.test_single_missing
- lib/iris/tests/test_aggregate_by.py TestAggregateBy.test_multi_missing
- lib/iris/tests/test_analysis.py TestAggregator_mdtol_keyword
- lib/iris/tests/test_cdm.py TestDataManagerIndexing.test_fancy_indexing_bool_array
- lib/iris/tests/test_cdm.py TestMaskedData.test_masked_field
- lib/iris/tests/test_cdm.py TestMaskedData.test_missing_file
- lib/iris/tests/test_cdm.py TestMaskedData.test_slicing
- lib/iris/tests/test_ff.py TestFF2PP2Cube.test_unit_pass_0
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_monotonic
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_global_xyzt_gems
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_global_xyzt_gems_iter
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_tmerc_grid_and_clim_bounds
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_lcc_grid
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_stereographic_grid
- lib/iris/tests/test_netcdf.py TestNetCDFSave
- lib/iris/tests/test_pandas.py TestAsSeries.test_masking
- lib/iris/tests/test_pandas.py TestAsSeries.test_copy_masked_false
- lib/iris/tests/test_pandas.py TestAsDataFrame.test_masking
- lib/iris/tests/test_pandas.py TestAsDataFrame.test_copy_masked_false
- lib/iris/tests/test_pandas.py TestSeriesAsCube
- lib/iris/tests/test_pandas.py TestDataFrameAsCube
- lib/iris/tests/test_peak.py TestPeakAggregator.test_peak_with_mask
- lib/iris/tests/test_peak.py TestPeakAggregator.test_peak_with_nan_and_mask
- lib/iris/tests/test_plot.py TestAttributePositive
- lib/iris/tests/test_plot.py TestPlotOtherCoordSystems
- lib/iris/tests/test_pp_cf.py TestAll
- lib/iris/tests/test_pp_module.py TestPackedPP.test_rle
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py TestAreaWeightedRegrid.test_missing_data
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py TestAreaWeightedRegrid.test_no_x_overlap
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py TestAreaWeightedRegrid.test_no_y_overlap
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py TestAreaWeightedRegrid.test_scalar_source_cube
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py TestAreaWeightedRegrid.test_non_circular_subset
- lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py TestConservativeRegrid.test_simple_missing_data
- lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py TestConservativeRegrid.test_missing_data_rotated
- lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py TestConservativeRegrid.test_rotated
- lib/iris/tests/integration/test_ff.py TestLBC.test_cube_mask
- lib/iris/tests/integration/test_netcdf.py TestLazySave.test_lazy_mask_preserve_fill_value
- lib/iris/tests/integration/test_netcdf.py TestCellMeasures.test_round_trip
- lib/iris/tests/integration/test_regrid_equivalence.py MixinCheckCode.test_source_mask
- lib/iris/tests/integration/test_regridding.py TestOSGBToLatLon
- lib/iris/tests/integration/test_trajectory.py TestTriPolar.test_tri_polar__nearest
- lib/iris/tests/unit/analysis/test_COUNT.py Test_masked
- lib/iris/tests/unit/analysis/test_PROPORTION.py Test_masked
- lib/iris/tests/unit/analysis/test_VARIANCE.py Test_masked
- lib/iris/tests/unit/analysis/cartography/test_project.py TestAll.test_cube
- lib/iris/tests/unit/analysis/interpolate/test_linear.py Test_masks
- lib/iris/tests/unit/analysis/interpolate/test_RectilinearInterpolator.py Test__call__masked
- lib/iris/tests/unit/analysis/maths/__init__.py CubeArithmeticMaskingTestMixin.test_partial_mask_in_place
- lib/iris/tests/unit/analysis/maths/__init__.py CubeArithmeticMaskingTestMixin.test_partial_mask_not_in_place
- lib/iris/tests/unit/analysis/maths/test_divide.py TestMasking.test_masked_div_zero
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____no_coord_systems
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____extrapolation_modes
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____rotated_to_lat_lon.test_grid_subset_missing_data_1
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____rotated_to_lat_lon.test_grid_subset_missing_data_2
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____rotated_to_lat_lon.test_grid_partial_overlap
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____rotated_to_lat_lon.test_grid_no_overlap
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py Test___call____circular
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py Test.test_mdtol
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py Test.test_common_mask_simple
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py Test.test_common_mask_broadcast
- lib/iris/tests/unit/cube/test_Cube.py Test___init___data.test_masked
- lib/iris/tests/unit/cube/test_Cube.py Test_xml.test_checksum_ignores_masked_values
- lib/iris/tests/unit/experimental/regrid/test__CurvilinearRegridder.py Test__call__multidimensional
- lib/iris/tests/unit/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py TestMdtol
- lib/iris/tests/unit/experimental/regrid/test_regrid_weighted_curvilinear_to_rectilinear.py Test
- lib/iris/tests/unit/fileformats/grib/save_rules/test_data_section.py TestMDI
- lib/iris/tests/unit/util/test_new_axis.py Test.test_masked_unit_array

**Comment by pp-mo** [comment]
! :fearful: !

**Comment by djkirkham** [comment]
Suggestion: Keep a reference to the mask as a dask object alongside the array object. The following class implements an array-like based on a proxy object which can be used in `dask.array.from_array()`:

```
class proxy_mask:
    def __init__(self,  proxy):
        self.proxy = proxy
        self.shape = proxy.shape
    def __getitem__(self, indices):
        res = proxy[indices]
        return res.mask if np.ma.is_masked(res) else np.array(False)
```
The problem with this is that you double the number of file reads when loading data.

**Comment by corinnebosley** [comment]
Note: Think about the mdtol kwarg.

**Comment by corinnebosley** [comment]
Decision: NaNs.
