### ISSUE TITLE
NetCDF loading

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2351]
**Accept:**
  * load NetCDF files to get cubes with lazy data
  * use iris.load_raw to get around merge requirement in "normal" loading (cf. #2350)

Note: biggus is also involved in netcdf *save*, but that has it's own ticket : #2347

**Comment by pp-mo** [comment]
Previous solution for this : #2308

This may be sufficient, but it needs reviewing.

**Comment by pp-mo** [comment]
**Relevant code sections**
(from https://github.com/SciTools/iris/issues/2302#issuecomment-273061295)
```
fileformats
    _pyke_rules."fc_rules_cf.krb"
        build_auxiliary_coordinate : OrthoArrayAdapter
        build_cell_measures : OrthoArrayAdapter
    netcdf
        _load_cube() : OrthoArrayAdapter
        Saver._create_cf_data_variable : save
```

**Comment by corinnebosley** [comment]
Have changed Biggus calls in sections outlined above to call the module iris._lazy_array instead.  Running tests now, can see a lot of fails unfortunately; too many to actually put on this ticket.  Seem to be a lot of checksum fails; arrays are not the same (although they look the same, I will have to dig deeper...)
