### ISSUE TITLE
Plotting vector fields with quiver

### ISSUE THREAD

**Issue by SimonPeatman** [SciTools/iris#2355]
Although iris.plot provides useful wrappers for certain matplotlib functions (e.g. plot, contour and contourf), one notable omission is quiver.  For example, it would be very useful to be able to plot a wind field using two Cubes which represent zonal and meridional wind:
```
import iris
import iris.plot as iplt
u, v = iris.load('wind.nc', ['eastward_wind', 'northward_wind'])
iplt.quiver(u, v)
```

This has been [mentioned before](https://github.com/SciTools/iris/pull/1923#issuecomment-176684886)  but as far as I can see no-one has opened an issue specifically for this feature request.

**Comment by dkillick** [comment]
Thanks for raising this @SimonPeatman! We will see what we can do to introduce this functionality to Iris.

Alternatively we always welcome code changes so if you felt like having a go yourself at introducing this functionality into Iris then we would be very happy both to receive the proposed change and to help you with getting it merged :smile:

**Comment by rcomer** [comment]
`iplt.quiver` was added at #3111.
