### ISSUE TITLE
Investigate option : replace masks with NaNs in Iris calculations

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2358]
**Accept:**
  * fully working tests with dask-type lazy cube data
  * all major operations have been refactored to emply NaNs in place of masked arrays

Notes:
  * Probably huge.
  * Probably needs to divide into separate tasks :
    * analyse what is involved
    * estimate effort required
    * implement (possibly)

**Comment by pp-mo** [comment]
Previous ideas here : https://github.com/SciTools/iris/issues/2316

**Comment by pelson** [comment]
Yay! We tried, realised it was a disaster, and ended up using dask's new mask array support (helping that cross the dask finish-line!). 🎉
