### ISSUE TITLE
Investigate possible slicing speed problem

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2367]
It seems that in ```tests/unit/cube/test_Cube.py -v Test_slices_over``` many of the tests got much slower when introducing the new lazy data handling (#2364).

E.G. ```test_1d_slice_coord_given```, taking 12sec instead of 1.7.
E.G. whole of ```Test_slices_over``` takes 75sec instead of 9.9sec.

This is ***decidedly peculiar***, as the test data used is *not* lazy but a real numpy array ?

**Comment by corinnebosley** [comment]
The data used in these tests are not lazy, but somewhere down the stack this happens:

cube.slices_over(stuff):
L.2718: return self.slices(stuff)
cube.slices(stuff):
L.2790: dims_index = list(self.shape)
cube.shape(stuff):
L.1594: shape = self.lazy_data.shape

I haven't worked out yet what takes so long, but this is the only place I can see that the original tests interact with the lazy array handling.

**Comment by pp-mo** [comment]
Spot on @corinnebosley !
Speed tests seem to indicate it is the lazy_data() call, and can be fixed by avoiding creating a lazy array if you don't need it, just by testing 'self.has_lazy_data()' first.

It seems like dask has a substantially higher overhead for creating a basic wrapper object than biggus.
A quick search shows there may be other places this could have an impact.
I'll think about that a bit longer + submit a PR to improve.

**Comment by pp-mo** [comment]
Now produced code to spit out test timings for all Iris tests.
See : #2372

**Comment by lbdreyer** [comment]
This needs reassessing to see whether it is still an issue

**Comment by dkillick** [comment]
No longer a problem.
