### ISSUE TITLE
PPField equality changes when loading data

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2368]
Given two identical pp files, loading them as fields with `iris.fileformats.pp.load()` produces fields which compare as unequal before the data is touched, but equal afterwards:
```
>>> import iris.fileformats.pp
>>> f1 = iris.fileformats.pp.load('file1.pp').next()
>>> f2 = iris.fileformats.pp.load('file2.pp').next()
>>> f1 == f2
False
>>> a = f1.data
>>> b = f2.data
>>> f1 == f2
True
```

**Comment by pp-mo** [comment]
Just to be clear : this happens in 'normal standard' Iris, nothing to do with Dask ?

**Comment by djkirkham** [comment]
@pp-mo Yes, normal Iris
