### ISSUE TITLE
handle fill value

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#2380]
currently fill value is patched into a dask array
see
iris._lazy_data.as_lazy_data (line 112)
```
        data.fill_value = fill_value
    elif not hasattr(data, 'fill_value'):
        data.fill_value = None  # make it look more like a biggus Array ?
    return data

```

consider alternative arrangements to enable fill value preservation

cube.fill_value may be a valid answer

**Comment by AlexHilson** [comment]
We could consider working directly with the underlying Dask graph. I've uploaded a notebook showing a (hacky) way of accessing the original fill_values after a simple concatenate operation.

https://gist.github.com/AlexHilson/42ee5f55962c49c1c6f9a99bbb250073

**Comment by corinnebosley** [comment]
Tests skipped:
- lib/iris/tests/test_abf.py TestAbfLoad.test_load
- lib/iris/tests/test_cdm.py TestMaskedData.test_save_and_merge
- lib/iris/tests/test_ff.py TestFF2PP2Cube.test_unit_pass_0
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_monotonic
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_global_xyzt_gems
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_global_xyzt_gems_iter
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_tmerc_grid_and_clim_bounds
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_lcc_grid
- lib/iris/tests/test_netcdf.py TestNetCDFLoad.test_load_stereographic_grid
- lib/iris/tests/test_pandas.py TestSeriesAsCube
- lib/iris/tests/test_pandas.py TestDataFrameAsCube
- lib/iris/tests/test_pp_cf.py TestAll
- lib/iris/tests/integration/test_netcdf.py TestLazySave.test_lazy_mask_preserve_fill_value
- lib/iris/tests/unit/fileformats/grib/save_rules/test_data_section.py TestMDI
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py TestFillValue
