### ISSUE TITLE
PP save (3 man days' effort)

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2382]
Not clear if there is serious work left here, after other factors are fixed (e.g. fill_value / mdi)
Otherwise, may be no direct dependency on lazy data implementation
Review later...

Acceptance:
See if there is anything to do here, and estimate
If there is work to do, the work itself will need estimating as a separate subsequent task

**Comment by corinnebosley** [comment]
Tests skipped:
?

**Comment by lbdreyer** [comment]
`lib/iris/tests/test_cdm.py TestMaskedData.test_save_and_merge`
Is still failing, which proves that this hasn't been done already

**Comment by lbdreyer** [comment]
We expect to spend more time working on pp saving at a later stage:

Part of this work will need to address:
[PR2453-comment](https://github.com/SciTools/iris/pull/2453#issuecomment-288759960)

**Comment by pp-mo** [comment]
I'm now combining this with #2507 ...
