### ISSUE TITLE
Ensure adequate testing for lazy data merge and concatenate (3 man days)

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2384]
At present, ```tests/unit/concatenate/test_concatenate.TestConcatenateBiggus``` is skipped, but really needs to be replaced by a dask-aware version.
I couldn't find anything specifically testing lazy merging -- I guess there *should* be something.

**Comment by djkirkham** [comment]
Extra tests have been added by https://github.com/SciTools/iris/pull/2492. I'm happy that they provide enought coverage.
