### ISSUE TITLE
Establish dialogue with dask devs

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2385]
Showcase odd behaviour of np.all / bool
See : https://github.com/SciTools/iris/issues/2308#issuecomment-273499060

**Comment by pp-mo** [comment]
Think this is also involved here : https://github.com/SciTools/iris/pull/2369/files/dd60f4298e44edf8e680f55055693bb0e68ce1d0#r101524531

**Note**: np.all(dask) is not the same as "dask.all()" -- the latter *is* a dask object (and therefore generally always tests "True")

**Comment by pelson** [comment]
Comms with the dask devs is generally excellent - extremely responsive, open and transparent. If there are issues that crop up, we can and should post them on the appropriate issue tracker (e.g. the dask one, if it is a dask bug).

Closing this issue out.
