### ISSUE TITLE
Why do we have code of the form... (1 man days' effort)

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2389]
```python
if (isinstance(data, np.ma.masked_array) and ma.count_masked(data) == 0):
    data = data.data
```
Is there some functional difference between an ndarray and a masked_array with no masked values?

----

Things to do:

 * determine if there is a performance degradation for using masked arrays with no masks over plain numpy arrays
 * determine the extent of usage of code of this form
 * make a recommendation on how to go forward

**Comment by pp-mo** [comment]
It's my belief this is a mistaken approach.
This should be using "np.ma.is_masked()" instead.

**Comment by djkirkham** [comment]
Good point, but the intention of my question was to ask why we are bothering to unmask the array at all. If an `ndarray` and a `masked_array` with no mask are functionally equivalent, what's the point?

**Comment by pp-mo** [comment]
> If an ndarray and a masked_array with no mask are functionally equivalent, what's the point?

I'm not totally sure, but I suspect there could be significant performance differences.
For instance, whenever you assign things into a masked array you need to be checking for ```np.ma.masked``` values.
It's quite possible that this is a negligible problem, but I think we should be careful.

Having said all that, I do think that it's awkward and irritating that when you subdivide a cube by indexing you can get some masked and some unmasked sub-cubes.
I think I'd like to consider changing that.
On a related matter: @marqh just found that there is a test that wrapping a masked array with no masked points produces a cube with a matching masked data array.
So I think that is evidence that is a previous definite design decision, not some coincidence.

**Comment by marqh** [comment]
i find this behaviour hard to justify in my mind

however, our testing is widely peppered with assumptions that this will take place

i would be happy to investigate further and gather some assessments of processing time and memory overhead

if we want to change this, we can; i'd just like a little caution, as this was done with explicit intent by Iris devlopers

**Comment by pelson** [comment]
Relates somewhat to #2046.

Closing this as obsolete.
