### ISSUE TITLE
dask cube design

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#2394]
* a cube provides the public API:
  * `cube.data` `cube.lazy_data()` `cube.has_lazy_data()`
  * `cube.has_lazy_data()` only checks if `cube._numpy_data` is None
* cube's are built on numpy, dask is provided for some extra functionality
* `cube.data` is mutable, in place and `cube.data` can be assigned into
  * when an array provided to a cube, the `self._numpy_data` is that thing
* a cube has a top level metadata entries for:
  * `fill_value`, which may be `None`
  * `dtype` which may be different from the `dtype` of the dask array, but must be the same as the dtype of the`self._numpy_array` if it is not None
  * `shape` which is always the same as the shape of `self._numpy_array` / `self._dask_array`, it is immutable
  * dask interpretations of cube data have `nan`s instead of masks
* a `cube.data` call always returns a numpy array or masked array: implementation question here:
  * ~~this type is determined by the type of the stored array, not whether there are masked values within it.~~
  * ~~the returned array will be cast from a masked array to an array if there are no masked values~~
  * if the data is lazy (`self._numpy_array` is None) and if there are no masked values: the returned array will be cast from a masked array to an array; if there is a `self_numpy_array`, this will be returned as is
* `cube.lazy_data()` will either return the lazy data if the cube's data has not been realised, or a dask wrapper around the cube's data array
  * `cube.lazy_data` may act as a setter, when called with a lazy object, it sets the cube's lazy data to this.  in this case `cube._numpy_data` is set to `None`
* a cube is lazy if it does not contain a numpy array in `cube._numpy_array`, implying it contains a dask array in `cube._dask_array`
  * a numpy array wrapped in a dask array is 'lazy' in the same way as a file format proxy wrapped in a dask array is.
  * can `cube._numpy_array` and `cube._dask_array` both be not None
* all iris fileformat data proxies return numpy arrays with `nan` values, never masked arrays, and cast to float if they need to
 * should arrays always be cast, in case they need to be merged, combined, or can non nan int arrays (etc.) stay as type

**Comment by bjlittle** [comment]
@marqh I think that we need to be clear and a little bit more precise from the outset on the vernacular that we use to describe things.

When you say `a dask wrapper around the cube's data array` I'm assuming that you mean we're opting to use a `dask container` that will be a `dask array`.

Also, from your use of `dask graph` here I'm assuming that you mean, again, a `dask array`. From what I understand all dask containers contain a dask graph, which is used by the dask schedulers to parallelise the compute process.

So I'm definitely :-1: on the use of `cube._data_graph` to mean a dask array.

Also, since we're in this space, can we please change `cube._my_data` to at least `cube._data`

**Comment by bjlittle** [comment]
From above, it's not clear the relationship between `cube._my_data` and `cube._data_graph`, we need to explicitly clarify

**Comment by bjlittle** [comment]
Do we need to clarify the situation of integral data type data in the cube and any casting that's performed to cope with nan's.

Do we need to also consider promoting the dtype of the payload into the cube metadata, along with the fill value?

**Comment by bjlittle** [comment]
We need to consider any alignment of extended loader proxy behaviour. What's the contract, do they provided nan only data of is this responsibility delegated to within the cube itself to handle?

**Comment by bjlittle** [comment]
For handcrafted cubes, do we persist concrete data passed into the cube down to `cube._my_data`, or do we wrap it in a dask array so that it lives in `cube_data_graph` ? i.e. default to a lazy philosophy

Can users pass in a data array rather than a numpy array?

Should we copy any concrete data passed into the cube to sever the reference link?

**Comment by AlexHilson** [comment]
Proposal: Can cube.lazy_data also allow setting of lazy data? This would allow in place modification of cubes (e.g. cube.analysis.maths.add with the in_place flag set) without having to realize the data. 

Approaches to this could be:

a) keep the existing cube.lazy_data() implementation that will set the cubes lazy data if passed an array. 
b) convert lazy_data() into a public attribute with getter and setter

**Comment by marqh** [comment]
Is

`cube.lazy_data = cube.data`

useful syntax
it is clearer than

`cube.lazy_data(cube.lazy_data())`

should lazy_data be a settable property?

**Comment by bjlittle** [comment]
@marqh We need symmetry in the API. If we have `cube.data` then (for me) we need `cube.lazy_data`. Keeping `cube.lazy_data()` as a function reeks of something that's just been bolted on and begs the question of why is it a function, how is it difference from `cube.data`

`lazy_data` needs to elevated to the same status as `cube.data`. It allows us (and the users) to easily see that if you want to deal with concrete data then use `cube.data` for getting and setting, and if you want to deal with lazy data then `cube.lazy_data` is your buddy.

Clearly, we need to extend `cube.lazy_data` with getters and setters that allow it to deal with receiving non-lazy data and providing the contract of `lazy_data()` ... but that's not difficult.

Also, unless you have an intimate understanding of what the heck `cube.lazy_data()` is doing, then `cube.lazy_data(cube.lazy_data())` is just plain impenetrable nonsense.

**Comment by marqh** [comment]
@bjlittle i'm tempted to agree with ^^^^

**Comment by marqh** [comment]
```
dtype which may be different from the dtype of the dask array, but must be the same as the dtype of theself._numpy_array if it is not None
shape which is always the same as the shape of self._numpy_array / self._dask_array, it is immutable
```

I think we need to change these

people can mess with things in subtle ways

my new proposal is

* shape is always inferred from the data
* self._dtype exists on the cube, but it may be None
  * if None, dtype deferes down to the data object

**Comment by marqh** [comment]
I am also very minded to provide a new piece of the public API

* `cube.core_data`

(i am not precious about the name)

this is
```
    @property
    def core_data(self):
        """
        The data at the core of this cube.
        May be a numpy array or a dask array.

        """
        if self._numpy_array is not None:
            result = self._numpy_array
        else:
            result = self._dask_array
        return result
```

so it's like accessing what used to be _my_data but in the public API
you get back what is 'core' to the cube

@bjlittle @djkirkham @pp-mo 
views on this please?!

**Comment by AlexHilson** [comment]
Bit of a tangent, but is it possible to default to using lazy data internally, even if the data has already been realized? This is possible as a realized numpy array can always be wrapped in a dask array.

The benefits of this approach are:
- Internal code is clearer. No more 'if lazy: / else:' structure. 
- A lazy cube feels faster even if the underlying data is realized. E.g. arithmetic would always be lazy
- Transparently regain the ability to do multicore / multimode processing on realized cubes. 

Drawbacks:
- If a new cube is created from the lazy_data 'has_lazy_data()' would go from returning 'False' to returning 'True', even though the realized numpy array still exists inside the dask array.
- Added overhead from converting numpy -> dask

**Comment by pp-mo** [comment]
> I am also very minded to provide a new piece of the public API
    cube.core_data
(i am not precious about the name)

Personally I'd suggest ```cube.any_data``` or ```cube.any_data()```.
Actually I'd prefer the functional form, but that's just because I personally dislike "computed properties", except for just making something read-only.
( I.E. if it "just is a value" use "object.x", but if it "does something" use "object.get/set_x(...)" )

I hope this is not going to become settable, in which case it is just ```cube._my_data``` all over again !

**Comment by pp-mo** [comment]
> @marqh We need symmetry in the API... If we have cube.data then (for me) we need cube.lazy_data. Keeping cube.lazy_data() as a function reeks of something that's just been bolted on and begs the question of why is it a function, and **how/why is it different from cube.data**

In my head, the difference is that ```cube.data``` is an object you can modify (has writeable content).
Whereas, ```cube.lazy_data()``` returns some information, but you *can't modify that to change the cube*  (or at the least, shouldn't attempt to?).

**Comment by pp-mo** [comment]
> lazy_data needs to elevated to the same status as cube.data. It allows us (and the users) to easily see that if you want to deal with concrete data then use cube.data for getting and setting, and if you want to deal with lazy data then cube.lazy_data is your buddy.

I thought we just ***agreed*** that real and lazy data are *not* on a par, and 'real' data is still the primary basis.
As-in : see declarations at top of ticket.
No ?

**Comment by pp-mo** [comment]
> Also, unless you have an intimate understanding of what the heck cube.lazy_data() is doing, then cube.lazy_data(cube.lazy_data()) is just plain impenetrable, unobvious nonsense.

I totally agree with this bit, and I think the usage should simply be consistent with cube *creation*...
Although you can't modify ```cube.lazy_data()```, you can re-base the cube onto a different lazy graph.
You can present either real or lazy data tp the cube constructor, and the cube just works it out, so I don't see why we can't do this with ```cube.data =``` too.
We should use "cube.data = <lazy object>" in place of ```cube.lazy_data(<lazy>)```.

**Comment by bjlittle** [comment]
@pp-mo Interesting. 

In that case you're likely to see code like this 
```python
cube.data = cube.lazy_data()
``` 
to make a cube with **concrete** data into a cube with **lazy** data (so if this were to happen the `cube._dask_array` should be set and the `cube._numpy_array` should be cleared. Right?)

This is opposed to the proposed 
```python
cube.lazy_data = cube.data
```

To me the second option is pretty clear what it's doing i.e. take this concrete data and make it lazy within the cube.

The danger of the first option is that it could be read as "take this lazy data and make it concrete"

We need to be clear on the message that we want to give to users and sympathetic on how they might interpret it. 

I'm not against `cube.data = cube.lazy_data()` but as long as we're happy explaining that `cube.data` is the **only** way in to setting data in an existing cube **and** it's smart enough to do the right thing. This would mean that `cube.lazy_data()` should stay as a function, it should **not** be capable of setting lazy data within the cube - it's only job is to return the lazy data from the cube i.e. the actual lazy data, or a lazy version of the concrete data.

**Comment by pelson** [comment]
I think this conversation has led its course - the iris 2.0 release candidate is making heavy use of dask, and there is no doubt that the interface is highly influenced by this discussion.
