### ISSUE TITLE
Consider allowing specifying chunk shape when creating lazy array. 

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2397]
The netCDF and PP proxy objects could be made more efficient: netCDF by specifying the chunk shape from the data variable; PP by specifying the field shape perhaps.

**Comment by bjlittle** [comment]
@corinnebosley :+1: for being able to specify the dask array `chunks` per proxy. 

The question is what should the default be per proxy? which I guess is pretty much tied to the file format that the data payload is coming from ...

Without thinking about it too much I would assume that for PP it makes sense to have `chunks` that are the size of the PPField, as to do anything the whole `PPField` has to be read; even to index into it (correct me if I'm wrong there)

For GRIB, we could align the `chunks` to the message size, akin to a `PPField` ... that kinda makes sense to me. Although the `gribapi` may offer a little bit more sophistication.

For NetCDF, well that's a little different, perhaps that could default to align with the underlying HDF5 chunk sizes?
