### ISSUE TITLE
Get all Iris tests working again (5 man days' effort)

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2398]
(refactor or replace implementation-specific tests)

**Comment by lbdreyer** [comment]
Relevant Issue: #2443

**Comment by lbdreyer** [comment]
Remove all `skip_biggus` skippers:
ldreyer@eld347 $ grep -ilr --color "@tests.skip_biggus"
- [ ] tests/test_pickling.py
- [ ] tests/test_cdm.py
- [ ] tests/test_cube_to_pp.py
- [ ] tests/test_analysis_calculus.py
- [ ] tests/test_pp_cf.py
- [ ] tests/test_pp_module.py
- [ ] tests/integration/test_aggregated_cube.py
- [ ] tests/integration/test_regridding.py
- [ ] tests/integration/test_pp.py
- [ ] tests/integration/experimental/test_regrid_ProjectedUnstructured.py
- [ ] tests/integration/test_netcdf.py
- [ ] tests/test_abf.py
- [ ] tests/test_netcdf.py
- [ ] tests/unit/concatenate/test_concatenate.py
- [ ] tests/unit/fileformats/rules/test__make_cube.py
- [ ] tests/unit/fileformats/grib/message/test_GribMessage.py
- [ ] tests/unit/fileformats/grib/test_load_cubes.py
- [ ] tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- [ ] tests/unit/fileformats/netcdf/test_save.py
- [ ] tests/unit/fileformats/netcdf/test__load_cube.py
- [ ] tests/unit/fileformats/test_rules.py
- [ ] tests/unit/fileformats/pp/test_PPField.py
- [ ] tests/unit/experimental/regrid/test__CurvilinearRegridder.py
- [ ] tests/unit/cube/test_Cube__operators.py
- [ ] tests/unit/analysis/maths/test_add.py
- [ ] tests/unit/analysis/maths/test_multiply.py
- [ ] tests/unit/analysis/maths/test_subtract.py

**Comment by pp-mo** [comment]
In context of #2507, I'm grabbing these ones (so, ticked them above) :
`lib/iris/tests/test_cube_to_pp.py:236`
`lib/iris/tests/test_cube_to_pp.py:270`
`lib/iris/tests/test_pp_cf.py:84`
 ==> "pp/bmdi problem"

`lib/iris/tests/test_pp_module.py:245 test_rle`
 ==> "Test loads in pp file and checks the data/mask which is different to the expected"

`lib/iris/tests/integration/test_pp.py:51`
`lib/iris/tests/integration/test_pp.py:86`
`lib/iris/tests/integration/test_pp.py:122`
 ==> Seg fault

**Comment by pp-mo** [comment]
:champagne: :cake:
