### ISSUE TITLE
rolling_window can crash with MemoryError

### ISSUE THREAD

**Issue by SimonPeatman** [SciTools/iris#2413]
On several occasions I have found, when using fairly large amounts of data (e.g. a few years of daily, single-level UM output at N216), that Cube.rolling_window() crashes with a MemoryError.  The problem goes away if I split the data into smaller chunks so presumably I am just running out of memory.

I have done a quick experiment with a relatively small Cube of shape (117, 40, 21, 57), about 22MB of data.  After reading in the Cube and performing rolling_window with window=20, the total memory usage of my IPython process increased by 134MB.  That is, the amount of memory Iris used to perform a rolling_window was about 6 times the size of the original data, which seems like a lot.

The rolling_window documentation says it "does not yet have support for lazy evaluation".  I assume that lazy evaluation would ease the memory problem.  Could this be implemented?

**Comment by pp-mo** [comment]
Not sure if this has been dealt with elsewhere, but it is really old with no further info here.

It is still the case that rolling_window does not support lazy operation, so it can easily fail on larger datasets with a memory error.  I fully expect that was the whole problem here.

It should be *possible* to calculate this in a lazy fashion.
We might fix that one day ?
I have not created an issue, as a current demand for this is not clear.
