### ISSUE TITLE
Add stash to cf mapping changes to change log

### ISSUE THREAD

**Issue by tv3141** [SciTools/iris#2414]
A few names in the cf to stash mapping in `lib/iris/fileformats/um_cf_map.py ` were corrected in [Iris 1.11](https://github.com/SciTools/iris/compare/v1.10.x...v1.11.x#diff-1680206bdc5cfaa83e14428f5ba0f848) and [Iris 1.12](https://github.com/SciTools/iris/compare/v1.11.x...v1.12.x#diff-1680206bdc5cfaa83e14428f5ba0f848).

I think changes to cf-standard names should be part of future version change logs, as they break existing code.

**Comment by ajdawson** [comment]
Thanks for bringing our attention to this. We should be recording these changes in our documentation as you suggest.
