### ISSUE TITLE
All-lazy statistics

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2418]
Ideally, make all stats calculate **via dask**, instead of requiring a alternative 'real data' algorithm.

Wishlist:
  * [ ] retain support for *non-lazy* user functions : automatically (?) convert to lazy ?
  * [ ] when stat is computed, _don't_ realise the source cube
    * ( see also:  `aggregated_by` should not realise source cube #2928 )
  * mostly about Aggregators, but also ..
    * [ ] consider 'aggregated_by' as well as 'collapse' ..
    * [ ] .. ? and rolling_window ? 
    * N.B. `collapse`, `aggregated_by` + `rolling_window` are the only existing stats methods
  * [ ] (vague objective) make _user-defined_ custom aggregators as simple as possible
  * [ ] simplify mechanism of Aggregator creation so only one calculation function is supplied (lazy or not)
  * [ ] (internal code hygiene) simplify cube / aggregator contract : AFAP move detail  away from cube code into generic Aggregator code

**Comment by pp-mo** [comment]
Providing a Lazy-Only-Aggregator is really pretty easy.
*E.G* some quick proof-of-priniciple code example here:
https://gist.github.com/pp-mo/12f97ec50ebc3e6f5c90cbf6d271d41c

***However,*** the way the real/lazy split is handled explicitly in existing cube operations is currently rather messy, and properly simplifying all that might be rather more work.

N.B. there are just 3 cube statistical operations at present : 
`collapsed`, `aggregated_by` and `rolling_window`.

**Comment by lbdreyer** [comment]
@pp-mo surely this has been completed by now?

**Comment by pp-mo** [comment]
> surely this has been completed by now?

Absolutely not :  it would ideally mean that `Aggregator`s have only an `aggregate` method and not an alternative `lazy_aggregate`, or at the least that the "main" one should call the "lazy" one.

**Comment by pelson** [comment]
I believe I'm up for doing this, but it isn't clear on the parts that remain. @pp-mo - could you produce a list of the things that, when done, would allow us to close this issue?

**Comment by rcomer** [comment]
If this were done, would the operators still accept user-defined non-lazy aggregators?

**Comment by pelson** [comment]
> If this were done, would the operators still accept user-defined non-lazy aggregators?

It would be relatively easy to turn ufunc type aggregators into lazy ones if it wasn't done out of the box (though I'd expect to be able to pass non-lazy aggregators and iris would defer the call to the aggregator until the correct point). Do you have concerns for aggregators similar to ``median``, which cannot be done out of core in a single-pass?

**Comment by rcomer** [comment]
It's not something I've done recently, but I have written my own aggregators in the past.  Most obvious example is the `iris.analysis.WPERCENTILE` which I originally wrote for use in my team.  [Here](https://github.com/SciTools/iris/blob/master/lib/iris/analysis/__init__.py#L1117) is the underlying numpy function.  Would it need re-writing?

Even for the most straight-forward cases where a Dask equivalent to a numpy/scipy function exists, there is a convenience of just grabbing the numpy/scipy version and creating an aggregator from it.  If a user has a relatively small data set, learning about Dask and its functions seems like unnecessary overhead.

**Comment by pelson** [comment]
Agreed. Ideally we would be able to take any aggregator and make it lazy (though not out of core / parallelised).

**Comment by rcomer** [comment]
I believe implementing this would fix #3190.
