### ISSUE TITLE
demo "something" Friday 17th ??

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2428]
* load and save - roundtrip equality : netcdf
    * load and save - roundtrip equality : PP
  * lazy stats
    * dask graphs display
  * ?something parallel
  * efficiency + chunking explanation + demo
  * actual benefits
    * load speed
    * stats speed
    * DEFAULT -- multiprocessing scheduler

**Comment by bjlittle** [comment]
Just some thoughts ...

- I mentioned at the start of the sprint that (for me) the theme was "**core confidence**", is that still applicable?
- We've grappled with some really thorny issues and technical debt, these are worth mentioning:
  - `dask` doesn't play with masked arrays
  - `dask` has `NaN` arrays support, suitable alternative to masked arrays, but the corner case is supported masked integral data
  - `biggus` dealt with the management of masked array `fill_value`, replacing `biggus` forces `iris` to deal with this issue head on

**Comment by dkillick** [comment]
Things we should say:

 * The areas we have touched (e.g. NetCDF):
   * The things we have encountered
 * The areas we have not touched
 * What's left outstanding (@pp-mo)
