### ISSUE TITLE
fill_value support

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2429]
Fill values are now part of the cube metadata
We should not be using numpy default fill-values to save data.

Todo:
  * Review all the file formats
    * loading must set cube.fill_value where appropriate
    * saving must require one, if data is masked
    * UM files can possibly implement format-specific default values
  * merge and concatenate to deduce and propagate fill_value (as currently done by biggus)
  * other cube operations and calculations likewise need to preserve or destroy fill_value
    * statistics ; arithmetic ; regridding

Note:
many tests may need reworking
expect that some of the current behaviour is flawed

**Comment by bjlittle** [comment]
Closed by #2492
