### ISSUE TITLE
Review user documentation of 'lazy' concept (5 man days)

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2436]
See : ```docs/iris/src/developers_guide/dask_interface.rst```.
If that's the developer view, what does a user need to know?

Acceptance:
 * updated above (developer) document
    * up-to-date with new internal API
    * clear distinction between what is internal to cube.py, and what is "public" for use elsewhere
    * details of fill-value support
    * clarification of cube `metadata` meaning and usage
 * new user documentation explaining:
   * basics of how Iris works with Dask
   * the handling of fill-values

**Comment by dkillick** [comment]
Replaced by #2509
