### ISSUE TITLE
Fix cube metadata usage

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2437]
Cube.metadata is used in at least 3 ways: 
  * in Iris and user code when making one cube (often of a different shape) "like" another
  * in cube.copy(), analagous with the previous idea
  * in merge+concatenate logic, to define what data is "compatible" i.e. matching cubes that can be combined
    * NOTE: merge (at least) records cube metadata in its 'CubeSignature', but does not use *all* the metadata properties when checking these for compatibility/equivalence (see `_CubeSignature._defn_msgs`)
  * ? possibly arithmetic uses a similar 'compatibility' test as in merge (not checked) ?

The current dask code has included 2 new items in cube.metadata : `cube._dtype` and `cube.fill_value`.
IIRC this was originally done to make cube.copy() work.
I'm not sure how it affects the choice of valid combinations in merge/concatenate, possibly not at all.
It seemed to make good sense then (at least to me), but now I'm not so sure....

The problem is that copying metadata from one cube to another is not always valid if they have different data.  (See : #2442)
  * E.G. assigning metadata with dtype != None to a non-lazy cube could result in an error.
  * likewise, fill_value should not really be copied if the data is possibly different.
  * these problems will also apply to usage `cube.copy(new_data)` -- e.g. providing new data should really _clear_ `._dtype` and `.fill_value`, _as if you had assigned it_.
  * the conceptual problem here is that "metadata" is supposed to be independent of the cube data.
    * that's why cell_methods are in metadata, but cell_measures are not

ACCEPTANCE:
  * work out exactly what metadata "should" be for
  * resolve these problems !

**Comment by bjlittle** [comment]
Closed by #2492
