### ISSUE TITLE
Fix copy/metadata problems

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2442]
Because you can supply new data when copying a cube, that makes an obscure failure mode where you can supply new data but it takes `_dtype` and `fill_value` from the original cube.
More generally, this can happen any time you copy metadata from one cube to another (as most regrid code does -- e.g. [here](https://github.com/SciTools/iris/blob/v1.12.0/lib/iris/analysis/_regrid.py#L392))

We can fix this by...
  * 1. fixing copy to keep `fill_value` and `_dtype` when data is copied, but losing them when it is replaced.
  * 2. fixing metadata setter to not assign `_dtype` + `fill_value`

#2437 relates
(this is a part of that)
... however, that now rather calls into question why they are in cube metadata **at all** ?
IIRC it was originally to make cube copy work !

In fact, I think we need to be clearer what "the point" of cube.metadata actually is. 
  * presumably just so you can copy from one cube to another
  * I believe that it is intended to contain the identity aspects that are **independent** of the data
    -- hence it contains cell methods, but not cell measures.
    -- that makes it seem like these things shouldn't be in there IMHO

**Comment by bjlittle** [comment]
Closed by #2492
