### ISSUE TITLE
Remove `core-dtype` from cml (1 man days' effort)

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2448]
core-dtype was introduced whilst we were messing around with the dtype/fill_value of a cube and it's array. Once this is sorted it should be remove from the cml
https://github.com/SciTools/iris/blob/dask/lib/iris/cube.py#L2939

(see [relevant comment](https://github.com/SciTools/iris/pull/2411/files#r106912894))

**Comment by dkillick** [comment]
As of #2543, we may have a different `core_dtype` to cube `dtype`. This bit of functionality makes retaining `core_dtype` in the CML beneficial, so we think we want to retain this for the time being.
