### ISSUE TITLE
lib/iris/tests/stock_arrays.npz inadvertently deleted?

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2455]
I noticed [this pull request](https://github.com/SciTools/iris/pull/2212/files) (On Oct 25, 2016, after the v1.10.0 release) where [updates](https://github.com/SciTools/iris/pull/2212/files#diff-abc4a60c7f52ec79f613acb077e8bbe0) were made to `lib/iris/tests/stock.py` to test whether `stock_arrays.npz` exists in the `stock` package, but then the `lib/iris/tests/stock_arrays.npz` file was [deleted](https://github.com/SciTools/iris/pull/2212/files#diff-bb81b1bdeb71f7ac7909b6a5e3852850). Was this intentional?

**Comment by ajdawson** [comment]
The description of the PR you linked makes it look intentional, yes. It's been moved to the test data repository by the looks of it. Is there a problem associated with this?

**Comment by ehogan** [comment]
Yes; when I try to use `realistic_4d` I get:
```
   File "/opt/scitools/environments/default/2017_03_02/lib/python2.7/site-packages/iris/tests/stock.py", line 476, in realistic_4d
    raise IOError('Test data is not available at {}.'.format(data_path))
IOError: Test data is not available at /opt/scitools/environments/default/2017_03_02/lib/python2.7/site-packages/iris/test_data/stock/stock_arrays.npz.
```

Ah, my apologies, I was thrown by the fact that there is a copy of `stock_mdi_arrays.npz` in the [iris/tests/](https://github.com/SciTools/iris/tree/master/lib/iris/tests) directory. This doesn't work for me because `test_data` isn't available.

Should `iris/tests/stock_mdi_arrays.npz` be removed?

**Comment by ajdawson** [comment]
You need to download the iris-test-data repository, and configure your install to find it. The test data (and test suite) aren't really part of our supported functionality, they are there as a convenience.

**Comment by marqh** [comment]
@ehogan 

do you think the provision of the test data would be a useful thing for a site wide deployment?

would you be content using an environment variable in order to access data for your uses?

ty

**Comment by ehogan** [comment]
Hi @marqh, for those wanting to run the tests and work through the user guide, it would be useful to have the test data available.

Is it not possible to continue to use [sample_data_path](https://github.com/SciTools/iris/blob/master/lib/iris/__init__.py#L457) for this?

I thought I'd reiterate my previous question (I think it may have been missed): Should `stock_mdi_arrays.npz` be removed from the [iris/tests/](https://github.com/SciTools/iris/tree/master/lib/iris/tests) directory?

**Comment by trexfeathers** [comment]
Of course a lot has changed since this discussion, but here is the current situation:
* #3913 is doing as suggested in removing `stock_mdi_arrays.npz`
* [See Testing > Running the tests in the Developer's Guide](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_running_tests.html?highlight=override_test_data_repository#running-the-tests) for the current instructions on control of test data location during testing

**Comment by ehogan** [comment]
Thanks @trexfeathers and @rcomer! :)
