### ISSUE TITLE
Problem with loading iris into Anaconda environment (Linux 64bits)

### ISSUE THREAD

**Issue by ghost** [SciTools/iris#2465]
Hello everyone, 

I'm currently facing an issue with importing iris into Spyder on Linux (from Anaconda). When I try:

"import iris"

I obtain

"OSError: [UT_PARSE] Failed to open UDUNITS-2 XML unit database"

I saw similar topics, but on Windows. Could anyone help me into understanding and solving this issue?
Could it be a path issue?

Thanks for your help,

Kaede

**Comment by cpelley** [comment]
Sounds like udunits is not being found.

Is libudunits2.so present under your environment?

If it is, then I guess it's not being picked up for some reason.  In which case you could try specifying its path in an iris site.cfg file:
```
cat > lib/iris/etc/site.cfg <<EOL
[System]
udunits2_path = ${CONDA_PREFIX}/lib/libudunits2.so
EOL
```

(where CONDA_PREFIX is an environmental variable set by conda for your currently sourced environment)

**Comment by Kaede22** [comment]
Thank you for your answer.

I will check it and keep you in touch with the progression.

2017-04-04 3:45 GMT-04:00 Carwyn Pelley <notifications@github.com>:

**Comment by marqh** [comment]
hello @Kaede22 

please may you check if you have a python package called `cf_units` installed

```
import cf_units
```

this should be imported and handle access to an underlying  `udunits2` package

**Comment by Kaede22** [comment]
Hello marqh

I checked the command :

*import cf_units*

I received :


*ImportError: cannot import name config*

I read some topics which say it could be related to circular import
dependency, but I don't know how to solve this.


Carwyn,

I looked for your solution but I do not understand what cat > X << EOL does.

2017-04-07 4:59 GMT-04:00 marqh <notifications@github.com>:

**Comment by Kaede22** [comment]
Any idea how to solve the issue?

**Comment by cpelley** [comment]
Hmm strange, I'm afraid I'm not all too familiar with cf_units or the deployment of packages to Anaconda.  @marqh any ideas?

**Comment by rcomer** [comment]
The OP of this issue is now a ghost, so I think we can close.
