### ISSUE TITLE
Remove config file

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2470]
Everything useful in the `site.cfg` seems now to be a path.
Some of those (iris-test-data) are now primarily managed through the import chain anyway, with temporary override provided via an environment variable.
The sole current exception seems to be "palette_path" but, being a path, it could presumably be managed in the same way.

I think the existing "point" of  `iris.config` is to manage settings depending on the external system, which we don't want hard-wired into the code (Iris or user).
However, if ***all*** those settings are going to be just paths, then we actually don't need a file for that and we can get rid of it.

**Comment by pp-mo** [comment]
As a module, `iris.config` is required for interpreting sytem-level controls and defining default settings.
I'm still trying to imagine what those might be, if they can't be determined in the code itself, and aren't paths.
Something like host names ?

**Comment by pelson** [comment]
cc: @corinnebosley. I think you have prior on this 😉 

I'll keep this in the 2.0.0 milestone for the next few days, but this isn't strictly something that *has* to get done by then (though this *is* the opportune time).

**Comment by djkirkham** [comment]
There's also `dot_path`. 

@pp-mo I'm curious as to why you think handling paths as imports is a better solution. Presumably you mean something like `iris_sample_data`? It makes sense in that case since the sample data is a resource we want to manage. But for a path to a location on the machine it seems like a heavy-handed approach

**Comment by pp-mo** [comment]
> why you think handling paths as imports is a better solution

Purely that ***if*** all the optional resources we require are in fact Python modules, ***then*** we can just use Python package management to control it, and we don't need a config file at all.

If there are significant counter-examples then it won't work, but right now it seems to me that all the uses we used to have for this are evaporating.
