### ISSUE TITLE
ECCODES (3 man days' effort)

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#2480]
A time-bound (two people, 1.5 days) scoping activity. If it all just falls into place, then great, do it! :+1:

**Comment by marqh** [comment]
I have expended a couple of hours or so on this and made lots of progress

I have a branch, derived from the iris-grib > iris work:
https://github.com/marqh/iris/pull/57

commits up to  	ae8bfef are already adopted

the latter commit on this PR take us very close to a fully functional eccodes based GRIB capability, on python3 and python2

the python2 tests all pass, after a little bit of MDI shenanigans, reflecting changes in the interface after discussion in the WMO expert team about signed and unsigned integers

there are five Python3 tests failing with numerical differences (and one import issue) which will take a little work to bottom out, but I expect really not much

https://travis-ci.org/marqh/iris/jobs/219254123
```
Ran 3961 tests in 263.127s

FAILED (SKIP=45, errors=1, failures=4)
```

This work is dependent on conda-forge for eccodes, which is on master now, but not the dask branch

this is pretty much done now though, and I may get around to the remaining Python3 tests before too long anyhow

**Comment by pelson** [comment]
Merged in https://github.com/SciTools/iris-grib/pull/92
