### ISSUE TITLE
Can't find pyke

### ISSUE THREAD

**Issue by guziy** [SciTools/iris#2482]
Hi:

Could you please direct me to where I should look for pyke module? I've tried one on github, but it does not seem to work on python3 (I have an error due to an oldstyle print while installing iris)

Cheers

**Comment by QuLogic** [comment]
Pyke3 is available on [SourceForge](https://sourceforge.net/projects/pyke/files/pyke/1.1.1/); it's not single-source, you need to get the pyke3 zip for Python 3.

**Comment by guziy** [comment]
Thanks @QuLogic: that solved my initial problem.
