### ISSUE TITLE
Albers Conical Equal Area Projection

### ISSUE THREAD

**Issue by cvelascof** [SciTools/iris#2496]
Hi All

Do you have any plans to implement in iris the Albers conical equal area projection in the near future?
So far I only found one reference in the whole iris reporsitory 
"CF_GRID_MAPPING_ALBERS = 'albers_conical_equal_area'" at https://github.com/SciTools/iris/blob/c577f76dbf490e9fbe9cbc0cfa6d25b5925f88d8/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L1051

Is there is any documentation on how add a new projection to iris?

Cheers

Carlos

**Comment by pelson** [comment]
Hi @cvelascof. What are you looking for in particular? NetCDF I/O? GRIB?

It is unlikely that there will be anybody who needs this more than yourself, so if you are interested in developing the feature, I can try to give some pointers?

**Comment by cvelascof** [comment]
Hi @pelson 
I would be happy to help to develop a NetCDF I/O for Albers Conical Equal area projection, but I would need some advice on how to add the new projection to Iris. Which routines and config files must me modified.

**Comment by pelson** [comment]
Best bet: follow the lambert azimuthal as a template.
Ping me on here if there is anything I can help with.

**Comment by cvelascof** [comment]
@pelson 
Hi Phil,

I have pushed the changes to add Albers Conical Equal Area projection into iris.
Unfortunately the Travis CI build failed (https://travis-ci.org/SciTools/iris/builds/333076377) because some experimental routines unrelated with my changes cannot run in python2.7. 
See (https://travis-ci.org/SciTools/iris/builds/333076377):
test_inverted (iris.tests.experimental.test_raster.TestGeoTiffExport) ... ERROR
test_masked (iris.tests.experimental.test_raster.TestGeoTiffExport) ... ERROR
test_unmasked (iris.tests.experimental.test_raster.TestGeoTiffExport) ... ERROR
because 
ImportError: No module named _gdal_array

Any ideas about how can I proceed?

Cheers

Carlos

**Comment by pelson** [comment]
> Any ideas about how can I proceed?  (``ImportError: No module named _gdal_array``)

We've seen this recently on master. Rebasing against upstream/master should fix the issue for you on travis.

There is a lot of overlap between this and #2496. Would you mind coordinating with @cvelascof to ensure you aren't duplicating effort on the Albers equal-area conic projection.

**Comment by pelson** [comment]
Closed by #2943
