### ISSUE TITLE
Iris equality

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2497]
We need to revisit and discuss cube equality in light of this [comment](https://github.com/SciTools/iris/pull/2492#discussion_r112453458), raised during the integration of the `DataManager` into the `Cube`.

How does cube equality relate to the job of merge and concatenate? How does this relate to how equality is performed between other iris objects, such as coordinates, cell measures, aux factories? etc

**Comment by pelson** [comment]
This isn't going to get in for v2.0. Such a fundamental issue should have come up by now if we were having issues with cube equality, right?

Anyway, I'm completely up for discussing this in the future, but will close this particular issue unless we actually need it.
