### ISSUE TITLE
Cube data API refactor

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2505]
Discuss cube API change/rationalisation with regards to how data, lazy data and real data are accessed, including usage of convenience method `core_data`, may overlap with #2506.

Also see https://github.com/SciTools/iris/pull/2461#discussion_r108866967

Action follow-on tickets if we decide to action an API refactor.

**Comment by dkillick** [comment]
After discussion, we have decided to maintain the status quo here.
