### ISSUE TITLE
PP load/save BMDI (5 man days' effort)

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2507]
Ensure that PP `BMDI` and `fill_value` is being handled correctly for PP load/save.

**Comment by pp-mo** [comment]
Not necessarily ***all*** about BMDI, but setting out to fix outstanding load/save and test problems.

**Comment by pp-mo** [comment]
Taking these skipped tests on from #2382 :
from [this comment](https://github.com/SciTools/iris/issues/2382#issuecomment-280377648)

`lib/iris/tests/test_cdm.py TestMaskedData.test_save_and_merge`
`lib/iris/tests/test_pp_module.py TestPackedPP.test_wgdos`
 ==> those both now fixed, according to #2398

`lib/iris/tests/test_pp_module.py TestPackedPP.test_rle`
  ==> **outstanding**

**Comment by pp-mo** [comment]
Tests highlighted by, + taken out of #2398
`lib/iris/tests/test_cube_to_pp.py:236`
`lib/iris/tests/test_cube_to_pp.py:270`
`lib/iris/tests/test_pp_cf.py:84`
 ==> "pp/bmdi problem"

`lib/iris/tests/test_pp_module.py:245 test_rle`
 ==> "Test loads in pp file and checks the data/mask which is different to the expected"

`lib/iris/tests/integration/test_pp.py:51`
`lib/iris/tests/integration/test_pp.py:86`
`lib/iris/tests/integration/test_pp.py:122`
 ==> Seg fault

**Comment by pp-mo** [comment]
Here's the PR : #2507

**Comment by dkillick** [comment]
Closed now that #2564 has been merged.
