### ISSUE TITLE
Set cube's fill value using the missingValue key in Grib2

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2515]
Regarding GRIB2

Currently, at save time, we use the cube's fill value to set the `missingValue` key. However, at load time we ignore the `missingValue` key at don't set a fill value on the cube, thus losing that information.

**Comment by ajdawson** [comment]
There is no information to ignore, grib uses a bitmap to define missing values and only stores non-missing values in the message. All the missingValue key does is determine what values are placed in the data array  when you request it as a 2d array, which I don't think we do, I think we extract the raw values and place them where we want them in a 2d array.

On save we pass a 2d array to gribapi and we have to tell it which values it should not bother saving.

**Comment by lbdreyer** [comment]
That makes sense, thanks @ajdawson !

I'll close this ticket then
