### ISSUE TITLE
In place Cube maths doesn't work correctly for operations which change dtype

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2522]
Operations in `iris.analysis.maths` that would change a Cube's dtype don't work correctly when given the `in_place` keyword. With older versions of numpy, the result will be cast to the Cube's data array's dtype (which may be correct behaviour, depending on how you look at it); with newer versions the Cube's data won't be changed at all.

When the `in_place` keyword is specified, the operation tries to write to the existing data array on the cube. With older versions of Numpy this works, but casts the dtype. With newer versions of numpy it fails and raises a `TypeError`, which is caught by [an except block](https://github.com/SciTools/iris/blob/e72d17f97a77a9e0969378263c3ab33a80b04b91/lib/iris/analysis/maths.py#L711) that is intended to be used to differentiate between Numpy ufuncs, which have an `out` parameter, and built-in in-place operators, which don't, and call the corresponding `__i<op>__` method on their first argument.

**Comment by pp-mo** [comment]
But is this really a dask issue at all ?
If not, it's just more mission creep (though I hope we're nearly done now).

**Comment by dkillick** [comment]
Scope creep or not, there is an issue here (which it looks like #2526 introduced):

```python
>>> a = np.arange(3, dtype=np.int64)
>>> cube = iris.cube.Cube(a)
>>> cube *= 5.0

Traceback (most recent call last):
  ...
ArithmeticError: Cannot perform inplace multiplication between <iris 'Cube' of unknown / (unknown) (-- : 3)> with int64 data and 5.0 with float16 data.
```

This situation is a bit ridiculous. IMO this should work exactly the same as:

```python
>>> cube = cube * 5.0
>>> print cube.dtype
float64
```

**Comment by djkirkham** [comment]
@pp-mo 
> But is this really a dask issue at all ?
> If not, it's just more mission creep (though I hope we're nearly done now).

It's been introduced as part of the dask development. It looks like hasn't worked since `__i<op>__` operators were added to the `Cube` class. The error is triggered by the `in_place` keyword being passed to `iris.analisys.maths.multiply`. Previously, cube *= 5.0` was effectively doing `cube = cube * 5.0`, and the in_place keyword wasn't passed.

Calling `iris.analisys.maths.multiply` directly with `in_place` set to `True` would always result in an error in this case.

**Comment by djkirkham** [comment]
I should make a clarification actually. The original issue I was reporting was to do with operations which use numpy ufuncs, such as log. Previously these would cast the dtype but now they fail silently. For the other operators, previously they would work but copy the data, now they fail as shown in @dkillick's example.

**Comment by pp-mo** [comment]
> should work exactly the same as

As just discussed (but maybe worth recording) ..
I think the augmented assignment and the 'in_place' concept (aka numpy 'out=') are really different things, but obviously related.

**In numpy,** use of out= implies that the content of an existing array is replaced, so basically for re-use of storage (or whatever views may share the same data).  A type change is not really expected, and allowing that to replace the data array will obviously uncouple any shared views.
Numpy used to (<=1.9 ??) enforce casting back to the existing type, but now (1.12) raises the above error message.
Like:
```
>>> np
<module 'numpy' from '/usr/local/sci/lib/python2.7/site-packages/numpy/__init__.pyc'>
>>> np.__version__
'1.8.2'
>>> a = np.arange(3)
>>> a += 1.5
>>> a
array([1, 2, 3])
>>>
```
but
```
>>> np.__version__
'1.11.1'
>>> a = np.arange(3)
>>> a += 1.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
>>> 
```
Interesting decision to change that at a minor release ...

**In Iris,** in_place *could* mean simply replace the `cube.data` content and doesn't *have* to mean actually re-using the underlying array -- but obviously we'd rather it did, *if possible*.
The existing (pre-dask) behaviour in Iris is that an in-place change will re-write the array, and currently errors if a dtype change would be required.
```
>>> iris.__version__
'1.12.0'
>>> np.__version__
'1.11.1'
>>> arr = np.arange(3)
>>> cube = iris.cube.Cube(arr)
>>> cube2 = iris.analysis.maths.add(cube, 1.3, in_place=True)
Traceback (most recent call last):
  * * *
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
>>> 
```

**Comment by pp-mo** [comment]
P.S. the error is not a dask issue.
The existing (pre-dask) behaviour in Iris is that an in-place change will re-write the array, and currently errors if a dtype change would be required.
```
>>> iris.__version__
'1.12.0'
>>> np.__version__
'1.11.1'
>>> arr = np.arange(3)
>>> cube = iris.cube.Cube(arr)
>>> cube2 = iris.analysis.maths.add(cube, 1.3, in_place=True)
Traceback (most recent call last):
  * * *
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
>>> 
```

**Comment by djkirkham** [comment]
@pp-mo 

> P.S. the error is not a dask issue.

For `+=` etc. on cubes, It's been introduced by our dask development because we now have `__iadd__` etc on the `Cube` class.

**Comment by pp-mo** [comment]
> we now have `__iadd__` etc on the Cube class

I think that's a useful benefit.
Maybe a demo citation as an example of how we're using this to improve the basics ?

**Comment by pp-mo** [comment]
To be clear, I think I now disagree with...
> This situation is a bit ridiculous. IMO this should work exactly the same as ...

Because in my head, of numpy *doesn't* allow it, I think it's ok for us to follow that.
```
>>> arr = np.arange(3)
>>> arr += 1.3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
>>> 
```

**Comment by dkillick** [comment]
>To be clear, I think I now disagree with...

>> This situation is a bit ridiculous. IMO this should work exactly the same as ...

> Because in my head, if numpy doesn't allow it, I think it's ok for us to follow that.

But this behaviour is nonsense! From a mathematical standpoint, NumPy is just not doing the right thing in this case.

**Comment by QuLogic** [comment]
This was deprecated in 1.7 and only made an error in 1.12; it wouldn't seem like such a random change if dependencies didn't get updated so slowly... (Though personally, breaking changes should probably have gone into 2.0, I'm not sure if NumPy follows those rules.)

**Comment by dkillick** [comment]
All things considered, I think we might just have to make do with this. There is a good argument to be had that Iris should replicate NumPy behaviour (whether we agree with it or not), and Iris is currently doing just that.

**Comment by djkirkham** [comment]
@dkillick Hang on, there's still an issue here. Unary operations that change the dtype, such as log, are currently failing silently when `in_place=True`. We should at least allow the `TypeError` to propagate.

**Comment by dkillick** [comment]
> there's still an issue here

Let's raise that as a separate thing then. The broader problem here is a non-issue, I think.

**Comment by djkirkham** [comment]
Umm... if you read my original comment, that's the exact thing I raised.

**Comment by dkillick** [comment]
Actually no, you said this:

> Operations in iris.analysis.maths that would change a Cube's dtype don't work correctly when given the in_place keyword.

It took until the second paragraph for you to mention the silent failure on the `TypeError`. Also, the title of this issue makes it clear that there is a general problem with inplace cube maths, the majority of which is no longer a problem. Thus, it is appropriate to close this issue and open a new issue that's more specific and isn't cluttered with unrelated discussions. New issues are cheap; there is no difficulty here.

**Comment by djkirkham** [comment]
I think it's quite clear if you read it that the issue is with operations failing silently, not when they raise an error, but to be fair I didn't mention that it was only unary operations (I didn't realise it was at the time).

> It took until the second paragraph for you to mention the silent failure on the  `TypeError`.

I didn't realise you had such a short attention span. May I should [mention your name in every paragraph](http://www.independent.co.uk/news/world/americas/donald-trump-intelligence-reports-white-house-read-them-mentioned-name-president-a7740726.html) to keep you interested.
