### ISSUE TITLE
Collapsed weights are inconsistently applied

### ISSUE THREAD

**Issue by duncanwp** [SciTools/iris#2542]
When collapsing a cube over a dimension for which the weights don't vary the result may or may not be correct (or at least what is expected) depending on the kernel used.

For example:
```
import numpy as np
import iris
from iris.coords import DimCoord
from iris.cube import Cube

lat = DimCoord(np.linspace(-10., 10., 5), standard_name='latitude', units='degrees', var_name='lat')
lon = DimCoord(np.linspace(-5., 5., 3), standard_name='longitude', units='degrees', var_name='lon')
alt = DimCoord(np.linspace(0., 7., 6),standard_name='altitude', units='metres', var_name='alt')

lat.guess_bounds()
lon.guess_bounds()

coord_list = [(lat, 0), (lon, 1), (alt, 2)]

data = np.reshape(np.arange(5 * 3 * 6), (5, 3, 6))

mock_cube = Cube(data, dim_coords_and_dims=coord_list, var_name='rain', standard_name='rainfall_rate',
                   long_name="TOTAL RAINFALL RATE: LS+CONV KG/M2/S", units="kg m-2 s-1")

weights = iris.analysis.cartography.area_weights(mock_cube)

# The weights don't make sense in this case because we're not collapsing over the latitude, in some cases this doesn't
# matter
mean = mock_cube.collapsed('altitude', iris.analysis.MEAN, weights=weights)

# But in some cases it does...
sum = mock_cube.collapsed('altitude', iris.analysis.SUM, weights=weights)

# Print the maximum difference between the collapsed cubes and a simple numpy collapse
print((mean.data - np.mean(mock_cube.data, axis=2)).max()) # Very small...
print((sum.data - np.sum(mock_cube.data, axis=2)).max()) # Very big...
```

I appreciate the weights could just be left out in this case, but I'm still a bit surprised at the difference. It appears to be the way in which the `numpy.ma.mean` method and `iris.analysis._sum` functions treat the weights. Is this to be expected?

**Comment by ajdawson** [comment]
A weighted sum is very different from a weighted mean. In the sum the values are multiplied by the weights then summed, so there is no surprise that the weighted sum is different from the unweighted sum (which is the same as a weighted sum with weights of 1). A weighted average divides through by the weights, so naturally you don't see the difference.

**Comment by duncanwp** [comment]
Ah, yes of course. Thanks Andrew :-)
