### ISSUE TITLE
Investigate DataManager.fill_value (setter) refactor

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2546]
Quoted from https://github.com/SciTools/iris/pull/2541#discussion_r115981411:

@djkirkham said:

> Following on from my comments below, I think the way this functions should work is as follows: if `fill_value` is not `None`, it constructs a dummy numpy masked array with dtype `self.dtype` and a fill value of `fill_value`. Then the actual value stored in `self._fill_value` is retrieved from that array. That way we exactly mimic what numpy does, except in the case where the fill value is `None`. What do you think?

**Comment by pelson** [comment]
Obsoleted by the use of dask masks.
