### ISSUE TITLE
test_netcdf : temp filename context manager

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#257]
Update test_netcdf to use the temp_filename context manager

**Comment by dkillick** [comment]
See #672.

**Comment by QuLogic** [comment]
That PR only adds new tests using the context manager. Presumably, this issue is about existing tests such as the class `TestNetCDFSave` which uses `save` & `os.remove` directly.

**Comment by dkillick** [comment]
@QuLogic you're probably right, but this issue is sooo old that I don't think anyone will be too fussed either way. I'm trying to close off some of these old issues and small, reasonably non-essential issues like this one are ripe for the picking...
