### ISSUE TITLE
var_name preventing cube merging

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2592]
Cubes and coords with different `var_name` attributes won't merge.

I believe this shouldn't be the case, as `var_name` is just an artefact of the netCDF file and has no bearing on the meaning of the actual data, unlike `standard_name` and `long_name`.

It's also quite difficult to tack down the reason for cubes failing to merge in this case.

**Comment by lbdreyer** [comment]
Looks like this is a replication of an existing (4 year old!) issue: #512
