### ISSUE TITLE
Publish final v2.0 documentation

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2601]

**Comment by corinnebosley** [comment]
Here are some initial suggestions for changes to the user guide: 
https://github.com/SciTools/iris/pull/2597#pullrequestreview-43667865
https://github.com/SciTools/iris/pull/2597#pullrequestreview-43666310

**Comment by pelson** [comment]
Closing this one out in favour of a task in the 2.0 project board. https://github.com/SciTools/iris/projects/16
