### ISSUE TITLE
Investigate min/max int dtype round trip

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2603]
See this [comment](https://github.com/SciTools/iris/pull/2597#discussion_r121623658) for context.

Investigate the limitation of int range values that can be converted to float and back again to int safely, and understand the scope of the problem.

Make recommendations for a way forward or advice to users.

**Comment by cpelley** [comment]
Regarding using the smallest container size, in our project I wrote a simple function for this purpose:
[ants.utils.ndarray.as_min_type](https://code.metoffice.gov.uk/trac/ancil/browser/ants/trunk/lib/ants/utils/ndarray.py?rev=3855#L295)

With full set of corresponding unittests of course [ants/tests/utils/ndarray/test_as_min_type.py](https://code.metoffice.gov.uk/trac/ancil/browser/ants/trunk/lib/ants/tests/utils/ndarray/test_as_min_type.py?rev=3855).

May come in handy here...

**Comment by djkirkham** [comment]
No longer an issue since we're no longer using NaNs to represent masked values.
