### ISSUE TITLE
Decide on environment and deploy pre-release on estate (MO specific)

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2611]

**Comment by corinnebosley** [comment]
I don't think that an alpha release is appropriate to put on any branch of the ```default``` environment, so I would push for Iris v2.0.0a0 to go into ```experimental```.  Particularly bearing in mind that [this page](http://www-avd/sci/software_stack/environments.html) (although it needs updating anyway) states that at any point we could give 2 weeks notice for the ```default-next``` environment to become ```default-current```.  This does not seem suitable for an alpha.

**Comment by pelson** [comment]
Agreed. I don't think this issue should be tracked in SciTools/iris though - it has no meaning outside of the MO's context. Happy to close?

**Comment by bjlittle** [comment]
Let's keep this open to capture any further conversation that may arise ...

**Comment by lbdreyer** [comment]
Why has this been re-opened? I don't think this or any "MO specific" issues should be on github

**Comment by lbdreyer** [comment]
This has now been done, so I'm going to close it, but again this work has no context externally
