### ISSUE TITLE
Announce pre-release to early adopters and community.

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2612]
First draft of announcement:

[version_announcement.txt](https://github.com/SciTools/iris/files/1091412/version_announcement.txt)

Suggestions for where to make announcement:
Yammer (despite how much I hate it)
Newsgroups (AVD General, more?)
...?

**Comment by corinnebosley** [comment]
Second draft of announcement, with the following tweaks and additions:

- Explicit reference to changes in behaviour for nans and masked points (not explained, just refers user to What's New).
- Explicit reference to reinstatement of iris-grib with request for feedback about this (this part specifically needs reviewing; I'm not happy with the wording of the paragraph or the capitalization of 'Iris-Grib').
- 'alpha version of pre-release candidate' changed to 'alpha pre-release candidate'.  Also not happy with this.  Not sure what words to use in what order here.
- All instances of '2.0.0a0' changed to '2.0a0'.

[version_announcement.txt](https://github.com/SciTools/iris/files/1115376/version_announcement.txt)

**Comment by lbdreyer** [comment]
The what's new link is broken, how about pointing to https://scitools-docs.github.io/iris/master/whatsnew/2.0a0.html ?

**Comment by lbdreyer** [comment]
> AVD are happy to announce that the Iris v2.0a0 is now available 

I would change to `AVD are happy to announce that Iris v2.0a0 is now available` 

> *If you are a K shell user, module may not be available. A fix is on the way. 
In the meantime, the suggested workaround is to run the following:
$ . /etc/kshrc

This is not the full workaround, the user also has to put the following into their ~/.kshrc file:
```
if [ -f /etc/kshrc ]; then
. /etc/kshrc
fi
```

**Comment by corinnebosley** [comment]
Announcement updated to include suggestions from Laura (most of which were to correct silly mistakes):

[version_announcement.txt](https://github.com/SciTools/iris/files/1119732/version_announcement.txt)
