### ISSUE TITLE
STASH regular expression

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2624]
I was just wondering whether there was a reason for using the regular expression `^\s*m(.*)s(.*)i(.*)\s*$` to determine whether a string contains a STASH code (see 
https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L308), rather than something more explicit like `^\s*m(\d{2})s(\d{2})i(\d{3})\s*$` (or even `^\s*m(\d*)s(\d*)i(\d*)\s*$`)? I have a case where the string I was checking contained the netCDF variable name `mlotstmin`, which matches with the current regular expression, even though it is not a STASH code!

**Comment by jkettleb** [comment]
As STASH codes are a UM thing and the UM uses only digits for model, section, item, then it makes sense to me that you can use the more strict regular expression.

Unless anyone knows of counter examples then can we put in a fix to make the regex more strict?  We currently have to put special code in our code bases to handle this case.

**Comment by ajdawson** [comment]
A more specific regex is appropriate for checking STASH codes. Feel free to submit a PR yourself to fix this if you have time. I've marked this as a bug and added it to the v2.0 milestone so it doesn't get lost.
