### ISSUE TITLE
Remove deprecated lib/iris/fileformats/ff.py

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2641]
The module `lib/iris/fileformats/ff` was deprecated in Iris 1.10

https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/ff.py#L20

**Comment by lbdreyer** [comment]
This includes removing:
* `iris.fileformats._ff.Grid`
* `iris.fileformats._ff.

**Comment by dkillick** [comment]
@lbdreyer actually I think we do _not_ want to remove the above items from `_ff.py` as they're all still being used – see, for example, [`_ff_replacement.py` L29](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/um/_ff_replacement.py#L29), which uses `FF2PP`. While all of this functionality is deprecated, it's also _private_ so no-one should be using it directly (and it won't emit deprecation warnings either).

We can't remove this yet as there's no replacement for the functionality! But the replacement may be `mule` in the future, at which point we can remove all of this. As such I'm going to tighten the scope of this issue to just the removal of `ff.py` – the deprecated public interface.

BTW, this is all a write-up of an offline conversation with @pp-mo, who originally put the ff deprecations in place.
