### ISSUE TITLE
Remove deprecated Class `iris.fileformats.pp.BitwiseInt`

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2646]
The class `iris.fileformats.pp.BitwiseInt` was deprecated in Iris 1.8.

https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L547

**Comment by lbdreyer** [comment]
`BitwiseInt` is being used [as a base class](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L702) so surely it can't be removed?

**Comment by dkillick** [comment]
> surely it can't be removed?

@lbdreyer I wonder if we can remove it as I think that all the bits in the subclass that make use of `BitwiseInt` are also deprecated and being removed...
