### ISSUE TITLE
Remove deprecated function `regrid_to_max_resolution`

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2665]
The function `iris.analysis.interpolate.regrid_to_max_resolution` was deprecated in Iris 1.10

https://github.com/SciTools/iris/blob/master/lib/iris/analysis/_interpolate_private.py#L642

**Comment by dkillick** [comment]
This links to #2653 so will be dealt with in #2695.

**Comment by dkillick** [comment]
Done in #2695.
