### ISSUE TITLE
Remove deprecated class `iris.fileformats.rules.CMCustomAttribute`

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2671]
The class `iris.fileformats.rules.CMCustomAttribute` was deprecated in Iris 1.10

https://github.com/lbdreyer/iris/blob/015cee9877df87d64e84146975feb9eefea84591/lib/iris/fileformats/rules.py#L250

**Comment by LukeC92** [comment]
This looks very similar to the previous issue I addressed. So long as nobody is already working on this I will remove this class and related code. Could somebody please move this to in progress?

**Comment by dkillick** [comment]
Closed by #2794.
