### ISSUE TITLE
Remove deprecated class `iris.fileformats.rules.CoordAndDims` 

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2672]
The class `iris.fileformats.rules.CoordAndDims` was deprecated in Iris 1.10

https://github.com/lbdreyer/iris/blob/015cee9877df87d64e84146975feb9eefea84591/lib/iris/fileformats/rules.py#L266

**Comment by LukeC92** [comment]
I will try working on this. Could somebody move this ticket to in progress?

**Comment by LukeC92** [comment]
I believe my Pull Request #2791 addresses this issue. All of the tests pass but I would appreciate it being reviewed and merged when appropriate.

**Comment by corinnebosley** [comment]
Closed by #2791
