### ISSUE TITLE
Remove deprecated function `iris.fileformats.rules.calculate_forecast_period`

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2673]
The class `iris.fileformats.rules.calculate_forecast_period` was deprecated in Iris 1.10

https://github.com/lbdreyer/iris/blob/015cee9877df87d64e84146975feb9eefea84591/lib/iris/fileformats/rules.py#L318

**Comment by corinnebosley** [comment]
Duplicated ticket.  See https://github.com/SciTools/iris/issues/2679
