### ISSUE TITLE
Remove deprecated `legacy_custom_rules` kwarg for `iris.fileformats.rules.Loader`

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2678]
The `legacy_custom_rules` kwarg for `iris.fileformats.rules.Loader` class was deprecated in Iris 1.9

https://github.com/lbdreyer/iris/blob/015cee9877df87d64e84146975feb9eefea84591/lib/iris/fileformats/rules.py#L872

**Comment by dkillick** [comment]
Closed by #2778
