### ISSUE TITLE
Remove deprecated function `iris.fileformats.rules.log`

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2680]
The function `iris.fileformats.rules.log` was deprecated (don't know when)

https://github.com/lbdreyer/iris/blob/015cee9877df87d64e84146975feb9eefea84591/lib/iris/fileformats/rules.py#L215

**Comment by LukeC92** [comment]
I hope to address this in the branch below. It seems to tie in with Pull Request #2679 on which my branch is based.
https://github.com/LukeC92/iris/tree/remove_rule_logging

**Comment by dkillick** [comment]
Looks like this was done as part of all the other work that's been going on in this space 👍
