### ISSUE TITLE
Update change management whitepaper

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#2692]
The work to introduce dask to Iris and release the results as Iris v2.0 has become the first significant test of Iris' [change management whitepaper](https://github.com/SciTools/iris/blob/master/docs/iris/src/whitepapers/change_management.rst). This test of the whitepaper appears to show the whitepaper is being a little too conservative on what we can and can't do at an Iris major version release.

We need to consider updating the change management whitepaper to reflect how we actually need to manage change at Iris major versions. It may be that we need to be less conservative about change at major versions – while, of course, adhering to SemVer.

Relates to [a discussion started](https://github.com/SciTools/iris/issues/2681#issuecomment-314768246) in #2681.

**Comment by pelson** [comment]
We added the temporary removal of the whitepaper pending further updates in #2862. I'll therefore move this out of the 2.0.0 milestone, but we certainly need to resolve this long-term.
