### ISSUE TITLE
Fix fill_value when saving to netCDF

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2703]
If the data is lazy masked, we aren't correctly setting the fill_value (see [here](https://github.com/SciTools/iris/pull/2699/files#diff-e055d3568b9b3f9cfe397cec7e016700R1952))

We need to set the fill_value correctly, the detail of which is given in [this comment](https://github.com/SciTools/iris/pull/2699#discussion_r130849528)

**Comment by dkillick** [comment]
Fixed by #2723
