### ISSUE TITLE
Fix fill_value when saving to pp

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2704]
When saving to pp, we now have to load in the data to get the fill_value which is not good and undos the goodness added in #2452.

Instead we could to load a slice of the array had get the fill value from that, similar to what will be done in issue #2703

**Comment by bjlittle** [comment]
We also need to consider whether we can avoid using `cm.data` in the `pp_save_rules.txt` lines 764 and 769, and revert to a cached fill_value akin to https://github.com/SciTools/iris/blob/v1.13.x/lib/iris/etc/pp_save_rules.txt#L764

**Comment by pp-mo** [comment]
#2744 addresses

**Comment by pp-mo** [comment]
Resolved by #2738
