### ISSUE TITLE
Fix PP test failiures

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2711]
Tests that need fixing:

expect mask array but get nans; get wrong bmdi
- [x] FAIL: test_save_and_merge (iris.tests.test_cdm.TestMaskedData)

expect ints get floats
- [x] FAIL: test_no_forecast_period (iris.tests.test_cube_to_pp.TestPPSave)
- [x] FAIL: test_no_forecast_time (iris.tests.test_cube_to_pp.TestPPSave)
- [x] FAIL: test_default_coord_system (iris.tests.test_cube_to_pp.TestPPSaveRules)

wrong bmdi
- [x] FAIL: test_pp_append_singles (iris.tests.test_cube_to_pp.TestPPSave)
- [x] FAIL: test_pp_save_rules (iris.tests.test_cube_to_pp.TestPPSave)
- [x] FAIL: test_user_pp_save_rules (iris.tests.test_cube_to_pp.TestPPSave)

**Comment by bjlittle** [comment]
The "wrong bmdi" class of test failures was pretty interesting ...

It's not really the case that the bmdi is wrong, it's not simply that the `bmdi` from the PP Field cannot be preserved from load through to save when the PP Field data is not masked i.e. there is no where to record the PP Field bmdi as a fill-value. In the previous world (master v2 alpha) where fill-value was an attribute on the cube, then that was possible and independent of whether the data payload was masked or not. In v1.13.x an interim solution was put in place to persist the bmdi from PP Field load through to saving (regardless of whether the PP Field data was masked) but only if the cube data was not realised - hardly ideal.

So at the moment, we're stepping back to the behaviour in iris prior to #2452

**Comment by lbdreyer** [comment]
Closed by #2728
