### ISSUE TITLE
Fix NetCDF test failures

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2712]
netcdf variable doesn't have _FillValue attribute
- [x] ERROR: test_lazy_mask_preserve_fill_value (iris.tests.integration.test_netcdf.TestLazySave)
        - Requires fix to issue #2703 in order to preserve fill_value on save
- [x] iris/tests/integration/test_netcdf.py", line 432, in test_multi_packed_multi_dtype
        - Requires fix to issue #2703, but disappearance of fill-value may be okay, PP data is not masked
- [x] iris/tests/integration/test_netcdf.py", line 427, in test_multi_packed_single_dtype
        - Loading i2 packed data for precipitation_flux is going wrong, don't know why ...
- [x] FAIL: test_netcdf_hybrid_height (iris.tests.test_netcdf.TestNetCDFSave)
- [x] FAIL: test_netcdf_save_multi2multi (iris.tests.test_netcdf.TestNetCDFSave)
- [x] FAIL: test_netcdf_save_multi2single (iris.tests.test_netcdf.TestNetCDFSave)
- [x] FAIL: test_netcdf_save_ndim_auxiliary (iris.tests.test_netcdf.TestNetCDFSave)
- [x] FAIL: test_netcdf_save_single (iris.tests.test_netcdf.TestNetCDFSave)

**Comment by bjlittle** [comment]
@lbdreyer All the TestNetCDFSave tests are fill-value related, so I'm going to put these on hold at the moment until we get the fill-value fix from @dkillick

**Comment by djkirkham** [comment]
All addressed in https://github.com/SciTools/iris/pull/2747

**Comment by pp-mo** [comment]
All good !
