### ISSUE TITLE
Fix concatenate test failures

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2715]
cube data fill value is wrong
- [ ] FAIL: test_concat_masked_2y2d_int16 (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_concat_masked_2y2d_int16_with_concrete_and_lazy (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_concat_masked_2y2d_int16_with_lazy_and_concrete (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__all_None (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__different_non_None (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__mixed (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__same_non_None (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_masked_and_unmasked__fill_value_equal (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_masked_and_unmasked_int16__fill_value_equal (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_masked_with_data_fill_value_difference_on_arrays (iris.tests.test_concatenate.Test2D)

**Comment by pp-mo** [comment]
All fixed now.
