### ISSUE TITLE
Fix other dtype related failures

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2716]
core-dtype is different but dtype is the same
- [x] FAIL: test_hybrid_height_cubes (iris.tests.integration.test_netcdf.TestSaveMultipleAuxFactories)

data dtype is ints not flaots as expected
- [x] FAIL: test_data (iris.tests.integration.test_pp.TestLoadPartialMask)
- [x] FAIL: test_lazy_data_masked__mask_set (iris.tests.unit.cube.test_Cube.Test_dtype)

**Comment by pp-mo** [comment]
By check:
 * FAIL: test_hybrid_height_cubes (iris.tests.integration.test_netcdf.TestSaveMultipleAuxFactories)
   * this fixes
 * FAIL: test_data (iris.tests.integration.test_pp.TestLoadPartialMask)
   * no longer fails
 * FAIL: test_lazy_data_masked__mask_set (iris.tests.unit.cube.test_Cube.Test_dtype)
   * **not yet done** : wait till after reorganisation from #2734
