### ISSUE TITLE
Fix other mask related failures

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2717]
expect and array with zeros where it is masked but instead have different fill values
- [x] FAIL: test_tri_polar__nearest (iris.tests.integration.test_trajectory.TestTriPolar)

the boolean mask array is wrong
- [x] FAIL: test_mdtol_below (iris.tests.unit.analysis.test_MEAN.Test_lazy_aggregate)
- [x] FAIL: test_mdtol (iris.tests.unit.analysis.test_STD_DEV.Test_lazy_aggregate)

wrong data fill value
- [x] FAIL: test__masked_ndarray (iris.tests.test_merge.TestDataMergeCombos)
- [x] FAIL: test__ndarray_masked (iris.tests.test_merge.TestDataMergeCombos)

expects lazy data but doesn't get it
- [x] FAIL: test_lazy_data (iris.tests.unit.fileformats.pp.test_as_pairs.TestAsFields)

cube is not equal to expected result
- [x] FAIL: test_iris_loading (iris.tests.test_ff.TestFFieee32)

**Comment by pp-mo** [comment]
Progress by item --
 * ~test_tri_polar__nearest (iris.tests.integration.test_trajectory.TestTriPolar)~
   * no longer fails
 * test_mdtol_below (iris.tests.unit.analysis.test_MEAN.Test_lazy_aggregate)
 * test_mdtol (iris.tests.unit.analysis.test_STD_DEV.Test_lazy_aggregate)
 * FAIL: test__masked_ndarray (iris.tests.test_merge.TestDataMergeCombos)
 * FAIL: test__ndarray_masked (iris.tests.test_merge.TestDataMergeCombos)
 * FAIL: test_lazy_data (iris.tests.unit.fileformats.pp.test_as_pairs.TestAsFields)
 * FAIL: test_iris_loading (iris.tests.test_ff.TestFFieee32)
