### ISSUE TITLE
Remove core-dtype from CML

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2720]
We no longer need the `core-dtype` entry in the CML as it is the same as the `dtype` entry for a `Cube`.

This is because within `Cube._xml_element`:
* the `core-dtype` entry calls `Cube.core_data().dtype`, and `Cube.core_data` calls `Cube._data_manager.dtype`, which calls `DataManager.core_data().dtype
* the `dtype` entry calls `Cube.core_data().dtype`, which is the same call chain as above.

**Comment by pelson** [comment]
No need to do this in the dask branch. We can do it on master once all merged back.

**Comment by djkirkham** [comment]
PR: #2823
