### ISSUE TITLE
Make PointInCell regridding scheme public

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2732]
That is, currently `iris.experimental.regrid.PointInCell`.
We anticipate this being used widely for ocean data regridding.
We should make this public so people can have confidence in using it, even for production processes.

Supporting factors:
 * it is worth promoting, as it solves some major problems being one of the few schemes that works with 2-D X and Y coordinates
 * we are now advising people to use this, so we would not contemplate actually removing this facility
 * while the underlying code can remain experimental, or private, the scheme class itself has a very straightforward API that is unlikely to change : http://scitools.org.uk/iris/docs/latest/iris/iris/experimental/regrid.html#iris.experimental.regrid.PointInCell

**Comment by pelson** [comment]
@pp-mo - I've removed the v2.0.0 milestone from this issue. I'm entirely in favour of this, but would like to have a clear milestone of what *has* to arrive in v2.0.0. This change does not meet that criteria. Is there some other milestone you'd like to log this under, or a label/some other means of remembering to get around to doing this?

**Comment by bjlittle** [comment]
@alastair-gemmell See [here](https://github.com/SciTools/iris/blob/master/lib/iris/analysis/__init__.py#L2164) for examples of schemes that are public and part of the core of Iris.

As a courtesy, also see [iris.experimental.concatenate](https://github.com/SciTools/iris/blob/master/lib/iris/experimental/concatenate.py) for an example of the exception to raise to users when they attempt to use functionality that has migrated from experimental to the core of Iris.

**Comment by lbdreyer** [comment]
Closed by #3390
