### ISSUE TITLE
Remove all EOL maintenance branches

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2736]
For the sake of cleanliness, all of our old end-of-life maintenance version branches should be removed once confirmed that they are merged back into master (i.e. so that we aren't losing commits).

In addition:
 * Remove the "decoupler" branch
 * Remove all merged feature branches

**Comment by djkirkham** [comment]
Curently working on removing the decoupler branch

**Comment by djkirkham** [comment]
`decoupler` has been deleted

**Comment by djkirkham** [comment]
Release branches:

v1.13.x
v1.12.x
v1.11.x
v1.10.x
v1.9.x
v1.8.x
v1.7.x
v1.6.x
v1.5.x
v1.4.x
v1.3.x
v1.2.x
v1.1.x
v1.0.x 
v0.9.x - PR https://github.com/SciTools/iris/pull/2853

**Comment by pelson** [comment]
Thanks @djkirkham.
