### ISSUE TITLE
Design a common strategy for handling masked data in file i/o

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2748]
Largely (but not entirely) netCDF-related concerns
 * how do we distinguish between masked + unmasked data
 * when do we attach a fill-value attribute
 * when do we check whether some valid datapoints match the fill-value "by mistake"

**Comment by pp-mo** [comment]
Some observations about netCDF4-python (tried with v1.2.4, where that matters):
  * in netCDF4-python , a "_FillValue" attribute is attached to a variable
    when the var is *created*.  This has nothing to do with setting the data.
    *   It always + only creates a "_FillValue" when the _keyword_ "fill_value" is not None.
  * when reading data from file, a masked array is returned always + only
    when there are values in that (sub-)array matching the fill-value.
    * "_FillValue" is used if present, else the dtype-specific default value
    * this is "dynamic" : the returned type can change whenever the data does
  * this masked/unmasked handling is treated DIFFERENTLY for byte data
    * this is noted as a problem, rooted in known problems for netcdf generally
    * see: https://github.com/Unidata/netcdf4-python/blob/v1.2.9rel/netCDF4/_netCDF4.pyx#L3957
  * the fill-value can *only* be assigned as part of the variable creation
    * it can't be modified afterwards, either with var._FillValue=, nor with var.setncattr
    * the 'var.setncattr' operation has been specifically blocked for this, in later releases

**Comment by pp-mo** [comment]
placeholder

**Comment by pp-mo** [comment]
@pelson initial preferred "simplest" proposal :
  * *always* record a fill-value (i.e. create a variable attribute) when storing masked data
    * even if the fill-value is inferred from the netcdf defaults
    * with lazy data, this means when *any* of the data is masked -- *which we can only determine afterwards*
  * *always* check the array against the fill value when filling, _if provided with an explicit fill-value control_
    * for masked ***or*** unmasked array (with given fill-value, or dedault)
        - check for *unmasked* points matching the value
    * for UNmasked array + given fill-value keyword
        - check for any points masking
           so implicitly : "if you really meant that, you would cast it as masked array"
    * for masked array with DEFAULT fill-value
        - check that no (unmasked) points match the (default) fillvalue
    * for UNmasked array with DEFAULT fill-value
        - STILL check
           * note that this WILL cause problems with (unmasked) BYTE data
                we will weather that for now + see if anything more needs to be done

**Comment by djkirkham** [comment]
(Basically copied from https://github.com/SciTools/iris/pull/2747#issuecomment-324361994)

>- always create netcdf data variables with a _FillValue attribute.
>- possibly make an exception for "unmasked" byte data 

This would have the same effect as not assigning a _FillValue at all because of how the netCDF4 library works. Personally, I think we should avoid writing a fill value if we don't have to; it's what we tried to do before (<=1.13), and changing it means changing a lot of test results. Though I don't much mind either way.

>- always check the array against the fill value when filling, if provided with an explicit fill-value control

OK. I'm assuming byte data would be an exception here.

>- there is also a blanket warning when saving masked bytes

**Comment by pp-mo** [comment]
Handling
 * BYTE types are special
  * warn if given any masked data
  * **do not** warn if it contains fill-values : we won't consider anything masked anyway
 * OTHER types consistent ...
  * make no difference between masked + non-masked arrays to be saved
  * warn if any fill-values are present (unmasked ones, in case of masked array)
    explain in terms of "this won't read back the same"

**Comment by pelson** [comment]
LGTM. 👍

**Comment by pp-mo** [comment]
Status report:
  * above remarks are a bit confusing in combination
  * I think the statement [here]() is a useful summary, probably still all up-to-date
  * using #2747 as the testcase, will review + re-summarise here when that is agreed + merged

**Comment by pp-mo** [comment]
Here's another go at a fuller statement

Loading:
 * on loading, *any fill-value or missing-data value defined by the format
should appear as the fill_value of a numpy masked array when realised*.
 * this must also work through deferred loading
   * ( the Proxy classes are responsible for this )

Merging:
 * merged data, from generalised "stack" and "concatenate" operations,
   *should have a fill-value equal to that of the components, if they all have the
    same fill-value*
 * in practice, merging components with different fill-values seems to
    provide a default fill-value.
   * it seems that Biggus, numpy.ma and dask currently all do this the same

Other operations (e.g. arithmetic):
 * generally *produce output with a default fill-value*

Saving:
 * the *fill-value of (numpy) masked data is **not** used in saving data*
   * (instead) we always use a default fill-value for the format
   * (except) some format.save() routines may have controls to set fill-value.

 * we aim to **check for + issue WARNINGS of fill-value 'collisions'**
   * in the following cases :
     * where masked data contains unmasked points matching a fill-value
     * unmasked data contains the format-specific default fill-value
   * this basically means : "whenever there are unmasked values which
     would read back as masked, we issue a warning + suggest a workaround"

 * netcdf is a special case, because :
   * all ordinary variable data is "potentially masked", owing to the use of
     default fill values (depending on type).
   * the exceptions are :
     * byte data is not treated as maskable unless it has an
        explicit "_FillValue" attribute
     * data may be tagged with a _NoFill attribute :
       * this is not currently officially documented, or widely implemented
         * for instance, netCDF4-python does not recognise or use this
       * that may change in future (possibly for netcdf4-python also) : 
         See discussion at : https://github.com/Unidata/netcdf-c/pull/470
   * small integers create problems, by *not* having the exemption applied
       to byte data, thus e.g. int32 data cannot in principle use a full
       range of 2**16 valid values
     * in any case, that full range rather assumes a 2s-complement
       representation, which is not itself guaranteed by netcdf.
       * But then, neither are NaNs, and both do actually work in all
             sensible cases.

**Comment by pp-mo** [comment]
The previous is open to discussion (!)
It should be consistent with the recent  #2747 and #2744

**Comment by pelson** [comment]
It looks very good to me. @djkirkham - would you be able to contribute to this discussion? Is this consistent with what you have implemented?

**Comment by pp-mo** [comment]
> @djkirkham ... Is this consistent with what you have implemented?

Just to be clear : I think this *is* now consistent with latest code (post #2747 and #2744).
If not then please say, because I really think it ought to be !

**Comment by djkirkham** [comment]
Just a few clarifications:

>  any fill-value or missing-data value defined by the format
should appear as the fill_value of a numpy masked array when realised.

By "defined by the format", do you mean the default values? Are you suggesting we don't use `_FillValue` or `BMDI` if given in the file?

> (instead) we always use a default fill-value for the format
> (except) some format.save() routines may have controls to set fill-value.

We're allowing user specified fill-values for netCDF4 passed directly through `iris.save()`

> we will check for ... fill-value 'collisions' ...  [when] unmasked data contains the format-specific default fill-value

It's still possible for a user to specify a fill-value even when the data is not masked. In fact it's useful to be able to do that in order to avoid collisions.

> data may be tagged with a _NoFill attribute ... netCDF4-python does not recognise or use this

I think netCDF4-python does honour this (but there are [issues](https://github.com/Unidata/netcdf4-python/issues/725)).

**Comment by djkirkham** [comment]
Regarding the final point, you can create a variable with a `_NoFill` attribute by setting `fill_value=False` when creating the variable. You can see the attribute with `ncdump -s`

**Comment by pp-mo** [comment]
Some answers to questions ...

> **By "defined by the format", do you mean the default values?**

Yes, if the format defines them.  That is, the type-specific ones in netcdf, and the magic BMDI value for UM files.  Grib doesn't specify anything, we'll have to see how that works out later.

>  **check for ... fill-value 'collisions' ... [when] unmasked data contains the format-specific default fill-value
> > It's still possible for a user to specify a fill-value even when the data is not masked. In fact it's useful to be able to do that in order to avoid collisions.

True.  

I will amend the comment + see if we can clarify those..
It almost seems like we should be source-controlling this statement !

**Comment by pp-mo** [comment]
> it almost seems like we should be source-controlling this statement 

Discussed with @pelson 
Possibly we can make this into an "IEP", cf. https://github.com/SciTools/iris/pull/1988
That is still not agreed, and haven't really decided whether to include in repo or not.

**Decided:**
Not ready to commit to an IEP process, so let's leave this for now.
For now, document the changes in the normal way : individually in whatsnew entries.
 * netcdf done in #2747
 * PP to-do in #2798
 * grib still to come

**Comment by pelson** [comment]
Did this get done @pp-mo? (i.e. putting it in a what's new?)

**Comment by pp-mo** [comment]
> Did this get done @pp-mo? (i.e. putting it in a what's new)

No, not as such.  The description here is for developer guidance only.
I think it is not appropriate to make a general statement about missing data handling, as these principles are only a development ideal and/or guideline :  Instead, we could have a whatsnew covering the practical changes to each fileformat.
Something like :
  * PP saves no longer respect the fill_value of masked cube data arrays.  Instead the "standard" BMDI of -1e30 is now always applied in PPField generation.  To save PP data with an alternative BMDI, use `iris.fileformats.pp.as_save_pairs` to generate PPFields and modify these before saving them to file.
 * NetCDF saves no longer respect the fill_value of masked cube data arrays.  Instead the NetCDF standard default fill values apply.  To use an alternative fill value, supply a `fill_value` keyword in the `pp.save` call.

Note: I didn't mention what happens on loads, because I think nothing there has changed.

**Comment by pp-mo** [comment]
> "NetCDF saves no longer respect the fill_value ..."

Actually we do have some whatsnew text that cover this one.
But still not for the PP save change, I think.

**Comment by dkillick** [comment]
On the topic of documenting this behaviour...

The first question must be "who is this documentation aimed at?" I think there are two main users:

* **developers**, who need to refer to the documentation of the behaviour in the future when making changes; either to ensure their changes adhere to the statements in the documentation, or that the documentation is updated in line with their changes if in the future we agree to change the behaviour. Devs would need detailed documentation.
* **users**, who may have queries about behaviour they've observed, or about how to implement custom behaviour (such as setting a specific fill-value). Users require much less documentation; a clear explanation of what will happen and a example of how to change it should suffice.

The next question is where could the documentation live? Given the above and the state of our existing documentation, the following are among the options:

* notes/improvements in appropriate docstrings for the various affected fileformat loaders and savers (for users) with a new entry in the developers guide containing the details
   * pros: quick to add as the docstrings in question already exist
   * cons: information is spread about all over the place so it may be difficult to see the coherent story as either a user or a dev; may mix user-level and developer-level information together
* a new whitepaper containing all the information, with a user-friendly summary at the top
   * pros: keep all the information together in one place
   * cons: does anyone read the whitepapers?; mixes user-level and developer-level information together
* replace the whitepapers concept with something different and still add it there
   * pros: firm up what whitepapers are all about
   * cons: need to define what "something different" is
* just leave it all here (!)
   * pros: simple, do nothing
   * cons: no-one will ever look at it again; devs will all forget it's here; not user-friendly
* something new
   * pros: might be the thing to fix all the information holes in Iris docs
   * cons: what will it be? what does it contain? where does it live? why should I look in it to find useful information?

My preference is probably evenly split between another whitepaper and improved docstrings. Further thoughts very much invited!

**Comment by pelson** [comment]
Sounds good to me @dkillick. Let's not over-do the white-paper. If it is <3 paragraphs I'd be very happy 😉 

As for the docstrings - could you take a look at doing this and ensuring the picture is consistent across the formats?

**Comment by dkillick** [comment]
Missing data whitepaper added in #2906. @pelson afraid it's a little longer than three paragraphs...

**Comment by dkillick** [comment]
Closed by #2906 being merged. Super job to all who were involved in hammering out the decisions made here :hammer: :100:
