### ISSUE TITLE
Increase nosetests timeout to stop PR tests failing

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2752]
NOTE: needs to be a ***temporary*** measure !

**Comment by lbdreyer** [comment]
Why does it need to be a temporary measure?

Is there a risk in having a higher timeout? I've never encountered a timeout when I ran tests locally

**Comment by ajdawson** [comment]
Can you try running the tests in serial on Travis to see if they still time out? That may point to/eliminate race conditions or other parallel demons as the cause of problems. (Add `--num-processors=1` to the test runner arguments).

**Comment by djkirkham** [comment]
@lbdreyer It's temporary in the sense that we need to figure out why there are so many timeouts now and hopefully reduce the time taken to run the tests.

@ajdawson I'll give that a try, thanks.

**Comment by pelson** [comment]
Closed by https://github.com/SciTools/iris/pull/2757.
