### ISSUE TITLE
Does iris.regrid() include coastline correction?

### ISSUE THREAD

**Issue by hai-peng-wang** [SciTools/iris#2759]
Hi there,

I'd like to ask the question - By using iris.regrid(), will the function automatically apply the coastline correction inside?

I tested the screen temperature by two step interpolation by Scipy and then compared with Iris.regrid. The results are the same, does this imply that the above statement is true?

I attached part of my code for you to examine my implementation of the two-step-interpolation by Scipy and the test:

~~~~~~~~~~~~~~~~
def transform_cube_by_masked_index(cube, masked_indx):
    """
    Transform the input cube based the land or sea mark given
    """
    new_cube_data = np.ma.masked_array(cube.data, mask=masked_indx)
    new_cube = cube.copy()
    new_cube.data = new_cube_data
    return new_cube

def get_cube_grid_points(cube):
    """
    Return the (longitude, latitude) as (x, y) grids from an input cube.
    """
    x = cube.coord('longitude').points
    y = cube.coord('latitude').points
    return (x, y)

def interp_by_scipy(src_data, src_grids, trg_grids, method='linear'):
    """
    Use Scipy to interpolate input source data to target grid.
    ------
    Input:
        src_data: the metadata on src_grids
        src_grids: a source grid tuple (1d_x_array, 1d_y_array)
        tgt_grids: a target grid tuple (1d_x_array, 1d_y_array)
        method: the interpolate method used by scipy RegularGridInterpolator
                only available "linear" & "nearest"
    """
    from itertools import product
    from scipy.interpolate import RegularGridInterpolator
    # Define the interpolator
    scipy_interp = RegularGridInterpolator(
            src_grids, src_data, method=method)
    # Derive
    drv_scipy_data = scipy_interp(
            list(product(trg_grids[0], trg_grids[1])))
    drv_scipy_data = drv_scipy_data.reshape(
            len(trg_grids[0]), len(trg_grids[1]))
    return drv_scipy_data

def two_stage_interp(cube_src, topo_tgt, lsm_src, lsm_tgt, method='linear'):
    """
    Do two stages interpolation (land & sea) seperately and then
    integrate the results together by using Scipy Interpolate.
    ------
    Input:
        cube_src: the phenomenon cube with the source grid;
        topo_tgt: the topography cube with the target grid;
        lsm_src: land sea mask for the source grid;
        lsm_tgt: land sea mask for the target grid;
        method: the interpolate method used by scipy RegularGridInterpolator
                only available "linear" & "nearest"
    Output:
        drv_cube: the regridded cube on the target grid
                  with integrated data of both land and sea.
    """
    # Get the land and sea index for both grids
    land_indx_src, sea_indx_src = get_land_sea_index(lsm_src)
    land_indx_tgt, sea_indx_tgt = get_land_sea_index(lsm_tgt)

    # Mask the src sea points for land cube
    cube_land_src = transform_cube_by_masked_index(cube_src, sea_indx_src)
    # Mask the src land points
    cube_sea_src = transform_cube_by_masked_index(cube_src, land_indx_src)
    # Mask the tgt sea points
    topo_land_tgt = transform_cube_by_masked_index(topo_tgt, sea_indx_tgt)
    # Mask the tgt land points
    topo_sea_tgt = transform_cube_by_masked_index(topo_tgt, land_indx_tgt)

    # Get the grids for both source and target
    land_grids_src = get_cube_grid_points(cube_land_src)
    sea_grids_src = get_cube_grid_points(cube_sea_src)

    land_grids_tgt = get_cube_grid_points(topo_land_tgt)
    sea_grids_tgt = get_cube_grid_points(topo_sea_tgt)

    # Derive the cube_aps2 from aps3
    drv_cube_land_data = interp_by_scipy(
        cube_land_src.data, land_grids_src, land_grids_tgt, method=method)

    drv_cube_sea_data = interp_by_scipy(
        cube_sea_src.data, sea_grids_src, sea_grids_tgt, method=method)

    # Combine the land & sea data together
    drv_cube_tgt = create_derive_cube(cube_src, topo_tgt)
    # Update with land data
    combined_data = np.where(land_indx_tgt,
                             drv_cube_land_data, drv_cube_tgt.data)
    # Update with sea data
    combined_data = np.where(sea_indx_tgt,
                             drv_cube_sea_data, combined_data)
    # update the cube with integrated data
    drv_cube = update_cube_with_new_data(drv_cube_tgt, combined_data)
    return drv_cube

# In the test case, it passed:
    def test_regrid_linear_coastline_iris(self):
        """
        Test the hypothesis that IRIS regridding already applies the coastline
        inside its algorithms. Use scipy linear two stage regridding to prove.
        """
        # Calculate Scipy two stage data
        drv_t_scn_scipy = two_stage_interp(
            self.t_scn_aps3, self.topo_aps2, self.lsm_aps3, self.lsm_aps2)
        scipy_results = drv_t_scn_scipy.data
        iris_results = self.drv_t_scn_iris.data
        assert_almost_equal(iris_results, scipy_results, decimal=2)
~~~~~~~~~~~~~~~~~~~~~~

I also did similarly by using iris.regrid() to do the two-stage-interpolation and have the same results with regridding without purposely doing land-sea-mask calculation. But maybe it is not necessarily proving what I asked. 

Thank you very much for your explanation and assistance in advance.

Best Regards
Haipeng

**Comment by pelson** [comment]
Hey Haipeng,

Good to hear from you.

There is no coastline correction taking place in any of the interpolation / regridding algorithms in Iris. We currently don't have any diagnostic specific regridding algorithms, which I believe would be necessary for applying sophisticated coastline corrections.

Out of interest, what kind of corrections are you looking for?

Thanks,

Phil

**Comment by hai-peng-wang** [comment]
Hi Phil,

Great to have your feedback.

What I'm after is that when regridding from a coarse grid to a finer one, the target grid point along the coastline needs to be treated specially. In short, the nearest same type of land/sea points are used to interpolate the value on the target grid point based on its type.

You're right that Iris regridding algorithms have no coastline correction (I also found out this later by asking the dump question). I've done some implementations about this last year with limitations/difficulties on validating the results with real data.

Thanks for your reply and Happy New Year! 

Haipeng

**Comment by pelson** [comment]
Cool. Thanks for letting me know.

I've never actually seen a coastline correction regridding algorithm in practice, so if you have a notebook you can share, I'd be super interested. No rush, and don't worry if you don't have anything.

Thanks!

**Comment by hai-peng-wang** [comment]
Hi Phil,

It's interesting to share and double-check my code. I need take some time to make my notebook better presented to be understood.

Cheers

**Comment by hai-peng-wang** [comment]
Hi Phil,

It's interesting to share and double-check my code. I need take some time to make my notebook to be better presented and easily understood. 

Cheers
HW

**Comment by hai-peng-wang** [comment]
Hi Phil,

Sorry about the late, too busy recently. 

I've uploaded my jupyter-notes at https://github.com/hai-peng-wang/machine_learning_regrid/blob/master/docs/MDS_iris_regrid_coastline_correction_algorithm_redev.ipynb and hope this make sense to you. My repo codes also might help.
