### ISSUE TITLE
Remove all components of Iris logger

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2797]
This Iris logger was decommissioned several years ago, but most of the components still remain in the guts of Iris.  This is becoming a problem for some users who wish to add their own logger, as the components which remain of the AVD logger override any additional ones.

I would recommend that the remaining components of the AVD Iris logger either be removed OR put back into use, but definitely not jot left as they are.

**Comment by pelson** [comment]
Some of this appears to be done in https://github.com/SciTools/iris/pull/2435.
