### ISSUE TITLE
Backward Compatability Documentation

### ISSUE THREAD

**Issue by LukeC92** [SciTools/iris#2830]
The Documentation on [Backwards Compatability](http://scitools.org.uk/iris/docs/latest/whitepapers/change_management.html#iris-backward-compatibility) could be clearer. Currently it says

"“Backwards-compatible” changes are those that leave any existing valid API usages unchanged (see terminology below). _Only such changes may be included in minor releases_."

It might be worth changing this to say:
"“Backwards-compatible” changes are those that leave any existing valid API usages unchanged (see terminology below). _Minor releases may only include backwards-compatible changes_."

or

"“Backwards-compatible” changes are those that leave any existing valid API usages unchanged (see terminology below). _Only backwards-compatible changes may be included in minor releases_."

**Comment by pp-mo** [comment]
Link to #2692
