### ISSUE TITLE
Change default behaviour for FUTURE option `cell_datetime_objects`

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2831]
This involves completing the following work:

* [x] set the default value of the FUTURE flag `cell_datetime_objects` to `True` in `iris.Future`.
* [x] raise a deprecation warning iff a user sets a value for this FUTURE flag (that is, raise a warning if the flag is set by the user, but *don't* raise a warning when the default behaviour is set up by Iris).
* [x] deprecate the old behaviour in [`iris.coords.Coord().cell()`](https://github.com/SciTools/iris/blob/master/lib/iris/coords.py#L1107) and raise a deprecation warning if a user tries to use the old behaviour.
* [x] dealing with unusual use-cases, such as https://github.com/SciTools/iris/blob/master/lib/iris/cube.py#L1954.
* [x] change all tests to expect the new default behaviour unless the test is directly testing the old behaviour.
* [x] Update all doc examples to use the new default behaviour:
    *  the section "Constraining on Time" in `docs/iris/src/userguide/loading_iris_cubes.rst`
    * `docs/iris/example_code/Meteorology/COP_1d_plot`
* [x] Add whatsnew entry.

**Comment by ajdawson** [comment]
In v2 our "future" will be the present. Shouldn't we just get rid of the old behaviour?

That is: remove the `cell_datetime_objects` future flag; trying to set it would yield the same behaviour as attempting to set an arbitrary unknown flag (e.g. `i_am_not_a_flag`). Then we do the future behaviour within `iris.coords.Coord.cell` and the old behaviour is no longer possible?

**Comment by dkillick** [comment]
@ajdawson unfortunately that would mean we remove public API without deprecation warnings, which is not a goer. What you describe is what will be true in Iris v3, once the future flags themselves have been deprecated.

**Comment by pelson** [comment]
> @ajdawson unfortunately that would mean we remove public API without deprecation warnings, which is not a goer

I pretty much agree. Whilst we are making a major change, and are well within our rights to break APIs, we also want to minimise the breakage so that we minimise the effort involved in migrating. The deprecations allow us to make the change in slower time.

Where behaviour behind a ```FUTURE.<feature> = False``` is already deprecated (e.g. unlimited time dimension on NetCDF), we *can* remove the functionality and remove the ability to set the ```FUTURE.<feature> = False```. We can also at this point entirely deprecate access to the ```FUTURE.<feature>``` state for complete removal in 3.0.

**Comment by dkillick** [comment]
We missed adding a deprecation directive to the description of `cell_datetime_objects` in the docstring for `iris.Future`. This should be done in a follow-up PR.
