### ISSUE TITLE
Fix broken doctest

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2837]
Now that @pp-mo has [restored doctests on Travis](#2833) we've a failing test that's preventing us merging to master; see https://travis-ci.org/SciTools/iris/jobs/290012281#L1393-L1401.

The failure text from the test is reproduced here:
```
File "userguide/interpolation_and_regridding.rst", line ?, in default
Failed example:
    print(new_column.coord('altitude').points)
Expected:
    [-- 494.44451904296875 588.888916015625 683.333251953125 777.77783203125
     872.2222290039062 966.666748046875 1061.111083984375 1155.555419921875 --]
Got:
    [           nan   494.44451904   588.88891602   683.33325195   777.77783203
       872.222229     966.66674805  1061.11108398  1155.55541992            nan]
```

**Comment by djkirkham** [comment]
I expect it's just a case of replacing the expected result with the actual. I encountered a few of these when working on dask masked stuff. When we had the "nans as masks" stuff, some of the tests were mistaking actual nans with masks.

**Comment by pelson** [comment]
This is priority number one - we need master to resume passing ASAP.

**Comment by dkillick** [comment]
Thanks all 👍
