### ISSUE TITLE
Check basic performance impacts of move from Biggus to Dask

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2839]
Perform minimal confidence tests
  * area of uncertainty is ***large data behaviour***  -- as not covered in standard iris test suite
  * key operations are file loading + saving.
    * (lazy stats + arithmetic are possible subsidiary areas )
  * key aspects are timings and memory usage
  * confirm that nothing *important* has a *seriously* reduced performance

Absolute-minimal large-data functions to cover :
  * loading : PP / FF/ NetCDF
  * "fast" (aka structured) loading of large FF
    * ( N.B. once loaded, we expect results are identical to normal PP/FF loads, as the lazy data provision is the same, with a proxy for each field data section )
  * data realisation : PP / FF/ NetCDF
  * saving to PP (from PP/FF/NetCDF)
  * streaming to NetCDF (from PP/FF/NetCDF)

**Comment by pp-mo** [comment]
Initial version of some "standard" performance tests, roughly tuned by hand to test proposed aspects:
https://github.com/pp-mo/iris_basic_performance_tests/tree/0.1

code: [standard_performance_tests.py](https://github.com/pp-mo/iris_basic_performance_tests/blob/0.1/standard_performance_tests.py)

Initial results comparison :
|       *version* |  Iris 1.13 | Iris 2.0a0 | Iris [<nc_simple_chunks>]() |
| --- | --- | --- | --- |

```
1v13
Test                        "PP load (plain)" :     1.076637 seconds
Test                   "PP load (structured)" :     0.847621 seconds
Test                           "PP data load" :     0.000049 seconds
Test                "Fieldsfile load (plain)" :     5.064258 seconds
Test           "Fieldsfile load (structured)" :     2.077609 seconds
Test                   "Fieldsfile data load" :     0.000008 seconds
Test                    "NetCDF load (plain)" :     0.229734 seconds
Test                       "NetCDF data load" :     0.000008 seconds
Test                          "PP save to PP" :     2.519118 seconds
Test                      "PP save to NetCDF" :     0.383260 seconds
Test                  "NetCDF save to NetCDF" :     2.181902 seconds
Test                      "NetCDF save to PP" :    69.754044 seconds

0v2a0
Test                        "PP load (plain)" :     1.293358 seconds
Test                   "PP load (structured)" :     1.005671 seconds
Test                           "PP data load" :     0.000276 seconds
Test                "Fieldsfile load (plain)" :     5.984852 seconds
Test           "Fieldsfile load (structured)" :     2.581901 seconds
Test                   "Fieldsfile data load" :     0.000014 seconds
Test                    "NetCDF load (plain)" :     0.230884 seconds
Test                       "NetCDF data load" :     0.000013 seconds
Test                          "PP save to PP" :     3.335268 seconds
Test                      "PP save to NetCDF" :     0.693001 seconds
Test                  "NetCDF save to NetCDF" :     2.847175 seconds
Test                      "NetCDF save to PP" :    76.802152 seconds

nc_small_chunks
Test                        "PP load (plain)" :     1.258870 seconds
Test                   "PP load (structured)" :     0.943731 seconds
Test                           "PP data load" :     0.000093 seconds
Test                "Fieldsfile load (plain)" :     5.838382 seconds
Test           "Fieldsfile load (structured)" :     2.610244 seconds
Test                   "Fieldsfile data load" :     0.000011 seconds
Test                    "NetCDF load (plain)" :     0.255428 seconds
Test                       "NetCDF data load" :     0.000010 seconds
Test                          "PP save to PP" :     2.628435 seconds
Test                      "PP save to NetCDF" :     0.727933 seconds
Test                  "NetCDF save to NetCDF" :     2.286657 seconds
Test                      "NetCDF save to PP" :    49.032603 seconds
```

**Comment by pelson** [comment]
Thanks @pp-mo. Useful intel.
I consider this good enough to get us through to the release candidate. 
Looks like we are going to need to do some detailed profiling on a few of these cases to identify any quick wins - no pressure to do that before the RC though.

**Comment by pp-mo** [comment]
Pushed up a fix to the data-load problem + a new set of results.
Using mk1 eyeball, I'm ok that the above results are broadly maintained
( though timings seem altogether noisier today : I had to reduce repeatability tolerances, and even then one set of tests failed )
The extra load performance measures look roughly like --

...  (version): |  "biggus" | "dask_nanmask" | "dask_masked" | dask_nanmask+% | dask_masked+%
--- | --- | --- | --- | --- | ---
PP data load                  | 0.217066 |  0.308971 |  0.298676 |  42.3%  |  37.6%
Fieldsfile data load          |  1.256854 |  1.313222 |  1.257878 |   4.5%  |  0.1%
NetCDF data load              |  2.808193 |  2.660896 |  2.150034 |   -5.2%  |  -23.4%

**Comment by pelson** [comment]
Closing this one out - we have enough info to tell us that we are not about to drop a clanger with regards to performance, even though it is clear that there is some tuning work that can/needs to be done going forwards.
