### ISSUE TITLE
Dask inferior to Biggus for streaming NetCDF data

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2840]
Encountered a specific problem while scoping #2839

It seems that streaming (unrealised) cube data from one NC file to another may be slower with Dask than Biggus.
More seriously, the memory usage seems much less well controlled, and can cause serious machine clogging,

**Comment by pp-mo** [comment]
Details:

Testing with this dataZoo file :
```
filepath = '/data/local/dataZoo/netCDF/largeFile/tas_day_HadGEM2-ES_historical_r1i1p1_18591201-20051130.nc'
nc_small = iris.load_cube(filepath)

print nc_small.shape
    (52560, 145, 192)

print nc_small.lazy_data().nbytes / 1.e6
    5853.0816

```

Size is such that 10 timepoints ~ approximately 1Mbyte of file data.

I have been timing saves of portions of this data to a new NetCDF file in the local temporary space.
Like this:
```
def time_datasave(cube):
    tmp_dir = os.path.join(os.environ['TMPDIR'], os.environ['USER'])
    tmp_filepath = os.path.join(tmp_dir, 'tmp.nc')
    t_start = datetime.datetime.now()
    iris.save(cube, tmp_filepath)
    t_end = datetime.datetime.now()
    print('Data size = {:.1f} Mbytes'.format(cube.lazy_data().nbytes / 1e6))
    print('Time taken : {:12.6f} seconds'.format(
        (t_end - t_start).total_seconds()))

```

Because of general Unix filesystem caching, things like this often need repeating to get consistent answers.
( For instance, loading this file can take about a minute, and repeating takes about 0.2 seconds ! )

**Comment by pp-mo** [comment]
Basic timings compared using above method + switching between Iris 1.13 and recent master (Iris commit [db473b1b5](https://github.com/SciTools/iris/tree/db473b1b5ff2edea3745180880430c31ed060340)) :

n-data-points | data-size | Dask time / secs (3 times)  | Biggus time / secs (3 times)
---- | ---- | ---- | ----
5000 | 0.56 Gb | 5, 1.5, 1.5 | 
10000 | 1.1 Gb | 
15000 | 

DASK
    :5000 --> 0.56Gb
        7, 7, 7
    :10000 --> 1.1Gb
        
    :15000 --> 1.7Gb
        

BIGGUS
    :5000 --> 0.56Gb
        5, 1.5, 1.5
    :10000 --> 1.1Gb
        8, 3, 3
    :15000 --> 1.7Gb
        10, 24, 17, 14

**Comment by pp-mo** [comment]
Viewing the system monitor during these tests reveals that Dask is using a lot of memory, whereas the Biggus operation hardly uses any. 
The 15k-point case produces a memory graph like this :
![screenshot_1700mb_save_memory](https://user-images.githubusercontent.com/2089069/31823288-90642364-b5a3-11e7-9c52-4319c83dd073.png)

Note: the load actually starts at about the -40 second points, and ends about 0.
What it may be doing for about 10 seconds after the memory is released is unclear.

**Comment by pp-mo** [comment]
It seemed obvious that the difference may be due to our crude chunking strategy.
But re-chunking the data does not seem to offer any immediate improvement :
```
>>> tmp = nc_small[:15000]
>>> tmp.lazy_data()
dask.array<getitem, shape=(15000, 145, 192), dtype=float32, chunksize=(15000, 145, 192)>
>>> tmp.data = tmp.lazy_data().rechunk((1, 145, 192))
>>> tmp.lazy_data()
dask.array<rechunk-merge, shape=(15000, 145, 192), dtype=float32, chunksize=(1, 145, 192)>
>>> time_datasave(tmp)
Data size = 1670.4 Mbytes
Time taken :    45.382178 seconds
>>> 
```

The system memory graph of this operation looks basically just the same as before, which is very puzzling.

**Comment by pp-mo** [comment]
Progress report:
Investigating with @djkirkham Friday (2017-10-20).
Found that while the above attempt to re-chunk has no effect, you ***can*** get this approach to work by instead supplying a chunks keyword to `da.from_array`.

**It seems...**
Re-chunking only affects the graphs built from a lazy array, and not the usage of the array itself : That is still optimised overall.

Thus, if you say `a1=da.from_array(proxy, (3,4)); a2=a1.rechunk((1,4)); a3 = a2 + 1`,
then the subsequent graph of  a3 shows 3 separate chunks of size (1,4).
However, when you evaluate `a3.compute()`, Dask still makes a single access `[0:3, 0:4]' on the proxy.

Whereas...
`a1=da.from_array(proxy, (1,4)); a3 = a2 + 1; a3.compute()`
Performs three proxy accesses `[0:1, 0;4]`, `[1:2, 0;4]`, `[2:3, 0;4]`,
which is what we basically need to avoid excessive memory usage.

Printing `repr(a3)` does not show any difference between these 2 cases, so the `chunks` keyword in the `from_array` call is setting not just the resulting property  'array.chunks' but also something fundamental about how the proxy is accessed (which can *not* be reset by a `rechunk` operation).

**Comment by pp-mo** [comment]
Awaiting #2844 merge
#2839 shows that it works

**Comment by pelson** [comment]
Think we can close this now @pp-mo? At the time of measurement, we were comparing apples & oranges (biggus with autochunking vs dask with full netcdf variable chunks). Now that we have a similar scheme for dask by default in iris, do we get back to a similar level of performance?

**Comment by pp-mo** [comment]
> Think we can close this ... Now that we have a similar scheme [[as biggus chunks]] do we get back to a similar level of performance?

#2839 indicates it should be ok.
More significantly, checking with System Monitor, the nasty memory usage was definitely fixed
