### ISSUE TITLE
Understand whether we need to do anything regarding a different dask engine

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2873]
From what I've understood, there hasn't been any *evidence* to suggest that it is necessary for iris to use anything but the defaults provided by dask. However, we do indeed prevent the default (threaded) engine and opt for the synchronous engine instead.

Without any evidence, I'd favour *not* overriding the default engine, so I'd like to gather some evidence to support its continued existence in the v2.0.0 release candidate.

**Comment by pp-mo** [comment]
#2879 addresses
