### ISSUE TITLE
Tweaks to documentation for v2.0 release

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2897]
A quick rundown of some problems I noticed checking through the [current whatsnew](https://github.com/SciTools/iris/blob/07b627b4e5292935ef975e3a5417663bd760a65c/docs/iris/src/whatsnew/2.0.rst)  + it's links ...
  * [x] the "Dask processing options" notes at the bottom of the ["Real and Lazy Data"](https://github.com/SciTools/iris/blob/07b627b4e5292935ef975e3a5417663bd760a65c/docs/iris/src/userguide/real_and_lazy_data.rst) userguide section are out-of date -- possibly can be removed altogether (see also: #2882)
  * [x] likewise, where in the initial whatsnew para talks about Dask schedulers, that is probably now obsolete.
  * a few items in the whatsnew "Deprecation removals" section really belong elsewhere :
    * [x] "iris.fileformats.pp_rules has been renamed ..."  --> in "Incompatible Changes" ?
    * [x] "When saving a cube or list of cubes in NetCDF format ..."  --> in "Incompatible Changes" ?
    * [x] "If the packing argument to iris.save is a dictionary ..."  -->  enhancement or bugfix ?
  * [x] we are still missing a whatsnew entry regarding changes to BMDI setting in saved PP data -- see [this comment](https://github.com/SciTools/iris/issues/2748#issuecomment-340775540) for some suggested text

**Comment by dkillick** [comment]
> where ... the initial whatsnew para talks about Dask schedulers

Having just read this section I think I'd prefer it if that paragraph was left in place. The statements remain true and accurate, and changing dask processing options will still affect how Iris works, it's just Iris no longer affects dask processing options at all. The paragraph might be improved by including a link to the dask docs on processing options though (this could be lifted directly from the section in the user guide that we probably no longer need).

**Comment by dkillick** [comment]
Completed in #2900 and #2903.
