### ISSUE TITLE
Improve the docs around adding/extending/replacing a graphics test

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2902]
Apologies if I've missed it, but I can't actually find any docs on how the image testing should be handled in Iris. I'm essentially looking for a guide on how to update or add a new test image.

Any pointers?

**Comment by pelson** [comment]
Phwoor. I've just found it. http://scitools.org.uk/iris/docs/latest/developers_guide/tests.html#graphics-tests

Sorry for the noise.

**Comment by pp-mo** [comment]
BUT note that the page at  http://scitools.org.uk/iris/docs/latest/developers_guide/graphics_tests.html#developer-graphics-tests is actually **still incomplete** :  I think this was left over when we cut 1.11/12/13, and still needs addressing ?

**Comment by pp-mo** [comment]
Related : #2331 #2176

**Comment by pp-mo** [comment]
Just re-checking this.
Despite the advice in the above dev-guide page, I once again can't work out how to make idiff work again...

**Comment by tkknight** [comment]
See https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_graphics_tests.html
