### ISSUE TITLE
Support for climatologies

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2904]
Support for climatologies has a few hurdles:

- Cell method information is being discarded on load (e.g. time: mean within years time: mean over years) - #1438
- Climatology bounds coords are not supported either, not even manually as the attribute is prohibited:

```Python
>>> cube.coord('time').attributes['climatology'] = 'climatology_bnds'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/atk/_dev/environments/latest/lib/python2.7/site-packages/iris/_cube_coord_common.py", line 65, in __setitem__
    raise ValueError('%r is not a permitted attribute' % key)
ValueError: 'climatology' is not a permitted attribute
```

**Comment by cpelley** [comment]
For saving we can make a fairly complete climatology.  We can set the cell method desired and we can shoehorn the climatology_bounds attribute in by altering slightly (something like climatology_bounds_).
That at least gets all the information in the file though at the expense of no longer being CF compliant.  However, on load we of course will loose our cell method information.

**Comment by pelson** [comment]
I wouldn't expect this to happen until Iris can support CF1.6 & CF1.7 properly. I've therefore classified this an enhancement, rather than a bug.

**Comment by bjlittle** [comment]
@cpelley Superseded by https://github.com/SciTools/iris/issues/3323
