### ISSUE TITLE
Remove system_test_grib_patch

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2911]
iris-grib may want to check this, but it doesn't belong in iris itself.

The offending test:

```
system_test_grib_patch (iris.tests.system_test.SystemInitialTest) ... SKIP: Test(s) require "iris-grib" package, which is not available.
```

https://github.com/SciTools/iris/blob/master/lib/iris/tests/system_test.py#L82

**Comment by gcaria** [comment]
I can't find this test on master, looks like this can be closed.

**Comment by rcomer** [comment]
Thanks @gcaria, looks like this test was removed at #3662 👍
