### ISSUE TITLE
Cube coords may have same standard name.

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#2917]
Should this work?  My gut feeling is that it shouldn't, but it does.

```python
import iris
import numpy as np

coord1 = iris.coords.DimCoord(range(4), standard_name='longitude')
coord2 = iris.coords.DimCoord(range(3), standard_name='longitude',
                               attributes={'eggs':'spam'})
coord3 = iris.coords.DimCoord(range(4), standard_name='longitude',
                               long_name='foo')

cube = iris.cube.Cube(np.arange(12).reshape(4, 3),
                      dim_coords_and_dims=[(coord1, 0), (coord2, 1)],
                      aux_coords_and_dims=[(coord3, 0)])
                      
print cube
```
gives

```
unknown / (unknown)                 (longitude: 4; longitude: 3)
     Dimension coordinates:
          longitude                           x             -
          longitude                           -             x
             eggs='spam'
     Auxiliary coordinates:
          longitude                           x             -

```

**Comment by ajdawson** [comment]
It doesn't sound like this would be meaningful. If two things have the same standard name they should be the same thing, and it probably doesn't make sense to have orthogonal dimensions that are the same thing...

I'm not sure it really matters that much though. We need to consider how easy this situation would be to arrive in, how bad it would be to arrive there, and how awkward/expensive it would be to protect against.

My gut feeling is it isn't very easy to arrive at this situation, and it wouldn't be that bad if you did...

**Comment by rcomer** [comment]
That's fair enough, though you do get an exception if you try to add duplicate coords with all the metadata matching.

**Comment by pelson** [comment]
Iris has been explicitly designed to allow cubes to have coordinates with duplicate standard names. As I recall, the CF conventions also explicitly allow this functionality (though normally they would share an axis). The usecase that we targeted related to the ability to represent multiple coordinate value observations with uncertainty (e.g. multiple depth sensors, each reading slightly different values).

That said, I do find it extremely niche behaviour - at the time of allowing this behaviour I was (and remain) extremely sceptical that it is a valuable feature. Especially given that had we not allowed duplicate standard names, we would have been able to use the standard name as a key for coordinate access.

Not sure there is anything we are going to do about this @rcomer. Are you happy for this issue to be closed?

Thanks,

**Comment by rcomer** [comment]
Thanks for taking the time to explain.  I'll close this.
