### ISSUE TITLE
Update zenodo, see https://zenodo.org/record/51860#.WTfBn7MSrSs

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2940]

**Comment by dkillick** [comment]
According to zenodo.org/account/settings/github/ (behind a login screen, hence no hyperlink), Zenodo will update automatically on cutting a new release of a tracked GitHub repo. @pelson has enabled tracking so all should be good now.

We should still make sure the badge on the README points to the latest release once we cut it, however. Looking at the links I think they're general so all is probably well here, but it is good to be certain.

**Comment by pelson** [comment]
Fixed in v2.0.x (and soon to be master). zenodo will be a DOI to the package, and from there can reference multiple versions.
