### ISSUE TITLE
Linear/Nearest neighbour regrid doesn't support zonal means

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2951]
- We can't currently regrid data with a length of only 1 in X or Y.
- What is wanted is that those cases should work as expected, analagous with "normal" 2d cases.
    - It would be acceptable that we still need X and Y dims (possibly length-1)
- We could fix the unreasonable assumption in the code [here](https://github.com/SciTools/iris/blob/master/lib/iris/analysis/_regrid.py#L235) though this is just the current point of failure and might not expose the full extent of the changes required.

Here is our workaround:
```Python
def regrid(src_cube, tgt_cube):                                             
    # Munge the source (duplicate source latitudes) so that we can utilise     
    # Linear regridding
     src_cube2 = src_cube.copy()
    src_cube2.coord(axis='x').points = -90
    src_cube2.coord(axis='x').bounds = [-180, 0]
    src_cube.coord(axis='x').points = 90
    src_cube.coord(axis='x').bounds = [0, 180]
    src_cube = iris.cube.CubeList([src_cube, src_cube2]).concatenate_cube()

    return src_cube.regrid(tgt_cube, iris.analysis.Linear())
```
Target grids can be global UM grids or whatever regional models like UKV etc.

**Comment by pp-mo** [comment]
Don't get what is meant here, in either case ?
  * nearest-neighbour can't do any averaging, practically by definition
  * linear regrid simliarly will only average between 2 nearest points in the coordinate

So the appropriate choice would seem to be an area-weighted regrid to a bounded cell in latitude.
But I think we *can* do that, regridding from any parallel lat-lon grid, with `iris.analysis.AreaWeighted`.

So what exactly is it we are missing here ?

**Comment by cpelley** [comment]
Hi @pp-mo, thanks for your interest.

Let's say:
```!python
source:      (latitude: 30; longitude: 1)
target:      (latitude: 10; longitude: 1)
```
Where longitude is identical between source and target.  We are having to test for this and unnecessarily run it through the interpolation API.  What do you think?

Cheers

**Comment by pp-mo** [comment]
> Let's say:

Interesting.
Could you be more specific about :
  * the extent of the lat + lon cells, 
  * what actual result is wanted ?
  * what it looks like when it's "not like this" (i.e. alternative of the "test for this" case)

Not asking much here 😁

**Comment by cpelley** [comment]
Hi @pp-mo, thanks for your response.  I'll pop around for a quick offline quick I think (at a time of your convenience).  Prob. save us an unnecessary to-and-fro.

Cheers

**Comment by pelson** [comment]
Closing until we have more detail. Happy to reopen when ready. 👍

**Comment by cpelley** [comment]
Thanks @pp-mo, yes.  I'll fluff out the ticket description using your comment along with my workaround for this.

**Comment by pelson** [comment]
IMO the minimum length of a dimension should be part of the interpolation scheme's definition. There should be no magic numbers - it entirely depends on the scheme. For example:

 * nearest neighbour interpolation: at least 1 point
 * linear interpolation: at least 2 points **or** an appropriate extrapolation scheme
 * cubic interpolation (not implemented): 3 points
 * area weighted [mean]: at least 1 bound

For that reason, I'm completely supportive of loosening the check if it is in the ``regrid`` method, as I believe this should be a fundamental responsibility of the regridding scheme being used.

**Comment by cpelley** [comment]
Thanks @pelson.  I think that sounds reasonable to me.  Hopefully if regridding uses the interpolation code (which in an ideal world I guess it would, but perhaps it doesn't currently -TBD) that there isn't a pre-existing creep of responsibility by the interpolation in this regard.

**Comment by nhsavage** [comment]
this is a common problem for making ancillary files where some of the important data sets are zonal means and so I have an interest in this. 

I am slowly understanding the problem here, but I think I need to look at the ANTS code now to understand exactly how the regrid is used.

**Comment by cpelley** [comment]
Thanks for your interest @nhsavage 

> ...I need to look at the ANTS code now...

You may want to look at the workaround in the ticket description.  That pretty much comes out of the ozone application.  Happy to clarify if it's not clear.

Cheers

**Comment by nhsavage** [comment]
I have to admit, I couldn't find the work around in the branch 756_OZONE_GEN as I'd missed the new function ancil_ozone.py ...

**Comment by cpelley** [comment]
- I propose we restrict the change initially to the following usecase: global zonal mean source to global/regional targets).  I think this is the most unambiguous and least controversial usecase.  How does that sound?

**Comment by nhsavage** [comment]
I see how that is unambiguous and uncontroversial. I am not sure how easy that is to achieve in the Iris code though. Any thoughts about this @pelson @pp-mo?
