### ISSUE TITLE
Lazy Loading of data when converting units

### ISSUE THREAD

**Issue by stevehadd** [SciTools/iris#2962]
Currently, if you load a cube using iris.load_cube, and then convert the units, say from Kelvin to Celsius,  all the data is then loaded into memory at that point. It would be nice if the conversion only happened when you call get_data(), and only for the data you are requesting.

**Comment by pp-mo** [comment]
Tricky !
It would be easy to "just" replace `cube.data` with `cube.core_data()` within `cube.convert_units`, 
but I don't think it would work as cf_units has no knowledge of Dask, and treats the "arrays" of values in ways that won't work with Dask arrays.
Time units would make this particularly difficult, I suspect.

I am investigating a solution to 'wrap' the cf_units operator ...

**Comment by pelson** [comment]
This was fixed in #2964. Will be available in v2.1. 🎉
