### ISSUE TITLE
Developer Guide: git setup and workflow

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#2963]
I've just gone back to the beginning in the Iris developer guide as I wanted to try making a branch on my home laptop.  As far as I can tell, the [Following the latest source](http://scitools.org.uk/iris/docs/latest/developers_guide/gitwash/following_latest.html) section, which tells you how to clone the master branch, is only relevant if you are then [Making a patch](http://scitools.org.uk/iris/docs/latest/developers_guide/gitwash/patching.html).  I don't think I've ever seen anyone send a patch to the Google Group.  Is this patching procedure something you'd still want to encourage?  If not, could these two sections be safely removed?  Then a potential new developer would go straight to the instructions on forking and cloning their own copy.

While I'm here, I think the [Development workflow](http://scitools.org.uk/iris/docs/latest/developers_guide/gitwash/development_workflow.html) section ought to have a link to the [Pull request checklist](http://scitools.org.uk/iris/docs/latest/developers_guide/pulls.html) before the bit about submitting for review.

**Comment by pelson** [comment]
Quite right. We get the content from "gitwash", and traditionally have simply pulled in what they say, but in this instance I agree with you. If you're happy to do it, let's just remove the section.

👍
