### ISSUE TITLE
Error loading files in multiple processes in Iris v2.0.0

### ISSUE THREAD

**Issue by stevehadd** [SciTools/iris#2979]
If you open a file in one process, then try to read from the same file in another process, the second process seems to hang.I have tested the script (link below) which demonstrates the problem in v1.13.0 and v2.0.0, and the script executes as expected in v1.13.0, but displays the problem in v2.0.0. 
The script which demonstrates the problem:
https://drive.google.com/file/d/1mqCqLubJEtzjwIDHgsN2r5k2CUm-vMZS/view?usp=sharing

The data I've tested it with can be found here:
https://s3.eu-west-2.amazonaws.com/stephen-sea-public-london/model_data/SEA_km4p4_ra1t_20180304T0000Z.nc

The testing was done on a Ubuntu 16.04 virtual machine.

**Comment by ajdawson** [comment]
Iris v2.0 uses a new backend ([dask](http://dask.pydata.org/en/latest/index.html)) to load data. Dask can do some clever things with scheduling, and I expect your use of multiprocessing and dask's default scheduling are stepping on eachother's toes.

The quick fix might be to tell dask to use the single threaded scheduler by adding the following at the end of your imports (this works on my machine :tm:):

```python
import dask
dask.set_options(get=dask.get)
```

In the long run, you might find that you can get dask to do most of this work for you and avoid having to manage the multiprocessing yourself (I'm no dask expert mind), see the [dask scheduler documentation](http://dask.pydata.org/en/latest/scheduler-overview.html) for a good starting place.

**Comment by pelson** [comment]
I think the suggestion should solve this issue for you @stevehadd.
Any problems, feel free to contact me and we can dig into it together.

---

Just as a side-note: in general, it is preferred to include the things like code in the issue itself - the internet has a terrible infestation of bit-rot, and links aren't as permanent as one would like (plus Google does a better job of indexing the page if the code is included). 😄

**Comment by stevehadd** [comment]
I finally got around to testing this, and the fix works for me too! Hopefully I will get round to doing things in a more daskonic/daskish (whatever the dask equivalent of pythonic) way.

**Comment by rcomer** [comment]
Update in case anyone else needs it: at Dask 0.19.4

```python
dask.set_options(get=dask.get)
```
throws
```
TypeError: The dask.set_options function has been deprecated.
Please use dask.config.set instead

  Before: with dask.set_options(foo='bar'):
              ...
  After:  with dask.config.set(foo='bar'):
              ...
```

Since `dask.config` did not exist at 0.17.1, the following works for me to get my code running across Dask versions:

```python
if hasattr(dask, 'config'):
    # Works at Dask 0.19.4
    dask.config.set(scheduler='single-threaded')
else:
    # Works at Dask 0.17.1
    dask.set_options(get=dask.get)
```
