### ISSUE TITLE
scitools-docs.github.io is broken

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2980]
The documentation build for the latest code in the main GitHub repository at https://scitools-docs.github.io/iris/master/index.html is broken

**Comment by pp-mo** [comment]
If I understand right, then #2981 may address this ?

**Comment by pelson** [comment]
Confirmed. Last commit on https://github.com/scitools-docs/iris was 19 hours ago, suggesting this is now fixed! 🎉
