### ISSUE TITLE
Travis targets not reporting errors

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2982]
For example, the problem that #2981 fixes : docs build fails, but no error is reported.

Within the `.travis.yml`, various stuff is occurring within command blocks.
  -- could be either the use of "if" blocks, or the travis ">" ??

As-is, errors occurring are not aborting subsequent operations, ***and*** not propagating upward to report a :x:
(? maybe only last command counts ?)
If this is purely due to block commands, it potentially applies to many different targets.

**Comment by djkirkham** [comment]
I think this issue has come up before. I believe the solution was to chain commands with `&&`

**Comment by pelson** [comment]
Will be fixed by #2983

**Comment by pp-mo** [comment]
> Will be fixed by #2983

Agreed, closing
