### ISSUE TITLE
Mixing lazy and non-lazy masked cubes in arithmetic

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#2987]
Suppose I have two cubes with inconsistent missing data points, and one of those cubes is lazy.  If I multiply the cubes together, I may get values where I shouldn't.  Example:

```python
import iris
import dask
import dask.array as da

print 'Iris version', iris.__version__
print 'Dask version', dask.__version__

cube1 = iris.cube.Cube(da.ma.masked_array(range(5), mask=[0, 0, 1, 0, 0]))
cube2 = iris.cube.Cube(da.ma.masked_array(range(5), mask=[0, 0, 1, 0, 1]))

print "Two lazy cubes:"
print (cube1 * cube2).data

cube1.data
print "One loaded, one lazy:"
print (cube1 * cube2).data
```

Output:
```
Iris version 2.1.0dev0
Dask version 0.17.1
Two lazy cubes:
[0 1 -- 9 --]
One loaded, one lazy:
[0 1 -- 9 16]
```

As I'm not 100% sure I'm using the Dask array correctly, here the problem is reproduced with a save and reload:
```python
import numpy.ma as ma

cube1 = iris.cube.Cube(ma.array(range(5), mask=[0, 0, 1, 0, 0]))
cube2 = iris.cube.Cube(ma.array(range(5), mask=[0, 0, 1, 0, 1]))

print "Two loaded cubes:"
print (cube1 * cube2).data

iris.save(cube2, 'test.nc')
cube2 = iris.load_cube('test.nc')

print "One loaded, one lazy:"
print (cube1 * cube2).data
```

Output:
```
Two loaded cubes:
[0 1 -- 9 --]
One loaded, one lazy:
[0 1 -- 9 4]
```

**Comment by rcomer** [comment]
I have just reproduced this issue at Iris1.13, so it is not specific to Dask.

**Comment by pp-mo** [comment]
I think this is actually a problem with the way that dask arrays combine with real ones, and not specific to Iris.
For instance ...
```
>>> cube1.core_data()
masked_array(data = [0 1 -- 3 4],
             mask = [False False  True False False],
       fill_value = 999999)

>>> cube2.core_data()
dask.array<array, shape=(5,), dtype=int64, chunksize=(5,)>
>>> 
>>> cube1.core_data() * cube2.core_data()
masked_array(data = [0 1 -- 9 8],
             mask = [False False  True False False],
       fill_value = 999999)

>>> cube2.core_data() * cube1.core_data()
dask.array<mul, shape=(5,), dtype=int64, chunksize=(5,)>
>>> 
>>> (cube2.core_data() * cube1.core_data()).compute()
masked_array(data = [0 1 -- 9 --],
             mask = [False False  True False  True],
       fill_value = -9223372036854775806)

>>> 
```

Or in a shorter form, not involving Iris ...
```
>>> a1 = da.ma.masked_array(range(5), mask=[0, 0, 1, 0, 0])
>>> a2 = da.ma.masked_array(range(5), mask=[0, 0, 1, 0, 1])
>>> (a1 * a2).compute()
masked_array(data = [0 1 -- 9 --],
             mask = [False False  True False  True],
       fill_value = 999999)

>>> a1.compute() * a2
masked_array(data = [0 1 -- 9 16],
             mask = [False False  True False False],
       fill_value = 999999)

>>> a2 * a1.compute()
dask.array<mul, shape=(5,), dtype=int64, chunksize=(5,)>
>>> (a2 * a1.compute()).compute()
masked_array(data = [0 1 -- 9 --],
             mask = [False False  True False  True],
       fill_value = 999999)

>>> 
```

**Comment by rcomer** [comment]
> But possibly we can adjust the Iris maths operations to work around it ?

Could we just make `_binary_op_common` do the operation on the lazy data?
```
In [21]: (cube1.lazy_data() * cube2.lazy_data()).compute()
Out[21]: 
masked_array(data = [0 1 -- 9 --],
             mask = [False False  True False  True],
       fill_value = 999999)
```
Would obviously need a bit more thought for the cases where `other` is [anything other than a cube](https://github.com/SciTools/iris/blob/master/lib/iris/analysis/maths.py#L761).

**Comment by pp-mo** [comment]
Aside : equivalent to above Iris-indpendent test showing (lazy-masked * real-masked) and (real-masked * lazy-masked) **in Biggus**:

Recall:
```
>>> realmasked = np.ma.ones(5); lazymasked = da.ma.masked_array(range(5), mask=[0, 0, 1, 0, 0])
>>> (lazymasked * realmasked).compute()
masked_array(data = [0.0 1.0 -- 3.0 4.0],
             mask = [False False  True False False],
       fill_value = 1e+20)

>>> realmasked * lazymasked
masked_array(data = [ 0.  1.  2.  3.  4.],
             mask = False,
       fill_value = 1e+20)

>>> 
```
Equivalent with Biggus:
```
>>> realmasked = np.ma.ones(5); lazymasked = biggus.NumpyArrayAdapter(np.ma.array(range(5), mask=[0, 0, 1, 0, 0]))
>>> lazymasked * realmasked
<_Elementwise shape=(5) dtype=dtype('float64')>
>>> (lazymasked * realmasked).masked_array()
masked_array(data = [0.0 1.0 -- 3.0 4.0],
             mask = [False False  True False False],
       fill_value = 1e+20)

>>> realmasked * lazymasked
masked_array(data = [  0.00000000e+00   1.00000000e+00   9.99999000e+05   3.00000000e+00
   4.00000000e+00],
             mask = False,
       fill_value = 1e+20)

>>> 
```

**Comment by pelson** [comment]
@pp-mo is this a dask bug (I've not looked at this for long enough to confirm). If so, please could you raise this on the relevant tracker and link here?

Thanks 👍

**Comment by pp-mo** [comment]
> @pelson is this a dask bug

I don't think it is a bug as such, but it is questionable behaviour IMHO.
The key points are, I think, these :

Firstly, in the operation `numpy_array * dask_array`, you can't stop it *trying* to convert `dask_array` by wrapping it with `np.array()` : Because the numpy array *has* an `__add__` method which does that, and it will get called first (i.e. before any `dask_array.__radd__`).

Secondly, when you pass any dask array into `np.array()`, it will realise it -- even though you did not call `compute()` + in fact nothing does call that.
As I said...
> Somehow it gets away with never actually calling compute(), which is a thing that Dask allow + I rather wish they did not.
So I always felt that this is a bad idea, but it's a pretty basic behaviour in Dask so I presume it's not reallly negotiable.

**Comment by rcomer** [comment]
Updated title to reflect that this is a general arithmetic problem and not specific to multiplication.

I don't think it was noted above, but the problem exists whichever order we put the lazy and realised data:

```python
import iris
import dask
import dask.array as da

print('Iris version', iris.__version__)
print('Dask version', dask.__version__)

cube1 = iris.cube.Cube(da.ma.masked_array(range(5), mask=[0, 1, 1, 0, 0]))
cube2 = iris.cube.Cube(da.ma.masked_array(range(5), mask=[0, 0, 1, 0, 1]))

print("Two lazy cubes:")
print((cube1 * cube2).data)

cube1.data
print("One loaded, one lazy:")
print((cube1 * cube2).data)

print("One lazy, one loaded:")
print((cube2 * cube1).data)
```

gives
```
Iris version 2.2.0
Dask version 1.0.0
Two lazy cubes:
[0 -- -- 9 --]
One loaded, one lazy:
[0 -- -- 9 16]
One lazy, one loaded:
[0 1 -- 9 --]
```

**Comment by rcomer** [comment]
My previous comment seems to no longer be true.

```
Iris version 2.4.0
Dask version 2.11.0
Two lazy cubes:
[0 -- -- 9 --]
One loaded, one lazy:
[0 -- -- 9 16]
One lazy, one loaded:
[0 -- -- 9 --]
```
This means the fix can be more straightforward.

**Comment by rcomer** [comment]
Joining up some dots:

* Issue and fix in `dask` for `dask_array * np_masked_array` case: https://github.com/dask/dask/issues/4441 https://github.com/dask/dask/pull/4506
* For `np_mask_array * dask_array` case, `dask` issue referencing more general `numpy.ma` issue: https://github.com/dask/dask/issues/6734 https://github.com/numpy/numpy/issues/15200
