### ISSUE TITLE
numpy FutureWarnings on iris.load()

### ISSUE THREAD

**Issue by adamcpovey** [SciTools/iris#2988]
Since updating numpy to 1.14.1, whenever I load a fairly boring netCDF file I receive a FutureWarning from the following line of each variable in the file:
https://github.com/SciTools/iris/blob/12b25a274edf45e23a5935ac1b085e4334467d18/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L1415

The warning is,
> FutureWarning: Conversion of the second argument of issubdtype from `str` to `str` is deprecated. In future, it will be treated as `np.str_ == np.dtype(str).type`.

I know how to ignore such warnings, but someone might want to check it.

**Comment by bjlittle** [comment]
Hi @adamcpovey 

Thanks for raising this issue :+1: 

Slightly confusing, but I just wanted to clarify ... PR https://github.com/SciTools/iris/pull/2954 was merged into `master` and should have resolved this issue. 

Are you sure that you are running against the latest version of the Iris `master` branch?

**Comment by adamcpovey** [comment]
Apologies for the wasted space - I thought I'd looked through the issues to see if anyone had already raised it. My Google-fu failed :(

`conda update iris` says I'm on the most recent version, 2.0.0. I assume that won't be updated till you push a release. I'll live with it till then.

**Comment by bjlittle** [comment]
Yup, when we push the next release, patch or minor, then you'll see this warning disappear.

Many thanks again @adamcpovey
