### ISSUE TITLE
ipyvolume

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#2990]
Have you guys seen this
https://github.com/maartenbreddels/ipyvolume
We've been using it to plot cube data and it works very nicely.

Do you have any appetite for this being part of quickplot or something. If so, what kind of functionality would be want to see in a PR?

**Comment by niallrobinson** [comment]
@dkillick @bjlittle just because I've seen you about lately

**Comment by pelson** [comment]
@niallrobinson - interested in helping setup an iris ipyvolume interface package in scitools-incubator?

Personally, I have no appetite to see this kind of thing in iris-core just yet, as it will be specialist and certainly hard to test. For that reason, closing the issue, but more than happy to open the repo 😉

**Comment by niallrobinson** [comment]
> interested in helping setup an iris ipyvolume interface package in scitools-incubator?

yup - sounds good

**Comment by pelson** [comment]
> yup - sounds good

https://github.com/SciTools-incubator/iris-ipyvolume

Happy for you to take the reigns on this repo.
