### ISSUE TITLE
Trajectory: List index out or range

### ISSUE THREAD

**Issue by rjdverbeek** [SciTools/iris#2993]
I get a list index out of range error when generating a trajectory under the following special situation:

I generated a set of waypoints:
```python
waypoints = [{'pressure': 250,
              'time': time.mktime(datetime.datetime(2018, 1, 3, 9).timetuple()),
              'latitude': 45, 'longitude': -60},
             {'pressure': 150,
              'time': time.mktime(datetime.datetime(2018, 1, 3, 10).timetuple()),
              'latitude': 55, 'longitude': 0}]
```

With the waypoints I generated a trajectory:
```python
traj = trajectory.Trajectory(waypoints, sample_count=10)
```

This resulted in: IndexError: list index out of range

When I use  the following waypoints with a slightly different time for the second waypoint (1 second later):
```python
waypoints = [{'pressure': 250,
              'time': time.mktime(datetime.datetime(2018, 1, 3, 9).timetuple()),
              'latitude': 45, 'longitude': -60},
             {'pressure': 150,
              'time': time.mktime(datetime.datetime(2018, 1, 3, 10, 0, 1).timetuple()),
              'latitude': 55, 'longitude': 0}]
```

I do not get the error, but the correct trajectory.

**Comment by pelson** [comment]
Thanks @rjdverbeek. Are you able to turn this into a simple case that we can reproduce easily? For example, we have quite a range of sample data in the iris docs, and could even make use of on of our stock cubes: https://github.com/SciTools/iris/blob/master/lib/iris/tests/stock.py

This does look like a bug though, so having something to quickly reproduce will dramatically simplify the process of fixing it (and adding a test to prevent this failing again in the future).

**Comment by rjdverbeek** [comment]
I have closed it by accident. The issue is not resolved yet.
