### ISSUE TITLE
'fill_value' availability in Iris v2.0.0

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2998]
Hello,

I need to determine the `fill_value` from the model output files I load via Iris. Using Iris v1.13.0 for PP model output files:

```
% module load scitools/production-os41-1
% python
Python 2.7.12 | Met Office - SciTools | (default, Jun 15 2017, 11:28:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
1.13.0
>>> cube = iris.load('/project/cdds/testdata/diagnostics/input/set1/u-ar050/ap6/ar050a.p618550511.pp', iris.AttributeConstraint(STASH='m01s30i294'))[0]
>>> print cube.lazy_data().fill_value
-1.07374e+09
>>> print cube.data.get_fill_value()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'get_fill_value'
```

and for netCDF model output files:

```
% module load scitools/production-os41-1
% python
Python 2.7.12 | Met Office - SciTools | (default, Jun 15 2017, 11:28:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
1.13.0
>>> cube = iris.load_cube('/project/cdds/testdata/diagnostics/input/set1/u-ar050/inm/cice_ar050i_1m_18540301-18540401.nc', iris.Constraint(cube_func=lambda cube: cube.var_name == 'vicen'))
>>> print cube.lazy_data().fill_value
1e+30
>>> print cube.data.get_fill_value()
1e+30
```
Firstly, this shows an inconsistency in the access of the `fill_value` between PP and netCDF model output files using Iris v1.13.0.

Using Iris v2.0.0 for PP model output files:

```
% module load scitools/experimental-current
% python
Python 2.7.12 | Met Office - SciTools | (default, Jun 15 2017, 11:28:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
2.0.0
>>> cube = iris.load('/project/cdds/testdata/diagnostics/input/set1/u-ar050/ap6/ar050a.p618550511.pp', iris.AttributeConstraint(STASH='m01s30i294'))[0]
>>> print cube.lazy_data().fill_value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Array' object has no attribute 'fill_value'
>>> print cube.data.get_fill_value()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'get_fill_value'
```
and for netCDF model output files:

```
% module load scitools/experimental-current
% python
Python 2.7.12 | Met Office - SciTools | (default, Jun 15 2017, 11:28:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
2.0.0
>>> cube = iris.load_cube('/project/cdds/testdata/diagnostics/input/set1/u-ar050/inm/cice_ar050i_1m_18540301-18540401.nc', iris.Constraint(cube_func=lambda cube: cube.var_name == 'vicen'))
>>> print cube.lazy_data().fill_value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Array' object has no attribute 'fill_value'
>>> print cube.data.get_fill_value()
1e+30
```

Using Iris v2.0.0 shows the same inconsistency, but this means I am unable to access the `fill_value` for PP model output files. Is this expected?

**Comment by ehogan** [comment]
I'm not sure if the first point in @pp-mo's comment [here](https://github.com/SciTools/iris/issues/2773#issuecomment-335526885) means that this is expected?

**Comment by ehogan** [comment]
It appears that I completely forgot about masked arrays yesterday when I wrote this! *facepalm*

The inconsistency arises due to the fact that the data loaded from the PP model output files data have no points marked as missing, while the data loaded from the netCDF model output files do.

I understand that it's not necessary to retain the `fill_value` if there are no points marked as missing, so I'll make the relevant changes to my code to handle this.

Apologies for the noise.

**Comment by pp-mo** [comment]
> I'm not sure if the first point in @pp-mo's comment here](https://github.com/SciTools/iris/issues/2773#issuecomment-335526885) means that this is expected?

Just to be clear, those ideas were all very worthy (IMHO! :wink: ) but the changes were driven by the need to use Dask when it did not support masked arrays, leading to the "alpha release" Iris v 2.0a0.

Since Dask now *does* support masked arrays, in Iris 2.0 things have changed again.

In summary, 'fill_value' now *only* exists as a property of real, masked data : there is no `cube.fill_value`.
