### ISSUE TITLE
Change in behaviour between Iris v1.13.0 and v2.0.0 related to masked arrays

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2999]
Using Iris v1.13.0:

```
% module load scitools/production-os41-1
% python
Python 2.7.12 | Met Office - SciTools | (default, Jun 15 2017, 11:28:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
1.13.0
>>> cube1 = iris.load('/project/cdds/testdata/diagnostics/input/set1/u-ar050/ap6/ar050a.p618550511.pp', iris.AttributeConstraint(STASH='m01s30i294'))[0]
>>> cube2 = iris.load('/project/cdds/testdata/diagnostics/input/set1/u-ar050/ap6/ar050a.p618550511.pp', iris.AttributeConstraint(STASH='m01s30i304'))[0]
>>> cube = cube1 / cube2
>>> print cube.has_lazy_data()
True
>>> print type(cube.data)
<class 'numpy.ma.core.MaskedArray'>
>>> print cube.has_lazy_data()
False
```

Using Iris v2.0.0:

```
% module load scitools/experimental-current
% python
Python 2.7.12 | Met Office - SciTools | (default, Jun 15 2017, 11:28:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
2.0.0
>>> cube1 = iris.load('/project/cdds/testdata/diagnostics/input/set1/u-ar050/ap6/ar050a.p618550511.pp', iris.AttributeConstraint(STASH='m01s30i294'))[0]
/opt/scitools/environments/experimental/2018_03_27/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/scitools/environments/experimental/2018_03_27/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
>>> cube2 = iris.load('/project/cdds/testdata/diagnostics/input/set1/u-ar050/ap6/ar050a.p618550511.pp', iris.AttributeConstraint(STASH='m01s30i304'))[0]
>>> cube = cube1 / cube2
>>> print cube.has_lazy_data()
True
>>> print type(cube.data)
/opt/scitools/environments/experimental/2018_03_27/lib/python2.7/site-packages/dask/local.py:271: RuntimeWarning: invalid value encountered in true_divide
  return func(*args2)
<type 'numpy.ndarray'>
>>> print cube.has_lazy_data()
False
```
In the case of Iris v1.13.0, the data are loaded after the divide; since the divide produces invalid values, the data are loaded as a masked array (a behaviour my code relies on). However, given the warnings from Iris v2.0.0, it seems the data are being loaded prior to the divide; `cube1` and `cube2` don't contain any invalid values, so are loaded as `numpy.ndarray`.

Is this expected?

**Comment by pp-mo** [comment]
> since the divide produces invalid values, the data are loaded as a masked array

I think that can't be quite right -- NaNs and the like will never be automatically translated into masked points.
That *could* happen in Iris "2.0a0", but not in Iris 1.13 or 2.0.

> Is this expected?

Well, maybe.  Pointwise arithmetic errors can be a bit of grey area and might differ between Biggus and Dask (which is the most important change between 1.13 and 2.0)

Is it easy to recast this in terms of abstract data so we can see some original data points + have a self-contained example here ?
Hint: create test data like ...
```
masked_data = np.ma.masked_array([1.0, 2, 3, 4], mask=[0, 1, 0, 1])
cube = cube(data)
```
... then make a lazy version of the cube  : in Iris 1.13, you must do it like this ...
```
lazy_cube = cube.copy()
lazy_cube.lazy_data(cube.lazy_data())
```
... in Iris 2.0 this has changed, but is a bit neater ...
`lazy_cube = cube.copy(cube.lazy_data())` ***or*** `lazy_cube = cube.copy(); lazy_cube.data = cube.lazy_data()`

**Comment by pp-mo** [comment]
Could you possibly recast this in terms of explicit data so we can see some original data points + have a self-contained example here ?
Hint: create test data like ...
```
masked_data = np.ma.masked_array([1.0, 2, 3, 4], mask=[0, 1, 0, 1])
cube = cube(data)
```
... then make a lazy version of the cube  : in Iris 1.13, you must do it like this ...
```
lazy_cube = cube.copy()
lazy_cube.lazy_data(cube.lazy_data())
```
... in Iris 2.0 this has changed, but is a bit neater ...
`lazy_cube = cube.copy(cube.lazy_data())` ***or*** `lazy_cube = cube.copy(); lazy_cube.data = cube.lazy_data()`

**Comment by pp-mo** [comment]
Ok, I was wrong !
It seems that biggus really ***does*** interpret inf/nan codes as masked points in some cases.
It's because Biggus requires you to specify a 'normal' or a 'masked' real result, and does not choose for you.
If you ask for masked data, 'bad' values are treated as masked.

For completeness, this shows the behaviour :
```
>>> import numpy as np
>>> import dask.array as da
>>> from biggus import NumpyArrayAdapter
>>> data1 = np.array([1.0, 2, 3, 4])
>>> data2 = np.array([1.0, 2, 0, 4])
>>> biggus_div = (NumpyArrayAdapter(data1) / NumpyArrayAdapter(data2))
>>> biggus_div
<_Elementwise shape=(4) dtype=dtype('float64')>
>>> biggus_div.ndarray()
/opt/scitools/environments/experimental_legacy/2018_03_27-1/lib/python2.7/site-packages/biggus/_init.py:2982: RuntimeWarning: divide by zero encountered in divide
  result = self._numpy_op(*np_operands)
array([  1.,   1.,  inf,   1.])
>>> biggus_div.masked_array()
masked_array(data = [1.0 1.0 -- 1.0],
             mask = [False False  True False],
       fill_value = 1e+20)

>>> dask_div = (da.from_array(data1, chunks=4) / da.from_array(data2, chunks=4))
>>> dask_div.compute()
array([  1.,   1.,  inf,   1.])
>>> 
```

**Comment by pp-mo** [comment]
So, that explains the difference : it is an Iris 1 --> 2  design change, not a bug as such.

What do you need to achieve ?
I think you can maybe use a 'masked_invalid' to achieve the same results ...
```
>>> da2 = da.ma.masked_invalid(dask_div)
>>> da2.compute()
masked_array(data = [1.0 1.0 -- 1.0],
             mask = [False False  True False],
       fill_value = 1e+20)

>>> 
```

Is that a viable solution for you ?

**Comment by ehogan** [comment]
If you're happy with this design change then we will update our code to do as you suggest. Thank you for your help! :)
