### ISSUE TITLE
Using IRIS

### ISSUE THREAD

**Issue by SamothKo** [SciTools/iris#3001]
Hello, 
for my work i find the IRIS Module. Know i played around with the code.

But if i want to use it for my data i get the error 
This behaviour is deprecated in favour of automatic promotion to Cubes. To switch to the new behaviour, set iris.FUTURE.netcdf_promote to True.

With the Comments on the side i can't fix the misstake.

I start like this:

```
In [1]: import numpy as np
   ...: import matplotlib.pyplot as plt
   ...: import iris
   ...: import iris.plot as iplt
   ...: 
   ...: filenames='/home/samothkociok/SIG-Lotos01Home/home/thomaskociok/scratch/projects/LOTOS-EUROS/
   ...: v2-1-000/output/LE_v2-1-000_conc-3d_20170504.nc'

In [2]: meteo_data=iris.fileformats.netcdf.load_cubes(filenames, callback=None)

In [3]: field = next(meteo_data)
/home/samothkociok/.conda/envs/thomypy/lib/python3.4/site-packages/iris/fileformats/cf.py:1140: IrisDeprecation: NetCDF default loading behaviour currently does not expose variables which define reference surfaces for dimensionless vertical coordinates as independent Cubes. This behaviour is deprecated in favour of automatic promotion to Cubes. To switch to the new behaviour, set iris.FUTURE.netcdf_promote to True.
  warn_deprecated(msg)`
```

Maybe someone can show me how it works.

Thanks a lot.

Samoth

**Comment by ajdawson** [comment]
This is not an error message, it is just a warning telling you that some default behaviour of the load command is changing in the version 2.0.0 release of iris.

Specifically, this one is telling you that any reference surface definitions will be loaded as cubes in the next release of iris, but currently they are not (i.e. you might see different output from load on iris 2.0.0).

You should add the following line before you use `iris.load_cubes` to turn on the new behaviour to make sure your program will work on newer versions of iris:

```python
iris.FUTURE.netcdf_promote =  True
```

**Comment by SamothKo** [comment]
Hello,
great. This produce 
In [5]: meteo_data
Out[5]: <generator object _interpret_fields at 0x7f8b71afe6c0>

How i can use this to get the values:
for exampel if i read netcdf files i normally us:
from netCDF4 import Dataset as NetCDFFile 
nc=NetCDFFile(readfile)
accum_dust = nc.variables['tdust'][ii,0,:,:]		        #total dust aerososl [time,Level,Lot,Lan]
accum_dust_units = nc.variables['tdust'].units		#kg m-3

Cheers
Samoth

**Comment by rcomer** [comment]
I recommend reading through the [Iris User Guide](http://scitools.org.uk/iris/docs/latest/userguide/index.html).

**Comment by SamothKo** [comment]
I already see the guide.

The problem is:
In [16]: print(meteo_data)
<generator object load_cubes at 0x7f8b71afef78>

Normally there should be a little bit more informations. Isn't?

**Comment by pp-mo** [comment]
The routine documentation, in reference docs, explains that it returns a Python generator :
http://scitools.org.uk/iris/docs/latest/iris/iris/fileformats/netcdf.html#iris.fileformats.netcdf.load_cubes

Normally, the low-level loading routines are only used when the file type cannot be identified.
Instead use 'iris.load', as explained in the User Guide.

**Comment by pelson** [comment]
Looks like using ``iris.load`` would solve the issue here.
