### ISSUE TITLE
Iris documentation - example test mpl UserWarning

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3032]
The `iris` documentation example test `docs/iris/example_tests/test_COP_1d_plot.py`, which calls `docs/iris/example_code/Meteorology/COP_1d_plot.py`, causes the following `matplotlib` `2.2.2` warning to be raised:
```script
<snip>/lib/python2.7/site-packages/matplotlib/ticker.py:1853: UserWarning: Steps argument should be a sequence of numbers
increasing from 1 to 10, inclusive. Behavior with
values outside this range is undefined, and will
raise a ValueError in future versions of mpl.
```
This is being generated by `matplotlib` itself, through it's own default choice of tick locations using `matplotlib.ticker.MaxNLocator` and the example `cube` data. The entry point to `matplotlib` from `iris` is from [iris.plot._draw_1d_from_points](https://github.com/SciTools/iris/blob/master/lib/iris/plot.py#L612) - btw no string axes are involved in the plot.

We should investigate this and circumvent within `iris` through our own choice of tick locator, or determine if this is an issue within `matplotlib` that requires fixing for the community.

**Comment by bjlittle** [comment]
See `nc-time-axis` PR [#34](https://github.com/SciTools/nc-time-axis/pull/34#discussion_r191933699)...

**Comment by pelson** [comment]
``nc_time_axis>=1.1`` should fix.
