### ISSUE TITLE
Update requirements to cf-units

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3049]
In light of https://github.com/SciTools/cf-units/pull/113, we need to update the `iris` [requirements](https://github.com/SciTools/iris/blob/master/requirements/core.txt#L7) for `cf_units` to `cf-units`.

**Comment by pelson** [comment]
This is such a mess. 😭

It seems pypi preserves the original package underscore/dash name, so nc-time-axis, which was registered as nc-time-axis is pip installed with [``pip install nc-time-axis``](https://pypi.org/project/nc-time-axis/), but cf-unit, which was *originally* registered as ``cf_unit`` continues to be [``pip install cf_unit``](https://pypi.org/project/cf_units/). 

I had originally written the following:

> I support @ocefpaf here, and am OK sticking with the pypi name for the time being. Longer term, I'm OK with a conda-forge & pypi rename, but that doesn't have to happen anytime soon IMO (I suppose that effectively means: I'm not motivated enough *right now* to make it happen, so unless somebody else is (now or in the future), it won't get done).


But I've just discovered that it is actually possible to ``pip install cf-units`` as well as ``pip install cf_units`` (these are aliases). For whatever reason, there is a lot of ```_``` usage in names on conda-forge. For example, ``jupyter-core``. Interestingly, pip can install both ``jupyter_core`` and ``jupyter-core``. This is the ideal situation, IMO, but appreciate that these semantics (``-`` ==  ``_``) are not a part of conda.


Phew.

Well, getting off the fence, in light of strong evidence either way, I'm quite happy to have renamed the repository to cf-units. I'm quite happy that the package is called ``cf-units``. I'm fine that despite this, the import name is ``cf_units``, and I'm OK with the fact that one *installs* the package with ``cf_units`` (but would be even happier if we could do both names! 😉 ).
