### ISSUE TITLE
Understand IRIS Cube

### ISSUE THREAD

**Issue by SamothKo** [SciTools/iris#3053]
Hi,
i have a little question...

I load the data in a iris cube and i got with:
iris.FUTURE.netcdf_promote =  True
meteo_data=iris.fileformats.netcdf.load_cubes(filenames, callback=None)
cube = iris.load(filenames)
print(cube)

something like this:
0: mass concentration of PPM2.5 in humid air / (kg m-3) (time: 24; layer: 5; latitude: 152; longitude: 116)
1: mass concentration of PPM2.5 in humid air / (kg m-3) (time: 24; layer: 5; latitude: 152; longitude: 116)
2: mass concentration of sodium in humid air / (kg m-3) (time: 24; layer: 5; latitude: 152; longitude: 116)

but it seems, that there are no values inside the cubes, only time, layer, latitude and logitude.
In my netcdf files are the falues... how i can fix it, and how i can do now a crosssection plot...

coord = cube[0].coord('latitude')
cross_section = next(cubes[0].slices([coord,cube[0].long_name]))

Best

**Comment by ajdawson** [comment]
Hi @SamothKo. There is nothing wrong here, we just don't print all the values when you print your `CubeList` (this is actually a list of 3 cubes not a single cube).

The [Iris User Guide](https://scitools.org.uk/iris/docs/latest/userguide/index.html) has an introduction to cubes and coordinates and how to interpret them that might help you understand what you are seeing, and how to do useful things like plotting loaded cubes.

In addition you can ask questions about the best way to do your analysis (and anything else iris/cartopy related) on the [iris discussion group](https://groups.google.com/forum/#!forum/scitools-iris).

**Comment by SamothKo** [comment]
Thanks :D
