### ISSUE TITLE
DOC: easier copy-and-paste of code examples

### ISSUE THREAD

**Issue by tv3141** [SciTools/iris#3057]
Code blocks in the user guide and reference guide cannot be copied and pasted as a whole as they contain `>>>` and `...`:
```python
>>> for foo in bar:
...     print(foo)
```

One approach would be a toggle like [numpy](https://www.numpy.org/devdocs/reference/arrays.ndarray.html) uses in their manual.

- [x] PR for http->https in [doc template]( https://github.com/SciTools/iris/blob/master/docs/iris/src/_templates/layout.html#L9)
- [x] PR for http->https in released [docs](http://github.com/scitools/scitools.org.uk)

**Comment by pelson** [comment]
We actually used to have this. Looks like it stopped working.

Looks like the move over to https stopped this working (diagnosed by enabling insecure scripts in the docs).

The line is at https://github.com/SciTools/iris/blob/master/docs/iris/src/_templates/layout.html#L9. It would take a PR to ``scitools/iris`` and a PR to http://github.com/scitools/scitools.org.uk to search and replace ``http://docs.python.org/2/_static/copybutton.js`` with ``https://docs.python.org/2/_static/copybutton.js``. Interested in doing it @tv3141 ?

**Comment by tv3141** [comment]
@pelson Yes, I can have a look at this.

**Comment by tv3141** [comment]
Copybutton is broken again in Iris2.2, [example](https://scitools.org.uk/iris/docs/v2.2/userguide/subsetting_a_cube.html#cube-iteration)

@pelson Do you want to reopen this ticket or open a new one?

**Comment by pelson** [comment]
I've reopened. Are you interested in taking a look at this @tv3141?

**Comment by stephenworsley** [comment]
This may be worth looking at https://github.com/scipy/scipy-sphinx-theme/pull/6.

**Comment by tkknight** [comment]
I believe the new Read The Docs style documentation has resolved this issue.  The **sphinx_copybutton** extension is used to handle this.

See https://scitools-iris.readthedocs.io/en/latest/installing.html for an example (note the icon on the right of the commands)

Note this documentation url is the **latest**, this points to **master**. When there is a release for Iris there will also be a **stable** release and a **tagged** release too.

I think we can close this issue now?

**Comment by bjlittle** [comment]
@tkknight Awesome, job done, thanks! :+1:
