### ISSUE TITLE
3d Plotting with IRIS

### ISSUE THREAD

**Issue by SamothKo** [SciTools/iris#3059]
Hello,
is there a way to use Iris to make a 3 D plot?

For example lat long and a cross-section Plot.

Thanks.

Samoth

**Comment by pelson** [comment]
Hi Samoth,

Best place to get help with these kinds of questions is either the [scitools-iris google group](https://groups.google.com/forum/#!forum/scitools-iris) or on [the python-iris tag on StackOverflow](https://stackoverflow.com/questions/tagged/python-iris).

A quick answer to this is that, no Iris doesn't have any 3d capabilities built-in. Given Iris' general direction of producing smaller sub-packages (e.g. iris-grib), I'd say that Iris itself will probably never have 3d plotting capabilities built-in, but we would love to see such a package exist (e.g. ``iris-plot``, ``iris-3dplot`` etc.). In fact, a similar issue was discussed recently in https://github.com/SciTools/iris/issues/2990 which may result in a package that implements ipyvolume (3d) visualisation with Iris. Placeholder (with no functionality yet) is at https://github.com/SciTools-incubator/iris-ipyvolume. cc @niallrobinson

If you have ever produced 3d visualisations in python, you are probably already qualified to produce such a package - Iris quickly exposes the underlying numpy arrays that can then be passed through to the appropriate tool. There are one or two helper functions at https://github.com/SciTools/iris/blob/master/lib/iris/plot.py which may be useful for doing this in a general sense.

Hope that is useful.

Cheers,

Phil
