### ISSUE TITLE
Artefacts in iris.quickplot contourf for regional plots

### ISSUE THREAD

**Issue by ledm** [SciTools/iris#3074]
Hi,

I'm attempting to use a iris.quickplot.contourf to produce a map of a regional subset of a global model. Unfortunately, quickplot makes some strange artefacts over regions:

![diag_cmip5_canesm2_omon_historical_r1i1p1_to2ms_tos_prep_map_4_diag_map_4_2001_2004_map_0](https://user-images.githubusercontent.com/4180685/41724929-925990b8-7566-11e8-93b9-6c255f82680e.png)
The data shown here was extracted from CMIP5 data by ESMValTool. github won't let me upload the netcdf file. I'd be happy to share it if needed.

The data range is from 80S -> 80N in latitude and longitude from 0E->30E and 280E -> 360E. The longitude bounds seem to have loaded correctly though, as no cell boundary is larger than 1 degree wide. 

Any ideas what could be causing these horizontal lines?

**Comment by pelson** [comment]
@ledm - one quick thing to check: does the longitude coordinate have the ``circular`` attribute set to ``True``?

The ranges that you report for longitude look curious. Have you used constraints, or the ``.extract`` method to limit your longitude range? It might be worth taking a look at the latter, as it also has the ability to "roll" the data values after extraction so that they are contiguous in longitude.

**Comment by ajdawson** [comment]
>Have you used constraints, or the .extract method to limit your longitude range? It might be worth taking a look at the latter, as it also has the ability to "roll" the data values after extraction so that they are contiguous in longitude.

Did you mean `.intersection` rather than `.extract` @pelson?

**Comment by ledm** [comment]
Hi @pelson @ajdawson , Thanks for getting back to me! 

I've had a quick check, and my dataset has circular set to True for the longitude coordinate. However, this issue still occurs when circular is set to False for the longitude attribute. Like I said earlier, I'm happy to share the netcdf file.

The region was extracted using `iris.Constraint` and `iris.extract`. The code that I used is viewable here in the `area_slice` function: 
https://github.com/ESMValGroup/ESMValTool/blob/REFACTORING_OceanTemperature/esmvaltool/preprocessor/_area_pp.py

**Comment by bjlittle** [comment]
Is this still an issue with the latest version of iris and cartopy 0.17.0 (or even the Cartopy master)?
