### ISSUE TITLE
Correct cell method 'method' and interval for UM fieldsfile/pp data

### ISSUE THREAD

**Issue by melissaebrooks** [SciTools/iris#3076]
The cell methods produced by loading a pp or fieldsfile in iris do not have the correct intervals or, for some fields, the method.

By default, all intervals are 1 hour (from incorrectly picking up the lbtim value). Fields that are accumulations are always read as means.

This snippet produces useful cell methods for typical NWP data, but does not cover all use cases.

def lbproc_interval_correct(field, cube):
    'calculates the correct interval for a cube/field'
    tbound_diff = None
    if cube.coords('time'):
        if cube.coord('time').bounds is not None:
            tbound_diff = cube.coord('time').bounds[0,1] - cube.coord('time').bounds[0,0]
    tproc_name = None
    
            
    if field.lbproc == 128:
        # need to determine if this field is a mean, or an accumulation!:
        cubename = trui.stashnum_to_cubename(field.lbuser[3], model_num=field.lbuser[6]).lower()
        if 'amount' in cubename and cube.units == 'kg m-2':
            tproc_name = 'accumulation'
            tproc_name_match = 'mean'
        else:
            tproc_name = 'mean'
            tproc_name_match = tproc_name
    elif field.lbproc== 4096:
        tproc_name = 'minimum'
        tproc_name_match = tproc_name
    elif field.lbproc == 8192:
        tproc_name = 'maximum'
        tproc_name_match = tproc_name
      
    if tproc_name:
        if field.lbtim.ib == 2:
            if field.lbtim.ia == 0 or tbound_diff is None or tproc_name == 'accumulation':
                new_cellm = iris.coords.CellMethod(tproc_name, coords="time")
            else:
                new_cellm = iris.coords.CellMethod(tproc_name, coords="time", intervals='{0:.2f} hour'.format(tbound_diff))
        else:
            raise ValueError('expecting ib=2')
        # now which cell method does this replace (if any)
        new_icellm = -1
        for i_cellm, cellm in enumerate(cube.cell_methods):
            if cellm.method == tproc_name_match and cellm.coord_names == ('time',):
                new_icellm = i_cellm
        
        # now replace/append:
        out_cellm = []
        for i_cellm, cellm in enumerate(cube.cell_methods):
            if i_cellm == new_icellm:
                out_cellm.append(new_cellm)
            else:
                out_cellm.append(cellm)
        if new_cellm == -1:
            out_cellm.append(new_cellm)
    return tuple(out_cellm)

**Comment by tv3141** [comment]
@malcolmbrooks I had a look at the docs, but I could not find a way to distinguish between a time mean and an accumulation. Using the cube name and unit seems to me a very brittle solution.

- `lbproc`
https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/_pp_lbproc_pairs.py#L33
    -  according to the UM docs F03 the line above should be ` "Time mean field or accumulation"`

- `lbtim`: 
    -  LBTIM is coded as (100 * IA + 10 * IB + IC)
    - `IA`: time interval in hours between the individual fields from which the mean [or accumulation] was computed. **This has a minimum value of 1 even for sampling frequencies < 1h**
    - "Note: This is not the period that the mean/accumulation is calculated over (which is defined by T1 and T2 as described above), rather it is the frequency with which the data in that period is sampled." (UM docs F03)

**Comment by nhsavage** [comment]
I've come across the same problem - I have started coding a solution to the cell method solution and I will shortly make a branch. Glad I discovered this ticket as its saved me a job.

**Comment by nhsavage** [comment]
I've created a branch on my fork to hold my potential solution. I've not tested it yet, and there's probably still lots of improvements. Note that this will not fix the ambiguity between mean and accumulation - that is inherent in the pp format.  I guess we could make the ambiguity explicit though.

**Comment by nhsavage** [comment]
code is at https://github.com/nhsavage/iris/tree/cell_t

**Comment by nhsavage** [comment]
This is still important, but I need to check if the problem is still present in the latest releases
