### ISSUE TITLE
silence intended UserWarnings in tests

### ISSUE THREAD

**Issue by tv3141** [SciTools/iris#3078]
The testing logs contain hundreds of `UserWarnings`. The vast majority seems to be:

```python
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.1.0.dev0-py3.6.egg/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:2029: 
UserWarning: Gracefully filling 'lat' dimension coordinate masked points
```
and
```python
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.1.0.dev0-py3.6.egg/iris/coords.py:1210: 
UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'latitude'.
```

Expected warnings that are intended should be silenced. As an example, Improver has a [decorator](https://github.com/metoppv/improver/blob/master/lib/improver/utilities/warnings_handler.py) that does this.

If there are no objections I will have a go at creating a pull request.

**Comment by pelson** [comment]
I think it is time that we considered silencing these warnings by default in all cases, TBH. Would you be interested in having a go at seeing what that actually looks like in practice? To be clear, I'm not suggesting we remove the warnings, I'm suggesting that they are silenced by default (like the standard DeprecationWarning in python).

**Comment by tv3141** [comment]
I can have a look at this. Do you prefer disabling UserWarnings only for testing, or in general?
