### ISSUE TITLE
Feature complete : mergeback 2d_coords

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3100]
Master ticket for completing current work on 2d_coords (part of ORCA data support effort).

Rationale :
  * **in the end**, the 2d_coords branch will eventually be ok to merge back
  * **in development**, we will want to merge in PRs that don't meet our usual standards
    * incomplete implementation
    * known problems
    * temporary limitations
    * documentation needs fixing
    * temporary implementation awaiting other outstanding work for a better solution
  * in these cases, all the outstanding work needs to be recorded in issues marked with the '2d_coords' label.
  * broken tests can skipped during development using "@skip_2d" #3099 
  * **once [all open issues+prs labelled 2d_coords](https://github.com/SciTools/iris/labels/2d_coords) are closed** (in theory), 
everything is up to standard + we can merge back.
    * but note especially : #3101, #3102
    * in practice, it will still want a bit of an overall review

**Comment by dkillick** [comment]
Done in #3153.
