### ISSUE TITLE
Add test for plotting 1D coord against 2D coord

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#3106]
This clearly shouldn't work as it doesn't make any sense, so an error needs to be thrown when a user attempts this.

I spent a little bit of time trying to construct a cube with a 2D coord and a 1D coord which I could try to plot against each other, but I had trouble.  There is however a cube used in 'iris.tests.test_plot.TestPlottingExceptions' which could be re-used for this.

**Comment by pp-mo** [comment]
Done in #3135
