### ISSUE TITLE
Outstanding review issues from #3096 (gridcell rotations)

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3114]
Premature merge.
Outstanding comments :
  * lots of stickler complaints
  * https://github.com/SciTools/iris/pull/3096#pullrequestreview-141076488
  * maybe reconsider https://github.com/SciTools/iris/pull/3096#discussion_r205756026
  * ? https://github.com/SciTools/iris/pull/3096#discussion_r205767222
  * ? consider : combine with other code for 3d latlon/xyz transform ?  https://github.com/SciTools/iris/pull/3096#discussion_r205778183
  * inherited + other comments to clarify
    *  https://github.com/SciTools/iris/pull/3096#discussion_r206112480
    * https://github.com/SciTools/iris/pull/3096#pullrequestreview-141902153
    * https://github.com/SciTools/iris/pull/3096#discussion_r206483318
  * should remove make-discontiguous routine : see https://github.com/SciTools/iris/pull/3127#discussion_r207522639

---

Missing test aspects : originally from #3103

CODE CHANGES
   * ~angles routine should handle non-2d coords with meshgrid~ 
      * Too tricky : ABANDONED ? but [this reduces the generality of "rotate_grid_angles"](https://github.com/SciTools/iris/issues/3145)

ANGLES TEST ASPECTS : **testing of 'grid_angles'**
   * **THINK THIS IS ALL NOW COVERED BY #3120** (check when that is accepted)
   *  (cube)
   *  unrecognised inputs (no shapes)
   *  missing y + x not cube
   *  coords
      *    not 2d : (support?)
      *    different shapes : error ~(except 1d?)~
      *    different cube dims ~(2d : ok for 1d)~
      *    different cs : error
      *    no cs, but not angles, i.e. plain X+Y coords : ??
      *    X/Y = coord/not, ***and*** not/coord
      *    cell_angle_boundpoints unrecognised

ROTATE TEST ASPECTS : **testing of 'rotate_grid_vectors'**
   * u+v
   * u+v with angles supplied
   * u+v with angles derived from u
   * angles method key
   * check that magnitudes remain unchanged
   * check actual angles-rotation calculation (known vector + angles)
   * ~check that non-2d cubes work~ (not supported now ?)
   * check masking of invalid points
   * check behaviour with 0-vectors ?
   * Exceptions:
     * angles not angular (bad unit)
     * u+v not same shape (implied by arithmetic)
     * angles not same dims as u+v  (implied by arithmetic)
   * ?possibly~ :  NaN angles handling ?

**Comment by pp-mo** [comment]
Checklist of things above

Outstanding comments :


Outstanding comments :
  * [X] ~lots of stickler complaints~ (presumably, all fixed in #3127
  * https://github.com/SciTools/iris/pull/3096#pullrequestreview-141076488
    * [ ] ["Can aa i.e. the grid cell angles also be masked, or just nans? ... should \[we *not* always\] return masked arrays in every case?" ](https://github.com/SciTools/iris/pull/3096#discussion_r205751999)
  * [ ] ["Any chance it would ever need to be upper-left, upper right?"](https://github.com/SciTools/iris/pull/3096#discussion_r205756026)
  * [ ] ["Kinda confusing names 03_to_12 and 0_to_1"](https://github.com/SciTools/iris/pull/3096#discussion_r205767222)
  * [ ] [" general purpose functions ... could we not put them somewhere else" / combine with other code for 3d latlon/xyz transform ?](https://github.com/SciTools/iris/pull/3096#discussion_r205778183)
  * inherited + other comments to clarify
    * [ ] ["Why are v and T used here? ... docs strings are not quite finalised yet?" / clarify inherited docstrings](https://github.com/SciTools/iris/pull/3096#discussion_r206112480)
    * [ ] ["a bit confusing" / comments in `_grid_angles. _latlon_from_xyz`](https://github.com/SciTools/iris/pull/3096#pullrequestreview-141902153)
    * [ ] ["so many commas" / comments in `_grid_angles. _latlon_from_xyz`](https://github.com/SciTools/iris/pull/3096#discussion_r206483318)
  * [ ] ["remove this now that we're not doing contiguity checks" / remove make-discontiguous routine](https://github.com/SciTools/iris/pull/3127#discussion_r207522639)

**Comment by lbdreyer** [comment]
All of these comments have been dealt with so I am going to close this.
