### ISSUE TITLE
RMS aggregator is not distributed/lazy

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#3123]
Unlike other aggregators (e.g. MEAN) I don't think the RMS aggregator is distributed or lazy. I'm happy to PR this if you want to give me any pointers about how to do it? (I'd really like to be able to demo something with the RMS aggregator next week).

**Comment by niallrobinson** [comment]
i've organised a pair program with @dkillick on Friday 3rd Aug.

**Comment by rcomer** [comment]
Looks like this was addressed by #3130.
