### ISSUE TITLE
Broken scatterplot

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3126]
Gallery example seems broken

The second plot from `/examples/Oceanography/atlantic_profiles` ...

comparing https://scitools-docs.github.io/iris/2d_coords_v0/examples/Oceanography/atlantic_profiles.html#atlantic-profiles-01
![atlantic_profiles_01_new-2d-plots](https://user-images.githubusercontent.com/2089069/43593128-f86d5442-966e-11e8-9c11-7cfca6714c6b.png)

with https://scitools-docs.github.io/iris/2d_coords_v0/examples/Oceanography/atlantic_profiles.html#atlantic-profiles-01
![atlantic_profiles_01-old-master-plots](https://user-images.githubusercontent.com/2089069/43593153-0714717e-966f-11e8-9038-39e88a075e8f.png)

**Comment by ajdawson** [comment]
Looks like some invalid values are being plotted, the cluster at the bottom left are likely the real values with temperature in 270-300K and salinity 34-37 PSU, the cluster at the top right have un-physical values for both temperature and salinity.

**Comment by ajdawson** [comment]
Indeed, the fill value for this data set is 32767, which is where the cluster in the top right is located. This is a manifestation of #3125 I expect.

**Comment by lbdreyer** [comment]
This is working again on the 2d coords branch (see https://scitools-docs.github.io/iris/2d_coords/examples/Oceanography/atlantic_profiles.html) so I am going to close this issue.
