### ISSUE TITLE
Lazy MEAN Aggregator doesn't support weights

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#3129]
Despite being a weighted aggregator, you can't actually pass weights to `iris.analysis.MEAN` when producing a lazy aggregation:

```python
b = da.from_array(np.array([1,2,3,4,5]))
MEAN.lazy_aggregate(b, 0, weights=[2, 4, 1, 6, 3])
```
```python-traceback
Traceback (most recent call last):
  File "/.../miniconda3/envs/scitools_dev/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-60626d069686>", line 1, in <module>
    MEAN.lazy_aggregate(b, 0, weights=[2, 4, 1, 6, 3])
  File "/.../git/iris/lib/iris/analysis/__init__.py", line 471, in lazy_aggregate
    return self.lazy_func(data, axis, **kwargs)
  File "/.../git/iris/lib/iris/analysis/__init__.py", line 1460, in inner_stat
    dask_result = dask_stats_function(array, axis=axis, **kwargs)
TypeError: mean() got an unexpected keyword argument 'weights'
```

This functionality is not tested by `iris.tests.unit.analysis.test_MEAN`.

One solution to this would be to use `da.average` rather than `da.mean` - but note there might be an implementational problem with `da.average` when [the input array is masked](https://github.com/dask/dask/issues/3846).

**Comment by valeriupredoi** [comment]
hey guys. we have this issue documented in ESMValTool - with specific examples and work started by Ben towards a solution, if it helps https://github.com/ESMValGroup/ESMValTool/issues/887

**Comment by bouweandela** [comment]
It looks like `dask.array.ma.average` is now implemented:
https://github.com/dask/dask/blob/44948eca09b046cc06169dbdfc3cf4a5750a2598/dask/array/ma.py#L262-L264

so I think the solution could be as simple as replacing `da.mean` by `da.ma.average` here:
https://github.com/SciTools/iris/blob/337f6f0b21b5053412d38d5047092961164ef59b/lib/iris/analysis/__init__.py#L1486-L1487

and pinning dask to an appropriately recent version.

**Comment by valeriupredoi** [comment]
good find @bouweandela ! Shall we tell the iris folk about it?
