### ISSUE TITLE
Numpy FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by tv3141** [SciTools/iris#3133]
```
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use 
`arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an 
array index, `arr[np.array(seq)]`, which will result either in an error or a different 
result.
```

- [x] iris/fileformats/pp_load_rules.py:326: `slice_0 = array[slice_inds]`
- [x] iris/analysis/geometry.py:227: `weights[slices] = subweights`
- [x] iris/analysis/_scipy_interpolate.py:290: `return self.values[idx_res]`
- [x] iris/analysis/trajectory.py:402: `source_data = source_data[fancy_source_indices]`
- [x] iris/analysis/trajectory.py:444: `new_cube_coord.points = src_coord.points[fancy_coord_index_arrays]`
- [x] iris/fileformats/pp_load_rules.py:326: `slice_0 = array[slice_inds]`
- [x] iris/util.py:164: `result = np.where(ndarray[last_element] >= _delta[last_element])[0]`
- [x] iris/util.py:165: `_delta[last_element] -= circular`
- [x] iris/util.py:166: `_delta[last_element][result] += 2*circular`
- [x] iris/analysis/_interpolation.py:300: `data = data[dim_slices]`
- [x] iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py:149: `result = regrid(self.data[index], self.x_dim,`
- [x] iris/analysis/__init__.py:1287: `data = array.astype('float32')[slices]`
- [ ] iris/experimental/stratify.py:181

<details>
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/fileformats/pp_load_rules.py:326: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  slice_0 = array[slice_inds]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3319: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  _data[indx] = dval

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/geometry.py:227: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  weights[slices] = subweights

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/tests/unit/analysis/maths/test_divide.py:74: RuntimeWarning: divide by zero encountered in true_divide
  com = self.data_op(dat_b, dat_a)
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/maths.py:779: RuntimeWarning: divide by zero encountered in true_divide
  ret = operation_function(x, other)

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3169: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dout = self.data[indx]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3201: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  mout = _mask[indx]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/_scipy_interpolate.py:290: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return self.values[idx_res]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/trajectory.py:402: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  source_data = source_data[fancy_source_indices]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/trajectory.py:444: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_cube_coord.points = src_coord.points[fancy_coord_index_arrays]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/fileformats/pp_load_rules.py:326: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  slice_0 = array[slice_inds]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/util.py:164: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = np.where(ndarray[last_element] >= _delta[last_element])[0]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/util.py:165: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  _delta[last_element] -= circular

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/util.py:166: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  _delta[last_element][result] += 2*circular

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/fileformats/pp_load_rules.py:326: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  slice_0 = array[slice_inds]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/_scipy_interpolate.py:290: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return self.values[idx_res]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3169: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dout = self.data[indx]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3201: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  mout = _mask[indx]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/trajectory.py:402: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  source_data = source_data[fancy_source_indices]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/trajectory.py:444: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_cube_coord.points = src_coord.points[fancy_coord_index_arrays]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/_interpolation.py:300: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[dim_slices]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py:149: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = regrid(self.data[index], self.x_dim,

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/fileformats/pp_load_rules.py:326: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  slice_0 = array[slice_inds]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/util.py:164: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = np.where(ndarray[last_element] >= _delta[last_element])[0]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/util.py:165: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  _delta[last_element] -= circular

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/util.py:166: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  _delta[last_element][result] += 2*circular

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3308: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  _mask[indx] = True

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/_interpolation.py:300: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[dim_slices]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/_scipy_interpolate.py:290: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return self.values[idx_res]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3169: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dout = self.data[indx]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/ma/core.py:3201: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  mout = _mask[indx]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/trajectory.py:402: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  source_data = source_data[fancy_source_indices]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/trajectory.py:444: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_cube_coord.points = src_coord.points[fancy_coord_index_arrays]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/fileformats/pp_load_rules.py:326: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  slice_0 = array[slice_inds]

/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0.dev0-py3.6.egg/iris/analysis/__init__.py:1287: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = array.astype('float32')[slices]
</details>

**Comment by pp-mo** [comment]
I proposed a fix for this where it occurs in Iris tests,
(but that is targetted at the 2d_coords feature, not yet against master):
https://github.com/SciTools/iris/commit/edfd1685618719ff352f1a4314a12e200eea432c#diff-b12e25c97af9e67b4ff5aad90ad8f553

**Comment by mariuszgithub** [comment]
2018-12-22 02:37:31,683 INFO friture.analyzer: Friture 0.35.0.0 starting on Linux (linux)
2018-12-22 02:37:32,209 INFO friture.audiobackend: Initializing audio backend
2018-12-22 02:37:32,210 INFO friture.audiobackend: Opening the stream for device 'default'
2018-12-22 02:37:32,228 INFO friture.audiobackend: Device claims 42 ms latency
2018-12-22 02:37:32,233 INFO friture.audiobackend: Success
2018-12-22 02:37:32,254 ERROR friture.audiobackend: Failed to read stream time
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/friture-0.35-py3.6-linux-x86_64.egg/friture/audiobackend.py", line 422, in get_stream_time
    return self.stream.time
  File "/usr/local/lib/python3.6/dist-packages/sounddevice.py", line 946, in time
    raise PortAudioError('Error getting stream time')
sounddevice.PortAudioError: Error getting stream time
2018-12-22 02:37:32,304 INFO friture.dockmanager: First launch, display a default set of docks
2018-12-22 02:37:32,308 INFO friture.audioproc: audioproc: updating self.freq cache
2018-12-22 02:37:32,308 INFO friture.audioproc: audioproc: updating window
2018-12-22 02:37:32,308 INFO friture.audioproc: audioproc: will decimate 1 times
2018-12-22 02:37:32,309 INFO friture.audioproc: audioproc: updating self.freq cache
2018-12-22 02:37:32,311 INFO friture.audioproc: audioproc: updating window
2018-12-22 02:37:32,323 INFO friture.spectrogram_image: palette preparation
2018-12-22 02:37:32,327 INFO friture.audioproc: audioproc: updating self.freq cache
2018-12-22 02:37:32,327 INFO friture.audioproc: audioproc: updating window
2018-12-22 02:37:32,327 INFO friture.audioproc: audioproc: will decimate 1 times
2018-12-22 02:37:32,328 INFO friture.audioproc: audioproc: updating self.freq cache
2018-12-22 02:37:32,330 INFO friture.audioproc: audioproc: updating window
2018-12-22 02:37:32,330 INFO friture.signal.frequency_resampler: freq scale changed to 1.000000
2018-12-22 02:37:32,330 INFO friture.signal.frequency_resampler: freq range changed 20.000000 24000.000000
2018-12-22 02:37:32,350 INFO friture.analyzer: Timer start
2018-12-22 02:37:32,351 INFO friture.analyzer: Init finished, entering the main loop
2018-12-22 02:37:32,452 INFO friture.plotting.glCanvasWidget: OpenGL format: version 3.0, No profile, Desktop OpenGL rendering
2018-12-22 02:37:32,455 INFO friture.plotting.glCanvasWidget: nouveau, NVA5, Version: 3.0 Mesa 18.0.5, Shaders: 1.30, Extensions: 225
2018-12-22 02:37:32,504 INFO friture.ringbuffer: Ringbuffer: growing buffer for length 15360
2018-12-22 02:37:32,578 INFO friture.signal.frequency_resampler: nsamples changed, now: 169
2018-12-22 02:37:32,579 WARNING py.warnings: /usr/local/lib/python3.6/dist-packages/friture-0.35-py3.6-linux-x86_64.egg/friture/signal/scipy_resample.py:129: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  Y[sl] = X[sl]

2018-12-22 02:37:32,579 WARNING py.warnings: /usr/local/lib/python3.6/dist-packages/friture-0.35-py3.6-linux-x86_64.egg/friture/signal/scipy_resample.py:131: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  Y[sl] = X[sl]

2018-12-22 02:37:32,580 INFO friture.spectrogram_image: Spectrogram image: canvas_height changed, now: 169
2018-12-22 02:37:32,581 INFO friture.spectrogram_image: Spectrogram image: canvas_width changed, now: 248

**Comment by mariuszgithub** [comment]
szkoda oczu na patrzenie

**Comment by pp-mo** [comment]
RE: Your latest traceback + error.
does hit the same numpy warning,
but seems it **_does not involve Iris ?_**
