### ISSUE TITLE
Documenting the addition of a gallery entry

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#314]
Adding a documentation gallery example is a useful entry point for a new contributor, but this process is not well documented in the developer guide (https://groups.google.com/forum/#!topic/scitools-iris-dev/s5kBjBXzmrA)

Scope:
Adapt the Iris developer guide to include a page on how to add an entry to the gallery.
Include the build and test processes and a note on rights for sample data.

**Comment by tkknight** [comment]
Completed.  See https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_documentation.html#gallery and https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_graphics_tests.html
