### ISSUE TITLE
Remove dask pinning

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3147]
Remove the dask pin introduced by #3127 
~Assuming they have a new release by then (should be dask 0.18.3 or later)~
**Good to go :** dask v 0.19 is now out, and fixes it

To check : the key failing test was 
```python lib/iris/tests/unit/cube/test_Cube.py -v Test_data_dtype_fillvalue.test_lazydata___getitem__dtype```

**UPDATE:** dask 0.19 fixes original, but seems to cause new problems with Iris tests :disappointed: 
See : https://github.com/SciTools/iris/pull/3159 and [its checks](https://travis-ci.org/SciTools/iris/builds/424243234?utm_source=github_status&utm_medium=notification)

**Comment by dkillick** [comment]
#3185 explores completely unpinning dask.
