### ISSUE TITLE
Error checking attribute compliance when saving cube

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#3161]
Hello, I have a cube with a climatological seasonal cycle of CERES-EBAF radiation data, which looks like the below. I found I cannot save this cube to a NetCDF file unless I delete the 'valid_min' and 'valid_max' cube attributes. I'm using Iris 2.1.0.

    Top of The Atmosphere Longwave Flux, Monthly Means, All-Sky conditions / (W m-2) (time: 12; latitude: 72; longitude: 144)
     Dimension coordinates:
          time                                                                        x             -              -
          latitude                                                                    -             x              -
          longitude                                                                   -             -              x
     Auxiliary coordinates:
          month                                                                       x             -              -
     Attributes:
          CDI: Climate Data Interface version 1.6.4 (http://code.zmaw.de/projects/cdi...
          CDO: Climate Data Operators version 1.6.4 (http://code.zmaw.de/projects/cdo...
          CF_name: toa_outgoing_longwave_flux
          Conventions: CF-1.4
          Fill_Value: Fill Value is -999.0
          IPCC_name: none
          NCO: 4.0.8
          comment: Data is from East to West and South to North. Climatology from 03/2000...
          institution: NASA/LaRC (Langley Research Center) Hampton, Va
          invalid_standard_name: TOA Longwave Flux - All-Sky
          title: CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages and...
          valid_max:       400.000
          valid_min:       0.00000
          version: This is version 2.8: January 23, 2015
     Cell methods:
          mean: month

If I use iris.save() to try to save this to a NetCDF file, I get the following error:

    File "/home/anaconda2/envs/main/lib/python2.7/site-packages/iris/io/__init__.py", line 407, in save
      saver(source, target, **kwargs)

    File "/home/anaconda2/envs/main/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 2343, in save
      fill_value=fill_value)

    File "/home/anaconda2/envs/main/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 961, in write
      self.check_attribute_compliance(cube, cube.lazy_data())

    File "/home/anaconda2/envs/main/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 1045, in check_attribute_compliance
      new_val = _coerce_value(val_attr, val_attr_value, data_dtype)

    File "/home/anaconda2/envs/main/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 1021, in _coerce_value
      if (val_attr_tmp != val_attr_value).any():

    AttributeError: 'bool' object has no attribute 'any'`

I thought that even if there is a problem with the cube data, the above error should not occur, so that a helpful error message can be printed.

**Comment by ajdawson** [comment]
I suspect it may be possible to fix the immediate error by replacing `(val_attr_tmp != val_attr_value).any()` with `np.any(val_attr_tmp != val_attr_value)` as the latter will be happy with scalar input.
