### ISSUE TITLE
Iris.quickplots.contour and contourf with irregular grids

### ISSUE THREAD

**Issue by ledm** [SciTools/iris#3183]
Hi,

when plotting a cube with an irregular grid using iris.quickplot.contour or contourf, iris just ignores the latitude/longitude and plots the raw data. For instance:

![diag_cmip5_cesm1-bgc_oyr_historical_r1i1p1_to3y_o2_prep_depth_layers_cabre1ab_2001_2004_map_1](https://user-images.githubusercontent.com/4180685/46025973-1444df80-c0e2-11e8-871f-9504fa69a6cf.png)

Is it possible to plot irregular grids using iris.quickplot?

I have also raised this issue in the [ESMValTool github](https://github.com/ESMValGroup/ESMValTool/issues/615) and they suggested that I bring it here.

**Comment by dkillick** [comment]
Hi @ledm, thanks for raising this with us! Iris is very much set up with the expectation of mostly regular grids, which means that it is not so good when handling things like observational data, or indeed ocean data (as can be seen here).

That being said, we have recently been working on improving Iris' plotting capabilities particularly with regard to ocean grids, so it's possible you'll be able to benefit from that work in this case - @pp-mo might be able to shed some more light on this. Could you give a brief description of the irregular grid you're working with here?

**Comment by ledm** [comment]
Hi @dkillick,

this example is from the CESM1-BGC model, from CMIP5, historical scenario, r1i1p1 ensemble member in the Oyr MIP. The field is dissolved oxygen concentration at 1000m depth, although of course all the marine fields use the same grid.  

Nearly all of the CMIP5 models use irregular grids for the marine component of the Earth system. At the moment, iris is not able to make plots for any of them without (relatively expensive) regridding to a regular grid. 

Having said that, matplotlib/cartopy are capable of producing plots of irregular grids, so I can't imagine adding irregular grid support to contour and contourf would be a significant task. 

Lee

**Comment by ledm** [comment]
Hi, 

iris.plot produces a very similar plot to iris.quickplot.plot:

![diag_cmip5_cesm1-bgc_oyr_historical_r1i1p1_to3y_o2_prep_depth_layers_cabre1ab_2001_2004_map_0](https://user-images.githubusercontent.com/4180685/46466721-f3f0e100-c7c3-11e8-93d5-a3f5f1b4e31b.png)

**Comment by pp-mo** [comment]
Hi @ledm I'm a bit confused here.  
The recent 2d_coords work (soon to be merged :crossed_fingers:) covers cubes looking like ...
```
phenomenon-type / (units) (-- : <NY>; -- : <NX>)
     Auxiliary coordinates:
          latitude            x          x
          longitude           x          x
```

We need to see the cube coordinates here, I think.

**Comment by ledm** [comment]
The files used to make this plot are on BADC, here:
/badc/cmip5/data/cmip5/output1/CCCma/CanESM2/historical/mon/ocean/Omon/r1i1p1/latest/tos/

I believe that this netcdf does load in iris such that it has auxiliary coordinates that match the ones you show here. I simply took the time average and sent them to quickplot.contourf (and iris.plot.contourf). Fingers crossed that the recent work gets merged soon so we can use it in ESMValTool. Cheers!

**Comment by pp-mo** [comment]
> Fingers crossed that the recent work gets merged soon 

It is in the recent Iris 2.2 release.
Can you confirm whether this now works for that data, or are there further problems ?
