### ISSUE TITLE
Decide whether cubes are iterable

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#3186]
At the moment, cubes report as being iterables, but raise an error if you try to iterate over a cube:

```python
>>> isinstance(cube, Iterable)
True

>>> for c in cube:
...     print c

TypeError: Cube is not iterable
```

This is confusing and potentially a bit awkward, as it looks like Iris can't make its mind up...

Of course this comes down to the presence of the `__iter__` method, whose presence means the Cube class reports as being iterable, while the method itself just raises an error. We could:

* remove the `__iter__` method, which is simple to do but unfortunately reverses the problem (Cube reports as not being iterable, while you actually _can_ then iterate over a cube on its leading dimension)
* explicitly support iterating by extending `__iter__`, which is more complicated and potentially undefined
* ... do something more clever than either of these suggestions
* just ignore it

**Comment by pp-mo** [comment]
Long long ago... 
we explicitly stopped cubes being iterables because it was confusing a lot of users.
See : https://github.com/SciTools/iris/issues/86
