### ISSUE TITLE
iris.analysis.STD_DEV missing weights option

### ISSUE THREAD

**Issue by BenMGeo** [SciTools/iris#3208]
To have a correct result, don't we need a weighted standard deviation?

**Comment by BenMGeo** [comment]
To keep you updated:

I created a work around for it.

```
def weighted_STD_DEV(cube, dim, weights=None):

    if weights is None:
        return (cube.collapsed(dim, iris.analysis.RMS)**2 -
                cube.collapsed(dim, iris.analysis.MEAN)**def weighted_STD_DEV(cube, dim, weights=None):

    if weights is None:
        return (cube.collapsed(dim, iris.analysis.RMS)**2 -
                cube.collapsed(dim, iris.analysis.MEAN)**2)**0.5
    else:
        return (
            cube.collapsed(
                dim,
                iris.analysis.RMS,
                weights=weights)**2 -
            cube.collapsed(
                dim,
                iris.analysis.MEAN,
                weights=weights)**2)**0.52)**0.5
    else:
        return (
            cube.collapsed(
                dim,
                iris.analysis.RMS,
                weights=weights)**2 -
            cube.collapsed(
                dim,
                iris.analysis.MEAN,
                weights=weights)**2)**0.5
```

**Comment by ledm** [comment]
Is Iris going to receive a weighted Standard deviation function? Including @pp-mo and @bjlittle.

**Comment by ledm** [comment]
Similarly, the following functions do not accept the "weights" argument, but they probably should!

- iris.analysis.VARIANCE
- iris.analysis.STDEV
- iris.analysis.MEDIAN

**Comment by pp-mo** [comment]
Thinking about it, I don't think weighted _MEDIAN_ makes sense.
Supplying weights implies that, somewhere, somehow, a summation is involved.

The current set of Iris aggregators is (my ordering) :
  MEAN, RMS, VARIANCE, STD_DEV, 
  GMEAN, HMEAN, 
  SUM,
  COUNT, PROPORTION,
  MIN, MAX,
  MEDIAN, PERCENTILE, WPERCENTILE,
  PEAK,

Of these, I think those that could support weights are potentially "MEAN, RMS, VARIANCE, STD_DEV, GMEAN, HMEAN, SUM"
( Though I think the underlying implementing functions of GMEAN and HMEAN don't support weights, so it's not entirely trivial ).

FWIW, I'm really not clear at all what WPERCENTILE does.

**Comment by ledm** [comment]
Weighted median is indeed a real thing and we've used it quite extensively in BGC-val. 

For instance, when we're looking at the ocean under the ORCA grid, we have high resolution around the equator and low resolution elsewhere. This means that there are lots of cells in the equatorial region, and this biases the value of the median. 

Similarly, this problem becomes more extreme if you want the median value along the z direction where the deepest levels are several hundred meters thick and the surface are only 1m thick.

To solve these issues, we use the weighted median where the cell area are used as the weights: https://en.wikipedia.org/wiki/Weighted_median

Having said that, if you already have a weighted percentile operator, then weighted median is only a special case of that value and shouldn't be hard to produce.

**Comment by BenMGeo** [comment]
wpercentile is officially the weighted percentiles and you can calculate the weighted median by choosing the 50 percentile, so this is included in my eyes.

**Comment by pp-mo** [comment]
> @ledm Weighted median is indeed a real thing ...

Ooh, now I get it !
Thanks for explaining, that is genuinely extremely helpful.

Ok, that is on the list too.
As you say it is "just" a special case.  
However our percentiles code is much more complex + opaque than the median, because the basic operation can add (replace) a dimension rather than simply removing one.

**Comment by rcomer** [comment]
Related: #3146

**Comment by krikru** [comment]
What's the point of closing issues due to lack of activity? It seems to me like this is a workaround to make up for lacking issue filtering capabilities. Isn't is good to keep all unresolved issues opened so that they can be tracked?

**Comment by trexfeathers** [comment]
>Isn't it good to keep all unresolved issues opened so that they can be tracked?

1. Keeping an issue open implies that it will eventually be fixed. Like many software packages, Iris has more issues than can be fixed with the available resource, so we must make tough priority calls. I feel closing stale issues is therefore the more honest approach.
2. Evolving situations often mean that issues are no longer required. This could be a feature that is no longer needed, a fix in a dependency package, or something that we already fixed and forgot to close. The stale mechanism is a good way to tidy these.

And we can always re-open when something is wrongly closed. @krikru would you like this to be re-opened?
