### ISSUE TITLE
Irregular grids in iris.analsysis.cartopy.area_weights 

### ISSUE THREAD

**Issue by ledm** [SciTools/iris#3211]
The `area_weights` function in [iris.analysis.cartopy.py](https://github.com/SciTools/iris/blob/v2.2.x/lib/iris/analysis/cartography.py) isn't built for working for irregular grids. 

Are there any plans to expand this function to handle irregular grids?

**Comment by ledm** [comment]
Similarly, it is possible to load the cell area or volumes from the fx_files (grid description files)? Cell area/volume would be a very useful auxiliary data in a cube.

**Comment by bjlittle** [comment]
@ledm Yup, the `iris.analysis.cartography.area_weights` was never built to handle irregular grids, sorry.

There has been debate that this function doesn't even really belong within `iris`, but we added it at the time as a user convenience. 

That said, there is a science mandate at the Met Office for `iris` to handle high resolution unstructured grids natively. This will be a major change and development investment to engineer and implement this for `iris`, so yes this is most definitely on the cards. We're tentatively spinning up on science requirements at the moment.

**Comment by bjlittle** [comment]
@ledm With regards to your request for cell areas and volumes... is this a request for `iris` to support [CF cell-measures](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#cell-measures) ?

**Comment by ledm** [comment]
In the context of ESMValTool, this problem was addressed when further support for FX files was added (around December 2018).

However, in the future, I can imagine it would be useful for cube metadata in iris to include cell area and volume. I would envision that this would work in the same way that cubes include dimension metadata. I don't know much about cell_measures in netcdfs, but it appears to be a similar idea.

**Comment by pp-mo** [comment]
Sorry I'm late to the party but ...
***Exactly what do you mean by irregular****
Can you provide a crude example of the types of coordinates you mean ?

I ask because, some people would call y=[1, 2, 3] x=[1, 4, 5] "irregular".

So, are your Xs and Ys **inherently 2-dimensional**, as @bjlittle implies where he calls the grid "unstructured" [in the comment above](https://github.com/SciTools/iris/issues/3211#issuecomment-498873555) ??

**Comment by ledm** [comment]
Yes, by irregular we mean that latitude and longitude are two dimensional coordinates, and that latitude and longitude both vary along both the x and y axes of the 2 dimensional arrays.
