### ISSUE TITLE
Silent package installation during `python setup.py install`

### ISSUE THREAD

**Issue by tv3141** [SciTools/iris#3224]
Iris installs `cycler`, `toolz`, and `cython` during `python setup.py install`, non of which is listed as Iris requirement.
https://travis-ci.org/tv3141/iris/jobs/453714575#L4937

There is no trace of this in the log files, as the installation is run in quiet mode: 
`python setup.py install --quiet`
https://github.com/SciTools/iris/blob/master/.travis.yml#L118

**Comment by bjlittle** [comment]
@tv3141 These packages are all dependencies pulled in by the primary package dependencies of `iris` i.e., `iris` requires `dask`, but `dask` then pulls in `toolz` as one of its dependencies e.t.c.
