### ISSUE TITLE
DOC: Add a link to `devdocs` in README

### ISSUE THREAD

**Issue by kaedonkers** [SciTools/iris#3226]
The [README](https://github.com/SciTools/iris/blob/master/README.md) for Iris currently has a link to the documentation for the latest [*release*](https://scitools.org.uk/iris/docs/latest/) of Iris. However it would also be useful to link to the documentation for the latest [*master*](https://scitools.org.uk/iris/docs/latest/) of Iris. This link is available in the repo [Wiki](https://github.com/SciTools/iris/wiki/Release-checklist-guidance), but not the README.

For instance this is implemented by Matplotlib with their `devdocs` -> https://matplotlib.org/devdocs/index.html

**Comment by tkknight** [comment]
The [README](https://github.com/SciTools/iris/blob/master/README.md) has been slimmed down to a logo, badges and a link to the documentation.  This was done to avoid duplication, lets keep all the info in the official documentation.

As of the imminent Iris 3.0.0 release the documentation is now provision via Read The Docs https://scitools-iris.readthedocs.io/en/latest/index.html#.

Currently there is only the link on the README and that uses the **latest**.  Using Read The Docs (and after Iris 3.0.0 is release) the following will be true:

- https://scitools-iris.readthedocs.io/en/latest/index.html.  This is **latest**.  Essentially the **latest development** docs, based on **master**.
- https://scitools-iris.readthedocs.io/en/stable/index.html.  This is **stable**.  This should be the **latest release**, as Read The Docs only knows of **Iris 3.0.0**, it should point to it.

Once Iris 3.0.0 is releases the README will also be updated to include a link to the **stable documentation**.

Note that you can still access the **legacy** documentation (Iris 2.4 and earlier) via https://scitools.org.uk/iris/docs/v2.4.0/

**Comment by tkknight** [comment]
I'll keep this issue open as a reminder to update the Iris [README ](https://github.com/SciTools/iris/blob/master/README.md)once Iris 3.0.0 is done.
