### ISSUE TITLE
Efficient disk access when subsetting a cube

### ISSUE THREAD

**Issue by tkarna** [SciTools/iris#3227]
When reading a netCDF file, iris reads the entire data array into memory before creating the subset. This becomes very expensive for large files and the process can easily run out of memory.

I'm working with NEMO ocean model output files that can be 100+ GB in size. Typically one wants to extract a time series from a 4D (t, x, y, z) field using the nearest neighbor method. If the netCDF file is not compressed, this is a relatively fast operation as one can just read a time series at a single (x, y, z) node.

Is there a way to extract a time series from a 4D field efficiently? Or do I have to write up the nearest neighbor lookup myself?

**Comment by bjlittle** [comment]
Hi @tkarna,

Thanks for getting in touch. Can you give me a specific example of the type of operation that you're doing, and also the version of iris.

Ideally, I'd like to recreate your issue and take it from there...

Thanks.

**Comment by tkarna** [comment]
Sure, here's an example. For the sake of completeness first define a 4D dataset:
```python
import datetime
import numpy
import iris

# fabricate a dummy (t, z, y, x) data set
lat = numpy.linspace(40, 50, 11)
lon = numpy.linspace(10, 30, 21)
z = numpy.linspace(0, 20, 6)
time = numpy.arange(32, dtype=float)*600.
date_zero = datetime.datetime(2000, 1, 1)
date_epoch = datetime.datetime.utcfromtimestamp(0)
time_epoch = time + (date_zero - date_epoch).total_seconds()
LON, LAT = numpy.meshgrid(lon, lat)
salt = 10*(numpy.sin(LAT/10.)*numpy.sin(LON/20.) + 1)
time_factor = 1.5 + 0.5*numpy.sin(2*numpy.pi/6/3600.*time)
depth_factor = 0.5 + z/20.
salt = depth_factor[:, numpy.newaxis, numpy.newaxis] * salt[numpy.newaxis, :, :]
salt = time_factor[:, numpy.newaxis, numpy.newaxis, numpy.newaxis] * salt[numpy.newaxis, :, :, :]

# create a cube
time_dim = iris.coords.DimCoord(time_epoch, standard_name='time', units='seconds since 1970-01-01 00:00:00-00')
z_dim = iris.coords.DimCoord(z, standard_name='depth', units='m')
lon_dim = iris.coords.DimCoord(lon, standard_name='longitude', units='degrees')
lat_dim = iris.coords.DimCoord(lat, standard_name='latitude', units='degrees')
cube = iris.cube.Cube(salt, standard_name='sea_water_practical_salinity', units='1')
cube.add_dim_coord(time_dim, 0)
cube.add_dim_coord(z_dim, 1)
cube.add_dim_coord(lat_dim, 2)
cube.add_dim_coord(lon_dim, 3)
iris.save(cube, 'salinity.nc')
```

Now extract a time series with iris. This reads the entire 4D data array into memory.
```python
cube = iris.load('salinity.nc', 'sea_water_practical_salinity')[0]
interp = iris.analysis.Nearest(extrapolation_mode='error')
target = [('depth', 8.0), ('latitude', 42.5), ('longitude', 15.5)]
cube_ts = cube.interpolate(target, interp)
```

Efficient extraction with `netCDF4`. Orders of magnitude faster if the data set is large.
```python
import netCDF4

# find nearest neighbor indices
target_z = 8.0
target_lat = 42.5
target_lon = 15.5

with netCDF4.Dataset('salinity.nc') as ncfile:
    lat = ncfile['latitude'][:]
    lon = ncfile['longitude'][:]
    z = ncfile['depth'][:]
    # find nearest point in each dimension
    # in the general case one should do a 3D search (e.g. with a KDTree)
    i = numpy.abs(target_z - z).argmin()
    j = numpy.abs(target_lat - lat).argmin()
    k = numpy.abs(target_lon - lon).argmin()

# extract time series
with netCDF4.Dataset('salinity.nc') as ncfile:
    time_epoch = ncfile['time'][:]
    # read only one (x, y, z) point from disk
    values = ncfile['sea_water_practical_salinity'][:, i, j, k]

cube_ts2 = iris.cube.Cube(values, standard_name='sea_water_practical_salinity', units='1')
time_dim = iris.coords.DimCoord(time_epoch, standard_name='time', units='seconds since 1970-01-01 00:00:00-00')
cube_ts2.add_dim_coord(time_dim, 0)
```
I'm using iris v2.2 installed with conda.

**Comment by pp-mo** [comment]
Great clear example ! :+1:
But I think there is a scope problem here...

This isn't a problem with netcdf access in general -- it is **specific to  the 'interpolate' operation**, 
which does not understand how to avoid accessing the whole cube data. 
In fact at present, it does simply fetch the lot : https://github.com/SciTools/iris/blob/v2.2.0/lib/iris/analysis/_interpolation.py#L614 

I'm not totally sure how to fix this, but there must be ways.
Perhaps we could load only the smallest hypercubic region including all the target source datapoints ?
From a quick look though, I think that the way the existing code is based on scipy makes it hard to do this :-(

**Comment by tkarna** [comment]
I agree that it's not easy to find a generic solution. Supporting nearest neighbor interpolation should not be too hard but, as you said, in the generic case one would need to find the convex hull that contains the target points, and do interpolation with the subset.

Maybe one could use `scipy.spatial.qhull` and `scipy.interpolate.griddata` to achieve this. These do triangulate the input data set, however, so this would be very slow if the triangulated source grid is large, e.g. when you do full 3D regridding.
