### ISSUE TITLE
Failing tests for Mercator coord_system

### ISSUE THREAD

**Issue by ajdawson** [SciTools/iris#3230]
The tests for the Mercator coord system are failing when run with cartopy 0.17. This looks like it is because the behaviour of cartopy changed ever so slightly with regard to the handling of the `latitude_true_scale` parameter in the Mercator projection. Previously cartopy used a default value of `0.0` for the proj4 parameter `lat_ts` if the `latitude_true_scale` parameter was not passed to the `Mercator` CRS, whereas from 0.17 it omits the `lat_ts` parameter from the proj4 definition if `latitude_true_scale` is not provided.

This is relevant because the tests for the Mercator coord system in iris create a default `iris.coord_systems.Mercator()` object, convert to a cartopy representation, then compare this to a `cartopy.crs.Mercator()` instance and expect them to be the same. However, since cartopy 0.17 they will not compare equal because their proj4 parameters will be different (`lat_ts=0.0` vs no `lat_ts`). I believe they are still equivalent since proj4 uses a default `lat_ts=0.0` if you don't provide it, they just don't look equal.

We may want to modify our tests to compare apples with apples. An `iris.coord_systems.Mercator` instance will always pass `latitude_true_scale` to the `cartopy.crs.Mercator` constructor when converting to a cartopy CRS, so our test should really compare this to a `cartopy.crs.Mercator(latitude_true_scale=0.0)` instance, otherwise we are assuming too much about how cartopy handles default arguments.

**Comment by corinnebosley** [comment]
Thanks @ajdawson, I'm on it.

**Comment by bjlittle** [comment]
Closed by #3232, thanks @corinnebosley
