### ISSUE TITLE
missing example in the user guide for time constraints

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#3235]
To my mind the Iris user guide skips a step in discussing time constraints. After the example with cube_11 = cube_all.extract(hour_11), an example where you have 2 dates in datetime format and want to constrain the data to be between these two dates seems a really common use case. 

something like:
```

d1 = datetime.datetime.strptime('20070416T0000Z', '%Y%m%dT%H%MZ')
d2 = datetime.datetime.strptime('20070430T0000Z', '%Y%m%dT%H%MZ')

daterange = iris.Constraint(time=lambda cell: d1<= cell.point <= d2)
data_subset = long_ts.extract(daterange)
```
Do other people think that this would be a useful addition? I think it is probably a fairly common use case and I got a bit confused by the discussion of partial datetime which cool but not needed here. I am happy to give this a go if people want it.

**Comment by bjlittle** [comment]
Thanks for taking the time to highlight this @nhsavage.

I think that this would make a nice addition to the user guide. It's a small example, but like you said, is a very common use case. So I think that many users would fine it both useful and helpful.

If you pushed up a PR, I'd merge it :smile:

**Comment by bjlittle** [comment]
@stephenworsley Reference [2.3.2 Constraining](https://scitools.org.uk/iris/docs/latest/userguide/loading_iris_cubes.html#constraining-on-time) on Time from the Iris documentation.

**Comment by lbdreyer** [comment]
A example for constraining to a datetime range has been added in #3352.
