### ISSUE TITLE
Loading grib cubes

### ISSUE THREAD

**Issue by WxmanJ** [SciTools/iris#3244]
There seems to be an issue recognizing/loading different levels using iris.load with grib data. 

My file contains the following parameter and levels per wgrib2.
`6:785353:d=2018121712:HGT:1 mb:anl:
12:1351029:d=2018121712:HGT:2 mb:anl:
18:1881529:d=2018121712:HGT:3 mb:anl:
24:2412622:d=2018121712:HGT:5 mb:anl:
30:2980133:d=2018121712:HGT:7 mb:anl:
36:3476637:d=2018121712:HGT:10 mb:anl:
43:4018497:d=2018121712:HGT:20 mb:anl:
50:4716310:d=2018121712:HGT:30 mb:anl:
57:5567301:d=2018121712:HGT:50 mb:anl:
64:6481437:d=2018121712:HGT:70 mb:anl:
71:7470405:d=2018121712:HGT:100 mb:anl:
80:8792618:d=2018121712:HGT:150 mb:anl:
89:10254096:d=2018121712:HGT:200 mb:anl:
98:11870166:d=2018121712:HGT:250 mb:anl:
107:13454106:d=2018121712:HGT:300 mb:anl:
116:15157797:d=2018121712:HGT:350 mb:anl:
125:16826020:d=2018121712:HGT:400 mb:anl:
134:18504973:d=2018121712:HGT:450 mb:anl:
142:19904612:d=2018121712:HGT:500 mb:anl:
150:21429165:d=2018121712:HGT:550 mb:anl:
158:22954595:d=2018121712:HGT:600 mb:anl:
166:24507009:d=2018121712:HGT:650 mb:anl:
174:26091169:d=2018121712:HGT:700 mb:anl:
182:27706005:d=2018121712:HGT:750 mb:anl:
190:29353389:d=2018121712:HGT:800 mb:anl:
198:31032891:d=2018121712:HGT:850 mb:anl:
206:32751968:d=2018121712:HGT:900 mb:anl:
214:34484719:d=2018121712:HGT:925 mb:anl:
222:36265219:d=2018121712:HGT:950 mb:anl:
231:38018840:d=2018121712:HGT:975 mb:anl:
247:41318522:d=2018121712:HGT:1000 mb:anl:
249:41822914:d=2018121712:HGT:surface:anl:
284:47033277:d=2018121712:HGT:tropopause:anl:
291:48605390:d=2018121712:HGT:max wind:anl:
312:52960486:d=2018121712:HGT:0C isotherm:anl:
314:53317888:d=2018121712:HGT:highest tropospheric freezing level:anl:
343:58003729:d=2018121712:HGT:PV=2e-06 (Km^2/kg/s) surface:anl:
349:58731366:d=2018121712:HGT:PV=-2e-06 (Km^2/kg/s) surface:anl:`

When viewing the cubes available with iris for the same file, I am getting the following results.
`0: geopotential_height / (m)           (pressure: 31; latitude: 361; longitude: 720)
1: geopotential_height / (m)           (latitude: 361; longitude: 720)
2: geopotential_height / (m)           (latitude: 361; longitude: 720)
3: geopotential_height / (m)           (latitude: 361; longitude: 720)
4: geopotential_height / (m)           (latitude: 361; longitude: 720)
5: geopotential_height / (m)           (latitude: 361; longitude: 720)
6: geopotential_height / (m)           (latitude: 361; longitude: 720)
7: geopotential_height / (m)           (latitude: 361; longitude: 720)
`

**Comment by WxmanJ** [comment]
Founds the load_raw() function that displays all variables.

**Comment by ajdawson** [comment]
For what it is worth, the original output you showed indicates iris is sucessfully loading all the fields shown in the wgrib2 output, that is:

* cube 0 has the 31 pressure levels
* the remaining 7 cubes are the 7 single level fields (surface, tropopause, max wind, 0C isotherm, highest freezing level, +/- 2PVU

Iris will always try to combine fields into the smallest number of cubes possible, in this case it was able to create a pressure dimension and merge all of the pressure level fields into one cube, which is generally more convenient for analysis.
