### ISSUE TITLE
Unit unification fails silently

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#3251]
hey guys, `iris.util.unify_time_units` seems to fail silently in some cases, here's an example case:

```
In [38]: iris.__version__                                                                                                                                     
Out[38]: '2.2.0'

In [39]: c.coord('time').units                                                                                                                                
Out[39]: Unit('days since 1860-01-01 00:00:00', calendar='gregorian')

In [40]: e.coord('time').units                                                                                                                                
Out[40]: Unit('day since 1950-01-01 00:00:00.0000000', calendar='365_day')

In [41]: iris.util.unify_time_units(iris.cube.CubeList([c, e]))                                                                                               

In [42]: c.coord('time').units                                                                                                                                
Out[42]: Unit('days since 1860-01-01 00:00:00', calendar='gregorian')

In [43]: e.coord('time').units                                                                                                                                
Out[43]: Unit('day since 1950-01-01 00:00:00.0000000', calendar='365_day')
```
and same behavior for iris=1.13 as well; this is something we have just noticed via ESMValTool. Could you pls have a look and investigate? I have a hunch this is due to different calendars but we'd be happy if iris threw at least a warning if not a full blown trace. Cheers muchly in advance!

**Comment by valeriupredoi** [comment]
ah cheers muchly @ajdawson - this is crystal clear now; am gonna close the issue, much appreciated! :beer:

**Comment by ajdawson** [comment]
It may have made more sense to implement this function by throwing an exception if multiple calendars were discovered. I don't recall what the design decisions were at the time, but changing it now could affect users expecting the old behaviour.

I would imagine a suitable work-around for you is to do this pre-check that all calendars are the same before calling `unify_time_units`, and take whatever action you need to if this condition is not met.

**Comment by valeriupredoi** [comment]
yup, that's exactly what we're doing now, the confusion stemmed from me overly trusting this function :grin:
