### ISSUE TITLE
Mis-named routine in docs for  iris.util.find_discontiguities

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3253]
From comment on diff, attached to #3144 :

https://github.com/SciTools/iris/commit/70f57e48d497fa726b0a8ded885c0c553859b686#commitcomment-32130089

> @zklaus Hi, sorry for the late show and not doing a proper issue, but:
In the docs for iris.util.find_discontiguities there are several mentions of iris.util.mask_discontiguities.
This function seems not to exist. Maybe the intention was iris.util.mask_cube?

**Comment by pp-mo** [comment]
@zklaus do you fancy submitting a fix for this yourself ?

If not, it seems quite simple, so I'll tackle it myself in a day or two.

**Comment by zklaus** [comment]
I'm a bit pressed for time. I'll leave it to @corinnebosley for now, otherwise I might get around to it late next week.
