### ISSUE TITLE
Clarify licence (LGPLv3, or GPLv3 as in COPYING file?)

### ISSUE THREAD

**Issue by mjwillson** [SciTools/iris#3254]
Your COPYING file contains the GPLv3 licence, but code headers state LGPLv3. Could you clarify what the intent is? Thanks!

**Comment by ajdawson** [comment]
The license is LGPL as stated by the COPYING.LESSER file. The GNU guidelines on how to apply the LGPL state that both COPYING (the GPL) and COPYING.LESSER (LGPL) should be present to indicate use of the LGPL, see https://www.gnu.org/licenses/gpl-howto.html.
