### ISSUE TITLE
Add support for cf_role timeseries_id in NetCDF

### ISSUE THREAD

**Issue by jiskattema** [SciTools/iris#3271]
Iris (master branch) reports errors when loading a netcdf file with timeseries data.
The file contains timeseries for various stations, and gives the station name using 'cf_role: timeseries_id' and string data. (example file attached)

[timeseries_id.cdl.txt](https://github.com/SciTools/iris/files/2879965/timeseries_id.cdl.txt)
[error.txt](https://github.com/SciTools/iris/files/2879981/error.txt)

Note that iris on conda (v2.2.0) can load the file, but that that version gives errors when you try to save the cube back to netcdf.

**Comment by jiskattema** [comment]
I have a branch that fixes this issue here https://github.com/NLeSC/iris/tree/timeseries

**Comment by pp-mo** [comment]
There is a problem with your example : It is not CF-compliant, because you must use character arrays and not strings.
See : http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_data_types 
> "NetCDF does not support a character string type, so these must be represented as character arrays. In this document, a one dimensional array of character data is simply referred to as a "string". An n-dimensional array of strings must be implemented as a character array of dimension (n,max_string_length), with the last (most rapidly varying) dimension declared large enough to contain the longest string in the array."

That's where the Iris error comes from, I think.iir

>  iris on conda (v2.2.0) can load the file, but that that version gives errors when you try to save the cube back to netcdf.


Oddly, I'm getting a different error to you :
```
>>> import iris
>>> print(iris.__version__)
2.2.0
>>> cube = iris.load_cube('timeseries_id.nc')
 . . . UserWarning: Failed to create 'station' dimension coordinate: The points array must be numeric.
Gracefully creating 'station' auxiliary coordinate instead.
  error=e_msg))
>>> print(cube)
precipitation_amount / (mm)         (-- : 2; time: 10)
     Dimension coordinates:
          time                          -        x
     Auxiliary coordinates:
          latitude                      x        -
          longitude                     x        -
          station name                  x        -
     Attributes:
          Conventions: CF-1.4
          description: Daily precipitation amount (in 0.1 mm)
          featureType: timeSeries
>>>
>>> print(cube.coord('station name'))
AuxCoord(array(['StationB', 'StationA'], dtype=object), standard_name=None, units=Unit('no_unit'), long_name='station name', var_name='station', attributes={'cf_role': 'timeseries_id'})
>>> 
>>> iris.save(cube, 'timeser_2.nc')
Traceback (most recent call last):
 . . .File "/opt/scitools/environments/experimental/2019_02_08/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 993, in write
    self._add_aux_coords(cube, cf_var_cube, dimension_names)
  File "/opt/scitools/environments/experimental/2019_02_08/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 1139, in _add_aux_coords
    coord)
  File "/opt/scitools/environments/experimental/2019_02_08/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 1656, in _create_cf_variable
    cf_name, points.dtype.newbyteorder('='), cf_dimensions)
  File "netCDF4/_netCDF4.pyx", line 2557, in netCDF4._netCDF4.Dataset.createVariable
  File "netCDF4/_netCDF4.pyx", line 3490, in netCDF4._netCDF4.Variable.__init__
TypeError: illegal primitive data type, must be one of dict_keys(['S1', 'i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f4', 'f8']), got object
>>> 
```

That is the same in both in Iris 2.2.0 and current master, for me.

**Comment by pp-mo** [comment]
>  iris on conda (v2.2.0) can load the file, but that that version gives errors when you try to save the cube back to netcdf.


Oddly, I'm getting a different error to you :
```
>>> import iris
>>> print(iris.__version__)
2.2.0
>>> cube = iris.load_cube('timeseries_id.nc')
 . . . UserWarning: Failed to create 'station' dimension coordinate: The points array must be numeric.
Gracefully creating 'station' auxiliary coordinate instead.
  error=e_msg))
>>> print(cube)
precipitation_amount / (mm)         (-- : 2; time: 10)
     Dimension coordinates:
          time                          -        x
     Auxiliary coordinates:
          latitude                      x        -
          longitude                     x        -
          station name                  x        -
     Attributes:
          Conventions: CF-1.4
          description: Daily precipitation amount (in 0.1 mm)
          featureType: timeSeries
>>>
>>> print(cube.coord('station name'))
AuxCoord(array(['StationB', 'StationA'], dtype=object), standard_name=None, units=Unit('no_unit'), long_name='station name', var_name='station', attributes={'cf_role': 'timeseries_id'})
>>> 
>>> iris.save(cube, 'timeser_2.nc')
Traceback (most recent call last):
 . . .File "/opt/scitools/environments/experimental/2019_02_08/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 993, in write
    self._add_aux_coords(cube, cf_var_cube, dimension_names)
  File "/opt/scitools/environments/experimental/2019_02_08/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 1139, in _add_aux_coords
    coord)
  File "/opt/scitools/environments/experimental/2019_02_08/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 1656, in _create_cf_variable
    cf_name, points.dtype.newbyteorder('='), cf_dimensions)
  File "netCDF4/_netCDF4.pyx", line 2557, in netCDF4._netCDF4.Dataset.createVariable
  File "netCDF4/_netCDF4.pyx", line 3490, in netCDF4._netCDF4.Variable.__init__
TypeError: illegal primitive data type, must be one of dict_keys(['S1', 'i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f4', 'f8']), got object
>>> 
```

That is the same in both in Iris 2.2.0 and current master, for me.
I can also successfully load with Iris master.

The difference might lie in the netCDF4-python version ??
I have ...
```
>>> import netCDF4 as nc
>>> print(nc.__version__)
1.4.2
>>> 
```
That is consistent with the version in the most recent CI tests : https://travis-ci.org/SciTools/iris/jobs/492807079#L1011

**Comment by pp-mo** [comment]
I tried just replacing the string variable with a character array, and then it definitely does work as expected, for me :
```
$ head timeseries_id_array.cdl.txt
// compile with: ncgen -k nc4 -o timeseries_id.nc timeseries_id.cdl
netcdf exmple {
dimensions:
	station = 2 ;
	time = 10 ;
	max_chars = 10 ;
variables:
	char station(station, max_chars) ;
		station:long_name = "station name" ;
		station:cf_role = "timeseries_id" ;

$ 
$ diff timeseries_id.cdl.txt timeseries_id_array.cdl.txt
5a6
> 	max_chars = 10 ;
7c8
< 	string station(station) ;
---
> 	char station(station, max_chars) ;
$ 

>>> cube = iris.load_cube('timeseries_id_array.nc')
>>> print(cube)
precipitation_amount / (mm)         (-- : 2; time: 10)
     Dimension coordinates:
          time                          -        x
     Auxiliary coordinates:
          latitude                      x        -
          longitude                     x        -
          station name                  x        -
     Attributes:
          Conventions: CF-1.4
          description: Daily precipitation amount (in 0.1 mm)
          featureType: timeSeries
>>> print(cube.coord('station name'))
AuxCoord(array(['StationB', 'StationA'], dtype='<U10'), standard_name=None, units=Unit('1'), long_name='station name', var_name='station', attributes={'cf_role': 'timeseries_id'})
>>> iris.save(cube, 'timeser_2.nc')
>>> 
```

**Comment by jiskattema** [comment]
My conda install was be broken during development, so that's probably the difference there.
I missed the fact that strings are valid netcdf, but not CF compliant.. replacing it with the char array does work.

**Comment by pp-mo** [comment]
Status Summary: 
I'm not quite sure which "bits" of your proposed change are still relevant here.

We are hoping to have a concerted effort on supporting CF>1.5 at some point, 
but meanwhile this does seem a useful proposal.  
**I think you can convert this into a viable PR by reverting the changes to handle string arrays, but it should also have some tests in it.**

**Comment by pp-mo** [comment]
The thing I'm **_not_** sure of is whether we can have a non-numeric "dimension coordinate".  I think that will be too much of a change to contemplate at this point.
Notes :
  * what CF calls a 'coordinate', iris refers to as a 'dimension coordinate'
    * this carries primary values associated with a dimension : the variable shares the dimension's name (though CF barely uses the concept of a dimension).
  * variables referenced in a 'coords' attribute that _aren't_ "dimension coordinates", Iris just calls  'auxiliary coordinate's, as CF does
  * in Iris ...
    * a dimension coordinate is represented by a DimCoord instance
    * an auxiliary coordinate can be represented as either a DimCoord, or an AuxCoord instance.  
    * a DimCoord must be 1-dimensional; the data is a "concrete" numpy array; it is checked for monotonicity on creation; it can't contain masked or NaN points
    * an AuxCoord can be multidimensional, and the data may be _lazy_ instead of concrete; points can be masked or NaNs

**Comment by jiskattema** [comment]
ok, i was just typing something similar ;)
remaining point of my changes is consistent handling of the 'instance variable', it is always created as a auxcoord, not as a fallback when creating it as a dimcoord fails. 
According to the CF spec it is allowed to have NaNs, be not monotonic, and be of any type so an AuxCoord would be a more natural fit.

**Comment by mo-g** [comment]
@jiskattema Can you point me to some reference for that? Looking through the 1.7 spec for 'instance variable' I get this:

> The instance variables **will be scalar coordinate variables**; the data variable and other auxiliary coordinate variables will have only an element dimension and not have an instance dimension, e.g. data(o) and t(o) for a single timeSeries.

**Comment by jiskattema** [comment]
Thanks for looking into this, but my original issue was solved (invalid netcdf).

I find the CF-conventions not very understandable on this topic. To summarizing my understanding:  instance variables in netcdf should always be AuxCoords in iris. 

Some relevant quotes from the CF-convention 1.6 are below.


Section 9.6 on missing data in discrete sampling geometries:
> 
> In data for discrete sampling geometries written according to the rules of this section, wherever there are unused elements in data storage, the data variable and all its auxiliary coordinate variables (spatial and time) must contain missing values. This situation may arise for the incomplete multidimensional array representation, and in any representation if the instance dimension is set to a larger size than the number of features currently stored. Data variables should (as usual) also contain missing values to indicate when there is no valid data available for the element, although the coordinates are valid.
> 
> Similarly, for indices where the instance variable identified by cf_role contains a missing value indicator, all other instance variables should also contain missing values.
> 

Section 9.5, second alinea, on the type of the instance variable:

> Where feasible a variable with the attribute cf_role should be included.  The only acceptable values of cf_role for Discrete Geometry CF data sets are timeseries_id , profile_id , and trajectory_id .   **The variable carrying the cf_role attribute may have any data type.**  When a variable is assigned this attribute, it must provide a unique identifier for each feature instance.   CF files that contain timeSeries, profile or trajectory featureTypes, should include only a single occurrence of a cf_role attribute;  CF files that contain timeSeriesProfile or trajectoryProfile may contain two occurrences, corresponding to the two levels of structure in these feature types.

labels data, section 6.1:

> Character strings labelling the elements of an axis are regarded as string-valued auxiliary coordinate variables. The coordinates attribute of the data variable names the variable that contains the string array. An application processing the variables listed in the coordinates attribute can recognize a string-valued auxiliary coordinate variable because it contains an array of character data.

**Comment by mo-g** [comment]
I don't think any of that specifically mandates the use of an AuxCoord - it seems permissive. I'd read that as - both Coord and AuxCoord are valid, subject to the data supplied meeting the internal requirements of those classes.

I also think an implementation that *forced* AuxCoord would be equally correct, but not more correct than the either/or approach currently taken.
