### ISSUE TITLE
Bug: Calculating wind stress curl using iris.analysis.calculus.curl

### ISSUE THREAD

**Issue by ledm** [SciTools/iris#3278]
Hi,

I'm trying to calculate wind stress curl from CMIP5 using `iris.analysis.calculus.curl`. I'm was getting the error:
```
ValueError: Vector phenomenon name not consistent between vector cubes. Got cube phenomena: downward_eastward_stress, downward_northward_stress; from standard names: surface_downward_eastward_stress, surface_downward_northward_stress.
```

I think the problem stems from: the calculus function is trying to determine the direction of the two cubes, but gets confused as the standard_name for these fields are: `surface_downward_eastward_stress` & `surface_downward_northward_stress`. 
This means that when you get to [Line 737](https://github.com/SciTools/iris/blob/master/lib/iris/analysis/calculus.py#L737) of the curl function in iris.analysis.calculus.py, you create two tuples: 

```
cube_directions: ('surface', 'surface')
cube_phenomena: ('downward_northward_stress', 'downward_eastward_stress')
```
It looks like the standard_name beginning with the word `surface` is what is causing the confusion.

**Comment by bjlittle** [comment]
We should investigate this to see if there is an easy win that might sneak into the 2.2.1 release... no promises though :stuck_out_tongue_winking_eye:

**Comment by ledm** [comment]
I've also found that curl fails when looking at 2D data, ie, datasets without a Z dimension.

ie: [Line 554 of calculus.py](https://github.com/SciTools/iris/blob/master/lib/iris/analysis/calculus.py#L554) fails:
```
        z_coord = i_cube.coord(axis='Z')
```

**Comment by pp-mo** [comment]
Sadly this won't go in 2.2.1 cos we're not ready on it yet.
