### ISSUE TITLE
Add lazy `aggregated_by`

### ISSUE THREAD

**Issue by zklaus** [SciTools/iris#3280]
At the moment, `collapsed` is the only lazy statistics method. It would be useful to also have `aggregated_by` in a lazy version, i.e. allow for the use of lazy aggregators.

This touches on #2418, and #2928.

**Comment by valeriupredoi** [comment]
any chance `collapsed` with kwargs alike `weights` can be converted to lazy as well? There are really large differences in performance between collapsing with/without weights, see https://github.com/ESMValGroup/ESMValTool/issues/887 (my apologies if this comment is slightly off-topic)

**Comment by zklaus** [comment]
@valeriupredoi I can definitely have a look. But first this needs to be finished.

**Comment by valeriupredoi** [comment]
absolutely - I will actually have a talk with @bjlittle about this (and other iris stuffs) on Monday :beer:
