### ISSUE TITLE
NaNs in coords of regridded cubes

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3282]
If you regrid a cube with an aux-factory, "ordinary" aux-coords are discarded, but factory dependencies are regridded.  If it involves any extrapolation, those points get NaNs.

Although it seems this was a definite past decision, I'm now questioning whether this is correct ...

Example:
```
>>> import iris
>>> import iris.tests.stock as istk
>>> 
>>> cube = istk.realistic_4d()[0, 0, [8, 30], 50:53]
>>> for axis in ('x', 'y'):
...   cube.coord(axis=axis).bounds = None
... 
>>> print(cube.coord(axis='y').points)
[-0.1206 -0.1008]
>>> 
>>> gridcube = cube.copy()
>>> gridcube.coord(axis='y').points = [-0.125, -0.115]
>>> result = cube.regrid(gridcube, iris.analysis.Linear())
>>> 
>>> print(cube.coord('surface_altitude').points)
[[205.14995 204.45988 202.7499 ]
 [321.84033 334.86038 351.05035]]
>>> 
>>> print(result.coord('surface_altitude').points)
[[      nan       nan       nan]
 [238.15329 241.34084 244.69345]]
>>> 
```

**Comment by pp-mo** [comment]
**Implementation Notes:**
The key code in question is about here : https://github.com/SciTools/iris/blob/v2.2.0/lib/iris/analysis/_regrid.py#L541
The question is, why does that explicitly set `extrapolation_mode` to `'nan'`, rather than using `self._extrapolation_mode`, as does the 'main' regrid call which handles the cube data.

The current code seems to emerge from [this very old discussion](https://github.com/SciTools/iris/pull/1160#issuecomment-45096290)
It seems to have been a crude way to avoid masked points in (aux)-coords, but we don't actually have that restriction any more, and I'm not sure that CF does either.
In any case, **_I don't follow why it is "better" to ban extrapolation in this case, even when the main operation allows it_** (default mode='linear' --> extrapolation_mode='extrapolate').
Maybe that was a mistake.  It does seem perverse in this case.

**Comment by pp-mo** [comment]
> Although it seems this was a definite past decision, I'm now questioning whether this is correct ...

Your take @bjlittle ?

**Comment by mo-g** [comment]
CF not only explicitly allows, but requires missing values in aux-coords, and the wording has certainly changed...

[1.6](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#coordinate-types):

> Auxiliary coordinate variables (spatial and time) must contain missing values to indicate a void in data storage in the file but must not have missing data for any other reason.

[1.7](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#missing-data):

> Missing data is allowed in data variables and auxiliary coordinate variables. ... Missing data is not allowed in coordinate variables.

Which would seem to imply that masked arrays are correct behaviour, and possibly were then. Would also like to hear @bjlittle's intake, since it's been a while and I'm as likely as not to be horribly misinterpreting the documentation. :rofl:
