### ISSUE TITLE
Implement new-style, simpler file licence headers.

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3285]
In line with comments [here](https://github.com/SciTools/iris/pull/3272#issuecomment-468000534) and [here](https://github.com/SciTools/iris/pull/3272#issuecomment-468235708), we can now relax our licence header testing.

Note: the new-style version is described [here](https://github.com/SciTools/scitools.org.uk/blob/master/documents/scitools_licensing.md#source-preamble)

~But, as we have still working code for it, I think it should continue to check the years if they are there.~
~So I think the sequence is:~
  ~1. modify `tests.test_coding_standards.LicenceHeaders`, to allow new-style headers.~
  ~1. replace headers as we visit files~
  ~1. at some future point, convert the remaining untouched ones and de-clutter the test~

**CHANGED: let's fix them all at once instead**
(see comments below)
We still need a header check, but the date is no longer part of it.

NOTE: We want to do this for v2.3,
but let's wait until all the oustanding 2.3-targetted issues from other contributors are in,
just to make it easier for everyone.

---
### Acceptance Criteria

- [x] All license headers follow [the new style](https://github.com/SciTools/scitools.org.uk/blob/master/documents/scitools_licensing.md#source-preamble) (e.g. the years have been removed)
- [x] Modified TestLicenseHeaders so that it no longer checks the years in the license headers

**Comment by bjlittle** [comment]
@pp-mo I think that we should tackle this in one move,  rather than drip feed the changes incrementally. 

What do you think?

**Comment by pp-mo** [comment]
> @bjlittle I think that we should tackle this in one move, rather than drip feed the changes incrementally.
What do you think?

Ok, I agree, and @lbdreyer says yes also.
So, I've now changed the title !

We want to do this for v2.3, 
but let's wait until all the oustanding 2.3-targetted issues from other contributors are in,
just to make it easier for everyone.

**Comment by lbdreyer** [comment]
Note that this issue is only targetting the removal of the years from the license headers, not the relicensing to BSD-3. We are only able to change to BSD-3 once all Iris contributors have signed the new cla

**Comment by trexfeathers** [comment]
I'll proceed assuming the years are staying in any non-python files such as [README.md](https://github.com/SciTools/iris/blob/master/README.md)

**Comment by bjlittle** [comment]
@trexfeathers Tackle this as you see fit, since you're running with it... as one mahoosive PR or in a sequence of smaller  PRs, say based on individual `iris` modules e.g., `experimental`, `fileformats`, `tests` etc, at whatever level of granularity you consider appropriate, and then just
- [ ] tick
- [ ] them
- [ ] off

... As you do them and get them merged. Your call, but please consider the reviewer who has to check your work 😉

**Comment by bjlittle** [comment]
Okay. One PR with 474 file changes it is then... 🙄

**Comment by bjlittle** [comment]
Closed by #3489
