### ISSUE TITLE
Clarify laziness status of all iris functions

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#3292]
Make clear in all docstrings which functions are lazy and which are not.

Currently only some functions have this description (presumably those which have been updated to be lazy recently).  It would be much more useful to the user if they could immediately see from every single docstring whether the function is lazy or not.

**Comment by corinnebosley** [comment]
- #3293

**Comment by trexfeathers** [comment]
@ESadek-MO and I have agreed to submit as much documentation as can be written before `v3.4`. Seems sensible to have a PR up on Monday 14/11.

We can keep this issue open if there are more modules still to cover.

**Comment by rcomer** [comment]
Is this now complete?

**Comment by ESadek-MO** [comment]
Yep, now complete, although there might have to be minor changes in the future if and when issues arise.
