### ISSUE TITLE
Cell methods for time mean or accumulation loaded from pp files always 1 hour

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#3303]
whatever the True averaging period of a diagnostic is Iris always sets it to: mean: time (1 hour) 

This is because of a misinterpretation of UMDP F03. The code in pp_load_rules.py has the following:

 intervals = '{} hour'.format(f.lbtim.ia)

UMDP F3 states:

13 LBTIM Time indicator.

_IA;for time aggregated fields IA is the time interval in hours between the individual fields from which the mean was computed. This has a minimum value of 1 when time aggregation is switched on, so sampling frequencies of less than one hour appear to be one hour._ 

This explains why the value is 1 hour for most means. The sampling interval is typically the model timestep which is between 20 minutes and 1 minute in real world models now. 

 UMDP F3 states that words 1-6 of the pp header are "For Accumulations/Means: start of A/M period."  and words 7-12 "For Accumulations/Means: end of A/M period." Therefore the correct way to calculate the period of an accumulation or mean is from the time headers lbyrd lbmond lbdatd minus lby lbmon lbdat  etc.

There is a potential issue though for operational pp format files "In the Operational PP format generated by Fieldcos, words 1-6 became the validity time and Words 7-12 became the data time for Accumulations and Means in the converted file. " This destroys the information on the meaning period. This also has potential implications as it could lead to negative times being calculated for the meaning period. For these fields we will need to set the averaging period to unknown.

**Comment by mo-g** [comment]
Is there an easy (and foolproof) way to identify Fieldcos files?

Also and possibly relatedly, is there a canonical public source for the UM documentation? I seem to be able to pirate copies from all sorts of places, but I can't find a Met Office hosted site for them (at least via my 5 minute google search, anyway).

It's been ¿three? years (@DPeterK help me out, I don't even know any more) since I last saw a copy!

**Comment by rcomer** [comment]
For climate timescales, typical averaging periods (indicated by the difference between words 7-12 and words 1-6) are days, months, seasons and years.  The sampling frequency (given by lbtim's "IA") may be every timestep, 6-houly (good for comparing to reanalyses), 24-hourly (good for studying the diurnal cycle) or something else.

So, if I load a file containing monthly means, I could have cubes that are identical apart from the cell_methods.  I therefore do a lot of constraining on cell_methods, which would break if they were all set to 1 month.

Do we have a CF-conventions expert who can confirm whether the `intervals` attribute is supposed to indicate the averaging period or the sampling frequency?

**Comment by pp-mo** [comment]
> whether the `intervals` attribute is supposed to indicate the averaging period or the sampling frequency?

It's definitely sampling frequency.  See [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#recording-spacing-original-data)
The averaging _period_ should be indicated by a bounds variable
 \- or possibly a [climatology variable](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#climatological-statistics) ( which have a very similar structure, but Iris doesn't support them properly yet ).

**Comment by nhsavage** [comment]
"The averaging period should be indicated by a bounds variable". That means there is a different issue with Iris. This is not a theoretical example, it is what brought me here. I have in a single file, data for one variable - say Air Temperature. There is hourly average data and daily average data. When these are loaded from the file, they merge into a single cube. How do we prevent this?

**Comment by pp-mo** [comment]
> When these are loaded from the file, they merge into a single cube. 

Interesting ...

It will really help if you can provide a reproducible example.
If it can't be done here, then I think it needs to be dealt with offline, as internal support.
Can we follow that up please ?

**Comment by nhsavage** [comment]
I sent a message to AVD support about this in February, which I followed up last week. That includes a reproducible example. I will forward it to you

**Comment by pp-mo** [comment]
Ah! seen that now ...

**Comment by nhsavage** [comment]
Closing this issue as it is clear that I have got the wrong end of the stick.
