### ISSUE TITLE
CF1.7 Support

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#3304]
Iris needs to support CF conventions version 1.7. At the moment Iris' CF conventions support is limited to v1.5. 

Rationale:

* CF1.7 support is required for Iris to be able to accurately load and handle metadata of CMIP6 datasets
* it is required by the ESMValTool project so that ESMValTool can offer model evaluation functionality for CMIP6
* it allows Iris to maintain its USP of understanding a dataset's metadata rather than just being able to represent it.

Note that one blocker to implementation here is that it is now harder to get a complete changelist between CF version releases, so it is hard to know what would be necessary to implement complete CF1.7 compliance!

Ping @zklaus, who raised this with me the other day – any chance you can interface with the CF community and see if you can get that changelist out of them?

**Comment by zklaus** [comment]
Hi @DPeterK , great to see this moving forward!
I'll do my best to get a changelog going with CF, but in the mean time there is already a [Revision History](http://cfconventions.org/cf-conventions/cf-conventions.html#revhistory) that can get us perhaps some of the way. Unfortunately, it refers to dates and not versions, but some points of reference might be

Date|Note
----|----
10 December 2008 | 2. Changed Document version to 1.4
25 October 2010 | 8. Changed document version to 1.5, 9. Changed document version to 1.6
18 July 2017 | 2. Where appropriate, changed document version from 1.6 to 1.7, and 1.7 (DRAFT) to 1.7.

**Comment by mo-g** [comment]
It's not going to be complete all the way back to 1.5, but there _is_ a github revision log for the 1.7 final branch: https://github.com/cf-convention/cf-conventions/commits/v1.7final

It's something.

**Comment by zklaus** [comment]
I had some discussions and as a result don't have a changelog, but some thoughts.

It seems less clear to me now, that the issues are really a matter of versions. For example, climatological time axis have already been in 1.5. On the other hand, some minor additions of later editions are probably handled without problems, like some new cell_methods, or new projections.

The problem we are facing is that it is not a very technical specification, but rather conversational. Having something like a formal grammar would make things much easier, of course.

Aside from all of this it might be necessary to better define what is meant by support. I can think of three parts: reading conformant files, representing features in memory, writing conformant files.

Not very helpful, I am afraid, but I'll keep digging.

**Comment by rcomer** [comment]
Is this done?  [Version 2.3 whatsnew](https://scitools-iris.readthedocs.io/en/stable/whatsnew/2.3.html) says we now support CF1.7.

**Comment by zklaus** [comment]
I think it's ok to close this. Given the amorphous nature of past CF versions, I guess the approach is to read everything best we can and to always write the latest version. With improved and improving CF procedures, perhaps we'll be able to do better in the future.
