### ISSUE TITLE
incorrect metadata for m01s09i215

### ISSUE THREAD

**Issue by ColemanTom** [SciTools/iris#3305]
Hi,

We have noticed that there is an error in the metadata for m01s09i215 : https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/um_cf_map.py#L613

According to the UM source code, it is cloud area fraction greater than 7.9 oktas, not 7.5 oktas.

**Comment by bjlittle** [comment]
@marqh @pp-mo Can either of you confirm that this is the case?

**Comment by ColemanTom** [comment]
If you look in the UM source code you can see the list of thresholds defined:

`atmosphere/large_scale_cloud/diagnostics_lscld.F90:DATA oktas/0.1,1.5,2.5,3.5,4.5,5.5,6.5,7.9/`

**Comment by bjlittle** [comment]
@marqh or @pp-mo can you re-spin metarelate to include this change please?

**Comment by ColemanTom** [comment]
This is still incorrect, new line number https://github.com/SciTools/iris/blob/main/lib/iris/fileformats/um_cf_map.py#L692

**Comment by trexfeathers** [comment]
>do we just update [um_cf_map.py](https://github.com/SciTools/iris/blob/main/lib/iris/fileformats/um_cf_map.py) directly?  Or will there be some other process?

@rcomer I don't know the answer I'm afraid, but would find it useful for this to be mentioned somewhere in the Contributing documentation?

**Comment by pp-mo** [comment]
> do we just update um_cf_map.py directly?

Yes, I believe that is the intent from now on.
