### ISSUE TITLE
Clarify plans for future Python 2 support past the EoL, and include on Python3Statement as appropriate

### ISSUE THREAD

**Issue by CAM-Gerlach** [SciTools/iris#3306]
As Cartopy, and many other dependencies (Numpy, Matplotlib, etc) will stop supporting Python 2 on or before the January 1, 2020 deadline, as an important package used in the atmospheric science community, I suggest publicly making clear your plans on whether and when you will drop Python 2 support. If you do plan to do it on or before January 2020, I suggest [adding](https://github.com/python3statement/python3statement.github.io) the project to the [Python3Statement](https://python3statement.org/), like most of the PyData stack and [MetPy](https://github.com/python3statement/python3statement.github.io/pull/123) have done, to make it easy and clear for users and downstream projects to find in one central place and help accelerate Python 3 adoption across the userbase.

Let me know if you'd like any help or have any questions. Thanks!

**Comment by CAM-Gerlach** [comment]
@pp-mo If you'd like, I can open a draft PR over on [python3statement/python3statement.github.io](https://github.com/python3statement/python3statement.github.io/) that can be merged if you decide to sign, so you don't actually have to do anything, aside from give us the final approval or not. Lmk, thanks.

**Comment by bjlittle** [comment]
@CAM-Gerlach Thanks for the nudge... see https://github.com/python3statement/python3statement.github.io/pull/230

**Comment by bjlittle** [comment]
@CAM-Gerlach Thanks for the nudge... see https://github.com/python3statement/python3statement.github.io/pull/230

**Comment by bjlittle** [comment]
Closed by https://github.com/python3statement/python3statement.github.io/pull/230

See https://python3statement.org/
