### ISSUE TITLE
Provide a user-updown feature voting page on the repo

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3307]
Want something that allows per-user voting on issues, to provide shared priority management

**Comment by bjlittle** [comment]
@pp-mo Can we now close this issue?

**Comment by rcomer** [comment]
Is there a plan to advertise this to the user community?  Reading and voting on issues could be an easy first step for those who are not yet involved in the development side of things.

I have just been through and voted for my favourites 😁.

**Comment by bjlittle** [comment]
@pp-mo We should also add a link in the docs and the `README.md` that allows users to easily get to the actual [Iris Issue Voting](https://vote.biglybt.com/SciTools/iris/Votable%20Feature) page.

**Comment by larsbarring** [comment]
Probably votable issues should disappear from the voting page when they are either closed or the `Votable Feature` label is removed?

**Comment by pp-mo** [comment]
> @bjlittle Can we now close this issue?

Just reviewing this : let's leave this in place till we address some of the excellent points raised above ...

**Comment by tkknight** [comment]
A nice approach here https://executablebooks.org/en/latest/feature-vote.html.  this uses github for voting but has the ability to view the results on sphinx docs, which I assume uses the git API to update the table daily.

**Comment by tkknight** [comment]
#4617 is now merged.  We have the ability to vote using 👍 on issue headers.  We do not have the ability to down vote though but I think this is acceptable.
