### ISSUE TITLE
Iris causes AttributeError when attempting to catch an OSError when loading a dataset

### ISSUE THREAD

**Issue by evertrol** [SciTools/iris#3312]
When attempting to open a NetCDF dataset in Iris, I wrap it in a `try: ... except OSError` block, to catch bad files or URLs. This can, however, cause an `AttributeError` instead.

An example (the corrupted file is truncated, while the HadCRUT dataset is not served by an OpenDAP server):

```
import iris
url = 'corrupted.nc'
url = 'https://crudata.uea.ac.uk/cru/data/temperature/HadCRUT.4.6.0.0.median.nc'
try:
    cube = iris.load(url)
except OSError:
    print('>>><<<')
print('continuing')
```

Note that while the `AttributeError` is raised, it is also ignored, and the script will continue.
The traceback and output for the corrupted file is:
```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 4563412416:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1700 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #003: H5Fsuper.c line 623 in H5F__super_read(): truncated file: eof = 21365110, sblock->base_addr = 0, stored_eof = 21365116
    major: File accessibilty
    minor: File has been truncated
>>><<<
Exception ignored in: <function CFReader.__del__ at 0x1147f51e0>
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/testiris/lib/python3.7/site-packages/iris/fileformats/cf.py", line 1124, in __del__
    self._dataset.close()
AttributeError: 'CFReader' object has no attribute '_dataset'
continuing
```
For the HadCRUT dataset, it is a bit longer: essentially a HTML page that netCDF4 can't parse (presumably, it tries to access OpenDAP API entry points).

----

The likely cause of this is Python's garbage collection attempting to clean up intermediate variables. In this case, it runs [the `__del__` method of `CFReader`](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/cf.py#L1122), which will unconditionally perform `self._dataset.close()` (it is probably also the garbage collector that safely ignores the raised exception inside the `__del__` method).
In this case, however, the `OSError` was raised in the netCDF4 module, when attempting to [load and create the netCDF4 Dataset](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/cf.py#L937):
```
self._dataset = netCDF4.Dataset(self._filename, mode='r')
```
and `self._dataset` was never initialized, or even declared, hence the `AttributeError`.

I think the simplest solution would be to complete remove the `__del__(self)` method from `CFReader`: if the `CFReader` instance is garbage collected (or explicitly deleted), its attributes, such as `_dataset`, will be deleted as well, and the filehandle closed.

This assumes `netCDF4.Dataset` is well behaved, and closes its file pointers when deleted (if it's using a Python file handler under the hood, it should do automatically); a quick test suggests it is indeed:
```
import netCDF4
ds = netCDF4.Dataset('HadCrut.4.6.0.0.median.nc')
del ds
import psutil
proc = psutil.Process()
print(proc)
print(proc.open_files())
```
yields:
```
psutil.Process(pid=23636, name='python3.7', started='14:32:40')
[]
```

Note that this is a CPython implementation detail. It is not a language feature, so there may be Python implementations that use Iris and netCDF4, but that do not close their file handles upon garbage collection (these would be far and few though, given the dependencies on numerous C libraries for these packages, which makes CPython almost a requirement).

**Comment by bjlittle** [comment]
@evertrol Thanks for taking the time to report this issue and investigate it further - much appreciated! :smile: 

I can easily recreate the issue with your example, so thanks again for providing this to clarify - invaluable. 

I'm keen to bank a fix for this, and this is what I'd recommend (after a quick test):

Ensure that the `cf.CFReader._dataset` has a **default** state before attempting to read the dataset, then attempt to read the NetCDF dataset i.e.

```python
    ....
    self._dataset = None
    self._dataset = netCDF4.Dataset(self._filename, mode='r')
    ....
```

The trick is then to ensure that the `cf.CFReader.__del__` method only attempts to close the dataset if it was successfully opened i.e.

```python
    if self._dataset is not None:
        self._dataset.close()
```
Do you fancy raising a pull-request with the fix, and perhaps add some simple tests for good measure? I'm happy to guide you through the process, if that helps?

**Comment by evertrol** [comment]
Happy to put in a PR.
Is there a particular reason you don't want to trust the automatic closing of the filehandle during garbage collection, but be more explicit?

**Comment by bjlittle** [comment]
At the time of writing (a wee while back now) we were keen to call [netCDF4.Dataset.close()](https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L2443) explicitly as it also handles error checking internally for cases when it can't close the file or view for whatever reason.

The thinking was that this might be handy for the user to know (in those very rare failure cases), rather than relying on the garbage collector and `netCDF4.Dataset` instance being well behaved.

Perhaps a tad over-cautious, but it seems like a harmless philosophy to adopt.

Can you buy into that? Happy to be convinced otherwise :wink:

**Comment by evertrol** [comment]
I'm curious now: would `netCDF4.Dataset.close()` raise an exception if it fails for some reason (it does appear so, stepping mentally through the code and looking at `_ensure_nc_success`)? Because that exception would be ignored during garbage cleanup, since it happens in the `__del__` attribute; just printed to stderr.

Of course, just like now, the user would still see the exception text, but the exception itself would be ignored. I'm not sure if that helps or confuses a user (note: this is so far just my mental exercise: I actually haven't tried to create such a problem and see what happens).

Apologies for being picky; I just like to avoid overriding or using `__del__`. Depending on how the `CFReader` class is viewed, perhaps an explicit close method would be more suitable, together with an `__enter__`/`__exit__` combo (that last part could possibly be implemented anyway?)
