### ISSUE TITLE
Support climatological statistics

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3323]
Provide end-to-end support for [climatological statistics](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#climatological-statistics) within `iris`.

Reference:
- https://github.com/SciTools/iris/issues/2904
- https://github.com/SciTools/iris/pull/2905

**Comment by bjlittle** [comment]
Ping @zklaus :smile:

**Comment by abooton** [comment]
Related to https://github.com/SciTools/iris/issues/1438

**Comment by trexfeathers** [comment]
Minimum implementation will be to allow Iris to load and save climatological statistics in NetCDF, even if there is not yet any specific functionality while the data is in a cube. Can achieve this by:
- adding a new parameter to the coordinate class specifying if the bounds are climatological or not
- adding more code to specify the type during the creation of bounds
- get_cf_bounds_var needs to return the bound type
- build_dimension_coordinate needs to supply the bound type when using the coordinate class

Will also need a 'round trip' test. Have a look at the AssertCDL test

**Comment by pp-mo** [comment]
> Some sample metadata to look at

E.G. [this "gridfile...Daily_Climatology_1982_2008_DayNightCombined-v02.0-fv01.0.cdl"](https://data.nodc.noaa.gov/testdata/netCDFTemplateExamples/grid/00000110200000-NODC-L4_GHRSST-SSTskin-AVHRR_Pathfinder-PFV5.0_Daily_Climatology_1982_2008_DayNightCombined-v02.0-fv01.0.cdl)
Yes?

**Comment by bjlittle** [comment]
Closed by https://github.com/SciTools/iris/pull/3395
