### ISSUE TITLE
Add some contact information to the iris home page?

### ISSUE THREAD

**Issue by jypeter** [SciTools/iris#3326]
Unless I missed something obvious, there is **no contact information** on the [iris home page](https://scitools.org.uk/iris/docs/latest/) (and the many other iris pages I visited)

I eventually followed a link to the iris github page after browsing the iris developper's guide, in the [Making your own copy (fork) of iris](https://scitools.org.uk/iris/docs/latest/developers_guide/gitwash/forking_hell.html) ! I could have gone to github directly, but you may want to make this easy for users

Once on the github page, you have a nice **Get in touch** section. I think you should have this Get in touch information on the main iris page, or have something similar to the [Getting involved](https://scitools.org.uk/cartopy/docs/latest/#getting-involved) section on the main cartopy page

**Comment by bjlittle** [comment]
Hey @jypeter, good to hear from you again :smile: 

Yup, I agree. This is something that should be easier for users - so let's commit to adding a similar *Getting Involved* section for `iris` that's similar to `cartopy`

Thanks for taking the time to feedback :+1:

**Comment by jypeter** [comment]
Hi @bjlittle ! Long time no see

The scitools doc already looks good, but you have to make it as easy as possible for end users, if they take the time to RTFM. I tell our many interns (and older scientists) to read the technical doc, but they want to spend all their time on science...

I'm trying to improve my low matplotlib skills while updating my related documentation, and I have been volunteered to check cartopy (as a replacement for basemap and an alternative to vcs), especially wrt orca grid, so you may read more github issues/questions.

**Comment by rcomer** [comment]
Iris _Getting Involved_ section could also include encouragement to vote on issues (#3307).

**Comment by tkknight** [comment]
There is now a [Getting Involved](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_getting_involved.html) section in the **Developers Guide** of the docs, see https://scitools-iris.readthedocs.io/en/latest/index.html#.  

The content is not on the main page but is linked to.  We could close this issue off as is or perhaps add a final paragraph/sentence on the main page linking to the Getting Involved? thoughts?

**Comment by rcomer** [comment]
The GitHub [get in touch](https://github.com/SciTools/iris/tree/v2.2.x#get-in-touch) section that @jypeter referred to is now reproduced in the Support section in the docs sidebar.  So yes, I think this issue has been addressed 🙂.
