### ISSUE TITLE
Partly broken ORCA example page?

### ISSUE THREAD

**Issue by jypeter** [SciTools/iris#3327]
I'm reviewing the **orca** support in iris/cartopy and I have looked at the [Tri-Polar Grid Projected Plotting](https://scitools.org.uk/iris/docs/latest/examples/General/orca_projection.html) page

I'm not sure the nearest neighbor solution used with `iris.analysis.cartography.project(cube, pcarree, nx=400, ny=200)` is the best way to go, but at least it provides a documented workaround

The problem here is that nothing is plotted for _Orthographic_

**Comment by bjlittle** [comment]
@pp-mo or @lbdreyer Would either of you care to comment?

**Comment by pp-mo** [comment]
I see it *did* work at Iris 2.1 : https://scitools.org.uk/iris/docs/v2.1/examples/General/orca_projection.html#orca-projection-02
I don't see any obviously relevant changes anywhere in lib/iris/analysis, so I suspect a change in cartopy.
I guess we need to investigate this ...

**Comment by tkknight** [comment]
The new Read The Docs style documentation has now been merged to master (not released), see #3752

You can see the gallery via: https://scitools-iris.readthedocs.io/en/latest/generated/gallery/index.html, and the specific example discussed here [Tri-Polar Grid Projected Plotting](https://scitools-iris.readthedocs.io/en/latest/generated/gallery/oceanography/plot_orca_projection.html#sphx-glr-generated-gallery-oceanography-plot-orca-projection-py) 

Is this issue still present?  If not can this issue be closed?

**Comment by bjlittle** [comment]
@tkknight LGTM :+1:
