### ISSUE TITLE
Clarify the computation of iris.analysis.cartography.area_weights

### ISSUE THREAD

**Issue by jypeter** [SciTools/iris#3328]
I have just had a look at the weight definition in the [iris.analysis.cartography.area_weights(cube, normalize=False)](https://scitools.org.uk/iris/docs/latest/iris/iris/analysis/cartography.html#iris.analysis.cartography.area_weights) documentation and I have some questions about it:

- do you use the **cell bounds** if they are available (I don't know if you forward the bounds information in a _cube_).
- what happens if there are no defined cell bounds in the original data? Do you throw an error? Or just use the distance between the cell centers? Or compute bounds on the fly?
- are there some cases where you can't compute the weights and you will just throw an exception? 

The formula you provide is a bit ambiguous with (lon1, lon0, lat1, lat0) and I don't have time to look at the code

I assume the actual code is correct, but if you use `r2` in the formula, you should probably also multiply with 4*pi/360/2

I'm comparing this with the [getWeights documentation in cdms2](https://cdms.readthedocs.io/en/latest/manual/cdms_2.html?highlight=getweights#rectgrid-methods-additional-to-horizontalgrid-methods)

Cell weight computation is an added value in this kind of package, so it needs an accurate documentation

**Comment by bjlittle** [comment]
@jypeter Have you taken a peek at the documentation for the [area_weights](https://scitools.org.uk/iris/docs/latest/iris/iris/analysis/cartography.html?highlight=area_weights#iris.analysis.cartography.area_weights) function?

To answer your questions:

1. In order to calculate the area weights the cube **must** have 1D latitude and longitude coordinates that are have bounds - otherwise an exception is raised.
1. As above. No bounds, then nothing fancy is done here, rather an exception is raised
1. Yes. Apart from requiring bounds, the latitude and longitude coordinates must be 1D, and their units must be in degrees or radians.

To answer your other questions, it may be helpful just to take a snoop at the actual [area_weights code](https://github.com/SciTools/iris/blob/v2.2.1/lib/iris/analysis/cartography.py#L351-L456).

Does this help?

**Comment by rcomer** [comment]
I had a peek at the code.  I think the ambiguity in the equation may come from the fact that Iris tries to be unit-agnostic where possible.  In this case, there is a check to make sure the latitude and longitude coordinates are in degrees _or radians_.  The coordinates are copied and converted to radians before the calculation (this is necessary for passing to `numpy.sin`).

So the given equation is correct if you assume your input coordinates are in radians, which admittedly will not be the case for the vast majority of datasets.

**Comment by jypeter** [comment]
@bjlittle I had looked at the area_weights documentation, but completely missed the **bounds** part of _The cube must have coordinates ‘latitude’ and ‘longitude’ with bounds_, but you may want to emphasize the requirements for bounds with something like _Returns an array of area weights, with the same dimensions as the cube, **or an error if the dimensions' bounds are not available**_ and the equation (if you keep it) could use something like `abs(lon_bounds[i+1] - lon_bounds[i])`

I also read the documentation too quickly, **assuming that the weights would be normalized**, but that you could also request the cells areas. _Area weights_ is thus a bit misleading and _weights are grid cell areas_ seem strange

It could be clearer if you replaced _Area weights are calculated for each lat/lon cell as:_ with _Areas are calculated for each cell as:_, but the equation will still look a bit strange if you don't know that the coordinates are converted to radians under the hood

There is also some **ambiguity for the normalization**. I assume that the sum of the weights will be `1.0` for the globe, and not just for the area covered by the supplied lon and lat axes' bounds. If that's indeed the case, you could change the _normalize_ kw doc to _If True, weights are grid cell areas divided by the total **globe** area_

I'm not familiar with the **cube**, and I will spend more time with cartopy than with iris, but is it obvious that lon and lat should be 1d vectors, or should this be mentioned?

And a bonus iris question (because I don't have time to search the doc): if the bounds are not defined, do you have a facility like the very usefule [cdms2 setAutoBounds](https://cdms.readthedocs.io/en/latest/manual/cdms_2.html?highlight=setautobounds#id3) ?

Wow, this is longer than the docstring itself

**Comment by jypeter** [comment]
Just adding a comment here! Maybe somebody will have time to clarify this in the next 500 days before this becomes stale again :)

**Comment by jypeter** [comment]
The link to `iris.analysis.cartography.area_weights` in my original question is dead, so I'm just putting here a new [link to search area_weights in the documentation](https://scitools-iris.readthedocs.io/en/stable/search.html?q=area_weights)

**Comment by trexfeathers** [comment]
Hi @jypeter, sorry there is such a delay on this, I'm sure it's no surprise that we have to make many harsh prioritisation calls.

- If you do find you have the time: we'd be happy to review proposed improvements to documentation
- If you don't have the time: you and your colleagues can [vote](https://github.com/SciTools/iris/issues/4631) to increase the priority
