### ISSUE TITLE
Support iris.plot.hist and iris.quickplot.hist

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3330]
There have been user requests for the `iris` convenience plotting capabilities to be extended such that a `cube` can be passed to `iris.plot.hist` and/or `iris.quickplot.hist` to generate histogram plots by using `matplotlib.pyplot.hist`

@BenMGeo do you have some example use cases to support his issue?

**Comment by pelson** [comment]
Hi from the other side! I found myself needing something like this recently... here is my use case:

I have all of the observed temperatures for a given site, I take only those of a given month and hour, and want to see the distribution of temperatures for that hour in that month. I then plan to fit that distribution to a statistical model and use it to calculate the climatological probability of a given temperature at a given time in a given month (pretty useful!).

**Comment by pelson** [comment]
For my own record, I hacked something together:

```
n_bins = 20
counts, bins = np.histogram(temp.data, np.linspace(temp.data.min(), temp.data.max(), n_bins + 1))
bounds = np.vstack([bins[:-1], bins[1:]]).T

frequency_cube = iris.cube.Cube(
    data=counts, long_name='temperature_frequency', dim_coords_and_dims=(
        (iris.coords.DimCoord(points=bounds.mean(axis=1), bounds=bounds, long_name='temperature'), 0),
    ),
)
```

And then I did a bar plot of the cube with:

```
# Plot the data as a histogram.
bar_widths = np.diff(data.coord('temperature').bounds, axis=1)[:, 0]
plt.bar(data.coord('temperature').points, data.data, width=bar_widths)
```

Truth be told, this is probably a good use case for something like pandas. The only way I could convince myself that it would be a good thing for Iris to have is if we needed multi-dimensional equivalents. For example, imagine having *all* sites, and *all* months, and *all* hours as 3 distinct dimensions, and wanted to do the same analysis and resulting in a multidimensional cube.

**Comment by trexfeathers** [comment]
>Truth be told, this is probably a good use case for something like pandas. The only way I could convince myself that it would be a good thing for Iris to have is if we needed multi-dimensional equivalents. For example, imagine having all sites, and all months, and all hours as 3 distinct dimensions, and wanted to do the same analysis and resulting in a multidimensional cube.

@pelson we've recently enhanced [`iris.pandas.as_data_frame()`](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/pandas.html#iris.pandas.as_data_frame), so that it can handle the n-dimensional case. Would that suit future use cases for you?
