### ISSUE TITLE
Make iris.analysis.PROPORTION lazy

### ISSUE THREAD

**Issue by kaedonkers** [SciTools/iris#3348]
@DPeterK did some excellent work on making several aggregators lazy (see https://github.com/SciTools/iris/pull/3168).

However it seem that `iris.analysis.PROPORTION` is not lazy yet (despite it relying on COUNT?)

I would submit a PR for this but I don't have time. I'm very happy to be beaten to it ;)

**Comment by bjlittle** [comment]
@kaedonkers Thanks for raising this.

I agree, it would be great to get coverage of all the aggregators :wink:
