### ISSUE TITLE
matplotlib 3 support

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#3400]
I noticed there is a temporary restriction for matplotlib versions (#3175). Are there any plans to remove this and make iris compatible with the latest version of matplotlib?

**Comment by bjlittle** [comment]
@dennissergeev Good question, thanks for asking 😁

We're in the process of aiming to release `iris` 2.3.0 by the end of September 2019, which will be the **last** release to support **Python2** :tada: 

After that, we're scheduled to make a major release of `iris` 3.0.0 in October 2019, which will be **Python3** only. For that release, we will also unpin our `matplotlib` 2.x dependency and move to `matplotlib` 3.x.

Hope this helps clarify. Also see our [milestones](https://github.com/SciTools/iris/milestones).

**Comment by bjlittle** [comment]
Reference https://github.com/conda-forge/iris-feedstock/issues/47
