### ISSUE TITLE
Weird num2date failure

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3402]
Reported by @rcomer https://github.com/SciTools/iris/issues/3239#issuecomment-475674052 ...

```
import iris

time_coord = iris.coords.DimCoord(range(5), units='days since 2001-05-01',
                                  standard_name='time')

# Add as aux coord
cube = iris.cube.Cube(range(5))
cube.add_aux_coord(time_coord, 0)

# Save and then load, attempt to print time coord.
print(cube.coord('time'))
iris.save(cube, 'test_cube.nc')
temp_cube = iris.load_cube('test_cube.nc')
print(temp_cube.coord('time'))
```

Problem looks like this ...
```
>>> print(temp_cube.coord('time'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/coords.py", line 786, in __str__
    points = self._str_dates(self.points)
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/coords.py", line 769, in _str_dates
    date_obj_array = self.units.num2date(dates_as_numbers)
  File "/opt/scitools/environments/default/2019_02_27/lib/python3.6/site-packages/cf_units/__init__.py", line 1989, in num2date
    return _num2date_to_nearest_second(time_value, cdf_utime)
  File "/opt/scitools/environments/default/2019_02_27/lib/python3.6/site-packages/cf_units/__init__.py", line 602, in _num2date_to_nearest_second
    dates = utime.num2date(time_values)
  File "cftime/_cftime.pyx", line 1211, in cftime._cftime.utime.num2date
  File "/opt/scitools/environments/default/2019_02_27/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/opt/scitools/environments/default/2019_02_27/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (5,)
>>> 
```

However it's proving hard to reproduce
(more to come...)

**Comment by rcomer** [comment]
Hi @pp-mo, thanks for pulling this out as its own issue.  You are right that it's not about the zero date problem that was causing Travis failures.  However, it **was** fixed by pinning `cftime` to the older version, so that's why the issues were linked in my head.

**Comment by rcomer** [comment]
Is it something to do with the mask?  

```
In [3]: temp_cube.coord('time').points
Out[3]: 
masked_array(data=[0, 1, 2, 3, 4],
             mask=False,
       fill_value=999999)
```
As far as I can tell, it is not possible to create a coord from scratch using a masked array.  The mask just disappears:

```
In [47]: time_coord = iris.coords.AuxCoord(ma.array(range(5), mask=[False, True, False, True, False]),
                                           units='days since 2001-05-01', standard_name='time')

In [48]: time_coord.points
Out[48]: array([0, 1, 2, 3, 4])
```

```
In [75]: time_coord = iris.coords.AuxCoord(ma.array(range(5), mask=ma.nomask),
                                           units='days since 2001-05-01', standard_name='time')
In [76]: time_coord.points
Out[76]: array([0, 1, 2, 3, 4])
```

**Comment by rcomer** [comment]
> not possible to create a coord from scratch using a masked array

Unless you go via `dask`...  which happens with auxillary coordinates loaded from NetCDF 💡 

```
In [7]: time_coord = iris.coords.AuxCoord(da.ma.masked_array(da.arange(5, chunks=5)),
   ...:                                   units='days since 2001-05-01', standard_name='time')
In [8]: time_coord.has_lazy_points()
Out[8]: True

In [9]: time_coord.points
Out[9]:
masked_array(data=[0, 1, 2, 3, 4],
             mask=False,
       fill_value=999999)
```

**Comment by rcomer** [comment]
I think [this may be the line](https://github.com/SciTools/iris/blob/ec46449b9705789268b77089a2161ff2c1d605c5/lib/iris/coords.py#L616) that stops coord points being a numpy masked array.  Maybe this method needs additional handling for the lazy array case?

**Comment by rcomer** [comment]
Now I am wondering whether disallowing masked arrays was a deliberate design choice.  Couldn't just removing the mask leave you with nonsense in the previously masked points?  So if we really don't want masked arrays, it might be better if they triggered an exception?

**Comment by rcomer** [comment]
The [cf conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#missing-data) say that "Missing data is allowed in data variables and auxiliary coordinate variables."

**Comment by rcomer** [comment]
Narrowing it down...

Given
```python
mytime = cftime.utime('days since 2001-05-01')

arr1 = ma.array(range(5), mask=ma.nomask)
arr2 = ma.array(range(5), mask=[0,0,0,1,0]) 
```

`mytime.num2date(arr1)` gives the now-familiar exception, wheras `mytime.num2date(arr2)` gives:

```
array([datetime.datetime(2001, 5, 1, 0, 0),
       datetime.datetime(2001, 5, 2, 0, 0),
       datetime.datetime(2001, 5, 3, 0, 0), None,
       datetime.datetime(2001, 5, 5, 0, 0)], dtype=object)
```

**Comment by rcomer** [comment]
👀 
https://github.com/Unidata/cftime/issues/60
https://github.com/Unidata/cftime/pull/55

**Comment by rcomer** [comment]
Hi @pp-mo, having had a long conversation with myself(!), I'm satisfied that there's nothing within Iris that we need to for this.  So I'll close this.  Obviously you are welcome to re-open if you disagree.

I've transferred my comments about masked coord points to #3419.
