### ISSUE TITLE
expose `error_on_mismatch` in concatenate?

### ISSUE THREAD

**Issue by mathause** [SciTools/iris#3403]
The function `iris._concatenate.concatenate` has the `error_on_mismatch` keyword. However, that does not seem to be exposed to `iris.cube.CubeList.concatenate`. Is there a good reason for this? It took me a lot of digging why my cubes would not concatenate.

``` python
iris.__version__
>>> 2.2.1dev0'
```

**Comment by wjbenfold** [comment]
For future reference, `iris.cube.CubeList.concatenate_cube` will invoke `error_on_mismatch` behaviour
