### ISSUE TITLE
The iris.coords.Coord class should be abstract

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3410]
The `iris.coords.Coord` class should be private i.e., `iris.coords._Coord`, as it is not intended to be used to create instances, but rather it's purpose is to act as the base class in the class hierarchy of `DimCoord` and `AuxCoord`.

---
### Acceptance Criteria
- [x] A user is no longer able to instantiate a Coord

**Comment by pp-mo** [comment]
> as it is not intended to be used to create instances

IMHO that means it should be abstract, not private.
It doesn't sound wise to me to make a parent of a public class *private* :  it makes it hard to work out what public API you can rely on, if some of it comes from a private.

For instance, it should remain possible to say `isinstance(thing, Coord)`, for which Coord needs to remain a public thing.  This is at least one thing that it is good for.

**Comment by bjlittle** [comment]
ABC works also for me :+1:

**Comment by bjlittle** [comment]
Closed by #3514
