### ISSUE TITLE
Allow pathlib.Path objects as file names

### ISSUE THREAD

**Issue by SimonPeatman** [SciTools/iris#3411]
The `load`, `load_cube`, `load_cubes`, `load_raw` and `save` functions all require the user to provide file names as a `str`.  However, in Python 3, the standard way of handling file paths is with `pathlib.Path` objects, or the subclasses `PosixPath` and `WindowsPath` (rather than with `os.path` which represented a path as a `str`).

For convenience, I suggest Iris should be able to accept either a `str` or a `Path`/`PosixPath`/`WindowsPath` object as a file name.

**Comment by bjlittle** [comment]
Hey @SimonPeatman, great to hear from you, and thanks for taking the time to raise this issue - much appreciated!

Agreed :+1: 

At the moment we're working on `iris` minor version `2.3.0`, the last version to support Python2. Then we'll be aiming to cut `iris` major version `3.0.0`, which will be Python3 only :tada: 

At that point, it'll make sense to address this particular issue. So I've added this issue to our `3.0.0` [milestone](https://github.com/SciTools/iris/milestone/37) and [project board](https://github.com/SciTools/iris/projects/23) to ensure that it's included :wink:
