### ISSUE TITLE
Address deprecations

### ISSUE THREAD

**Issue by abooton** [SciTools/iris#3443]
* Deprecations to be identified and listed
* Then deprecated as appropriate.

**Comment by bjlittle** [comment]
@abooton thanks for raising this issue to collate deprecations... but what does `[M]` mean?

**Comment by lbdreyer** [comment]
List of deprecations that need removing:
- [ ] iris.Future.cell_datetime_objects (deprecated Iris 2.0.0)
- [ ] iris.Future.netcdf_promote (deprecated Iris 2.0.0)
- [ ] iris.Future.netcdf_no_unlimited (deprecated Iris 2.0.0)
- [ ] iris.Future.clip_latitudes (deprecated Iris 2.0.0)
- [ ] iris.fileformats.pp._LBProc.flags attribute (deprecated 1.7.2? #1415)

**Comment by stephenworsley** [comment]
Removing all these flags will mean the Future class has no flags. This will break some of the tests in test_Future.py until another flag is added. The sollution I'm currently working on is to keep these in but to skip these tests so that we retain the structure of the tests.

**Comment by lbdreyer** [comment]
All deprecations have been addressed in #3459 and #3464 and #3461 
so this can now be closed
