### ISSUE TITLE
Required version of python should be explicitly stated in the docs

### ISSUE THREAD

**Issue by wood-chris** [SciTools/iris#3472]
I've tried installing iris with various different versions of python with Anaconda:

## python 2

creating a conda env specifying `python=2` using both conda2 and conda3 installs iris, but see same issue as #3472 

## python 3.3

```
conda create --name iris2 python=3.3
<installing stuff>
$ source activate iris2
(iris2) $ python
Python 3.3.5 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:22:11) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(iris2) $ conda install -c conda-forge iris
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - iris -> netcdf4 >=1.4
  - iris -> numpy >=1.14|>=1.14,!=1.15.2
  - iris -> python 2.7*|3.4*|3.5*|3.6*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0
  - pip (target=pip-8.0.3-py33_0.tar.bz2) -> python 2.7*|3.4*|3.5*|3.6*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0
  - pip (target=pip-8.0.3-py33_0.tar.bz2) -> setuptools
  - pip (target=pip-8.0.3-py33_0.tar.bz2) -> wheel
  - python 3.3*
  - setuptools (target=setuptools-20.1.1-py33_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*|3.6*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0
  - wheel (target=wheel-0.29.0-py33_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*|3.6*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0
Use "conda info <package>" to see the dependencies for each package.
```

## python 3.5

```
$ conda create --name iris python=3.5
<installing stuff>
(iris)$ python
Python 3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:41:05) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.conda/envs/iris/lib/python3.5/site-packages/iris/__init__.py", line 110, in <module>
    import iris.cube
  File "/home/me/.conda/envs/iris/lib/python3.5/site-packages/iris/cube.py", line 36, in <module>
    import dask.array as da
ImportError: No module named 'dask'
>>> exit()
```

...but `dask` already is installed:

```
conda install dask
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /home/me/.conda/envs/iris:
#
dask                      0.17.2                     py_0    conda-forge
```

## python 3.6 (default python3 version)

```
$ conda create --name myenv python=3
<installing stuff>
$ source activate myenv
(myenv) $ conda install -c conda-forge iris
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - iris -> cartopy >=0.14
Use "conda info <package>" to see the dependencies for each package.
```

The _only_ way I can install it is to use Miniconda, and even then only with python 3 (see #3471).

Are there ways around any of these? I can't find a way of sorting out conflict errors in Conda, but maybe I've been looking in the wrong place!

**Comment by bjlittle** [comment]
@wood-chris Thanks for taking the time to raise this issue.

At various points in time unfortunately we've had to pin back on various versions of `dask` and/or `matplotlib`, which might be causing the issue here i.e., the Anaconda distribution of pre-installed packages are too recent given the packages that are specifically pinned by `iris`.

Could you do a `conda list -n <your-env-name> --explicit` to show the packages and versions in your environment to help clarify?

You could also try `conda install -c conda-forge --no-deps iris`. However, that may install `iris` successfully but may not behave as expected.

Let me know how you get on.

Also, we'll be soon releasing `iris` version `3.0.0` which will be completely unpinned, and thankfully will play nicely with the Anaconda distribution out the box. This is because `3.0.0` will drop support for Python2, thus we can finally unpin `matplotlib` 😄

**Comment by bjlittle** [comment]
@wood-chris The versions of python supported by iris are now stated in the documentation, see https://scitools-iris.readthedocs.io/en/stable/installing.html#installing-iris

Note that, from `iris` 3.x onwards only Python3 is supported, and from `iris` v3.1 we'll have dropped support for Python3.6

I'm going to close this issue now, but please feel free to re-open to continue the discussion here, if that's still relevant. Thanks :+1:
