### ISSUE TITLE
Add Support for Loading/Saving Ancillary Variable to/from NetCDF

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#3473]
Part of #3358

Modify the NetCDF loader/saver such that it supports AncillaryVariables.

---
### Acceptance Criteria
- [x] Added tests for loading a NetCDF file with an Ancillary Variable (that are passing) : see #3556 
- [x] Added tests for saving a cube with an AncillaryVariable to NetCDF file (that are passing)  : see #3550 
 - [x] Additional related : #3557

**Comment by pp-mo** [comment]
All the criteria are met, so this is all done 
( all bar the feature-branch mergeback : https://github.com/SciTools/iris/pull/3704 )
Closing.
