### ISSUE TITLE
Curl on rotated pole grid

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris#348]
Trying to use `iris.analysis.calculus.curl()` with data on a rotated pole grid causes the following exception:
```
  File ".../iris/analysis/calculus.py", line 527, in curl
    raise ValueError('Expecting latitude as the y coord and longitude as the x coord for spherical curl.')
```
This is because the routine is incorrectly checking for a coordinate name of "latitude" and does not accept "grid_latitude" where appropriate.

The same problem also occurs a few lines later with:
```
new_lat_coord = d_j_cube_dphi.coord(name='latitude')
```

With these lines fixed it seems the routine will operate correctly.

**Comment by lbdreyer** [comment]
Presumably this can be closed since #1795 has been merged.
