### ISSUE TITLE
List whitepapers on docs contents page

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3484]
Thought this might be a useful idea to promote the technical discussions (of which we could usefuly do more ?)

Suggestion : like [this commit](https://github.com/SciTools/iris/pull/3444/commits/9d9f4bb8a02d6b24dea95f1f53dab1bf4cf8734f)
The intended effect is simply to list the individual titles under the mainpage section.
That probably isn't at all the right way to do it though :  Possibly can usw templating to automate ??

**Comment by tkknight** [comment]
The new Read The Docs style documentation has now been merged to master (not released), see #3752

The **Technical Papers** (renamed from **White Papers**) are currently under the **REFERENCE** side bar section and on the main content (bottom of page).  See https://scitools-iris.readthedocs.io/en/latest/index.html

This makes is more visible. 

We could promote things further using banner notices if we think it is appropriate - but perhaps not for this atm.

**Comment by pp-mo** [comment]
Yes, I think the new RTD format will fix this for us, because you can open up the nav section and view the titles, without needing to go via another page as at present..
