### ISSUE TITLE
Investigate expected TestGribMessage failures

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3488]
Investigate the following `iris.tests.integration.test_pickle.TestGribMessage` expected failures:

- [test_protocol_0](https://github.com/SciTools/iris/blob/master/lib/iris/tests/integration/test_pickle.py#L70)
- [test_protocol_1](https://github.com/SciTools/iris/blob/master/lib/iris/tests/integration/test_pickle.py#L73)
- [test_protocol_2](https://github.com/SciTools/iris/blob/master/lib/iris/tests/integration/test_pickle.py#L77)

Reference PR https://github.com/SciTools/iris/pull/2608

**Comment by trexfeathers** [comment]
@pp-mo / @lbdreyer can this be closed? I believe you recently did some super work removing all GRIB stuff from core Iris?

**Comment by lbdreyer** [comment]
@trexfeathers yes this can be closed. This testing [has been ported to iris-grib](https://github.com/SciTools/iris-grib/pull/201). There are [some outstanding issues](https://github.com/SciTools/iris-grib/issues/202), but those are being tracked on iris-grib instead
