### ISSUE TITLE
Support `iris.plot.fill_between` and `iris.quickplot.fill_between`

### ISSUE THREAD

**Issue by zklaus** [SciTools/iris#3493]
It is fairly common to have `fill_between` plots as in [timeseries.pdf](https://github.com/SciTools/iris/files/3788002/timeseries.pdf) to show ranges or uncertainties.

It would be nice to support this in iris.

**Comment by bjlittle** [comment]
@zklaus Nice. That's kinda what I was after, and not a million miles away from what I was imagining.

Interesting that you've dug around and prised out `_fixup_dates` :thinking: . Clearly this is something that would be handled for free under the hood automatically by `iris.plot.fill_between`.

Naively, to me it seems like you should be able to pass into `fill_between` any combination of cubes, coords, or arrays, and also honour the use of the `data` kwarg from matplotlib, as you might expect i.e., `iris.plot.fill_between` is just an `iris` wrapper around `matplotlib.pyplot.fill_between`.

So in essence, your examples might look like:
```python
min = cube.collapsed('Ensemble index', iris.analysis.MIN)
max = cube.collapsed('Ensemble index', iris.analysis.MAX)
mean = cube.collapsed('Ensemble index', iris.analysis.MEAN)
coord = cube.coord('time')
plt.fill_between(time, min, max, alpha=.3)
plt.plot(time, mean, label=cube.attributes['experiment_id'])
```
and
```python
std = cube.collapsed('Ensemble index', iris.analysis.STD_DEV)
mean = cube.collapsed('Ensemble index', iris.analysis.MEAN)
coord = cube.coord('time')
plt.fill_between(time, mean-std, mean+std, alpha=.3)
plt.plot(time, mean, label=cube.attributes['experiment_id'])
```
Something along those lines as a first cut should hit the mark, right?

**Comment by zklaus** [comment]
Yeah, sounds good!
