### ISSUE TITLE
Invalid coords in summary is superfluous

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#3496]
I'm pretty sure that `cube.summary()` will never produce an Invalid coordinate. Specifically, when this line is called:
https://github.com/SciTools/iris/blob/1d7d0b564e82acbbcd25ccd5963b246b186434c8/lib/iris/cube.py#L2045
I believe that `invalid_coords` will always be empty. It is essentially defined as a coordinate which is neither a scalar coordinate nor a vector coordinate, however vector coordinates are already defined so that they contain all coordinates which are not scalar coordinates. This means that all coordinates are necessarily either scalar or vector coordinates at this point.

**Comment by bjlittle** [comment]
@stephenworsley Great spot :eyeglasses: . 

I agree. The concept of `invalid_coords` is, dare I say, invalid... and what's more I've never, ever seen any. 

I think this is ancient code from when we were first developing `iris` and it wasn't well defined the coordinates that we were dealing with. After checking, I believe it's safe to purge this technical debt. 

Thanks!

**Comment by rcomer** [comment]
There seem to be a few redundant bits in there.  E.g.

* If `self.coord_dims(coord)` is empty, how could the coord shape be anything other than `(1,)`?
https://github.com/SciTools/iris/blob/1d7d0b564e82acbbcd25ccd5963b246b186434c8/lib/iris/cube.py#L2020-L2021

* How would anything in `self.dim_coords` be scalar?
https://github.com/SciTools/iris/blob/1d7d0b564e82acbbcd25ccd5963b246b186434c8/lib/iris/cube.py#L2025-L2026
