### ISSUE TITLE
New extrapolation modes for iris.analysis.interpolate.linear()

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris#351]
Add two new extrapolation modes to `iris.analysis.interpolate.linear`:
- "nearest": Just duplicate the nearest defined value.
- "missing": Mask out any areas which would require extrapolation.

**Comment by ajdawson** [comment]
The function `iris.analysis.interpolate.linear` is deprecated. Its replacement `iris.analysis.Linear` supports masking extrapolated values, and the `iris.analysis.Nearest` object provides nearest neighbour interpolation.
