### ISSUE TITLE
Update iris logo

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3524]
Require to incorporate the latest `iris` logo changes from @abooton in time for the `2.3.0` and `3.0.0` releases.

---
Acceptance Criteria:
- [x] Update logo in 2.3 documentation to be the latest  (See PR #3599)
- [x] Update logo in 3.0 documentation to be the latest 
      (**NOTE:** will happen with upcoming 2.3.x mergeback... see PR #3615)
- [x] Update https://twitter.com/scitools_iris logo

**Comment by lbdreyer** [comment]
Preferrably do this in the v2.3.x then we will add it to master (and v3) as part of the mergeback

**Comment by abooton** [comment]
New logo has been added to the 2.3.x branch in PR #3599 .  The docs haven't been rebuilt yet though.

**Comment by lbdreyer** [comment]
The docs have been built and it looks to me like it has picked up the new logo see:
https://scitools-docs.github.io/iris/v2.3.x/index.html

If you compare that to the docs built from the master branch:
https://scitools-docs.github.io/iris/master/index.html
You can see the logo is different

You can see the built documentation for the v2.3.x branch was updated 17 hours ago:
https://github.com/SciTools-docs/iris/tree/gh-pages/v2.3.

**Comment by lbdreyer** [comment]
The new logo does not appear in the README, for either the master or v2.3.x branch, because the README points to `iris/master/docs/iris/src/_static/logo_banner.png`

So once we have done the mergeback this will be fixed

**Comment by lbdreyer** [comment]
The new logo is on the master branch, now that the 2.3.x mergeback (#3615) is in :tada: :raising_hand_woman:
