### ISSUE TITLE
Remove experimental equalise_cubes

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3528]
Follow-up on #3527, and remove the `iris.experimental.equalise_cubes` module, akin to #3523.

Target this for the `3.1.0` release.

**Comment by bjlittle** [comment]
Closes #3342

**Comment by larsbarring** [comment]
Now, when this function becomes a 'regular member of iris', would it be possible to have it returning the attributes ( etc) that had to be removed to equalise the cubes?

**Comment by bjlittle** [comment]
Hey @larsbarring,

Good to hear from you. I'm assuming that this is because you want to reattach some of the metadata that was removed?

**Comment by larsbarring** [comment]
Yes, either reattaching as for example with tracking_id, or just to know what is not consistent when I expected it to be.
Lars

**Comment by bjlittle** [comment]
Thanks @larsbarring, much appreciated.

My head is in the space of considering how to make `iris` more lenient and customisable for users, particularly when performing such operations as this, as well as concatenation, merging, arithmetic and equality.

You should probably also be aware of https://github.com/SciTools/iris/issues/3325 which intends to address the issue of `iris` being opinionated about what `attributes` it cares about.

Anyways, I appreciated the unnecessary hoops that users are forced to jump through, so your use case here is valuable, thanks for taking the time to feedback 😃
