### ISSUE TITLE
Define test structure

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris#353]
1. Define:
   - the testing philosophy (e.g. The split between unit tests and integration tests. Should unit tests prefer mock? etc.);
   - the testing structure and naming conventions, for example:
     - e.g. https://groups.google.com/forum/?hl=en-GB&fromgroups=#!topic/scitools-iris-dev/OMbwsyyLszI
     - #350
   - document both within the Iris developer guide.
2. Create follow-on issue(s) to transform the existing tests.

**Comment by pelson** [comment]
Think this has been addressed in http://scitools.org.uk/iris/docs/latest/developers_guide/tests.html
