### ISSUE TITLE
Black is invisible

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3542]
There was no whatsnew for #3518 to publicise what's been done.
I think it's worth it just to inform people that the code format testing has been updated.

Meanwhile, even if you go looking in the developers' guide, the new information doesn't appear for some odd reason.

So [this line](https://github.com/bjlittle/iris/blame/15e7f2c8fe2c24c90f41ee7600e949535fb4e772/docs/iris/src/developers_guide/index.rst#L15) says that the new "code_format.rst" page should now appear on the devguide menu, but [here in the built docs](https://scitools-docs.github.io/iris/master/developers_guide/index.html) it mysteriously does not.

I couldn't work out what's wrong here, but if we get a fix to give this some publicity, then obviously we'll fix that too...

---
Acceptance Criteria:
- [x] code_format.html appears in the developer's guide in the "latest" documentation (fixed in #3577 and #3578)
- [x] Add whats new docs_change to mention code_format.html page (see #3581)

**Comment by bjlittle** [comment]
@pp-mo Yeah, I noticed that the latest docs weren't rendering any changes. Oddness that definitely needs investigating :confused:

**Comment by pp-mo** [comment]
Since #3577 , still not working.

I think I messed up the doctr command.
Please see #3578

**Comment by lbdreyer** [comment]
@pp-mo assuming #3578  works, it looks like all that's left for this ticket is a whats new for black

**Comment by lbdreyer** [comment]
Acceptance criteria have been completed so I am going to close this issue.
