### ISSUE TITLE
Re-order constraints topics in User Guide

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3553]
It's got a bit bloated + confusing.
Just re-prioritising the discussion topics would improve it.
See [comment on #3463](https://github.com/SciTools/iris/pull/3463#discussion_r346771973)

**Comment by tkknight** [comment]
is this issue still valid @pp-mo ?

**Comment by trexfeathers** [comment]
> is this issue still valid @pp-mo ?

#4656?
