### ISSUE TITLE
AuxCoords (and AncillaryVariables) lose reference to dimensions when they become scalar

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#3555]
There is currently no way to have an `AuxCoord` (or similar object) maintain a reference to a scalar coordinate. This might be desirable in order for scenarios like the following example to work:

```python
from iris.cube import Cube, CubeList
from iris.coords import DimCoord, AuxCoord

cube = Cube([[0,1],[2,3]])
lat = DimCoord([0,1], long_name="lat")
lon = DimCoord([0,1], long_name="lon")
aux = AuxCoord([[1,2],[3,4]], long_name="foo")
cube.add_dim_coord(lat, 0)
cube.add_dim_coord(lon, 1)
cube.add_aux_coord(aux, (0,1))

list = CubeList([cube[0], cube[1]])
merged_cube = list.merge_cube()
```

Currently, this code throws an error because there is no way for differing AuxCoords to 'add a dimension'. Currently, It would be difficult to modify `merge()` to be able to reassemble the original cube since we have no way of knowing when a dimension should be added to the AuxCoord.

If it were possible in some way to associate AuxCoords to a scalar coordinate (a coordinate equivalent to the dimension it was associated to before slicing), then it would be possible to modify `merge()` behaviour to allow the original cube to be reassembled.

One potential problem with this approach would be the lack of a way to save such an association. This would only help when slicing and merging happen in the same opperation.

**Comment by stephenworsley** [comment]
So to add to the weirdness of merge, if we try instead to merge the following CubeList
```python
list = CubeList([cube[0, 0], cube[0, 1], cube[1, 0], cube[1, 1]])
```
then we are able to reconstruct the original cube.
If we then change `aux` to be
```python
aux = AuxCoord([[1,2],[1,2]], long_name="foo")
```
then this coordinate ends up collapsed to one dimension in the final cube.

It seems as though merge will only expand the dimensionality of scalar coordinates and does so in a way that depends on their data.

**Comment by rcomer** [comment]
Related I think: #3084
