### ISSUE TITLE
Data not loaded lazily in a large UM format file

### ISSUE THREAD

**Issue by ScottWales** [SciTools/iris#3586]
When I try and load a large (~ 30 GB, 2120x2600 grid, 90 levels) UM format file in Iris I am getting out of memory errors in the `iris.load()` call.

I expect instead that Iris should be able to `load()` any size UM file, and that an out of memory error should only occur if you try to load lazy data that is too large for memory.

It appears that array data is being read at https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L597 when the file is first loaded. I don't entirely understand Iris's lazy_data module, but perhaps the `open()` here could be wrapped by dask.delayed so that the file is only read from when data is needed, something like
```
    def __getitem__(self, keys):
        @dask.delayed
        def load_data():
            with open(self.path, "rb") as pp_file:
                pp_file.seek(self.offset, os.SEEK_SET)
                data_bytes = pp_file.read(self.data_len)
                data = _data_bytes_to_shaped_array(
                    data_bytes,
                    self.lbpack,
                    self.boundary_packing,
                    self.shape,
                    self.src_dtype,
                    self.mdi,
                )
                return data
        data = dask.array.from_delayed(load_data(), shape=self.shape, dtype=self.dtype)
        return data.__getitem__(keys)
```

**Comment by pp-mo** [comment]
The whole point of the PPDataProxy object is that it creates a delayed access to the data, which is triggered by the `__getitem__` call.  Iris.load creates these objects and wraps them in dask arrays, so that when the lazy array is computed, the `__getitem__` call performs a delayed file fetch.
In effect, this does 

A load operation only creates PPDataProxy objects to put them inside lazy arrays in this way, so this code line should never get called at all during a load operation, but only subsequently when real cube data is fetched.
Can you explain what you are doing more exactly ?

Warning : you may need to be cautious if using debugging with an IDE that displays object properties automatically :   Anything that attempts inspects the ".data" property of a cube will trigger data loading.  I have this problem with Eclipse IDE : if you type a cube variable name it will try to autocomplete on names of properties, and this can trigger premature cube loading.
You can check by printing 'cube.has_lazy_data()' : if False, it has happened !

**Comment by ScottWales** [comment]
Thanks, sorry for not being clear, I am just talking about `iris.load` failing, I'm not looking at the cube's  data. It appears that rather than performing a delayed file fetch the data is actually being loaded, and then wrapped in a dask array.

Take the following test, which mocks out the PPDataProxy loading to just return a giant numpy array (imagine in practice this is a data field in the file).
```python
import iris
import numpy
import unittest.mock as mock
    
f = iris.sample_data_path("uk_hires.pp")


def big_data(*args, **kwargs):
    raise BaseException() # Note memory errors seem to be getting caught somewhere
    return numpy.zeros((1024**3, 1024**3))

    
with mock.patch.object(
    iris.fileformats.pp.PPDataProxy, "__getitem__", side_effect=big_data
) as getitem:
    c = iris.load(f, iris.AttributeConstraint(STASH='m01s00i033'))
    getitem.assert_not_called()
```
As you say this should not be called at all, as it's just doing a load and should not touch the data fields. Running this test however I get:
```
Traceback (most recent call last):
  File "loadtest.py", line 18, in <module>
    c = iris.load(f, iris.AttributeConstraint(STASH='m01s00i033'))
  File "s/conda/irisdev/lib/python3.7/site-packages/iris/__init__.py", line 304, in load
    return _load_collection(uris, constraints, callback).merged().cubes()
  File "/conda/irisdev/lib/python3.7/site-packages/iris/__init__.py", line 271, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/conda/irisdev/lib/python3.7/site-packages/iris/cube.py", line 144, in from_cubes
    for cube in cubes:
  File "/conda/irisdev/lib/python3.7/site-packages/iris/__init__.py", line 258, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/conda/irisdev/lib/python3.7/site-packages/iris/io/__init__.py", line 203, in load_files
    fnames, callback, constraints
  File "/conda/irisdev/lib/python3.7/site-packages/iris/fileformats/rules.py", line 452, in load_cubes
    user_callback_wrapper=loadcubes_user_callback_wrapper,
  File "/conda/irisdev/lib/python3.7/site-packages/iris/fileformats/rules.py", line 368, in _load_pairs_from_fields_and_filenames
    for field, filename in fields_and_filenames:
  File "/conda/irisdev/lib/python3.7/site-packages/iris/fileformats/rules.py", line 434, in _generate_all_fields_and_filenames
    filename, **loader.field_generator_kwargs
  File "/conda/irisdev/lib/python3.7/site-packages/iris/fileformats/pp.py", line 1682, in _interpret_fields
    _create_field_data(field, (field.lbrow, field.lbnpt))
  File "/conda/irisdev/lib/python3.7/site-packages/iris/fileformats/pp.py", line 1748, in _create_field_data
    field.data = as_lazy_data(proxy, chunks=block_shape)
  File "/conda/irisdev/lib/python3.7/site-packages/iris/_lazy_data.py", line 195, in as_lazy_data
    data = da.from_array(data, chunks=chunks, asarray=asarray)
  File "/conda/irisdev/lib/python3.7/site-packages/dask/array/core.py", line 2771, in from_array
    return Array(dsk, name, chunks, meta=meta, dtype=getattr(x, "dtype", None))
  File "/conda/irisdev/lib/python3.7/site-packages/dask/array/core.py", line 1017, in __new__
    meta = meta_from_array(meta, dtype=dtype)
  File "/conda/irisdev/lib/python3.7/site-packages/dask/array/utils.py", line 88, in meta_from_array
    meta = x[tuple(slice(0, 0, None) for _ in range(x.ndim))]
  File "/conda/irisdev/lib/python3.7/unittest/mock.py", line 960, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/conda/irisdev/lib/python3.7/unittest/mock.py", line 1026, in _mock_call
    result = effect(*args, **kwargs)
  File "loadtest.py", line 11, in big_data
    raise BaseException()
BaseException
```
It looks like it is using 'dask.array.from_array()' in the `as_lazy_data()` function, which is reading in the data from the proxy as a numpy array and then just wrapping it with a dask array. There should be a dask.delayed layer in there at some point to avoid doing an actual read from the file during setup.

Strangely memory exceptions seem to get caught at some point (hence the BaseException in my test). In practice for a file with lots of fields the data accumulates until the computer runs out of memory.

**Comment by pp-mo** [comment]
Stop press !
#3659 may relate to / fix this problem.

Apologies, I think I had not properly understood this problem before.
Possibly I didn't see it fetching data when it should not because of version differences.

**Comment by ScottWales** [comment]
Great, I look forward to the fix

**Comment by abooton** [comment]
The fix mentioned above went into Iris2.4 which has been released.
