### ISSUE TITLE
Correct CellMethod.__str__ method to be CF-compliant

### ISSUE THREAD

**Issue by MoseleyS** [SciTools/iris#3592]
As shown in the CF-standard (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html) the correct format for writing a cell method is "coord: method". Iris currently prints "method: coord" instead which should be corrected.

**Comment by MoseleyS** [comment]
If you want something done, do it yourself...

**Comment by trexfeathers** [comment]
Actively working on this

**Comment by MoseleyS** [comment]
> Actively working on this

Thanks! I haven't got to it yet - in spite of having a reminder...
