### ISSUE TITLE
Get new logo into README

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3610]
Was referencing master branch explicitly in url based on '''https://raw.githubusercontent.com/SciTools/iris/master/...'''

Fixed by making relative link in README  :
https://github.com/SciTools/iris/commit/cb65a1bc2e186fc561e87315c09e86c3d448d68d

**Comment by lbdreyer** [comment]
@pp-mo can this be closed?

**Comment by pp-mo** [comment]
> can this be closed?

Thanks @lbdreyer 
I think so, I can't really see why I created a separate issue in the first place.
