### ISSUE TITLE
Can't save compressed PP data

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3676]
Iris has [this code](https://github.com/SciTools/iris/blob/v2.4.0/lib/iris/fileformats/pp.py#L1254) to save PP fields while (re-)packing the data.

I think this ***should*** mean that you can store data as compressed PP fields by just setting LBPACK and BACC.  
But at present, it does not work, and creates files that will not read back, because it doesn't correct the field length in LBLREC.

Example:
```
>>> import iris
>>> from iris.tests import get_data_path
>>> import iris.fileformats.pp
>>> 
>>> cube = iris.load_cube(get_data_path(['PP', 'aPPglob1', 'global.pp']))
>>> prs = iris.fileformats.pp.save_pairs_from_cube(cube)
>>> f0 = next(prs)[1]
>>> f0.bacc = -3.0
>>> f0.lbpack =1
>>> iris.fileformats.pp.save_fields([f0], 'tmp.pp')
>>> 
>>> print(iris.load('tmp.pp'))
/home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/pp.py:1887: UserWarning: LBLREC has a different value to the integer recorded after the header in the file (1676 and 1677). Skipping the remainder of the file.
  pp_field.lblrec * PP_WORD_DEPTH, len_of_data_plus_extra
< No cubes >
>>> 
```

**NOTE:** I'm really not clear that we *actually need to fix this.*
For however long it hasn't worked, nobody has yet complained or reported it.
So, we could just decide to not support this (and possibly, remove the Iris code support).

**Comment by trexfeathers** [comment]
Adding the following to the top of the script fixes it. The problem affects Iris and Mule alike, which makes me think that something has changed the behaviour of the `memoryview` returned by `mo_pack.compress_wgdos()`; perhaps a change in Python itself?

```python
