### ISSUE TITLE
Version wrong in <title> tag in Iris 2.4 documentation

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#3690]
From the eagle-eyed @jonseddon 🦅 👁 :

"I just noticed that the text inside the HTML <title> tag for the Iris 2.4 documentation at https://scitools.org.uk/iris/docs/v2.4.0/gallery.html says “Thumbnail gallery &#8212; Iris 2.2.0 documentation” rather than 2.4. It’s correct in the equivalent page in the version 2.3 documentation. I’ve not done an extensive search of all pages, but it looks like there’s a similar problem in the version 2.4 User Guide at https://scitools.org.uk/iris/docs/v2.4.0/userguide/index.html."

This appears to be matched by the version drop-down in the top right, too.

**Comment by tkknight** [comment]
The new Read The Docs style documentation has now been merged to master (not released), see #3752

Read The Docs handle this now based upon the version/release values in Iris and should just work.  This will be fully tested when the next Iris release is done.

I see no need to update Iris 2.4 with a hotffix.

I propose closing this.
