### ISSUE TITLE
cube.intersection() returns points outside range due to bounds even when ignore_bounds is True

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#3698]
I have a cube with a longitude dimension with the first and last two points like so
```
print cube.coord('longitude')[[0,1,-2,-1]]

DimCoord(array([  1.25,   3.75, 356.25, 358.75]), bounds=array([[  0. ,   2.5], [  2.5,   5. ], [355. , 357.5], [357.5, 360. ]]), standard_name=u'longitude', units=Unit('degrees'), var_name='longitude', coord_system=GeogCS(6371229.0))
```

Using the intersection method to get the longitudes to go between -30 to 330, with ignore_bounds=True, gives
```
cube_int=cube.intersection(longitude=(-30,330), ignore_bounds=True)
print cube_int.coord('longitude')[[0,-1]]
DimCoord(array([-31.25, 326.25]), bounds=array([[-32.5, -30. ],
       [325. , 327.5]]), standard_name=u'longitude', units=Unit('degrees'), var_name='longitude', coord_system=GeogCS(6371229.0))
```

The point -31.25 has incorrectly been put at the start of the points array, instead of at the end as 328.75. This seems to be because its associated bounds are [-32.5, -30. ]. Removing the bounds gives the correct result:
```
cube.coord('longitude').bounds=None
cube_int=cube.intersection(longitude=(-30,330))
print cube_int.coord('longitude')[[0,-1]]
DimCoord(array([-28.75, 328.75]), standard_name=u'longitude', units=Unit('degrees'), var_name='longitude', coord_system=GeogCS(6371229.0))
```

So it seems that the bounds are not being ignored even with ignore_bounds=True.

This is in iris v.2.3.0, but I don't see any reference to this bug being fixed in v.2.4.0.

**Comment by rcomer** [comment]
This should be fixed by #4278, which will be included in Iris v3.2.  In future that first point (-31.25) will instead become the last point (328.75), regardless of the `ignore_bounds` setting.
