### ISSUE TITLE
Iris data model goes over and beyond CF

### ISSUE THREAD

**Issue by larsbarring** [SciTools/iris#3727]
I do enjoy using iris, but I must also say that sometimes it tests my patience. 
I typically work on projection data from different modelling institutes, which all aim at following the CMIP and CORDEX data specs to the letter. But now and then they miss out on some detail that slip through the CMOR and other quality control tools. But these mistakes invariably show up as problems in iris when merging cube lists and similar operations. But alright, this is something one have to live with, and as long as the mistakes are in parts covered by the CF Conventions or the CMIP/CORDEX data specs it could actually be a good thing.
But I find it more difficult to like is that iris also refuses to merge cubes where non-CF attributes do not agree perfectly. Here is an example from a recent attempt to merge three cubes:
```
time:units                    days since 1949-12-01 00:0...  days since 1949-12-01T00:0...  days since 1949-12-01 00:0...
latitude:long_name                               'latitude'          'latitude coordinate'                     'latitude'
longitude:long_name                             'longitude'         'longitude coordinate'                    'longitude'
grid_longitude:long_name      'longitude in rotated pole...  'longitude in rotated pole...  'longitude in rotated-pole...
```
gives the following error:

```
MergeError: failed to merge into a single cube.
  Coordinates in cube.aux_coords (scalar) differ: time.
  Coordinates in cube.dim_coords differ: grid_latitude, grid_longitude.
  Coordinates in cube.aux_coords (non-scalar) differ: latitude, longitude.
```
It would be helpful if iris could issue a warning (specifyng what it finds different) rather than just throw an error (that is only moderately helpful) when differences are found in parts not covered by the CF Conventions.

**Comment by trexfeathers** [comment]
Hi @larsbarring, have you tried applying [iris.util.describe_diff](https://scitools.org.uk/iris/docs/latest/iris/iris/util.html#iris.util.describe_diff) to your example?

**Comment by rcomer** [comment]
If it helps, I wrote [a function to compare two coordinates](https://gist.github.com/rcomer/443dc06dbef2d804ebf703b44aba5bc5).

**Comment by larsbarring** [comment]
Thanks Ruth, this was good help (again)!
A couple of thoughts so far:
1. Ruth's function finds several differences in the cube coordinates (still working on sorting these), but the iris.util function found none. Maybe ideas from the former could be used in the latter?
2. Some modelling institutes prefer the `proleptic_gregorian` calendar even though the simulated period is not even near the julian/gregorian calendar shift date. This means that for those datasets the `proleptic_gregorian` is the same as the `gregorian` calendar, and it should not be flagged as an incompatibility.
3. The CF Conventions does not mandate, to my knowledge, the precision or encoding (e.g. float32 or float64) of the coordinates (CMIP/CORDEX might do that), so such differences should be flagged as warnings and points compared at the lower precision.

I am not much of a python programmer (:-(  so I cannot contribute in that respect, only in the more limited sense that I report use cases and make suggestions.

**Comment by rcomer** [comment]
@bjlittle did mention an intention to retire `describe_diff` (among others) over on [#2992/comment](https://github.com/SciTools/iris/issues/2992#issuecomment-554034775).  So I believe he has a plan in mind to do this better.  However, `describe_diff` does not seem to be marked as deprecated by Iris 2.4, so I guess the plan is not as advanced as he would have liked.

**Comment by pp-mo** [comment]
>  deprecated by Iris 2.4
Actually, as we have a major version coming up (Iris 3.0), a lot of things will change, and deprecation is not strictly required ...
Can't say exactly how that might affect this, though.  @bjlittle what are the plans ?

**Comment by larsbarring** [comment]
Closing this as it is too unspecific, and underlying problems was solved with help of @rcomer's [comment](https://github.com/SciTools/iris/issues/3727#issuecomment-638374743)
