### ISSUE TITLE
Some gallery plots not included in their pages

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#3728]
Not all gallery pages currently include an image of the plot generated by their code. All items still have their respective images on [the main gallery page](https://scitools.org.uk/iris/docs/latest/gallery.html). I haven't found any examples where only a subset of a page's images are missing.

Examples:
- [Quickplot of a 2d cube on a map](https://scitools.org.uk/iris/docs/latest/examples/General/global_map.html) (both plots missing)
- [Multi-line temperature profile plot](https://scitools.org.uk/iris/docs/latest/examples/General/lineplot_with_legend.html)

**Comment by tkknight** [comment]
The new Read The Docs style documentation has resolved this issue.

See https://scitools-iris.readthedocs.io/en/latest/generated/gallery/index.html.  Note this is the **latest**, this points to **master**.  When there is a release for Iris there will also be a **stable** release and a **tagged** release too.

I think we can close this issue now?

**Comment by trexfeathers** [comment]
I can confirm that this appears to be solved, thanks @tkknight!
