### ISSUE TITLE
Format and other issues with _ff._adjust_field_for_lbc

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#3741]
I am trying to analyse some LBCs. These have a value of LBTIM of 12

According to UMDP F3  this is correct as the calendar these files use is a 360 day calendar:
`
LBTIM is coded as (100*IA + 10*IB + IC) `

and IC is defined as 
`= 2 if the ’360-day’ calendar (i.e. 12 30-day months) is used for T1 and T2.`

Furthermore there is an error in the format statements in the raise, leading to an unhelpful error in this case:

```
        # Set LBTIM to indicate the specific time encoding for LBCs,
        # i.e. t1=forecast, t2=reference
        lbtim_default = 11
        if field.lbtim not in (0, lbtim_default):
            raise ValueError('LBC field has LBTIM of {:d}, expected only '
                             '0 or {:d}.'.format(field.lbtim, lbtim_default))
        field.lbtim = lbtim_default
```

:d format is not defined for splittable ints so instead of getting a useful error message the stack trace ends as follows:

```
  File "/lib/python3.6/site-packages/iris/fileformats/_ff.py", line 566, in _adjust_field_for_lbc
    '0 or {:d}.'.format(field.lbtim, lbtim_default))
TypeError: unsupported format string passed to SplittableInt.__format__
```

This incorrect format is used widely in this module

**Comment by nhsavage** [comment]
a minimal example for the format issue can be shown here: 

```
>>> from iris.fileformats.pp import SplittableInt
>>> three_six_two = SplittableInt(362)
>>> 'LBC field has LBTIM of {:d}'.format(three_six_two)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to SplittableInt.__format__
```

vs 

```
>>> 'LBC field has LBTIM of {}'.format(three_six_two)
'LBC field has LBTIM of 362'
```

**Comment by nhsavage** [comment]
746e1b39 fixed the issue with an incorrectly formatted error message. Code now gives 2 warnings and loads no data:

```
/home/h03/fris/code/iris/lib/iris/fileformats/_ff.py:813: UserWarning: Input field skipped as PPField creation failed : error = 'LBC field has LBTIM of 2, expected only 0 or 11.'
  warnings.warn(msg.format(str(valerr)))
/home/h03/fris/code/iris/lib/iris/fileformats/_ff.py:813: UserWarning: Input field skipped as PPField creation failed : error = 'LBC field has LBTIM of 12, expected only 0 or 11.'
  warnings.warn(msg.format(str(valerr)))
```

**Comment by nhsavage** [comment]
30114da fixes the issue. The value of LBTIM will now only be set to 11 if it is zero. Otherwise it will be unchanged. I assume that this was done to allow LBC files which do not fully comply with UMDP F3 to load. These were probably generared by the old LBC generation code MakeBC, and if we can test this fix against some files from that era, it would be useful. There currently seem to be no LBC files at all in the test collection 

If the safety of comparing to a list of valid values of LBTIM is desired to be kept, I would recomend a minimum list of 11, 12 and 14 for all 3 possible calendars.

**Comment by nhsavage** [comment]
Note that the only tests at present are using mock to set up header for an LBC file (probably similar to ones with some incorrect headers). I will now survey the available LBC files and discuss some more appropriate tests. Although the test for a 'bad' LBTIM code is there, the mock uses an integer not a splittable int so the test passes, when it shouldn't.  https://github.com/SciTools/iris/blob/be9e2ff703e4a87f2c2533e86bd06aa402563b80/lib/iris/tests/unit/fileformats/ff/test_FF2PP.py#L489

**Comment by trexfeathers** [comment]
See also #3748, which has stemmed from discussions around this subject.
