### ISSUE TITLE
LBC File Integration Tests

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#3748]
After discussion with @nhsavage during #3743, we believe it would be beneficial to have one or two integration tests for parsing LBC files - to be stored in [SciTools/iris-test-data](https://github.com/SciTools/iris-test-data).

@nhsavage will be sourcing these files in due course. It is important that these files:
- represent typical LBC files that we expect Iris to work with
- will not take too long to process

See [SciTools/iris-test-data](https://github.com/SciTools/iris-test-data), and try running any [existing Iris integration tests](https://github.com/SciTools/iris/tree/master/lib/iris/tests/integration) that use iris-test-data files, for an idea of appropriate files.

**Comment by nhsavage** [comment]
actually I was wrong - there is already 1 integration test for LBCs.  Data is at https://github.com/SciTools/iris-test-data/tree/master/test_data/FF/lbc and the test is [here](https://github.com/SciTools/iris/blob/master/lib/iris/tests/integration/test_ff.py)

**Comment by nhsavage** [comment]
Looking in detail at this file, many of the headers are wrong. It also will have been created with the legacy code makeBC not the more modern CreateBC (when this file was uploaded 18 Nov 2014, CreateBC had not been released (27 Feb 2015). Therefore an LBC file with some valid metadata should be included, possibly incliding a 360 day calendar and a variable resolution file.
