### ISSUE TITLE
Unpin matplotlib

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3759]
The `matplotlib` package has been pinned to `<v3.3.0` to temporarily avoid test failures within `iris` due to the latest release `v3.3.0`.

See https://github.com/SciTools/iris/pull/3758.

**Comment by trexfeathers** [comment]
Should hopefully be addressed by the unpin proj task - [see comment on #3154](https://github.com/SciTools/iris/issues/3154#issuecomment-663497294).

**Comment by tkknight** [comment]
The[ read the docs yml conf](https://github.com/SciTools/iris/blob/master/ci/requirements/readthedocs.yml) file also will need to be unpinned.

**Comment by trexfeathers** [comment]
Closed by #3811
