### ISSUE TITLE
Pipenv install not working

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#3777]
Clean pipenv install didn't work on MacOS. Here's the stack trace

```
$ pipenv install scitools-iris
Installing scitools-iris…
Error:  An error occurred while installing scitools-iris!
Error text: Collecting scitools-iris
  Using cached scitools_iris-2.4.0-py3-none-any.whl (2.3 MB)
Collecting dask[array]>=1.2.0
  Using cached dask-2.22.0-py3-none-any.whl (828 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cartopy
  Using cached Cartopy-0.18.0.tar.gz (14.4 MB)

    ERROR: Command errored out with exit status 1:
     command: /Users/niall/.local/share/virtualenvs/Projects-PTYlTbKT/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gn/lb9wdf291_d3nc2cq41mc1qw0000gp/T/pip-install-zir3_v5j/cartopy/setup.py'"'"'; __file__='"'"'/private/var/folders/gn/lb9wdf291_d3nc2cq41mc1qw0000gp/T/pip-install-zir3_v5j/cartopy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/gn/lb9wdf291_d3nc2cq41mc1qw0000gp/T/pip-pip-egg-info-sp58ptt2
         cwd: /private/var/folders/gn/lb9wdf291_d3nc2cq41mc1qw0000gp/T/pip-install-zir3_v5j/cartopy/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/private/var/folders/gn/lb9wdf291_d3nc2cq41mc1qw0000gp/T/pip-install-zir3_v5j/cartopy/setup.py", line 43, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gn/lb9wdf291_d3nc2cq41mc1qw0000gp/T/pip-install-zir3_v5j/cartopy/setup.py", line 45, in <module>
        raise ImportError('NumPy 1.10+ is required to install cartopy.')
    ImportError: NumPy 1.10+ is required to install cartopy.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in scitools-iris. Report this to its maintainers.
✘ Installation Failed
```

**Comment by bjlittle** [comment]
@niallrobinson Thanks for taking the time to report this. We clearly need to address some requirement issues for the PyPI package.
Ideally we'll need to address this as part of the `iris` 3.0 release, with in pending.

**Comment by niallrobinson** [comment]
thanks Bill. For a bit of context about why not conda: I'm trying to deploy this on a serverless AWS deployment, and the deploy tools (Zappa) work with pipenvs

**Comment by niallrobinson** [comment]
interestingly I just tried this inside an Amazon Linux Docker container and it has seemed to work. I think it's due to the lack of `gcc` on my mac perhaps?

**Comment by bjlittle** [comment]
@niallrobinson Okay, so I've dug a wee bit deeper on this, as I'm currently attempting to rationalise the `PyPI` and `conda` dependencies for `iris` in the pending `v3.0.0` release...

So this issue that you're experiencing is relating to a change in `cartopy` from `v0.17` to `v0.18`, where they decided to pull [PEP518](https://www.python.org/dev/peps/pep-0518/) support through the `pyproject.toml` file. For a history of this, see:

- https://github.com/SciTools/cartopy/issues/1584
- https://github.com/SciTools/cartopy/issues/1552
- https://github.com/SciTools/cartopy/issues/1264

Ideally, it would be great if `cartopy` used [PEP518](https://www.python.org/dev/peps/pep-0518/) and [PEP517](https://www.python.org/dev/peps/pep-0518/), as it would resolve this (from my naive perspective).

Your temproary workaround for this, is to first `pip install numpy` into your environment, then `pip install scitools-iris`.

I suspect that will only be the beginning of you're woes if your taking the `pip` route, as you'll then need to get `proj`, `geos`, `udunits2` et al in the environment to make it "all just work".

HTH

**Comment by bjlittle** [comment]
@niallrobinson I'm going to close the PR, as this is really a `cartopy` issue.
