### ISSUE TITLE
Add support for Iris on Graviton 2

### ISSUE THREAD

**Issue by andyevansweather** [SciTools/iris#3788]
I tried installling iris on an [AWS Graviton 2 Server](https://aws.amazon.com/ec2/graviton/) and was unable to do so.

Steps to reproduce error:

* Set up an AWS Graviton Server in eu-west-1
* SSH into instance
* Follow [iris instructions on how to install from source](https://scitools.org.uk/iris/docs/latest/installing.html)
* It will fail on install

**Comment by andyevansweather** [comment]
Thanks for this.

I have managed to install iris ok on T2 and T3 instances on [aws](https://aws.amazon.com/ec2/instance-types/), however, I believe that it is because the Graviton Servers are ARM architecture and this is what is causing the problem - for example, I have tried installing on an m6g where this issue was first noticed.

**Comment by trexfeathers** [comment]
>  the Graviton Servers are ARM architecture

Ah! We're definitely out of our wheelhouses with this one then. We'll need to set aside some time for investigation of this, so it's unlikely to happen soon. If it's something that you need quickly please say so and we'll see what we can do; and if you believe you can offer any more help on the matter that would also be helpful.
