### ISSUE TITLE
Public Docs

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#3809]
I'm not certain, but I think the public documentation is currently pointing at the development version of Iris as "latest", and I can't see a way to show a released version.
https://scitools-iris.readthedocs.io/en/latest/

Ping @SciTools/iris-devs

**Comment by rcomer** [comment]
@bjlittle has assured me this is in hand.

**Comment by tkknight** [comment]
Hi @rcomer.  This was a change https://github.com/SciTools/scitools.org.uk/commit/d912760b7f1f40b2fb2828ad7e26a9bc7b29b8ff to point the scitools.org.uk **latest** to the ReadTheDocs **latest**.

It is now clear the **latest** means two different things on these two web sites. I have reinstated the latest to point to the latest Iris release v2.4.0 https://github.com/SciTools/scitools.org.uk/commit/dc039d7f0843f3dddbc927798bfe8772534614ee but kept the the index redirect to use when we do an Iris 3.0.0 release (https://github.com/SciTools/scitools.org.uk/tree/master/iris/docs/latest_readthedocs) by which time we should have a tagged, stable Iris 3.0.0 on ReadTheDocs.

**Comment by rcomer** [comment]
Great, thanks @tkknight !
