### ISSUE TITLE
Feature request: Linear regression

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#3810]
Hello, a feature that currently seems to be missing from Iris is being able to do linear regressions e.g. to compute linear trends over time, which is important when studying climate change, for instance. I would have thought that even just having ordinary least squares (OLS) regression would be useful for many users.

The most obvious way to do this that I can think of (from a user rather than developer perspective) is to include it as an option under iris.analysis for use with cube.collapsed e.g. "cube.collapsed('time', iris.analysis.OLS)". I think it would make most sense for this to return a CubeList with cubes containing the intercept and slopes - this would make it a bit different from other iris.analysis functions, but I don't think this would matter a lot.

**Comment by rcomer** [comment]
Related: #3331
