### ISSUE TITLE
mpl 3.3+ deprecation warning

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3822]
## 📰 Custom Issue

PR https://github.com/SciTools/iris/pull/3762 unpinned `matplotlib<3.3`.

However, the tests are now generating the following `matplotlib` deprecation warning, which should be resolved before a hard traceback is encountered from `matplotlib>=3.5` onwards:
```shell
.../iris/lib/iris/plot.py:252: MatplotlibDeprecationWarning: 
The IndexFormatter class was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  formatter = mpl_ticker.IndexFormatter(ticks)
```
This issue is based on `SciTools/iris` latest `master` commit https://github.com/SciTools/iris/commit/13e8b2c63825e616b68427bdbdf5e58a0f016988.

For example, the above deprecation warning can be recreated by running the following `iris` unit test:
```shell
> python lib/iris/tests/unit/quickplot/test_scatter.py
```

**Comment by trexfeathers** [comment]
Closing since discussion is taking place in duplicate #3848
