### ISSUE TITLE
Re-word "CF 1.5/1.7" label and use to collate netcdf/CF issues 

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3827]
I'm hopeful that, shortly after Iris 3.0, we can plan to do some rework on netcdf loading and CF support.

Only *some* of that work is about supporting new CF features, some of it being more of internal code work, 
especially what would be involved in retiring/replacing Pyke (#3415).

So I suggest renaming the "Feature : CF 1.6/1.7" to "Feature : netcdf+CF"
And I would *add* to that label, at least the following related issues :
  * #3415
  * #3343
  * #3644
  * #3409
  * #3725
  * #3325

**Comment by pp-mo** [comment]
@bjlittle do you approve this approach ?
It seems to me that our other existing "Feature" labels are ongoing categories rather than specific goals+targets, so I think this re-purposing of the CF label would make sense..

**Comment by bjlittle** [comment]
We've not openly discussed it, but yeah it seems that through use the _Feature_ labels tend to be for on-going _themed_ work.

It makes sense to me to re-badge that lable to be more openended and inclusive, rather that CF version specific.

I've no objections... so go for it :rocket: 

@SciTools/iris-devs Any other opinions?

**Comment by pp-mo** [comment]
Ok, I'm just doing this...
