### ISSUE TITLE
Docs directory prune: iris/docs/iris -> iris/docs/

### ISSUE THREAD

**Issue by tkknight** [SciTools/iris#3836]
## 📚 Documentation

This is not about the contents of the documentation, instead it is about having a more **sensible directory structure**.  The docs currently live in ``iris/docs/iris``.  There seems no reason to have ``iris`` in the path twice so I propose moving the docs to ``iris/docs``.

There may be several locations where this path needs to be updated (docs, Makefile, image testing repo etc).

Suggest this is done after the **Iris 3.0.0** release to avoid impacting any outstanding docs related changes for now.

There is another issue (https://github.com/SciTools/iris/issues/3416) about moving directories, in this case for the test directory - not related to the documentation though.

**Comment by trexfeathers** [comment]
I'm not clued up on the docs side of things, but the existing directory structure **is** the favoured convention for source code (`iris/lib/iris`) - see https://github.com/SciTools-incubator/iris-ugrid/pull/4#issuecomment-671294821. I assume there is either a similar argument for the docs, or maybe it was only done for consistency. It's a difficult thing to phrase as a web search!

**Comment by tkknight** [comment]
From some initial investigation my docs directory proposal seems to fit with the community approach.
