### ISSUE TITLE
More "What's New" internal entries for Iris 3.0.0rc

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#3837]
## 📚 Documentation

#3769 introduced the concept of including internal entries in "What's New"s (see https://github.com/SciTools/iris/pull/3769/commits/4761a10630b044aedb38f56f96ecff3f52085ca4#diff-1d55b4ca42106b167556e0b3e3cc1012R67-R69), and examples of such entries have been added since. But the content of Iris 3.0 originates from a long time before that - any commit since [v2.3.0](https://github.com/SciTools/iris/tree/v2.3.0), excluding the content of [v2.4.0](https://github.com/SciTools/iris/tree/v2.4.0), is new content, and includes many unmentioned internal changes.

@SciTools/iris-devs do we need to retrospectively add pre-#3769 internal "What's New" entries? If so, how diligent do we need to be - all of them, or just the highlights? Example absences from the top of my head are removing support for Python2, and simplifying all the licence headers.

**Comment by trexfeathers** [comment]
FWIW I feel that documenting all the internal changes is an ideal way to communicate to our various stakeholders how much work has gone into v3.0.0 'under the surface', but it will probably take considerable resource to do this work.

**Comment by trexfeathers** [comment]
An offline discussion has decided that we will be OK with retrospectively adding just the highlights.

Going forward, this should be easier. Effectively _every_ PR should now be accompanied by a "What's New" entry. It will therefore become part of the PR process that there _must_ be a separate "What's New" PR created just in time for review - this is simple/consistent to remember, and creating the separate just-in-time PR minimises the chance of conflicting changes on [latest.rst](https://github.com/SciTools/iris/blob/master/docs/iris/src/whatsnew/latest.rst).

**Comment by bouweandela** [comment]
You could also consider using the pull request title and/or text to write the changelog. For example, you could requre that the text of each pull request contains a whatsnew section that you automatically extract before making the next release to compose the changelog.

For the [ESMValTool project](https://github.com/ESMValGroup/ESMValTool), I wrote [a small script](https://github.com/ESMValGroup/ESMValTool/blob/master/esmvaltool/utils/draft_release_notes.py) that I use to generate the changelog from the merged pull requests since the previous release. That way you would avoid having to make many separate pull requests just to update whatsnew.

**Comment by trexfeathers** [comment]
> each pull request contains a whatsnew section that you automatically extract before making the next release to compose the changelog

I'd definitely be in favour of this (although not for 3.0!). If text wasn't provided, we could default to using the PR title and author and include as a bullet point under a heading called `Other`. @tkknight what do you think?

**Comment by tkknight** [comment]
I am keen to keep the what's new as simple as we can get it.  Having the developer add it makes sense (potentially in a separate PR as discussed) and it also allows them to use ReStructuredText to link to the API Reference docs, other documentation pages etc. 

I am typically all for automation but I feel it would negate the richer information as stated above that I think it makes the what's new entries much more user friendly.

**Comment by rcomer** [comment]
I agree with @tkknight that the finished version is likely to be more user-friendly if added to manually.  E.g. “[The appropriate contribution for a pull request might in fact be an addition or change to an existing "What's New" entry.](https://github.com/SciTools/iris/blob/544d324c4cc638fbccc06cbcde9e05a170a1a205/docs/iris/src/developers_guide/documenting/whats_new_contributions.rst#writing-a-contribution)” That statement makes a lot of sense if you have several PRs addressing the same functionality, but I’m not clear that you could achieve it with automation.

**Comment by trexfeathers** [comment]
OK, sounds like the current situation is probably where we want to be - at least for now. If the juggling of `latest.rst` turns out to be more difficult than predicted then I'm sure we can revisit.
