### ISSUE TITLE
Extend Resolve support for AncillaryVariable and CellMeasure

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3839]
## ⚙ Feature Request

To extend the capability of `iris.common.resolve.Resolve` to be able to handle and resolve `iris.coords.AncillaryVariable` and `iris.coords.CellMeasure` metadata.

## Motivation

This will enhance cube arithmetic to include this metadata in its resultant `iris.cube.Cube` result. Also it will provide a more complete and richer, generic way to combine common metadata through the direct use of `iris.common.resolve.Resolve`.

**Comment by stephenworsley** [comment]
@bouweandela @zklaus Is this something you would be interested in for improving `AncillaryVariable` handling in cube arithmetic?

**Comment by zklaus** [comment]
Sounds good! [The docu](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/common/resolve.html) gives some more details. Let's talk about it at the workshop?

**Comment by bjlittle** [comment]
> Another extension that could be useful would be the extension to more than two cubes. I am thinking, for example, multi-model analysis with shared time and space axis thanks to prior regridding, or multi-variable analysis for one member.

@zklaus I *think* this might be possible... I can certainly see the benefit, as in, resolve this list/bunch of cubes to discover the common shape and metadata (if there is one, lenient or strict), then use the resolver as a factory to manufacture "like" cubes from several disparate models.

That's what you're suggesting here, right?

**Comment by zklaus** [comment]
Exactly, @bjlittle!

**Comment by pp-mo** [comment]
@SciTools/peloton not a priority.
Please re-open if you disagree
