### ISSUE TITLE
Netcdf load ignores 'scale_factor_at_projection_origin' of Stereographic grib-mapping

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3845]
The CF conventions state that ['scale_factor_at_projection_origin' is a [required attribute for Stereographic grid-mapping](https://cfconventions.org/cf-conventions/cf-conventions.html#_stereographic)
But our code is [completely ignoring this](https://github.com/SciTools/iris/blob/a338ca530d5220330f136e58a70d502f62f52e6a/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L1479).  
( Note that the comment ["this is checked elsewhere"](https://github.com/SciTools/iris/blob/a338ca530d5220330f136e58a70d502f62f52e6a/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L1496) is totally untrue !  It couldn't be really, as this is the only place that we will inspect the file variable )

By ignoring this, we are mis-representing any input where this is different from 1.0.

Suggested action:
**We should either support this, or at least check it and raise an error/warning when our loaded version is incorrect.**

Note also:  when saving, we currently  [warn that the result is not exact + don't save anything](https://github.com/SciTools/iris/blob/a338ca530d5220330f136e58a70d502f62f52e6a/lib/iris/fileformats/netcdf.py#L2130).
We could fix that too, but at least it is not "wrong".

**Comment by wjbenfold** [comment]
We also have a converse issue - our Stereographic projection has a `true_scale_lat` attribute that isn't represented in the CF conventions

https://github.com/SciTools/iris/blob/b141b01b754fb0f012a0b4ffc812d66a3ca4c271/lib/iris/coord_systems.py#L901-L902

**Comment by pp-mo** [comment]
> our Stereographic projection has a true_scale_lat attribute that isn't represented in the CF conventions

_Mathematically_, I think it is ~equivalent to the CF 'scale factor at projection origin' control.
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_stereographic

Stereographic construction is a simple perspective projection from the opposite pole, 
so the scale factor is everwhere > that at the centre.  
Can't quite do the maths, but it maybe something like S.F.=cos(polar-angle)^2 ??

So I think you can calculate the 'standard parallel', as long as the origin S.F. is < 1.

**Comment by wjbenfold** [comment]
I'm happy that one could be calculated from the other, it just seemed odd to have a `true_scale_lat` attribute when the CF convention is to have `scale_factor_at_projection_origin` (it also makes the translation between the proj CRS and ours just a little more complicated for no apparent reason).

**Comment by pp-mo** [comment]
> @pp-mo was this closed by #4773 ?

Sadly no, it appears that the [successor of the routine linked above](https://github.com/SciTools/iris/blob/4fa3f06caf2175b8654fdb4a2bcd83080b7a1418/lib/iris/fileformats/_nc_load_rules/helpers.py#L406)  is still ignoring true-scale-lat on input.
So it need doing + this issue remains !

**Comment by pp-mo** [comment]
However, since we can now save one, it is at least easier to test -- a round-trip should be good enough.
