### ISSUE TITLE
Replace deprecated IndexFormatter

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#3848]
## 📰 Custom Issue

Matplotlib has deprecated the IndexFormatter class https://github.com/matplotlib/matplotlib/pull/16170.This is used in only one place in the Iris code:
https://github.com/SciTools/iris/blob/a2f49c3eebfa26180c6299f9cc59687ca8303a40/lib/iris/plot.py#L251-L256
A suggestion is given here for how to replace IndexFormatter with a given example https://github.com/matplotlib/matplotlib/issues/16631#issuecomment-594008777.

**Comment by stephenworsley** [comment]
It seems as though Iris is setting its own underlying values in the case of string coordinates on this line:
https://github.com/SciTools/iris/blob/a2f49c3eebfa26180c6299f9cc59687ca8303a40/lib/iris/plot.py#L441
These values seem to be anticipating the behaviour of IndexFormatter and this line would have to change if we adopted the formatter described in the above link.

**Comment by rcomer** [comment]
Another [comment](https://github.com/matplotlib/matplotlib/issues/16631#issuecomment-594108101) further down that issue suggests using `FixedLocator` and `FixedFormatter`.  I think that may be simpler than the `FuncFormatter` option.

**Comment by bjlittle** [comment]
@stephenworsley This is the same as #3822, right? :thinking:

**Comment by stephenworsley** [comment]
@bjlittle yes you're right, I hadn't spotted that one.

**Comment by stephenworsley** [comment]
Closed by #3857.
