### ISSUE TITLE
Iris-sample-data README.rst references Iris INSTALL file for instructions to install

### ISSUE THREAD

**Issue by munslowa** [SciTools/iris#388]
Add clear instructions either in the Iris INSTALL file for instructions to install or add a file in the Iris-sample-data repository to give instructions for installation.

The information on where the sample data needs to be put is in iris.config.SAMPLE_DATA_DIR which is  'Defaults to “sample_data” sub-directory of the Iris package install directory'.

**Comment by pelson** [comment]
Seems to be up to date on the INSTALL document now:

```
If you wish to run any of the code examples
(see http://scitools.org.uk/iris/docs/latest/examples/index.html) you will also
need the Iris sample data. This can also be installed using conda::

conda install -c conda-forge iris-sample-data
```
