### ISSUE TITLE
API Link

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#3880]
## 📚 Documentation
I was just looking at the new docs homepage and realised it’s not that obvious how to browse the various modules ([“reference documentation”](https://scitools.org.uk/iris/docs/v2.4.0/iris/iris.html) in the legacy docs).  This is served by the “Iris API” link in the new docs, but that’s under “Developer Guide”.  Should we have this linked somewhere more prominent?

**Comment by tkknight** [comment]
The link could move to **User Guide** or **Reference** section, which I think makes more sense.

In terms of making it more prominent, there is a sphinx extension named [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/) that may be of use (I've not played with it yet).  I've mentioned this extensions in an issue I just created https://github.com/SciTools/iris/issues/3883 capturing some thoughts after getting the docs to the state it is in now (a good one).

**Comment by tkknight** [comment]
I had a quick play with the panels extensions, see https://iris-test-doc.readthedocs.io/en/latest/ (this link will only show the content until this issue is closed)

**Comment by rcomer** [comment]
I like the examples under “More links....” Nice bold buttons for people who know what they’re looking for and a helpful description for those who don’t.

**Comment by tkknight** [comment]
I've iterated on this, see https://iris-test-doc.readthedocs.io/en/latest/#play-4

**Comment by tkknight** [comment]
The links shared to show the rendered html has now moved onto to show the PR I've created for this https://github.com/SciTools/iris/pull/3884.
