### ISSUE TITLE
[PI] Docs: Potential Future Improvements Overview

### ISSUE THREAD

**Issue by tkknight** [SciTools/iris#3883]
## 📚 Documentation

The Iris docs have been **overhauled** ready for the **Iris 3.0.0** release but I have some ideas on how to improve more....

### Small things

&#x2612; ~~Review the steering council documentation, https://scitools.org.uk/organisation.html#organisation-top~~
- [ ] The use of **OVERRIDE_TEST_DATA_REPOSITORY** is cited in the composed docs but not in the [iris.config](https://scitools-iris.readthedocs.io/en/latest/_modules/iris/config.html?highlight=OVERRIDE_TEST_DATA_REPOSITORY) docstrings.  Perhaps it should
- [x] Update the [release steps for maintainers](https://scitools-iris.readthedocs.io/en/latest/developers_guide/release.html#post-release-steps) to include a tweet announcement.
- [x] Review the Iris wiki on github (https://github.com/SciTools/iris/wiki).  This has recently been **disabled** so the link no longer works.  The content includes out of date info and some old release notes documentation.
- [x] #3885. Include a reference for [WSL ](https://docs.microsoft.com/en-us/windows/wsl/install-win10)on the [installing Iris ](https://scitools-iris.readthedocs.io/en/latest/installing.html) page.  Useful for users/devs who only have Windows 10, and it works great in my experience.

### Ideas

&#x2612; ~~Add a section for a **FAQ**: Too much upkeep and not enough use-case~~
&#x2612; ~~Use asciinema to capture some guides.  Example for a user on singularity, see https://asciinema.org/~vs~~
- [x] Add a section for "**Why Iris?**"
- [x] Add a **Glossary**
- [x] Consider adding more [badges ](https://shields.io/) to the [README](https://github.com/SciTools/iris/blob/master/README.md) or the docs themselves, where appropriate.

### Sphinx extensions

- [x] Consider using if appropriate, https://github.com/djungelorm/sphinx-tabs?  **This is redundant as sphinx-panels supports this too.**
- [x] #3884.  Consider using if appropriate, https://sphinx-panels.readthedocs.io/en/latest/

**Comment by trexfeathers** [comment]
> Include a reference for WSL on the installing Iris page. Useful for users/devs who only have Windows 10, and it works great in my experience.

I'd appreciate this. Haven't investigated fully yet but it appears that a Windows-Conda install can no longer build docs since `common.metadata` was added.

**Comment by tkknight** [comment]
I will draft a small PR for the WSL thing - I'm thinking just a one liner (or maybe a note)  and use the link I gave in the issue overview

**Comment by trexfeathers** [comment]
@ESadek-MO could we close this and split any remaining work into independent issues?

**Comment by ESadek-MO** [comment]
I had created changes citing OVERRIDE_TEST_DATA_REPOSITORY in config.py, but on further thought I feel it's no longer appropriate; it's mentioned lower down in the config, albeit slightly vaguely, but I believe that's sufficent.
