### ISSUE TITLE
"Get Help" option in issue creation

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#3905]
## 📰 Custom Issue

In the process of opening My First Issue over at `dask`, I noticed they have a "General Question" option in their issue choices (which in their case takes you to StackOverflow).
https://github.com/dask/dask/issues/new/choose

This seems like a good idea, so maybe we should copy it.

**Comment by tkknight** [comment]
I notice this **General Question** template type on some github projects when I was exploring options for the Issue templates.  I think we should have something like this but perhaps we need to finalise where it should link to first, #3860

**Comment by trexfeathers** [comment]
We now encourage people to visit the [`Q&A` section of Discussions](https://github.com/SciTools/iris/discussions/categories/q-a).
