### ISSUE TITLE
error in cube._intersect_modulus due to processing accuracy

### ISSUE THREAD

**Issue by BenMGeo** [SciTools/iris#3907]
## 🐛 Bug Report
I currently ran into an error in iris 2.4 `cube._intersect_modulus` and this might also be an issue for the new version 3.1 (though I did not test it yet)

The respective lines are:
https://github.com/SciTools/iris/blob/077df3ec15530255df80c2fc330eb21998e24769/lib/iris/cube.py#L3094-L3098

Version 2.4:
https://github.com/SciTools/iris/blob/08827854a0de2e73ad4b9fdfedc2e141775a2bc9/lib/iris/cube.py#L2571-L2573

I have a dataset with 0.1 degree longitude interval and symmetric bounds that is circular and want to intersect the longitude's range [-10, 35]. When hitting the bound checks, the error is produced.

While `values.max()` gives 359.95,`values.min()` gives -0.05 and `modulus` gives 360, the calculation of `values.min() + modulus` gives 359.94999999999.... < 359.95 which returns a true value for the case, which it should not.

Thus, the intersection fails.
I suggest the following add-on to the logical statement:
`and not np.isclose(values.max(), values.min() + modulus)`

## Environment 
 - Ubuntu 20.04
 - Iris Version: 2.4
 - Python 3.8
 - for use in ESMValTool diagnostic (https://github.com/ESMValGroup/ESMValTool/tree/master)

**Comment by stephenworsley** [comment]
Thanks for the input. I think your proposed solution is probably correct, though I'd want make sure these cases wouldn't cause anything to break later on in the code. With that said, I think this particular case may be due to adding floats of different type. Note:
```
>>> np.float32(-0.05) + 360 == np.float32(359.95)
False
>>> np.float64(-0.05) + 360 == np.float64(359.95)
True
>>> np.float32(-0.05) + np.float32(360) == np.float32(359.95)
True
```
If for some reason this inequality absolutely needs to be precise, it may need to handle types of precision more carefully.

**Comment by BenMGeo** [comment]
I checked the types and yes, you are correct. values.min() and values.max() are float32 and modulus is float.

Maybe a typecasting would be sufficient as well.

**Comment by BenMGeo** [comment]
I just got the hint over at ESMValTool, that this seems to be the same issue as #3391.

**Comment by rcomer** [comment]
Having recently dived into this method, I suspect the purpose of this check is that you don't end up with more than one cell mapping to the same when you do `iris.analysis.cartography.wrap_lons(values, minimum, modulus)`.  If that is the case, when using points, it should probably check for equality.  How about something like
```python
np.any(values.max(axis=0) - values.min(axis=0) >= modulus)
```
?

**Comment by BenMGeo** [comment]
I think that would not change the behavior f the test.

With the values of the example above, this would still need a typecasting to make sure that the values are equal. 
(I assume the `axis` is now in play because there are now nonregular grids?)

Having `modulus` cast to the same type as the values, it should be fine, I assume.

**Comment by rcomer** [comment]
With the `axis` keyword, all the lower bounds (`bounds[:,0]` if the coord is increasing) are compared separately from all the upper bounds (`bounds[:1]`).  The existing test uses the flattened array. For a coordinate that spans 360 degrees, we might expect `bounds[0, 0] + modulus == bounds[-1, 1]`, which then triggers the current error if there are accuracy issues, as you say.  If we check upper and lower bounds separately, I think `maximum - minimum` should be no larger than `modulus - bound_width`.

**Comment by BenMGeo** [comment]
Sounds good to me. The question is, if casting is less effort, but that's up to you experts ;)

**Comment by rcomer** [comment]
> Having recently dived into this method, I suspect the purpose of this check is that you don't want more than one cell mapping to the same when you do `iris.analysis.cartography.wrap_lons(values, minimum, modulus)`. If that is the case, when using points, it should probably check for equality. How about something like
> 
> ```python
> np.any(values.max(axis=0) - values.min(axis=0) >= modulus)
> ```
> 
> ?

I made a branch to try with the above change, and it broke two existing tests:
https://github.com/SciTools/iris/blob/323d2a19783f058d29bf3edcec9154a4e15b4d36/lib/iris/tests/unit/cube/test_Cube.py#L1507-L1527

It seems it is deliberate that we handle the case where `points.max() == points.min() + modulus`.

**Comment by stephenworsley** [comment]
Having taken another look at the code that would run after this check, it seems as though it's written to be lenient in most points. In particular, I'd say any leniency here should not be more lenient than these lines: https://github.com/SciTools/iris/blob/732800d39d55ae692cd095937b1dd7d3ed401015/lib/iris/cube.py#L2867-L2870
It's difficult to say there wouldn't be some odd edge case if we allowed this to be more lenient, but I'd say there's still a case for something like `and not np.isclose(values.max(), values.min() + modulus)` like originally suggested.

**Comment by ESadek-MO** [comment]
Has this been tested since v3.0 and been found to definitely still be an issue? @BenMGeo

**Comment by BenMGeo** [comment]
Unfortunately, I switched fields and am currently not actively working with this.

**Comment by bjlittle** [comment]
Discussed at the @SciTools/peloton, and we agreed to close this issue.

@BenMGeo Thanks for the discussion, but if anyone from the community cares about this issue please reopen or ping us to discuss further.

Thanks 👍
