### ISSUE TITLE
ESMValCore and ESMValTool switch to iris3

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#3908]
Hey guys, just to keep you updated we are currently testing the switch to the shiny new `iris3` in both ESMValCore and ESMValTool, and thought we'd have an issue here keep track of this test work; we have started the tests in ESMValCore in https://github.com/ESMValGroup/ESMValCore/pull/819 and there are lots of good news about it - a few functions have had to be changed but with those changes the comprehensive GA tests pass well (see the issue description); we'll start the same in ESMValTool, and I'll update this issue :beer: Also, feel free to close this if you consider it clutter :+1:

**Comment by valeriupredoi** [comment]
cool, cheers for the feedback Bill! we're zeroing-in and have started looking at ESMValTool too in https://github.com/ESMValGroup/ESMValTool/issues/1862 :+1: :beer: When are you guys thinking of moving the rc to a stable release and put it on conda-forge and PyPi?

**Comment by bjlittle** [comment]
@valeriupredoi Simply check the associated GitHub [v3.0.0 Milestone](https://github.com/SciTools/iris/milestone/37) for the release - we're trying to honour the date mentioned there.

At the moment, we're aiming for mid-November, week commencing 9 Nov 2020 :+1: 

Do you guys have a release roadmap you can easily point me at for ESMValTool?

**Comment by bouweandela** [comment]
Our release schedule lives here: https://docs.esmvaltool.org/en/latest/community/release_strategy.html#upcoming-releases

**Comment by bouweandela** [comment]
@SciTools/iris-devs Is there any news on when iris 3 will be released? The feature freeze for the v2.2 release of ESMValCore, the framework that runs the scientific recipes provided by the ESMValTool, is February 1 and the release is planned one week later. We have preliminary support for iris 3 implemented in https://github.com/ESMValGroup/ESMValCore/pull/819 based on the release candidate, but time for still including this is starting to run out. The next release after that is planned for June.

**Comment by trexfeathers** [comment]
Hi @bouweandela, I believe the finishing touches are going in this weekend, so there should be news (hopefully good) early next week 🤞

**Comment by bouweandela** [comment]
Just saw the release on Conda! :partying_face:

**Comment by bjlittle** [comment]
@bouweandela I hope it's been worth waiting for :wink: 

Iris 3.0 has been released and is now available on conda-forge. Hopefully just in time to make your pending release of ESMValTool

**Comment by bjlittle** [comment]
@valeriupredoi I'm going to close this issue now.

If you object, then we can reopen it, or create another separate issue for `iris` 3.1.0
