### ISSUE TITLE
Make the "io picker" work with file-format extension packages

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3918]
## ✨ Feature Request
Enable optional file-formats, provided as extension packages, to modify the Iris process of "identify a file type and invoke the correct loader" 

## Motivation
So Iris can load unstructured data automatically, if iris-ugrid is available, as it does for iris-grib.
But also, because the "io picker" code still includes (minimal) support code for optional formats (GRID, and to-be UGRID), which should really be coded entirely in the extension packages.

## Additional context
Grib-specific support remains in core Iris [here](https://github.com/SciTools/iris/blob/v3.0.0rc0/lib/iris/fileformats/__init__.py#L65-L90)
We would like to tidy that, and to add UGRID support in a similar way, so we need to fix that.

Notes : 
  1. we also need to invent some way of controlling relative picker priorities, which can work when we no longer have a simple static list of available format handlers.
  2. 'ugrid' support needs to overlay the standard netcdf file-pickers.  When no mesh is found in the file, this should behave exactly as it did before.

**Comment by trexfeathers** [comment]
The main driver of this (UGRID integration) has been superseded by alternative concepts, so closing. Can exhume if needed.
