### ISSUE TITLE
References to CF Version support by netCDF loaders

### ISSUE THREAD

**Issue by jonseddon** [SciTools/iris#3926]
## 📚 Documentation
#3925 updates documentation to reflect the CF version now used when saving netCDF files. While checking that I'd not missed any other locations in the documentation where this was referenced I found that the CF version used by the loader was mentioned in two docstrings:

* The module level docstring at the top of `lib/iris/fileformats/netcdf.py` (Version 1.4, 27 February 2009)

* The module level docstring in `lib/iris/fileformats/cf.py` (Version 1.5, October, 2010)

I don't know how the netCDF loader works. Are these two docstrings correct? If they need updating then I can easily add this to #3925. The reference for CF1.7 will be: Version 1.7, 10 August 2017.

**Comment by lbdreyer** [comment]
Thanks for this @jonseddon !

The docstrings you mention are both out of date as we now handle loading CF 1.7 netCDF files. I'd be tempted to just remove the specific version altogether, so for example just have 
```
[CF]  NetCDF Climate and Forecast (CF) Metadata conventions.
[NUG] NetCDF User's Guide, https://www.unidata.ucar.edu/software/netcdf/docs/
```
After all we haven't pinned down the netcdf version. And I want to avoid having multiple places to update, everytime we update to a new CF version

**Comment by lbdreyer** [comment]
Not sure why this didn't close automatically despite the two being linked, but #3925 was merged so this can now be closed
