### ISSUE TITLE
Warning when importing Iris

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/iris#3937]
Hi,
the simple command

    import iris

in python leads to

   /home/ubuntu/.local/lib/python3.6/site-packages/iris/config.py:73: UserWarning: Ignoring config item 'Resources':'test_data_dir' (section:option) as '/home/h05/itwl/projects/git/iris-test-data/test_data' is not a valid directory path.
  warnings.warn(msg.format(section, option, c_path)) 

What is this?

OS: Ubuntu 18.04
Python 3.6.9

**Comment by trexfeathers** [comment]
Hi @MHBalsmeier. This suggests an Iris installation from a branch/fork other than `master`. Following any of the instructions in [Installing Iris](https://scitools-iris.readthedocs.io/en/latest/installing.html) should definitely avoid this warning (same for the less recommended `pip install scitools-iris`). How did you install your copy of Iris?

**Comment by MHBalsmeier** [comment]
I did not want to use conda for various reasons, and it took me very long until I finally managed to sucessfully install iris. I  wrote down all the steps that got me there in a gist:

https://gist.github.com/MHBalsmeier/a586426026aaee186edfbf1995018a2c

I applied this on various Ubuntu 20 machines / VMs and it worked fine, now I had to install it on a Ubuntu 18 machine and the warning came.

**Comment by trexfeathers** [comment]
Thanks for the detail @MHBalsmeier. From your description I'm at a loss to explain how this has happened, but here's the fix anyway:

If you open `/home/ubuntu/.local/lib/python3.6/site-packages/iris/etc/site.cfg`, I expect you will find this line, which is referencing someone else's local file:

```
test_data_dir = /home/h05/itwl/projects/git/iris-test-data/test_data
```

**If you _don't_ need to run any of Iris' test that require iris-test-data** (I'm guessing so from [your gist](https://gist.github.com/MHBalsmeier/a586426026aaee186edfbf1995018a2c)):
    Just delete the offending line.

**If you _do_ need to use iris-test-data**:
    Follow the recommended steps under [Running the tests](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_running_tests.html?highlight=iris-test-data#running-the-tests).

**Comment by MHBalsmeier** [comment]
Thanks, this worked.

You mentioned that `pip install scitools-iris` is not recommended. As you see in my gist, I am doing `pip install --user scitools-iris` as well as later `python setup.py build`. Is the pip install unnecessary?

**Comment by trexfeathers** [comment]
>Is the pip install unnecessary?

I _think_ so. My main uncertainty is how `pip` or `setup.py` handle dependencies; they both have access to the necessary dependency information (the individual `.txt` files in the [`requirements/`](https://github.com/SciTools/iris/tree/master/requirements) directory), but I can't be sure if `pip` is doing anything extra beyond what `setup.py` does. I suggest trying a fresh install without the `pip` step, and see if the core dependencies (see directory linked above) get installed anyway.

**Comment by trexfeathers** [comment]
... of course for your use case the dependency management is handled anyway so I think you're safe to only use `setup.py`.

**Comment by MHBalsmeier** [comment]
Okay, thanks, I'll try this next time.
