### ISSUE TITLE
Import Iris Issue?

### ISSUE THREAD

**Issue by Veganveins** [SciTools/iris#3938]
## 📰 Custom Issue
Hi There, 

I installed `iris` using `conda install -c conda-forge iris` as directed [here](https://scitools.org.uk/iris/docs/latest/installing.html). And I confirmed that I was able to import the package in a test.py file. 

The issue I am seeing is specifically in iPython--if I try to run my code in iPython I can't seem to import the package without getting an error of "Ambiguous 'iris' package"
![image](https://user-images.githubusercontent.com/16780529/102547258-efecc900-4086-11eb-862f-0d0170846a30.png)

But I don't think the issue is that "i don't have iris installed" because if I create a .py file with one simple line `import iris` I am able to run that file at the command line `python test.py` without any errors. Furthermore I can do things like iris.load() and iris.util.squeeze() from the _python file_, but apparently not from iPython (nor can I get it to import from a jupyter notebook.

Here's an example of what it looks like if I try the import using python (it works) 

![image](https://user-images.githubusercontent.com/16780529/102547876-d4ce8900-4087-11eb-9fcb-0385df125ba1.png)

Anyone have any guesses on what the problem could be, ie why the import works in python but not iPython or a jupyter notebook?? I feel like I'm probably just doing something dumb but for the life of me I can't figure it out...

**Comment by rcomer** [comment]
This really is only a guess as I’ve never seen that error before: is your `ipython` separate from your conda environment?

From your `(base)` command prompt, I guess you have conda activated.  So if you do

`which python `

you should get the path to your conda installation.  If you do

`which ipython`

do you get something else?

**Comment by Veganveins** [comment]
Hi @rcomer ,

Thank you so much for getting back to me-- in fact I do seem to have separate environments, great call!

![image](https://user-images.githubusercontent.com/16780529/102630582-b8c7f780-411a-11eb-883d-b619a008785f.png)

...Any hints on how I could activate the conda environment within iPython?

**Comment by rcomer** [comment]
I’m something of a `conda` novice myself, but I would try adding `ipython` to the conda environment:

`conda install ipython`

then, when `conda` is activated, you automatically use this new copy of `ipython`.

**Comment by Veganveins** [comment]
THAT WORKED!!

Ruth thank you so much ❤️❤️

I know it was a silly question but can't tell you how much I appreciate the help :)

**Comment by rcomer** [comment]
Great - glad it worked!

**Comment by rcomer** [comment]
I’ll close this as resolved.
