### ISSUE TITLE
Installing Iris without Conda on Ubuntu is VERY difficult.

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/iris#3949]
Hi,

I found it very difficult to install Iris without Conda on Ubuntu. I finally wrote down a way that worked for me in a [Gist.](https://gist.github.com/MHBalsmeier/a586426026aaee186edfbf1995018a2c)

Even this still leads to warnings when importing. I know some students who wanted to install and use iris, but couldn't get it done, so left it.

Maybe there should be some clearer instructions for how to install Iris without Conda.

**Comment by trexfeathers** [comment]
Hi @MHBalsmeier

This is a subject that has received a lot of attention but unfortunately there are no easy solutions for those who can't use `conda`. This is mainly due to dependency availability via `conda` vs `pip`. Some more detail is available in #3716 and #3777.

Thanks for your Gist. @SciTools/iris-devs what do we think about providing explicit guidance for a non-conda Iris install?

**Comment by MHBalsmeier** [comment]
Well I could also provide some more specific installation instructions in the requirements directory. The main problems are that pyke is not installable via pip and that udunits2 and some other linux packages need to be installed before actually being able to install the required python packages. This is not clearly mentioned in the *.txt files in the requirements folder. I am also still unsure wether apt-get install udunits-bin libudunits2-dev is enough or wether one has to install udunits2 manually, but this is another topic.

**Comment by jvegasbsc** [comment]
`Pyke` is no longer mantained and under MIT license. Maybe we can consider to create a fork that we can upload to PyPi, with the explicit notice that it will not be maintained?

**Comment by MHBalsmeier** [comment]
This would be helpful I think.

**Comment by bouweandela** [comment]
> @SciTools/iris-devs what do we think about providing explicit guidance for a non-conda Iris install?

For the ESMValTool project, where we have a conda environment containing many packages for working with climate data in addition to iris, installing packages from conda can be really slow and require a lot of memory. Some days it takes an hour and 10 GB of RAM just to solve the environment, which does not make for a very good first experience with our tool for new users. It would be really great if we could offer users an alternative, so I would be in favor of making the instructions on how to do this clearly visible.

**Comment by trexfeathers** [comment]
>Pyke is no longer mantained and under MIT license. Maybe we can consider to create a fork that we can upload to PyPi, with the explicit notice that it will not be maintained?

https://pypi.org/project/scitools-pyke/

**Comment by MHBalsmeier** [comment]
Ah didn't know pyke is on pypi. Then, this

    sudo apt-get install udunits-bin libudunits2-dev libproj-dev proj-bin libgeos-dev libcunit1-dev python3-pip python3-tk
    pip3 install numpy astropy tqdm oktopus bs4 setuptools nc_time_axis cython cfunits cf-units cftime cf-python dask[array] netcdf4 pandas stratify pyugrid scitools-pyke blackfilelock imagehash nose pre-commit asv scitools-iris

should be enough to install iris from scratch (at least on Ubuntu).

**Comment by trexfeathers** [comment]
@MHBalsmeier you have a good understanding of non-Conda Iris installation - certainly better than mine. Being an open-source package, we love it when our users contribute to Iris; would you be happy to submit an addition section for the **[Installing Iris](https://github.com/SciTools/iris/blob/master/docs/iris/src/installing.rst)** page? I'd be happy to review and merge this.

I suggest the guidance should include a note that the underlying packages are liable to change, so any guidance could become out of date without warning. Including a date stamp would be a good idea for this same reason.

[Contributing to the documentation](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_documentation.html)

**Comment by MHBalsmeier** [comment]
Sure, I'll do that.

**Comment by bjlittle** [comment]
Closed by #3958
