### ISSUE TITLE
Google search still gives the old documentation as one of top search results

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#3979]
## 📰 Custom Issue

Hey guys, just heads up that the old 2.x documentation links still pop up in Google searches in top three results, and could even be the top result (see eg "quickplot" where the actual working link is fourth or fifth result). Not an issue perse but rather a heads up just so you are aware of this, you may get questions from people not finding what they're looking for :+1: 

![google-iris](https://user-images.githubusercontent.com/28983971/106898840-969b3080-66ec-11eb-8e8e-22252d7f80f9.png)
![quickplot-search](https://user-images.githubusercontent.com/28983971/106898856-9ac74e00-66ec-11eb-8ef7-58b24464a939.png)

**Comment by bjlittle** [comment]
@valeriupredoi I'm going to close this issue, thanks for letting us know.

This trend will change over time, and customising your google searches to between the period `01 Jan 2021` to `14 May 2021` gives:
![Screenshot from 2021-05-14 02-21-15](https://user-images.githubusercontent.com/2051656/118206858-4bb35680-b45b-11eb-9ae3-82391fedf660.png)
![Screenshot from 2021-05-14 02-22-02](https://user-images.githubusercontent.com/2051656/118206919-71d8f680-b45b-11eb-88e5-c7660337e766.png)
