### ISSUE TITLE
PP saving soil depths incorrectly setting LBLEV=0

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#4082]
## Expected behaviour

[PP saving `Single depth level (soil depth)`](https://github.com/SciTools/iris/blob/3fec756c6107ea71e64e0fe7a07882f8dbde3071/lib/iris/fileformats/pp_save_rules.py#L743-L758) should be setting `pp.lblev` correctly per level, rather than the current default of `0`.

## Environment 
 - Iris Version: known for `v2.3` onwards, but likely historic too

**Comment by ESadek-MO** [comment]
Related to #3820

**Comment by ESadek-MO** [comment]
So, after a bit of digging it seems `pp.lblev` can't be calculated within the `_vertical_rules`. There is the potential that there might be identifiers after this stage which would allow `pp.lblev` to be set, but I'm yet to find a straightforward solution to this.

**Comment by ESadek-MO** [comment]
@SciTools/peloton think that the solution to this is to include workarounds for this in the Further Topics documentation.
