### ISSUE TITLE
Implement OR for Iris ConstraintCombinations

### ISSUE THREAD

**Issue by jamesp** [SciTools/iris#4091]
## ✨ Feature Request
Implement the OR operator for Constraints

## Motivation
Constraints can be combined to give a `ConstraintCombination` object.  Only the `__and__` operation has been implemented (i.e. `c1 & c2`), it would be useful to create a combination of `c1 | c2`.

**Comment by rcomer** [comment]
[Interesting](https://stackoverflow.com/questions/45412581/combine-iris-constraints-with-or), though I've long since forgotten what I wanted to do with them!

**Comment by jamesp** [comment]
Interesting discussion, thanks for the link @rcomer.  I can see the argument both ways on this one.
