### ISSUE TITLE
Linkcheck failures

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4103]
## 📰 Custom Issue

Two link checks seem to be consistently failing across PRs.

* http://matthew-brett.github.com/pydagogue/gh_delete_master.html
  Looks like there is a straight substitution for this: https://matthew-brett.github.io/pydagogue/gh_delete_master.html
* https://readthedocs.org/dashboard/scitools-iris/version/v3.0.0rc0/
   No idea what to do about this one 🙁

**Comment by tkknight** [comment]
I will pick this up.  Think the second link should be https://readthedocs.org/dashboard/scitools-iris/version/v3.0.0rc0/edit/ (note the `edit` added to the end).  Note you also need to be logged in to view this edit page.  Will look to update the `release.rst` page to be clearer.

**Comment by tkknight** [comment]
The linkcheck is now passing but the standard tests are timing out on cirrus-ci.  Will wait and retry the CI tests tomorrow.
