### ISSUE TITLE
Gallery: wind plot missing lake features

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4110]
## 📚 Documentation

The [Plotting Wind Direction Using Quiver](https://scitools-iris.readthedocs.io/en/stable/generated/gallery/meteorology/plot_wind_speed.html) example uses NaturalEarth to add lake outlines.  But those outlines don't actually show up in the displayed plots.  It looks like they disappeared at Iris 2.1:

* [Iris 2.0 version](https://scitools.org.uk/iris/docs/v2.0/examples/Meteorology/wind_speed.html)
* [Iris 2.1 version](https://scitools.org.uk/iris/docs/v2.1/examples/Meteorology/wind_speed.html)

**Comment by rcomer** [comment]
`grep` confirms that this is the only example that uses `cartopy.feature`

**Comment by rcomer** [comment]
Running this example locally:

* I do not get the lake outlines with Iris3.0.1 (default-next).
* I do get the lake outlines with my `iris-dev` environment, which still has Cartopy 0.18.  Also the doctest fails.

**Comment by rcomer** [comment]
There were some changes to edgecolor handling for Matplotlib v3.4: https://matplotlib.org/stable/users/whats_new.html#collection-color-specification-and-mapping

So I think the gallery example is fixed, but we need to update the reference imagehash.

**Comment by jamesp** [comment]
@rcomer agree, editing the gallery test file I see the same.  the outlines are in my dev version, if I comment out `ax.add_feature(lakes)` the test will pass. 

Agree the thing to do here is add the new image hash.
