### ISSUE TITLE
Ability to specify grid_mapping name

### ISSUE THREAD

**Issue by bsherratt** [SciTools/iris#4122]
## ✨ Feature Request
When saving a netCDF file, it would be helpful to have an option to choose the names used for ["grid mapping variables"](http://cfconventions.org/cf-conventions/cf-conventions.html#grid-mappings-and-projections) - the dummy variables used to hold parameters for coordinate reference systems.

## Motivation
I have to provide data for a system that *appears* to be strangely specific about things like this.

In fact, the final product may not be so picky, but its specification does strongly imply that a specific `grid_mapping` must be used. And of course there's a simple enough workaround, to save the files as usual then tweak them with `netCDF4`.

Whether or not it's required on this particular occasion, it's possible that there may be some future need for it. It strikes me as very similar to choosing the `_FillValue`, which Iris *does* expose as an option.

## Additional context
If I've interpreted the CF conventions correctly:
- Every variable and dimension may have a `grid_mapping` attribute, which should be the name of another variable in the file (a "grid mapping variable")
- A grid mapping variable has no data, only a `grid_mapping_name` attribute and various attributes as required by the CRS to define it
- The actual name used for the grid mapping variable is irrelevant, as long as it's consistent. Iris chooses it to be the same as the `grid_mapping_name`.

@stephenworsley has suggested that the cleanest way of implementing this would be to add a `CoordSystem.var_name` attribute, in line with `Cube.var_name` and `Coord.var_name`. This would also allow a slightly more consistent round-trip when loading and re-saving netCDF files, by simply setting that attribute according to whatever is found in the file.

**Comment by bjlittle** [comment]
@bsherratt Thanks for taking the time to raise this. We've briefly discussed this and we feel that we'd like to discuss this more openly, so I'm going to covert this issue to a GitHub Discussion... and we can take it from there.

Thanks again :beers:
