### ISSUE TITLE
Coordinate description can't be extracted as formatted date-time

### ISSUE THREAD

**Issue by alastair-gemmell** [SciTools/iris#4177]
Submitted on behalf of an Iris user who isn't on GitHub:​

The code for generating this this string:

`DimCoord([2020-08-13 00:00:00], standard_name='time', calendar='gregorian', long_name='time', var_name='time')`

... is a complex combination of cf_units and numpy, and there is no public API for just getting `2020-08-13 00:00:00` alone. 

It is possible to generate the string using your own code:

```
coord = cube.coord('time')
dt = coord.units.num2date(coord.points[i])
desired_string = str(dt)
```

...but it would be more useful if there was a public API for doing it.

**Comment by rcomer** [comment]
I just realised you can also do

```python
coord = cube.coord('time')
desired_string = str(coord.cell(i))
```

**Comment by trexfeathers** [comment]
That's cool, I haven't come across `coord.cell()` before. This still looks like a candidate for a convenience function, you've just made it easier to write!

**Comment by rcomer** [comment]
Avoiding `num2date` has the advantage that you can still get something if the coord is not a time coord.  Using `num2date` could give you more flexibility to format the string how you like via the `datetime.strftime` method.

**Comment by trexfeathers** [comment]
We've discussed this during a @SciTools/peloton meeting, and decided that having this level of convenience would actually make Iris *less* helpful, as there would be so many convenience functions as to make Iris' API unreadable.

Therefore closing.
