### ISSUE TITLE
Running local tests: is nox the best way?

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4189]
## 📰 Custom Issue

If you follow the developer's installation instructions, it [tells you to check your environment](https://scitools-iris.readthedocs.io/en/latest/installing.html#running-the-tests) by running `python setup.py test`, with a link to the main testing page.  But the [main testing page](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_running_tests.html#developer-running-tests) tells you that `setup.py test` is deprecated and to use `nox` instead.  `nox` makes its own environments though, so it isn't going to help you test the environment you just installed.

When the developers' guide was revamped last year, I _really liked_ that it essentially said "here is a yml file that lets you easily make an environment that contains everything you need for testing".  The guidance to use `nox` seems a bit orthogonal to that approach.

If I've understood, `nox` is something of a black box that will only run the pre-determined sets of tests.  If I do get a test failure, I'd like to investigate it by e.g. poking at objects in an interactive python session, or re-running individual tests.  It's not clear to me if and how I can do that with `nox`'s environments.

I did have my first go at running the tests under `nox` yesterday.  They seemed to run OK, but I got these errors after each session:
<details>
<summary>nox errors</summary>

```
Traceback (most recent call last):
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/managers.py", line 597, in _run_server
    server.serve_forever()
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/managers.py", line 173, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "[git-path]/iris/.nox/tests-3-7/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfsc00002070b44262400000291'
```
</details>

All of this makes me think we should still be advertising a non-deprecated way to run the tests in a user-controlled environment.  #3835 listed a few ways:

* `python -m iris.tests.runner --default-tests`
* `python -m unittest discover iris`

Then there's also `pytest` (though I just tried pointing `pytest` at the iris tests in a clean branch and got 6 failures/errors :cry: ).  Obviously experienced devs may have their own preferred way to do it, but I think we should advertise something straightforward that newbie devs can just run.

**Comment by trexfeathers** [comment]
I don't disagree; it's important to be able to run subsets of tests on an ad-hoc basis, and I expect I've been personally spoiled by PyCharm so I'm ignorant of many problems in this area.

But I'd also like to note that I love having a common entry point for developers and the CI - you can run locally exactly what the CI runs, in theory reducing nasty surprises when pushing PR's.

**Comment by rcomer** [comment]
> I love that Nox gives a common entry point for developers and the CI

Oh yeah, I'm not saying we should remove the `nox` guidance.  But at the moment the guide reads to me like `nox` is the only recommended way to do it.
