### ISSUE TITLE
Trial GitHub Actions vs Cirrus CI

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#4191]
## 📰 Custom Issue

@ocefpaf has correctly pointed out (https://github.com/SciTools/cf-units/pull/175, https://github.com/SciTools/nc-time-axis/pull/66) that GHA is the most popular CI implementation for scientific Python projects. Given that barriers to involvement are a big factor in the health of a project: we need a **really good** reason to go against the crowd as we do now using Cirrus CI.

I believe our reasons for using Cirrus are to minimise the runtime for a full CI run. **We should therefore do a trial to see if it possible to get similar/faster runtime using GHA instead.** I'm told that GHA also has caching solutions like Cirrus does, and the minutes are free for public repositories so there should be no trouble with parallelism.

**Comment by trexfeathers** [comment]
I probably shouldn't have been so quick to shoot down @jamesp's idea on https://github.com/SciTools/iris-grib/issues/242!

**Comment by rcomer** [comment]
Cartopy went to GHA in December https://github.com/SciTools/cartopy/pull/1691
