### ISSUE TITLE
pre-commit, black and isort

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4226]
## 📰 Custom Issue

When committing a change to a local branch, `black` and `isort` now tell you which files need fixing, but don't go ahead and fix them.  Is this intentional?  I think they were changed to do a `--check` at #4181, which makes sense within the context of the CI, but it's not obviously so helpful when committing a change.

In order to commit my change, I installed `black` and `isort` to run them directly.  I looked in [.pre-commit-config.yaml](https://github.com/SciTools/iris/blob/main/.pre-commit-config.yaml) to find out what versions I needed.  `conda` couldn't seem to find the specified `black` version, so installed that with `pip` instead.  This all feels unnecessarily complicated - is there a simpler way to install the right versions of these tools?

**Comment by trexfeathers** [comment]
It was deliberate to do this, I believe for consistent behaviour - not all the three have an option to fix problems for the user. Is that right, @bjlittle?

No solution is perfect. We were previously maintaining Black versions in multiple places, which on occasion have diverged and caused awful confusion when pushing changes.

@rcomer your experience is the lesser of the various evils, IMHO - it was difficult, but nothing was happening 'invisibly'. But if you disagree / have suggestions: I'm sure we'd all love to improve the situation!

**Comment by rcomer** [comment]
> not all the three have an option to fix problems for the user

`flake8` does tell you what's wrong with the files though, so you can go ahead and fix them manually.  I can't see a way to fix the `black` and `isort` issues without installing those tools (I may well be missing something).  If I happen to install the wrong versions*, then I may be back to

> awful confusion when pushing changes

If we could make `black` and `isort` apply changes on commit, then probably the contributor never needs to install these.

*or worse, _not_ install `isort` and pick up a centrally installed ancient version 😬🤦‍♀️

**Comment by trexfeathers** [comment]
>If we could make `black` and `isort` apply changes on commit, then probably the contributor never needs to install these.

A valid counter-argument. I could be convinced either way TBH!

**Comment by bjlittle** [comment]
@rcomer I think this is now `isort`ed, see #4235 :rofl:
