### ISSUE TITLE
```Coord.is_contiguous()``` assumes too much

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#423]
The `is_contiguous` method assumes that the lower bound is in index `0`, but when you reverse a coordinate, it is usually in index `1`. Because of this:

```
>>> from iris.coords import DimCoord
>>> c = DimCoord(tuple(range(10)), 'latitude')
>>> c.is_contiguous()
False
>>> c.guess_bounds()
>>> c.is_contiguous()
True
>>> c[::-1].is_contiguous()
False
>>> c[::-1].bounds         
array([[ 8.5,  9.5],
       [ 7.5,  8.5],
       [ 6.5,  7.5],
       [ 5.5,  6.5],
       [ 4.5,  5.5],
       [ 3.5,  4.5],
       [ 2.5,  3.5],
       [ 1.5,  2.5],
       [ 0.5,  1.5],
       [-0.5,  0.5]])
```

**Comment by jkettleb** [comment]
Thanks for pointing me to this @ajdawson.  Of @pelson 's three suggestions - the last seems to make the most sense to me (based on a guess is that fixing the assumption that the first bound is the lower one is much more 'non-local' in the code base than modifying the step=-1 indexing).

**Comment by pelson** [comment]
The conventions are pretty good here, and even define the contiguous concept:

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#cell-boundaries
