### ISSUE TITLE
Misleading docs for iris.fileformats.pp.save

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#425]
The docs for iris.fileformats.pp.save (http://www.scitools.org.uk/iris/docs/latest/iris/iris/fileformats/pp.html?highlight=save%20cube#iris.fileformats.pp.save) should be updated to reflect iris.save being the preferred method of saving data into a cube. 

Further, the docs should be updated to state that 'cube' may only be a single cube &ndash; passing a iris.cube.CubeList or list of cubes causes iris.fileformats.pp.save to exit with an error:

```
>>> import iris.fileformats.pp as ipp
>>> type(cubelist)
<class 'iris.cube.CubeList'>
>>> ipp.save(cubelist, '/filepath/cubes.pp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/../iris/lib/iris/fileformats/pp.py", line 1598, in save
    n_dims = len(cube.shape)
AttributeError: 'CubeList' object has no attribute 'shape'
```

And again:

```
>>> ipp.save([cubelist[0], cubelist[1]], '/filepath/cubes.pp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/../iris/lib/iris/fileformats/pp.py", line 1598, in save
    n_dims = len(cube.shape)
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by jonnyhtw** [comment]
Hi there

Has there been a solution to this?

I am currently unable to save my `iris.cube.CubeList` to a NetCDF file using Iris version 2.1.0 ...

```
>>> type(all_cubes)

iris.cube.CubeList

>>> iris.save(all_cubes,outdir+'foo.pp')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-5a29685d3771> in <module>()
----> 1 iris.save(all_cubes,outdir+'foo.pp')

/nesi/nobackup/niwa00013/williamsjh/miniconda2/envs/master/lib/python2.7/site-packages/iris/io/__init__.pyc in save(source, target, saver, **kwargs)
    425                 if i != 0:
    426                     kwargs['append'] = True
--> 427                 saver(cube, target, **kwargs)
    428         # Netcdf saver.
    429         else:

/nesi/nobackup/niwa00013/williamsjh/miniconda2/envs/master/lib/python2.7/site-packages/iris/fileformats/pp.pyc in save(cube, target, append, field_coords)
   1986     """
   1987     fields = as_fields(cube, field_coords, target)
-> 1988     save_fields(fields, target, append=append)
   1989 
   1990 

/nesi/nobackup/niwa00013/williamsjh/miniconda2/envs/master/lib/python2.7/site-packages/iris/fileformats/pp.pyc in save_fields(fields, target, append)
   2189     try:
   2190         # Save each field
-> 2191         for pp_field in fields:
   2192             # Write to file
   2193             pp_field.save(pp_file)

/nesi/nobackup/niwa00013/williamsjh/miniconda2/envs/master/lib/python2.7/site-packages/iris/fileformats/pp.pyc in <genexpr>(***failed resolving arguments***)
   2126 
   2127     """
-> 2128     return (field for cube, field in save_pairs_from_cube(
   2129         cube, field_coords=field_coords, target=target))
   2130 

/nesi/nobackup/niwa00013/williamsjh/miniconda2/envs/master/lib/python2.7/site-packages/iris/fileformats/pp.pyc in save_pairs_from_cube(cube, field_coords, target)
   2050     # unused?
   2051 
-> 2052     n_dims = len(cube.shape)
   2053     if n_dims < 2:
   2054         raise ValueError('Unable to save a cube of fewer than 2 dimensions.')

AttributeError: 'CubeList' object has no attribute 'shape'
```

Thanks!

Jonny Williams
NIWA, New Zealand

**Comment by bjlittle** [comment]
Hi @jonnyhtw!

Good to hear from you.

This is actually a good feature request, and we've never really got around to provisioning the ability to save multiple cubes to one file - sorry about that! 

It sounds simple, but it's actually a pretty involved problem to solve in `iris`, but I suspect there are other users out there that would also like this feature.

That said,  I've added the `Votable Feature` label to this issue - so simply add a :+1: to the issue to register your vote for this feature :smile:

**Comment by jonnyhtw** [comment]
Hi there! 

Thanks so much for your help on this!

Please excuse the question, but how do I add my thumbs up to the issue?! I can't work it out... 😆 

Many thanks

Jonny

**Comment by bjlittle** [comment]
![github-issues-425](https://user-images.githubusercontent.com/2051656/59603055-4c70d000-9100-11e9-9042-dc5e068c825f.png)
@jonnyhtw You should be able to add your thumbs up on the main text of this issue as highlighted above.

Does this work for you?

**Comment by QuLogic** [comment]
That spot is only visible if there's already a reaction. New reactions can be added by clicking the smiling face in the top right of the description (next to the Member flair in your example).

**Comment by jonnyhtw** [comment]
> ![github-issues-425](https://user-images.githubusercontent.com/2051656/59603055-4c70d000-9100-11e9-9042-dc5e068c825f.png)
> @jonnyhtw You should be able to add your thumbs up on the main text of this issue as highlighted above.
> 
> Does this work for you?

Yes! Thanks a lot for the clarification. I've put my 👍 up!

Cheers

Jonny

**Comment by jonnyhtw** [comment]
> That spot is only visible if there's already a reaction. New reactions can be added by clicking the smiling face in the top right of the description (next to the Member flair in your example).

Got it, thanks! 😃

**Comment by stephenworsley** [comment]
@jonnyhtw can you clarify what is in your cubelist? Having just tried to make and save a CubeList (with Iris 2.2), I was able to save a CubeList to a .pp file using iris.save.

**Comment by jonnyhtw** [comment]
Hi there

Thanks for that @stephenworsley. I've also just tried this with another CubeList (actually one of length 1 and one of length 2) and it worked!

To be honest I can't remember exactly what was in the CubeList but it seems that it is not the fundamental inability to write CubeLists to a PP file which is the problem.

Hope that makes sense.

Thanks

Jonny

**Comment by bjlittle** [comment]
@jonnyhtw Clearly previously I was having a senior moment...we've just double check all of our `iris` savers, and we do indeed support saving multiple cubes in a `iris.cube.CubeList` to a single file for all of the main fileformats i.e. NetCDF, PP and GRIB2 e.g.
```
>>> import iris
>>> iris.__version__
'2.2.1dev0'
>>> cube = iris.load_cube('global_t/global.grib2')
>>> print(cube)
air_temperature / (K)               (latitude: 73; longitude: 96)
     Dimension coordinates:
          latitude                           x              -
          longitude                          -              x
     Scalar coordinates:
          forecast_period: -11055.0 hours, bound=(-28587.0, 6477.0) hours
          forecast_reference_time: 1998-03-06 03:00:00
          pressure: 100000.0 Pa
          time: 1996-11-30 12:00:00, bound=(1994-12-01 00:00:00, 1998-12-01 00:00:00)
     Cell methods:
          mean: time
>>> iris.save([cube]*3, 'test.nc')
>>> iris.save([cube]*3, 'test.grib2)
>>> iris.save([cube]*3, 'test.pp')
```
This just works :+1: Note that this was using the latest `iris` version `2.2.1`

So we were curious about your failure and attempted to recreate it this side... but we can't do that easily.

What version of `iris` are you using, and can you recreate the issue on your side again to give us more detail?

**Comment by bjlittle** [comment]
@jonnyhtw I'm going to close this issue, resulting from https://github.com/SciTools/iris/pull/3354 and the fact that all our savers allow you to save one or more cubes in an `iris.cube.CubeList` to either NetCDF, PP or GRIB2.

I you manage to re-create your issue, then we're really interested to know the details, so simply open an new issue and we'll take it from there.

Thanks again :wink:

**Comment by jonnyhtw** [comment]
OK thanks! 

The reason I commented on this in the first place was that I was getting the same error message as given above...

`AttributeError: 'list' object has no attribute 'shape'`


I'm pleased that it's gone away, albeit mysteriously!

Ngā mihi nui; thanks a lot.

Jonny

**Comment by bjlittle** [comment]
Ka manaakitia koe! - You're welcome! (well, according to Google Translate) :smile: 

If you have any further problems, questions or requests, then please do just raise an isses
