### ISSUE TITLE
Lazy regridding of FF files up to 10x slower than realised data

### ISSUE THREAD

**Issue by jamesp** [SciTools/iris#4280]
## 🐛 Bug Report
For some files output from the Met Office UM iris 3 performs regridding up to 10x slower than iris 2.4.

This has been traced to the changes made to the regridder in #3598. #4225 was proposed as a quick fix to revert to the regridder as it was at iris v2.4, but this is not a complete solution as it will remove the important optimizations that were introduced in the PR.

As a workaround, users can realise the cube data before regridding to retain performance.  However, this is not a long-term solution as prevents larger than memory calculations.

This is a high priority issue that must be addressed in the next minor version of iris.

**Comment by wjbenfold** [comment]
Closing this as fixed by PR #4400
