### ISSUE TITLE
Run tests on Windows

### ISSUE THREAD

**Issue by jamesp** [SciTools/iris#4336]
## ✨ Feature Request

We provide iris 3 for Windows via conda-forge - see https://anaconda.org/conda-forge/iris. There are known users of iris on Windows. We should setup CI to run the test suite on Windows.

**Comment by trexfeathers** [comment]
This could definitely be good thing, but the way people have talked before: it also sounds like a significant extra commitment. This is presumably a combination of extra potential problems arising at any given time due to a 'wider CI net', plus the extra expertise we may need to keep it working.

**Comment by tkknight** [comment]
We can at least try to get the CI working, if it highlights many issues then it is more of a known issue as right now it is an unknown unknown.  Suggest any effort to this will managed and prioritised, unless we have help from contributors outside the Met Office.

**Comment by wjbenfold** [comment]
I've started making changes to .cirrus.yml that run the tests against Windows to try this

**Comment by wjbenfold** [comment]
A confluence page exists to document the progress that has been made on understanding this
