### ISSUE TITLE
Confusing error message when applying "concatenate_cube" to multi-variable cube list

### ISSUE THREAD

**Issue by tinyendian** [SciTools/iris#4342]
## 🐛 Bug Report
Method `concatenate_cube` in source file `cube.py` can produce a confusing error message when it is (mistakenly) used on a multi-variable cube list. It reports identical cube names, e.g., `Cube names differ: air_pressure != air_pressure` when the cube list contains multiple instances of `air_pressure` cubes (along with cubes for other variables, such as `air_temperature`), which will probably confuse users (it did confuse me :-)).

## How To Reproduce
Steps to reproduce the behaviour:

1. Prepare two data files with two variables, with time steps of one variable stored across both files and with some differences in their metadata (so that cubes cannot be automatically concatenated and the variable will thus appear as multiple cubes when loaded by Iris)
2. Load the data using `cubes = iris.load(['file1', 'file2'], ['var1', 'var2'])`, with `cubes` now containing, e.g., `[var1, var1, var2]`
3. Concatenate the cubes using `cubes.concatenate_cube()`
4. As expected, a `ConcatenateError` message appears, which may list the same variable names as different:
```
iris.exceptions.ConcatenateError: failed to concatenate into a single cube.
  Cube names differ: var1 != var1
```
The error message might (correctly) say `var != var2` if cube order in `cubes` is different.

## Expected behaviour
The error message should read
```
iris.exceptions.ConcatenateError: failed to concatenate into a single cube.
  Cube names differ: var1 != var2
```
instead, to make it clear that the user erroneously tried to apply `concatenate_cube()` on a cube list that contains multiple variables.

## Environment 
 - OS & Version: Ubuntu 18.04.4 LTS
 - Iris Version: 3.1.0

## Additional context

Looking at the code (line 558 in `cube.py`), it seems to me that
```
"Cube names differ: {} != {}".format(names[0], names[1])
```
should be replaced by
```
"Cube names differ: {} != {}".format(unique_names[0], unique_names[1])
```
as `unique_names` is guaranteed to contain different names at positions `0` and `1`.

**Comment by trexfeathers** [comment]
This is a great idea @tinyendian, thanks for suggesting it! We believe the fix should be as simple as what you have suggested; do you fancy taking it on?

If not, this is an ideal opportunity for _anyone_ looking to get involved with Iris 🙂

**Comment by tinyendian** [comment]
Thanks, @trexfeathers, I'll create a pull request (and I'll work my way through the contributor's guidelines 🙂).
