### ISSUE TITLE
Review regridding result change from Cartopy v0.19 to v0.20

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#4346]
As explained in [this comment](https://github.com/SciTools/iris/pull/4331#discussion_r717510131)
> @bjlittle "I can't identify the root cause for the change in numbers here... hence why I've introduced a minimum pin for cartopy in iris (after all, this is a major release update of proj)
We either accept this change "as is"... or dig deeper"
... I'm still in favour of creating an issue to cover this, if that seems like a pragmatic compromise. Then we can dedicate some time to digging a bit further to understand the root cause of the issue (if possible), but bank this PR and move on.

The failing test checks a few specific points from a regridding result 
It's a nearest-neighbour regridding from an unstructured cube to a target grid defined in a gnomomic projection.
It seems that the nearest-neighbour regridded values are different, which implies that the coordinate projection points must have shifted.

For now, we have simply [adopted new result values](https://github.com/SciTools/iris/pull/4331#pullrequestreview-759440405).

Clearly the results shift when going from Cartopy 0.19 to 0.20, which means (probably) PROJ 7.2 --> Proj 8.1 
  * Possibly the target points are just 'unlucky' in falling "just between" input locations, in which case adjusting the target grid slightly might enable this to give the same, stable results for both old+new versions
  * Or, possibly, there is a change (or even a definite problem) relating specifically to the Gnomonic projection

**Comment by rcomer** [comment]
See #4901.  Since the functionality in question is now deprecated, we decided it is not worth the resource to investigate.
