### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [SciTools/iris#4426]
## ✨ Feature Request
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

## Motivation
[Rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13)

## Additional context
Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/Iris/lokal -name '*.py')
```

**Comment by elfring** [comment]
:crystal_ball: Would you dare to try a variant of the shown Perl command example out on another development repository?

**Comment by rcomer** [comment]
Hello @elfring, sorry you didn’t previously get a reply to this.  I am unfamiliar with Perl, but you appear to be suggesting some sort of find-and-replace to apply across the Iris codebase.  You have identified that there is a risk with this approach

> Please check also for questionable change suggestions because of an evolving search pattern.

I would be surprised if any project would take such a risk without there also being a clear benefit.  Could you explain what the benefit would be?  Have you found specific problems in Iris that would be solved by this?

**Comment by elfring** [comment]
>…, but you appear to be suggesting some sort of find-and-replace to apply across the Iris codebase.

Yes.

Your understanding is appropriate.


>You have identified that there is a risk with this approach

The shown transformation approach has got general software limitations.
But you might notice that it can work reasonably well for further development considerations.


>Could you explain what the benefit would be?

:eyes: Please take another look at information in [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13).
How do you think about the support for in-place operations? :thinking:

**Comment by rcomer** [comment]
The PEP tells us why in-place operations are useful in general.  It does not tell us why the specific proposed change is useful to Iris.

Having browsed some of the [equivalent threads in other projects](https://github.com/issues?q=is%3Aissue+author%3Aelfring+archived%3Afalse+augmented+sort%3Acomments-desc+), I do not see value in keeping this one open.
