### ISSUE TITLE
truncated comments in cell_methods 

### ISSUE THREAD

**Issue by larsbarring** [SciTools/iris#4427]
## 🐛 Bug Report
In code that sequentially aggregated observational data it seems that `cell_methods` comments may be truncated under certain circumstances. This is an excerpt from a file produced by iris 3.1.0:

```
 !ncdump -h myfile.nc 
     float tasmin(y, x) ;
        tasmin:standard_name = "air_temperature" ;
        tasmin:long_name = "Daily Minimum Near-Surface Air Temperature" ;
        tasmin:units = "K" ;
        tasmin:cell_methods = "time: minimum within days (comment: 18h(day-1)-18h) time: mean over days time: mean" ;
        tasmin:grid_mapping = "lambert_conformal_conic" ;
        tasmin:coordinates = "height lat lon time" ;
```
Note the parenthesis within the `cell_method` comment.  The cell methods represent 
1.  minimum within day (i.e., 18 UTC the day before to 18 UTC)
2.  mean over days [within the month] of the daily minima
3.  mean over months [within the year] of the daily minima

where the aim is to compact 2 and 3 to 
2.  mean over days [within the year] of the daily minima

However, this is how it looks when reading this file into iris:
```
 air_temperature / (K)                                  (projection_y_coordinate: 823; projection_x_coordinate: 567)
    ....
    Cell methods:
        minimum within days                              time (18h(day-1)
        mean over days                                   time
        mean                                             time

**Comment by wjbenfold** [comment]
The issue looks to be that the regex shown below is applied to the cell_methods string and assumes that the next closing bracket after an opening bracket matches to that opening bracket (thus not handling nested brackets). It's not possible to generally handle nested brackets with a regular expression, so it may be that a different approach is required to handle this.

https://github.com/SciTools/iris/blob/6d24b30dcf5948aaa0abbe53a5300d89022a1da9/lib/iris/fileformats/netcdf.py#L188-L199

**Comment by larsbarring** [comment]
@wjbenfold thanks for the good attempt at a PR (myself I was not able to locate the regex that was the origin of the problem).

In general, I think that Iris should be able to read what Iris is able to write, and that is independent of what is purist's CF and what might not be. 

In this particular case I cooked up the cell method comment myself and the files were created just fine. But when reading them for the next step of the workflow they just tripped.
