### ISSUE TITLE
`nose` missing some tests

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4431]
## 📰 Custom Issue

We have some tests for NetCDF loading that are created by using `setattr` on the test class:

https://github.com/SciTools/iris/blob/0a0cb8722153440a4db2a7bb53ba3998a507cd2f/lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__hybrid_formulae.py#L242-L278

`nose` does not seem to be discovering these.  They run fine if you run the module directly, and they are also discovered by `pytest`.  So this issue would be solved by implementing #3835 🙂

**Comment by wjbenfold** [comment]
Decision from peloton is to fix this here by building the tests in such a way as nose discovers them.

We're keen to move to pytest soon, but not soon enough that this shouldn't be fixed to run on nose.
