### ISSUE TITLE
Stop GHA running in forks?

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4441]
## 📰 Custom Issue

I recently updated my default branch in my Iris fork to be up-to-date with `main`.  This caused the lockfile and stale actions to start running there, which seems like a waste of processes.  I have disabled them for mine, but maybe it would be a good idea to turn them off for forks in general.  See https://github.com/matplotlib/matplotlib/pull/21692 for an example of how that can be done.

**Comment by jamesp** [comment]
Seems sensible to me!
