### ISSUE TITLE
Error reading NetCDF file dimensions with units degrees

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#4460]
## 🐛 Bug Report
(Edited to show the error is associated with the coordinates having units 'degrees' rather than no units.)
I can create a NetCDF file of a field with 'longitude' and 'latitude' coordinates with units 'degrees' using the netCDF4 module version 1.5.8. Its metadata appears correct according to ncdump and the data it contains looks correct according to ncview. When I read the file using iris 3.1.0, however, it assigns the name 'grid_latitude' to both coordinates.

## How To Reproduce
Steps to reproduce the behaviour:

Creating the file, reading it in with iris and printing the cube:
```
import numpy as np
import iris
import netCDF4

lat_vals=np.arange(-90,90)
lon_vals=np.arange(360)
data_out=np.random.normal(0,1,(len(lat_vals),len(lon_vals)))

fname='test.nc'
f = netCDF4.Dataset(fname, 'w')
lat_dim=f.createDimension('latitude', len(lat_vals))
lats=f.createVariable('latitude', 'f4', ('latitude',))
lats[:]=lat_vals
lon_dim=f.createDimension('longitude', len(lon_vals))
lons=f.createVariable('longitude', 'f4', ('longitude',))
lons[:]=lon_vals
data=f.createVariable('data', 'f4', ('latitude','longitude'))
data[:]=data_out

#Commenting these next two lines makes iris read the file correctly
lats.units='degrees'
lons.units='degrees'

f.close()

cube=iris.load_cube(fname)
print(cube)
```

This gives the result
```
data / (unknown)                    (grid_latitude: 180; grid_latitude: 360)
    Dimension coordinates:
        grid_latitude                             x                   -
        grid_latitude                             -                   x
```

## Expected behaviour
That iris would name the coordinates "latitude" and "longitude".

## Environment 
 - OS & Version: CentOS Linux 7
 - Iris Version: 3.1.0

**Comment by PAGWatson** [comment]
Just to add, iris 3.0.4 doesn't seem to have this problem.

**Comment by bjlittle** [comment]
@PAGWatson You beat me to it :wink: 

I'm going to regression test against different versions of `iris`. To me this seems like we've adopted a new default behaviour, which to be honest, has surprised me as much as you... so I'll start digging :monocle_face:

**Comment by bjlittle** [comment]
@PAGWatson Okay, so I've narrowed down exactly where this regression in behaviour occurs.

![image](https://user-images.githubusercontent.com/2051656/146216577-06333e96-74b4-4c00-9b51-d3535f3eda1c.png)

Essentially, PR #4198 caused the regression in expected behaviour.

With commit dccb6a55c9c05f4d8ef0efde05c1f16c5957050f we have the behaviour as you've stated in this issue, and the previous commit 
0c942c053fcdee00e555ecbc57bea63362946661 gives us the expected behaviour, i.e.,
```shell
data / (unknown)                    (latitude: 180; longitude: 360)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
```

**Comment by bjlittle** [comment]
@PAGWatson I've added this to the `iris` 3.2 milestone, so you'll see this fix early next year... the `iris` 3.2 release is scheduled for Feb-Mar 2022.

See [v3.2.x GH Discussions](https://github.com/SciTools/iris/discussions/4129) for a pulse on the state of play for the `iris` 3.2.0 release 👍

**Comment by bjlittle** [comment]
@PAGWatson Thanks for raising this issue 🍻, and apologies again for the regression

**Comment by bjlittle** [comment]
Ping @pp-mo Heads-up 😉

**Comment by PAGWatson** [comment]
@bjlittle Great, thanks for looking into this.

**Comment by pp-mo** [comment]
Just FYI, I am now looking into this.
It is definitely a bug that I introduced #4198  !!
I have a handle on the problem, but it may take a while to sort it out.
