### ISSUE TITLE
Use of `standard_name` and `TXYZ` on special coordinates

### ISSUE THREAD

**Issue by BorjaEst** [SciTools/iris#4517]
## ✨ Feature Request
It should ALSO be possible to use the `standard_name` and the coordinate letter `TXYZ` for referring the 4 most common coordinates when performing statistical and other functions. For example:
```py
mean = cube.collapsed('latitude', iris.analysis.MEAN)
```
AND
```py
mean = cube.collapsed('Y', iris.analysis.MEAN)
```

## Motivation
Basically, [CF Conventions 1.9](https://cfconventions.org/cf-conventions/cf-conventions.html#_naming_conventions) does not restrict the way a variable or coordinate is named in the netCDF. Therefore if you have to perform an analysis from multiple sources, you cannot rely on the variable name. For example, if I want to calculate the mean of a cube:

For source 1 would be:
```py
mean = cube.collapsed('latitud', iris.analysis.MEAN)
```

For source 2 might be:
```py
mean = cube.collapsed('lat', iris.analysis.MEAN)
```

That is not reliable, it requires effort from the programmer to prepare the analysis for every source (or extend it with a dynamic coord read which I could not figure out on iris). Instead, as specified by CF Conventions and reproduced by other libraries [cf-python](https://ncas-cms.github.io/cf-python/analysis.html#id29), [cf-xarray](https://cf-xarray.readthedocs.io/en/latest/coord_axes.html#axes-and-coordinates), the usage of standard names is recommended for the special coordinates described at section 4 at [CF Conventions 1.9](https://cfconventions.org/cf-conventions/cf-conventions.html#coordinate-types).

## Additional context
This is collected form [CF Conventions 1.9](https://cfconventions.org/cf-conventions/cf-conventions.html#coordinate-types):
"Because identification of a coordinate type by its units is complicated by requiring the use of an external software package [UDUNITS] , we provide two optional methods that yield a direct identification. The attribute axis may be attached to a coordinate variable and given one of the values X, Y, Z or T which stand for a longitude, latitude, vertical, or time axis respectively. Alternatively the standard_name attribute may be used for direct identification. But note that these optional attributes are in addition to the required COARDS metadata."

**Comment by BorjaEst** [comment]
Nevermind, looks it already uses "standard_names".

**Comment by rcomer** [comment]
@BorjaEst in case it helps, you should also be able to do something like
```python
y_coord = cube.coord(axis="Y")
mean = cube.collapsed(y_coord, iris.analysis.MEAN)
```

**Comment by BorjaEst** [comment]
> @BorjaEst in case it helps, you should also be able to do something like
> 
> ```python
> y_coord = cube.coord(axis="Y")
> mean = cube.collapsed(y_coord, iris.analysis.MEAN)
> ```

Yes @rcomer, actually that helps a lot, thanks!
