### ISSUE TITLE
Can't install Iris in Python3 AWS Sagemaker environment

### ISSUE THREAD

**Issue by MOJSN** [SciTools/iris#4520]
## 🐛 Bug Report
Install fails for Iris in the Python3 env on Sagemaker with `The environment is inconsistent, please check the package plan carefully`

Not sure if source of issue is AWS or Iris.

## How To Reproduce
Steps to reproduce the behaviour:

1. Create a new Notebook under Sagemaker
2. Open with JupyterHub and choose `conda_python3` kernel
3. Open a terminal and 'source activate python3`
4. Do usual `conda install -c conda-forge iris`
5. (grinds away and eventuall gives up with "The environment is inconsistent...")

## Expected behaviour
Iris gets installed. Worked last time I did this several months ago.

## Screenshots
dump of session:
```
sh-4.2$ source activate python3
(python3) sh-4.2$ conda install -c conda-forge iris
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::nbclient==0.5.2=pyhd8ed1ab_0
  - conda-forge/linux-64::matplotlib==3.3.4=py36h5fab9bb_0
  - conda-forge/noarch::qdarkstyle==2.8.1=pyhd8ed1ab_2
  - conda-forge/linux-64::scikit-image==0.16.2=py36hb3f55d8_0
  - conda-forge/noarch::python-language-server==0.36.2=pyhd8ed1ab_0
  - conda-forge/linux-64::widgetsnbextension==3.5.1=py36h5fab9bb_4
  - conda-forge/noarch::flake8==3.8.4=py_0
  - conda-forge/noarch::ipywidgets==7.6.3=pyhd3deb0d_0
  - conda-forge/noarch::typing-extensions==3.7.4.3=0
  - conda-forge/noarch::path.py==12.5.0=0
  - conda-forge/noarch::dask==2021.2.0=pyhd8ed1ab_0
  - conda-forge/noarch::nbformat==5.1.2=pyhd8ed1ab_1
  - conda-forge/linux-64::path==15.1.2=py36h5fab9bb_0
  - conda-forge/linux-64::nbconvert==6.0.7=py36h5fab9bb_3
  - conda-forge/linux-64::distributed==2021.2.0=py36h5fab9bb_0
  - conda-forge/noarch::anaconda-client==1.7.2=py_0
  - conda-forge/noarch::aioitertools==0.7.1=pyhd8ed1ab_0
  - conda-forge/linux-64::matplotlib-base==3.3.4=py36hd391965_0
  - conda-forge/linux-64::pluggy==0.13.1=py36h5fab9bb_4
  - conda-forge/noarch::black==20.8b1=py_1
  - conda-forge/linux-64::blaze==0.11.3=py36_0
  - conda-forge/noarch::pyls-spyder==0.3.2=pyhd8ed1ab_0
  - conda-forge/noarch::odo==0.5.1=py_1
  - conda-forge/linux-64::keyring==22.0.1=py36h5fab9bb_0
  - conda-forge/noarch::anaconda-project==0.9.1=pyhd8ed1ab_0
  - conda-forge/noarch::importlib_metadata==3.7.0=hd8ed1ab_0
  - conda-forge/linux-64::jupyter==1.0.0=py36h5fab9bb_6
  - conda-forge/noarch::jupyterlab_server==2.3.0=pyhd8ed1ab_0
  - conda-forge/noarch::seaborn-base==0.11.1=pyhd8ed1ab_1
  - conda-forge/noarch::imageio==2.9.0=py_0
  - conda-forge/noarch::numpydoc==1.1.0=py_1
  - conda-forge/linux-64::yarl==1.6.3=py36h8f6f2f9_1
  - conda-forge/noarch::jsonschema==3.2.0=py_2
  - conda-forge/noarch::flask==1.1.2=pyh9f0ad1d_0
  - conda-forge/noarch::seaborn==0.11.1=hd8ed1ab_1
  - conda-forge/noarch::helpdev==0.7.1=pyhd8ed1ab_0
  - conda-forge/linux-64::nb_conda==2.2.1=py36h5fab9bb_4
  - conda-forge/noarch::nbclassic==0.2.6=pyhd8ed1ab_0
  - conda-forge/noarch::sphinx==3.5.1=pyhd8ed1ab_0
  - conda-forge/noarch::jupyterlab_launcher==0.13.1=py_2
  - conda-forge/linux-64::spyder==4.2.0=py36h5fab9bb_0
  - conda-forge/linux-64::importlib-metadata==3.7.0=py36h5fab9bb_0
  - conda-forge/linux-64::pytest==6.2.2=py36h5fab9bb_0
  - conda-forge/noarch::pyls-black==0.4.6=pyh9f0ad1d_0
| ^Cfailed with initial frozen solve. Retrying with flexible solve.
```
Keeps retrying and eventually gives up.

## Environment 
 - OS & Version: ```Linux ip-....-.amzn1.x86_64 #1 SMP Mon Nov 1 20:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
 - Iris Version: Latest from conda-forge (didn't install)

## Additional context

I note that there is a lot of JupyterLab in the inconsistency list. Was that in previous packaging of Iris? (particualrly the jupyterlab_server)

<details>
<summary>Click to expand <b>this section...</b></summary>

```
Please add additional verbose information in this section e.g., code, output, tracebacks, screenshots etc
```
</details>

**Comment by jamesp** [comment]
I've not used sagemaker before, but I can tell you that conda doesn't handle the situation of "install this big new set of dependencies into an existing environment" very well.  Do you have the ability to create new conda environments in sagemaker? Something like:

```conda create -n iris_n_friends -c conda-forge iris ipykernel```

That would help nail down if this is an issue specific to the existant environment, or an incompat with sagemaker in general.

FYI, these are the [named dependencies of iris when adding to a conda env](https://github.com/conda-forge/iris-feedstock/blob/ec2ad9488668606d79f5021ac39645cde305f0ed/recipe/meta.yaml#L26-L35):
        - python >=3.6
        - cartopy >=0.18
        - cf-units
        - cftime >=1.5.0 
        - dask-core >=2
        - matplotlib-base
        - netcdf4 >=1.4
        - numpy >=1.14,!=1.15.2
        - scipy
        - python-xxhash

**Comment by MOJSN** [comment]
I can create new envs per your line above - but interestingly pyhton then fails `import iris` once activated.

Sagemaker uses full `anaconda` rather than `minconda` per the recommended installation intructions. Might this be a factor ?

(I am creating a clean standard env and trying to do the line by line installs. WLYK)

**Comment by jamesp** [comment]
Anaconda is essentially miniconda + 100s of packages installed by default from pkgs/main. So if that is the env you are activating it might not be surprising that it struggles to install iris from conda-forge.

`conda create ...` should make a completely new environment, isolated from the anaconda provided envs.

**Comment by MOJSN** [comment]
OK - sorted. Partly [PICNIC](https://en.wikipedia.org/wiki/User_error), partly `conda-forge` incompatabiltities with installation in standard Sagemaker kernels.

1. I was using legacy `source activate env` rather than `**conda** activate env` which doesn't resolve all the environment links and executables, so that didn't help (and [I'm not alone](https://stackoverflow.com/questions/49600611/python-anaconda-should-i-use-conda-activate-or-source-activate-in-linux))
2. There are many inconsistencies being thrown between standard AWS envs and the `conda-forge` packages

**Resolution**
1. Create seperate env per above command: `conda create -n iris_n_friends -c conda-forge iris ipykernel`
2. Register as Jupyter kernel: `python -m ipykernel install --user --name iris_n_friends --display-name "iris"`
3. Select new kernel for notebook

I was doing this as a qucik/temporary thing. If you want the kernel to persist you need to create the env on the EBS volume for the Sagemaker instance and then configure the instance at start up to recognise and use it. See this [set of instructions](https://medium.com/decathlontechnology/making-jupyter-kernels-remanent-in-aws-sagemaker-a130bc47eab7) for example.

An alternative is to create a seperate containerised image (for Studio). See: https://aws.amazon.com/blogs/machine-learning/bringing-your-own-custom-container-image-to-amazon-sagemaker-studio-notebooks/
