### ISSUE TITLE
Add setup.py command to do a full in-place build

### ISSUE THREAD

**Issue by esc24** [SciTools/iris#456]
It is convenient as a developer to do in place builds. Previously this meant calling `python setup.py build_ext --inplace`. However, one now needs to build the standard names file and it would be good to be able to trigger the pyke rules compilation in a similar way to the out of place build.

Implement a new setup.py command called `build_inplace` (or a better name if you can think of one) that does the equivalent of:
1. `python setup.py build_ext --inplace`
2. `python setup.py std_names`
3. `python setup.py pyke_rules` (see #435)

Note you must be able to pass the -I, -L -R options (and their equivalents) though to the build_ext command, and `--with-unpack` must work.

**Comment by pelson** [comment]
The standard approach of ```pip install -e .``` has become ubiquitous.
What is missing is the fact that we have some bespoke commands that one must remember to do. I'd like them to be rolled into the standard build.

**Comment by rcomer** [comment]
Did #2891 address this?

**Comment by pp-mo** [comment]
> Did #2891 address this?

I believe that `pip install -e .` now works, so I guess "yes".

I checked this : it runs `python setup.py develop`, which correctly generates pyke rules and std_names.py 👍

**Comment by pp-mo** [comment]
Thanks for highlighting @rcomer  !
