### ISSUE TITLE
Quicker/easier informative plot titles

### ISSUE THREAD

**Issue by wjbenfold** [SciTools/iris#4570]
## 📰 Custom Issue

@WilliamIngramAtmosphericPhysics previously suggested a number of enhancements to the iris.quickplot title. These could be default, available with keywords or in some way a user could have the opportunity to personalise them. They could also be available in a repository of other iris convenience functions aimed at specific subsets of users with common goals.

Possible inclusions:

-  what the quantity is (& not "air temperature" if it is in fact "increment to air temperature from convection").
- quote the STASHcode if there is one.
- an option to provide a user STASHmaster.
- what the units are, I think even if they are the SI ones.
- scalar coordinate values, and other attributes
- the time information in all the detail possible.
- Any other optional attributes which like STASHcode are very informative for relevant fields to people who know about them.

**Comment by WilliamIngramAtmosphericPhysics** [comment]
Thanks, @wjbenfold!

I was thinking of something like pp_guess_title in the ukmo PVWave/IDL library, which some readers will remember.  If you didn't set a title for a map plot it was called & its title used, but I also often called it direct to check just what was in something I'd read in.  I think I found what it gave generally about what I wanted, but then I was a MOHC climate modeller like its authors, & of course iris has a much wider user base than that. There were about 3 lines of up to dozens of characters, I think, content & length depending on what metadata was present & what it said, but basically telling me the things I might want to know, not the array sizes which iris currently concentrates on - & omitting anything that didn't seem to have a useful value set.

Looking at its code, I see
> ; If no keywords are selected then the default is to provide all keywords to the command! 
> ; If you specify a keyword then the default is overridden and you are only provided with the keyword or keywords that you added to the command.
> ; 
> ;  /name      -- The returned string will contain field name.
> ;  /level     -- The returned string will contain the level info.
> ;  /time      -- The returned string will contain the time info.
> ;  /proc      -- The returned string will contain the processing info.
> ;  /scaling   -- The returned string will contain scaling info. based on the BMKS value.
> ;  /submodel  -- The returned string will contain submodel info based on lbuser(4), stash2submodel() and submodel2name()
> ;  /exptname  -- The returned string will contain the expt name.

so maybe maximal-by-default would work... STASHcode, suitename & CMIP experiment name, say, may mean nothing to many people but don't take up many characters so maybe it would be OK to put them in the title by default if they're present in the metadata - as well, perhaps, as various other metadata I'm not so used to - suggestions?  pp_guess_title didn't give resolution/array dimension, which I don't normally want, but maybe some people would?  For a plot, units are IMO better on the colour bar as iris quickplot already does, but could be useful when the routine's being used in other contexts.  Similarly no point in giving the domain for the caption to a plot, but I think it would sometimes be valuable.  (I normally have global fields.)  If it is being used by quickplot it'd only get 2-D cubes/slices, but it would be useful to have such functionality for any cube.

**Comment by rcomer** [comment]
It may be worth noting that `mule` has already solved the problem of getting a stashmaster file into a python dictionary.  So even without modifying Iris we can do something like

```python
import iris
import iris.quickplot as qplt
import matplotlib.pyplot as plt
import mule

STASHMASTER_DICT = mule.stashmaster.STASHmaster.from_version("10.2")

fname = iris.sample_data_path("A1B.2098.pp")
cube = iris.load_cube(fname)
qplt.contourf(cube)
plt.gca().coastlines()

stash_int = cube.attributes["STASH"].lbuser3()
stash_name = STASHMASTER_DICT[stash_int].name
mytitle = f"{stash_name} ({stash_int})"
plt.title(mytitle)

plt.show()
```

![quickplot_stashmaster](https://user-images.githubusercontent.com/10599679/153760461-1a1a1325-97dd-49c4-b499-25e186451b67.png)

There is also a `mule.stashmaster.STASHmaster.from_file` function, so you could pass custom stashmaster files.  I'm not sure how widely available `mule` is outside the Met Office, but if we are targetting 

> specific subsets of users with common goals

that might not matter?

**Comment by wjbenfold** [comment]
We've discussed before whether it would be useful for groups of users with similar aims to have their own packages that they share and maintain of auxiliary functions that accomplish specific goals (but which aren't sufficiently widely applicable that they belong in the core of Iris, with the associated impacts on being able to find what you're looking for in the api / documentation / config). Might some of the above needs apply to a candidate for such a group of users, or are they sufficiently widespread that the additions should sit within the core of Iris?

**Comment by WilliamIngramAtmosphericPhysics** [comment]
Thanks, @rcomer!

I wasn't actually thinking of finding & adding the STASHmaster name corresponding to the STASHcode, but just adding the STASHcode itself for the benefit of those users it does mean something to (immediately or after looking it up in a STASHmaster), only a few easily-ignored characters for those it doesn't.  pp_guess_title did use the STASHmaster name but I thought it didn't have much else to go on, while I thought that an iris cube should normally have plenty of other information in the metadata to give a general description useful to most users, & the STASHmaster name would often just repeat that, at some length.

But I may be wrong - am very happy to hear the facts or other people's opinions!

**Comment by WilliamIngramAtmosphericPhysics** [comment]
@wjbenfold, thanks for the suggestion, but no, what I'm suggesting is the opposite - the default, even for users who don't know the code exists, would be for the title to contain some summary information would normally be useful.  Tweaking what went in was possible in pp_guess_title & makes sense to me for users who want it, but I don't remember ever using it - either I took its defaults or I set the title myself.
