### ISSUE TITLE
Weighted `aggregated_by`

### ISSUE THREAD

**Issue by schlunma** [SciTools/iris#4581]
## ✨ Feature Request

Similar to `iris.cube.Cube.collapsed`, it would be nice if `iris.cube.Cube.aggregated_by` could also support `weights`.

## Motivation

`iris.cube.Cube.aggregated_by` currently [does not support weights](https://github.com/SciTools/iris/blob/e3fbd843d0c64a027d5ff460a5564fdd3a87439d/lib/iris/cube.py#L3895-L3901). Using weights in `aggregated_by` might be helpful in lots of use cases, e.g., when calculating annual means for monthly data where the months have a different number of days.

## Additional context

I tried to implement this for the non-lazy case (see [this commit](https://github.com/schlunma/iris/commit/d020bd2f9db5fa9d3d54619b7555173f1daafe51)). It actually doesn't require a lot of changes. If you think this feature is helpful, I can come up with a solution for the lazy case and open a pull request.

Thanks!!

**Comment by rcomer** [comment]
This has been requested before - #3290, so seems like a good idea to me.  There was talk in that issue of rationalising some of the `collapsed`/`aggregated_by` code though, which would have made it a bigger task I guess.
