### ISSUE TITLE
Suggestion: add an isel-like method to iris cubes

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#4603]
## ✨ Feature ~~Request~~ Suggestion

As far as I know, iris cubes don't have an index selector like the [`isel` method xarray has](https://xarray.pydata.org/en/stable/generated/xarray.Dataset.isel.html). Is this something that can be emulated with existing methods? If not, I suggest adding a method like that to iris cubes (and cube lists). 

## Motivation
The idea is to use this method as follows:
```python
some_cube.isel("longitude", 123)
```
which returns a slice of cube at the longitude's _index_ `123` (not value).

I currently have a prototype for it in [`aeolus`](https://github.com/exoclim/aeolus/blob/main/src/aeolus/coord.py#L775), and it can handle cubes or iterables of cubes. It obviously can be renamed to keep iris different to xarray :)

It's a simple shortcut method, but I thought iris community might benefit from it.

**Comment by pp-mo** [comment]
> `some_cube.isel("longitude", 123)`

Of course, we do _have_ index selection, but you need to put it in the right dimension e.g. `[..., 123, :]`.
So in code we have stuff like this ...
```
inds = [slice(None)] * cube.ndim
(lon_dim,) = cube.coord_dims('longitude')
inds[lon_dim] = 123
result = cube[inds]
```

**Is that the correct equivalent of what you're suggesting here ?**

I would say we could come up with a nicer API style for this ...

**Comment by dennissergeev** [comment]
Your solution is much shorter and more elegant, hats off to you!

Nevertheless, this could be wrapped in a method, I suppose.

**Comment by rcomer** [comment]
We can also use `subset`:

```python
required_lon = some_cube.coord("longitude")[123]
result = some_cube.subset(required_lon)
```

**Comment by trexfeathers** [comment]
Sounds like you're happy @dennissergeev 😀. We're closing it but feel free to re-open if you disagree.
