### ISSUE TITLE
Support CRS datum information

### ISSUE THREAD

**Issue by bsherratt** [SciTools/iris#4619]
## ✨ Feature Request

Support for the `datum` attribute of a coordinate reference system.

## Motivation

Higher resolution modelling is now revealing slight discrepancies when transforming between different coordinate systems. Through various discussions, including on met office yammer, the key underlying issue appears to be that `iris.coord_system.CoordSystem` has no concept of a "datum", so are therefore missing information about positions on the surface of the earth relative to an ellipsoid (see [this document](https://www.ordnancesurvey.co.uk/documents/resources/guide-coordinate-systems-great-britain.pdf) for details).

It seems that the *easiest* way to support this, from where iris currently stands is to:

- Add a `datum` attribute to `iris.coord_system.CoordSystem` subclasses.

- [Modify these methods](https://github.com/SciTools/iris/blob/b42c65da21cbf487723ee585cadbe26a5155afb2/lib/iris/coord_systems.py#L296-312) to pass the datum to cartopy.

  Most code that does any kind of coordinate transformation with iris (including plotting and regridding) goes via at least one of these methods, either explicitly or implicitly, so fixing it here is crucial. Cartopy can handle datum shifts ([it uses PROJ via pyproj](https://scitools.org.uk/cartopy/docs/latest/), which [does support this](https://pyproj4.github.io/pyproj/stable/api/transformer.html#transformer)), but it is ([almost](https://github.com/SciTools/iris/blob/b42c65da21cbf487723ee585cadbe26a5155afb2/lib/iris/coord_systems.py#L555-559)) never told about the datum by iris.

- Allow loading this from a file. The [CF conventions](http://cfconventions.org/cf-conventions/cf-conventions.html#grid-mappings-and-projections) do specify how to represent a datum in a netCDF file. Though I suspect that many files in practice do not have this information, so it should also be easy for the user to set one manually, and ideally this should be made clear in the documentation somewhere.

- Ensure the new datum information is saved to a (netCDF) file, to minimise the chance of related issues arising in the future.

**Comment by nhsavage** [comment]
I have an example notebook which should help demonstrate the issue and hopefully also help test a fix (there are a few caveats that  need to explain, so I will bring it to surgery later)

**Comment by bjlittle** [comment]
When #4617 lands, then we'll have votable issues 🚀 

This will really help us prioritise and focus on issues that the community want solved.

**Comment by bjwheltor** [comment]
CF support for a datum is mentioned in the description above, but it does not explicitly mention that the CF Convention optional grid mapping attribute called `crs_wkt`, which may be used to specify multiple coordinate system properties in so-called well-known text format (usually abbreviated to CRS WKT or OGC WKT) - see [5.6.1. Use of the CRS Well-known Text Format](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#use-of-the-crs-well-known-text-format). Might this not be useful to include support in Iris for this? Although it is rather unwieldy, it does allow comprehensive description of the CRS.

Having come late to this, apologies if I'm missed the subtleties of this request.

**Comment by nhsavage** [comment]
>  Might this not be useful to include support in Iris for this? Although it is rather unwieldy, it does allow comprehensive description of the CRS.
I think that is a really good thing to aim for. However, I believe that the long  term aim is to use PyProj directly in Iris to store CRS info. I think that supporting WKS would probably need to wait for that to be implemented, whereas as this ticket is a stop-gap solution to fix the biggest current source of problem. Please can someone say if I have got this wrong?

**Comment by trexfeathers** [comment]
#4643 would be a solution to this.
