### ISSUE TITLE
Stale GHA instructions to reopen issue do not work for non GitHub team members

### ISSUE THREAD

**Issue by tkknight** [SciTools/iris#4628]
## How To Reproduce
Steps to reproduce the behaviour:

1. The [stale GitHub action ](https://github.com/SciTools/iris/blob/main/.github/workflows/stale.yml#L49) suggests to mention @SciTools/iris-devs to have a stale issue re-opened, however we have learned a mention can only be done by someone already in the [GitHub team](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams).
 

## Expected behaviour
The stale comments should state a way that works.

## Environment 
N/A

## Additional context
A GitHub action (GHA) could be created to look for specific text such as `/not stale` or `ping @Scitools/iris-devs` on a new issue comment that will then add a comment itself and mention the team, I think the GHA will have permission to do this (needs testing).

conda-forge does something similar as per the [comment](https://github.com/SciTools/iris/pull/4617#issuecomment-1062772351) in #4617.

Alternatively a GHA could be triggered to just reopen the issue, similar to the above but triggred by `/reopen`.

**Comment by bjlittle** [comment]
Also see #4133, which is another use case where we want non-members of `SciTools` to be able to easily `@mention` us to get our attention

**Comment by wjbenfold** [comment]
This is also assumed to work in the developer guide here: https://scitools-iris.readthedocs.io/en/stable/developers_guide/contributing_documentation_easy.html

**Comment by tkknight** [comment]
Mentioneing a group is also not allowed in a GitHub Action unless you create a personal access token according to this: https://github.community/t/team-mention-from-bot-not-working/144323

**Comment by trexfeathers** [comment]
Discussion in @SciTools/peloton: a full solution to the tagging problem involving GHA is over-engineered. Modifying [the comment](https://github.com/SciTools/iris/blob/10cec6911db04782b9b532601b2929c60ab3125c/.github/workflows/stale.yml#L49) to NOT suggest tagging seems like a good enough solution.
