### ISSUE TITLE
Retire "Feature: Votable" label

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#4630]
## 📰 Custom Issue
Now that #4617 has landed, can we please now retire the [Feature: Votable](https://github.com/SciTools/iris/labels/Feature%3A%20Votable) label?

I believe it has served it's purpose and is now superseded by #4617... plus it's now confusing having two different methods to vote.

I vote (obvz) for #4617, so up vote this issue and we'll retire the label.

**Comment by rcomer** [comment]
I had just assumed that we would TBH.

**Comment by rcomer** [comment]
> anyone who had used the label to vote on an issue has the option to up vote the associated issue with a 👍 instead

I think voting on the old page added a 👍 on the issue anyway?  Now I try to check, [the page appears to be broken](https://vote.biglybt.com/SciTools/iris/Votable%20Feature).  We should maybe replace it with something more robust 😉

**Comment by tkknight** [comment]
Does anyone else have any thoughts before we action the retirement of this label?

**Comment by bjlittle** [comment]
@tkknight I'm just going to action this now... otherwise it's just going to linger around and get forgotten about.

Plus it muddies the waters, given our new world of votable issues, thanks to your awesome efforts 🍻

**Comment by bjlittle** [comment]
Now no more 👍
