### ISSUE TITLE
Handling invalid times in Nimrod radar data

### ISSUE THREAD

**Issue by SimonTett** [SciTools/iris#4632]
## ✨ Feature Request
Deal with invalid seconds in nimrod data triggering an  error in iris.fileformats.nimrod_load_rules.time

## Motivation
I am processing Nimrod data in the BADC archive and data for 2004-2006 has invalid seconds with a value of -32768.
 cftime.datetime triggers an error when given a time of -32768 seconds. I tried to use the callback feature, but that is called after the times are set in the cube and so cannot fix the time before cftime.datetime is called (and fails).

## Additional context
 My solution was to remove the vt_second from the call to datetime as resolution of the radar data is 5 minutes, so seconds are not that important. I then “monkey” patched iris.fileformats.nimrod_load_rules.time. This is not an elegant solution… 

Three potential solutions:
1)  Modify iris.fileformats.nimrod_load_rules so that the callback function is called before times are set. 
2) Deal with invalid times when creating the field (before converting it to a cube)
3) Ignore seconds when creating the cftime.datetime 

This is the relevant bit of code in time after my modification: 

valid_date = cftime.datetime(
            field.vt_year,
            field.vt_month,
            field.vt_day,
            field.vt_hour,
            field.vt_minute,
            #field.vt_second, # seconds occasionally invalid but not needed for nimrod...
        )

</details>

**Comment by trexfeathers** [comment]
Thanks @SimonTett, we agree that this isn't particularly elegant. However it may be the correct thing to do in this case:

* We're dealing with a file that is acknowledged to contain invalid information.
* We have fewer users using Nimrod formats than other formats, and we have to make tough prioritisation calls 😥

We'll leave this open as a marker, so anyone is welcome to propose a fix if they have time. We'd be happy to review a pull request if you put one up 🙂 Your point 2 is the only one we think we'd consider acceptable.
