### ISSUE TITLE
Makes My MC Crash

### ISSUE THREAD

**Issue by TenQYT** [SciTools/iris#4667]
## 🐛 Bug Report
[crash-2022-03-28_20.08.15-client.txt](https://github.com/SciTools/iris/files/8363803/crash-2022-03-28_20.08.15-client.txt)

## How To Reproduce
Steps to reproduce the behaviour:

1. 
2. 
3. 

## Environment 
 - OS & Version: [e.g., Ubuntu 20.04 LTS]
 - Iris Version: [e.g., From the command line run `python -c "import iris; print(iris.__version__)"`]

## Additional context

<details>
<summary>Click to expand <b>this section...</b></summary>

```
Please add additional verbose information in this section e.g., code, output, tracebacks, screenshots etc
```
</details>

**Comment by rcomer** [comment]
Perhaps this was intended for https://github.com/IrisShaders/Iris?
