### ISSUE TITLE
Problems comparing time coord cell objects

### ISSUE THREAD

**Issue by pdearnshaw** [SciTools/iris#4697]
## 📰 Custom Issue
From iris v3, cells for time coordinates now use cftime.datetime objects. These objects cannot be sorted or compared in the guise of coordinate cells, e.g.

```python
import cftime
import iris.coords

t1 = cftime.datetime(2022, 3, 8, 12, 0, 0)
t2 = cftime.datetime(2022, 3, 9, 12, 0, 0)
c1 = iris.coords.Cell(point=t1)
c2 = iris.coords.Cell(point=t2)
cells = [c1, c2]
print(sorted(cells))
```
will fail with the error:

```
Traceback (most recent call last):
  File "./test_time_sort.py", line 19, in <module>
    print(sorted(cells))
  File "lib/python3.8/site-packages/iris/coords.py", line 1513, in __lt__
    return self.__common_cmp__(other, operator.lt)
  File "lib/python3.8/site-packages/iris/coords.py", line 1419, in __common_cmp__
    "Cannot determine the order of " "cftime.datetime objects"
TypeError: Cannot determine the order of cftime.datetime objects
```

This protection was probably added to the cells construct at a time when cftime.datatime objects could not be compared, but now they can and as such the protection should be removed, e.g. from the above t1 and t2 can be compared sensibly. I would hope that lines 1413 to 1420 of coords.py can be simply removed. However, a tranche of tests will also likely need to be re-engineered as well.

**Comment by wjbenfold** [comment]
Thanks for the issue @pdearnshaw! I can't see where cftime's docs specify that it's now possible to compare them, unless that's implicit in them now being comparable to python datetime objects for some calendars?

**Comment by rcomer** [comment]
Looks like that exception has been in place since well before we started using `cftime` - #1016.  Maybe it’s only causing problems now because the `num2date` functions previously returned `datetime.datetime` objects by default - https://github.com/SciTools/cf-units/pull/168.

**Comment by rcomer** [comment]
I also can't see anything in the docs, but rich comparison is defined here:
https://github.com/Unidata/cftime/blob/dc75368cd02bbcd1352dbecfef10404a58683f94/src/cftime/_cftime.pyx#L1314

Looks like, as long as both objects have the same calendar (or both have real-world calendars) the comparison will work.  Since the comparison uses the timetuple, even datetimes without calendars work:
```
In [8]: cftime.datetime(2020, 1, 1, calendar=None) < cftime.datetime(2020, 2, 1, calendar=None)
Out[8]: True
```

**Comment by rcomer** [comment]
Added myself as an assignee as I have a branch.
