### ISSUE TITLE
`iris.Constraint.extract()` should alert the user if `None` returned

### ISSUE THREAD

**Issue by hsteptoe** [SciTools/iris#4700]
## ✨ Feature Request
`iris.Constraint.extract()` should alert the user if `None` returned, rather than silently returning `None`.  

## Motivation
There are cases where the user might expect `iris.Constraint.extract()` to return a cube, but you get `None`.  For example, due to a floating point mismatch between float32 vs float64. Although this might be expected behaviour it's not very user-friendly and there seems to be iris precedent for warning users [eg. coordinate bounds](https://github.com/SciTools/iris/blob/478fa635a043da138a2f12905c7359739d94ff29/lib/iris/coords.py#L2216)

## Additional context
This issue continues an email discussion started with @jamesp 

## Suggestion
As with `iris.coords` issue a `warnings.warn()` with a helpful message. Hopefully this will avoid a breaking change?

**Comment by trexfeathers** [comment]
Thanks for getting in touch @hsteptoe, we've discussed this one at length within the team.

>There are cases where the user might expect `iris.Constraint.extract()` to return a cube, but you get `None`.  For example, due to a floating point mismatch between float32 vs float64. Although this might be expected behaviour it's not very user-friendly and there seems to be iris precedent for warning users [eg. coordinate bounds](https://github.com/SciTools/iris/blob/478fa635a043da138a2f12905c7359739d94ff29/lib/iris/coords.py#L2216)

We actually often hear from users that Iris already raises too many warnings, and there is a risk that people become over saturated and don't know which warnings actually need their attention. We are therefore very reluctant to add further warnings unless we believe the majority of users need to be notified (and indeed we hope to reduce the volume of warnings in future). As [documented behaviour](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.html#iris.Constraint.extract), this isn't a case for which we want to add an Iris warning.

If there is specific behaviour that you need to be warned about, we recommend including your own warning, or perhaps [an assertion or exception](https://stefan.sofa-rockers.org/2018/04/16/assertions-and-exceptions/), in your own script(s).
