### ISSUE TITLE
Core dump when using contourf

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/iris#4730]
I am experiencing a core dump when using contourf of iris. This is an MWE:

```
import iris
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import iris.plot as iplt

lat_plot_deg = [45, 40]
lon_plot_deg = [0, 5]
values = [[0, 0], [0, 0]]
ax = plt.axes(projection = ccrs.EckertIII())
lat_coord = iris.coords.DimCoord(lat_plot_deg, standard_name = "latitude")
lon_coord = iris.coords.DimCoord(lon_plot_deg, standard_name = "longitude")
new_cube = iris.cube.Cube(values, dim_coords_and_dims = [(lat_coord, 0), (lon_coord, 1)])
print("Before.")
cf = iplt.contourf(new_cube)
print("After.")
```

OS: Ubuntu 20.04

Packages:
matplotlib 3.5.2
cartopy 0.20.2
scitools-iris 3.2.1

Any ideas how this could be solved?

**Comment by trexfeathers** [comment]
Hi @MHBalsmeier, thanks for getting in touch.

Unfortunately I can't replicate this in an environment with those exact versions (nor any other versions I've tried). So it could be:

* Operating system specific (I only have RHEL 7.9 available to me)
* Hardware specific

Did you create this install using [the instructions you wrote](https://scitools-iris.readthedocs.io/en/latest/installing.html#installing-from-source-without-conda-on-debian-based-linux-distros-developers)? There might be a problem that doesn't afflict Conda but does afflict other install methods 😅

**Comment by rcomer** [comment]
Is it definitely an Iris problem?  E.g. if you do

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

lat_plot_deg = [45, 40]
lon_plot_deg = [0, 5]
values = [[0, 0], [0, 0]]
ax = plt.axes(projection = ccrs.EckertIII())
print("Before.")
cf = plt.contourf(lon_plot_deg, lat_plot_deg, values)
print("After.")
```

does everything work?

**Comment by trexfeathers** [comment]
Sounds like it's going to be very difficult to help on this one 😔

None of the core team have easy access to a Debian instance, and we are also therefore inexperienced in such matters. You may well be one our most experienced Debian-based Iris users! The nature of the error also makes it hard to guess at likely causes.

@SciTools/developers any ideas?

**Comment by bouweandela** [comment]
> None of the core team have easy access to a Debian instance

You could run a [Docker](https://www.docker.com/) container: `docker run -it ubuntu:20.04`

**Comment by bouweandela** [comment]
@SciTools/iris-devs Regarding the installation instructions: I would recommend running a nightly test suite that tests all installation instructions, so you find out about installation problems before your users do.

**Comment by zklaus** [comment]
I think this is almost guaranteed *not* to be an Iris problem since Iris doesn't contain binary extensions. Instead, it is most likely due to incompatible dependencies, which in turn most probably happened via binary installs done by pip that conflict with system binaries, as @bouweandela pointed out.

To make sure this doesn't happen, @MHBalsmeier, you can try to run pip with the applicable `--no-binary` switch. For pip 22.0.4, that would be
```
pip install --no-binary ":all:"
```
but I don't know your version of pip or when this exact switch was introduced. If it doesn't work, have a look at `pip install --help`.
This will likely uncover some binary packages that are missing, which you can add to the apt install line, if available. If they are not available, I am afraid you are out of luck and your only options become using conda/mamba or adding the missing packages to the linux distribution. Packaging for Debian and/or Ubuntu is straightforward enough and having an Iris package in there would be mighty fine.

**Comment by trexfeathers** [comment]
>Packaging for Debian and/or Ubuntu is straightforward enough and having an Iris package in there would be mighty fine.

All the straightforward things add up to a lot of work; we have to choose which ones we do! It's good to know what interest there is, so thanks 😊

**Comment by MHBalsmeier** [comment]
@bouweandela Your problem is a dependency issue that has often been raised in cartopy since 0.20.0 came out. See my comment [here](https://github.com/SciTools/iris/issues/4468#issuecomment-997997068). cartopy wants proj>=8.0.0 but the Debian package gives you 6.something. So you have to install proj manually from source in order to use cartopy.

I did not put this into the installation instructions because I thought this problem might solve itself once the Debian package ships the newer version.

I found out that line 1009 in plot.py throws this, but not if you remove the 'transform' argument from the kwargs dictionary.

One more hint: I run a script that also throws this error every day in batch mode on a server. The problem occurred for the first time on May 4th. I update all Debian and python packagedsevery day. So it must be something that was released on May 3rd.
Too bad I do not have the log. When I saw the problem for the first time I thought it was matplotlib because it has had a release on May 3rd. But downgrading matplotlib did not help.

There must be something wrong in the code somewhere I think. The example is very simple and should work. I assume some low-level problem with array indices or so that does not occur in conda because conda might handle the details of memory allocation etc. differently. Might be, however, that this problem is not in iris but in matplotlib or who knows where.

**Comment by zklaus** [comment]
Re packaging, there is a healthy community that helps newcomers and for pure Python packages, they can usually be maintained by "the Python team". While there certainly is an expectation that people don't just show up, drop a package into everyone's lap and leave, it is perfectly normal that activity goes up and down and that people leave the team again.

To make progress here, could you determine which binary packages were installed by pip? It is exceedingly difficult to produce a segfault/core dump in a pure Python package with no underlying problem in a binary extension or library.

**Comment by MHBalsmeier** [comment]
@zklaus How do I determine which binary packages were installed by pip?
I just installed proj 9.0.0 manually from source (I had 8.0.0 before), but this did not solve it either.
Interesting that this is so hard to reproduce.

**Comment by rcomer** [comment]
> I found out that line 1009 in plot.py throws this, but not if you remove the 'transform' argument from the kwargs dictionary.

💡

I made a mistake in my script above.  Since the x and y points are latitudes and longitudes, there should have been `transform=ccrs.PlateCarree()` in the call to `contourf`.

**Comment by rcomer** [comment]
Shapely cut a release on the 3rd:
https://github.com/shapely/shapely/releases/tag/1.8.2

**Comment by rcomer** [comment]
This comment looks relevant 👀 https://github.com/SciTools/cartopy/issues/2006#issuecomment-1062135274

**Comment by MHBalsmeier** [comment]
@rcomer 
```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

lat_plot_deg = [45, 40]
lon_plot_deg = [0, 5]
values = [[0, 0], [0, 0]]
ax = plt.axes(projection = ccrs.EckertIII())
print("Before.")
cf = plt.contourf(lon_plot_deg, lat_plot_deg, values, transform=ccrs.PlateCarree())
print("After.")
```
This throws the error. So no iris problem.


> Shapely cut a release on the 3rd: https://github.com/shapely/shapely/releases/tag/1.8.2

Downgrading shapely to 1.8.1.post1 does not help ... but


> This comment looks relevant eyes [SciTools/cartopy#2006 (comment)](https://github.com/SciTools/cartopy/issues/2006#issuecomment-1062135274)

downgrading to 1.8.0 does. I want to find out more about this anyway, but since this is not an iris problem, I am closing this.
Thank you all!
