### ISSUE TITLE
Extend `expanduser` behaviour

### ISSUE THREAD

**Issue by wjbenfold** [SciTools/iris#4772]
## ✨ Feature Request

`iris.save` should expand `~` to e.g. `/home/wjbenfold`

## Motivation

I'm surprised when an iris save operation fails with a `PermissionError` because I've passed in a path starting with `~`, particularly having just successfully loaded a file from a path starting with `~`. Making this consistent would make using Iris easier and less surprising.

**Comment by rcomer** [comment]
👍 for making things consistent.
