### ISSUE TITLE
addition to Further Topics: Aux Factories and their Creation 

### ISSUE THREAD

**Issue by acchamber** [SciTools/iris#4788]
## 📚 Documentation

There's no documentation currently on how to use the iris.aux_factory module at the moment, either on creation of new factories or how to work with them in cubes. Seems a fitting topic for a Further Topics section? 

See related discussion https://github.com/SciTools/iris/discussions/4780_

**Comment by trexfeathers** [comment]
Thanks @acchamber. We consider Aux Factories to be among the most complex pieces of Iris' public API, with only a few niche uses, hence why we so far haven't gone beyond writing API docstrings.

Do you have some examples of when people want to use Aux Factories? It may be that the documentation should simply advise NOT using them (!), but we'd need to know more to be sure.

**Comment by acchamber** [comment]
So, the reason I had to figure out how to create them was that I had some grib data that is in model-level format, and I needed to feed it into a suite ethat required input data to have a hybrid-pressure coordinate. The grib cube came with the level pressure and sigma data as coordinates and I have another cube with the surface pressure data, so had to figure out the exact syntax to add the the hybrid pressure factory to my input data.

**Comment by acchamber** [comment]
@trexfeathers That sounds great. I don't know when I'll be able to get around to it, but my hope is this summer to do so (along with the other topics I've raised)
