### ISSUE TITLE
Addition to Further Topics: iris.analysis and You 

### ISSUE THREAD

**Issue by acchamber** [SciTools/iris#4789]
## 📚 Documentation

Iris.analysis can do alot more than MAX/MIN/MEAN, but that's all users are often aware it can do. A further topics section showcasing some more uses might increase that awareness. There is already a seed of this in the [API page](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/analysis.html) and the linked gallery sections, but moving some of it into a Further Topic section and adding some more text might improve awareness

https://github.com/SciTools/iris/discussions/4780_

**Comment by trexfeathers** [comment]
@acchamber would a highly visible link from [Cube Statistics](https://scitools-iris.readthedocs.io/en/stable/userguide/cube_statistics.html) to the [API page](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/analysis.html) do the trick?

Or is there some further detail that you believe would be helpful?

**Comment by acchamber** [comment]
I think it would certainly help, although they do highlight the flaw in how the documentation for iris is written. Unsurprisingly, programmers writing it have focused on the _abstract_ use case of a method in the broadest possible sense, while users are focused on what can iris _practically do_ to their data.

An example from that page 

> ## Partially Reducing Data Dimensions
> Instead of completely collapsing a dimension, other methods can be applied to reduce or filter the number of data points of a particular dimension.
>  ### Aggregation of Grouped Data
>  The [Cube.aggregated_by](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/cube.html#iris.cube.Cube.aggregated_by) operation combines data for all points with the same value of a given coordinate. To do this, you need a coordinate whose points take on only a limited set of different values – the number of these then determines the size of the reduced dimension. The [iris.coord_categorisation](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/coord_categorisation.html#module-iris.coord_categorisation) module can be used to make such ‘categorical’ coordinates out of ordinary ones: **The most common use is to aggregate data over regular time intervals, such as by calendar month or day of the week.**

Both the title and the subtitle are very vague and abstract - accurate descriptions of what they do, but not catching any users eye about why they care. The paragraph starts at a high level aswell. Only at the very end of the paragraph is the practical purpose of the operation revealed, when it is likely what the user is actually searching for - how to perform a certain manipulation on their data which matches their use-case.

**Comment by trexfeathers** [comment]
@acchamber that's an excellent point, and fits with the @SciTools/iris-devs' wider ambitions for the docs. We will hopefully make time to pick this up in future, but don't let that stop you putting up your own pull request if you feel able.
