### ISSUE TITLE
Reset GHA cache_build

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#4814]
## 📰 Custom Issue

This isn't an automated process, so this issue is a reminder to reset the GHAs `cache_build` back to `0` when the `cache_period` is greater than `2022.12`.

Where given a `cache_period` of `YYYY.PP`:
* `YYYY` is the calendar year
* `PP` is the week number of the year divided by `2` (currently) 

The `cache_period` of `2022.13` should occur from Monday 27 June 2022.

Reference: See #4809

**Comment by trexfeathers** [comment]
What's the value in cleaning this up? As far as I understand: it's just an arbitrary variable that allows us to 'kick the jukebox', with no intention that it means anything to developers. Can we not just leave it until we need it again?

Sorry if I've missed something.

**Comment by pp-mo** [comment]
> What's the value in cleaning this up? As far as I understand: it's just an arbitrary variable that allows us to 'kick the jukebox', with no intention that it means anything to developers. Can we not just leave it until we need it again?
> 
> Sorry if I've missed something.

Yes I thought this too.
I thought we can just leave it at 'cache_build = 1', for as long as we like.
Or, anytime we want, we can set it back to 0 as long as other signature items have since changed.

?no?

**Comment by bjlittle** [comment]
Sure, we absolutely could... I'm perhaps just being over-conscientious. Otherwise the `cache_build` just keeps getting bigger, and personally I'd prefer to see it only north of `0` by exception.

But, yeah, no harm, no foul.
