### ISSUE TITLE
Site Map?

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4828]
## 📚 Documentation

This is a documentation feature request!  Is it possible to get a site map within Sphinx, so you can see the whole docs structure laid out?  Often I know roughly where in the structure the page I'm looking for is, but not exactly.  So I find myself clicking around looking for it.

**Comment by tkknight** [comment]
There is a sphinx extension https://github.com/jdillard/sphinx-sitemap that creates a ``sitemap.xml`` that is used by search engines to know what pages exist.  I believe readthedocs does this [automagically ](https://docs.readthedocs.io/en/stable/hosting.html?highlight=sitemap#sitemaps) for us.

I think you are suggesting a single index page for all the docs - probably excluding the api stuff?  Do you have an example?

**Comment by rcomer** [comment]
> I think you are suggesting a single index page for all the docs

Yes that's what I meant though I don't know of other packages that do it.  Of course, you may prefer to ignore this issue until someone votes for it!
