### ISSUE TITLE
__init__.py file seems to be missing fileformats import

### ISSUE THREAD

**Issue by alisonpeard** [SciTools/iris#4868]
## 🐛 Bug Report
Cannot import fileformats. Seems to be because it is not included in the main __init__.py file for iris.

## How To Reproduce
Steps to reproduce the behaviour:

1.  install iris v3.2.1.post0
2. `import iris`
3. `iris.fileformats`

## Expected behaviour
`AttributeError: module 'iris' has no attribute 'fileformats'`

## Environment 
 - macOS 12.4
 - iris v3.2.1.post0

## Additional context
Adding `from iris import fileformats` to the main __init__.py file resolves the issue.

**Comment by pp-mo** [comment]
This is not really broken, it is just that we minimised all our imports, so "iris.fileformats" is no longer automatically imported when you simply "import iris". See [this note in the v3.1 release notes](https://scitools-iris.readthedocs.io/en/latest/whatsnew/3.1.html#incompatible-changes)

We have previously been caught out ourselves when subpackages that were previously "automatically present", then disappeared in later versions of a package.
I think our view of this is that all subpackages should be explicitly imported.
