### ISSUE TITLE
Viewing cube.data dtype without loading data

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#4876]
Hello, I have some code where I want to know the dtype of a cube's data but I would rather not load the data, as some of the files being read in are very large. I can't find a way to see cube.data.dtype without it triggering loading of the data - is there any way to do this?

**Comment by rcomer** [comment]
Hi @PAGWatson, you should be able to get the dtype off the cube itself.
```python
print(cube.dtype)
```
https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/cube.html#iris.cube.Cube.dtype

**Comment by PAGWatson** [comment]
Ah right, thanks, I swear I tried that and it didn't work - must have been my mistake. It's working now though :-)
