### ISSUE TITLE
`cf_profile` and `cf_patch`

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4891]
## 📰 Custom Issue

Because I am hoping to add some `pytest` style tests in Iris (#4792, #4889), I thought I should check what is in the `setUp` of our `IrisTest` class, that these `pytest` tests would be missing.  The only thing I found was

https://github.com/SciTools/iris/blob/08fe9c1fb18b753ee1293929db0435d58bdd31d3/lib/iris/tests/__init__.py#L150-L152

A documentation search on `cf_profile` only produces the [v1.3 whatsnew](https://scitools-iris.readthedocs.io/en/latest/whatsnew/1.3.html#customised-cf-profiles).  Does anyone know anything about these hooks?  If we think they are useful, they should probably be better documented.

**Comment by bjlittle** [comment]
Basically, they're a backdoor to allow customised behaviour for NetCDF that was Met Office specific i.e., an internal extension to the CF Metadata Conventions.

TBH I'd personally be in favour for dropping support for it

**Comment by trexfeathers** [comment]
I'm hoping @pp-mo might have an opinion when he's back?

**Comment by trexfeathers** [comment]
@SciTools/peloton believe this is here to override any local `site.cfg` settings. However `cf_profile` and `cf_patch` are no longer commonly used members of `site.cfg`, so this is unlikely to 'spike the wheel' of any developers.

So we're in favour of pulling these items out of test set up; most likely it will be fine.

Leaving this open until it has been tried!
