### ISSUE TITLE
Unpin shapely

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#4912]
#4911 has pinned shapely due to an error described here https://github.com/SciTools/cartopy/issues/2067 which caused errors in our documentation. This pin should be removed when this issue has been solved in cartopy or shapely.

**Comment by trexfeathers** [comment]
Closed in #4925

**Comment by trexfeathers** [comment]
> Closed in #4925

No it hasn't, we'll still need to do a merge-back from the `v3.3.x` branch.

**Comment by pp-mo** [comment]
> > Closed in #4925
> 
> No it hasn't, we'll still need to do a merge-back from the `v3.3.x` branch.

Done! #4944
