### ISSUE TITLE
Iris import error

### ISSUE THREAD

**Issue by NMC-DAVE** [SciTools/iris#4938]
## 🐛 Bug Report

Hi guys:
        When I use `import iris` and call `iris.fileformats.netcdf.save` function,
I get the following error. So why? Thanks very much.

`
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

# get no attribute error
>>> import iris
>>> iris.fileformats.netcdf.save
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'iris' has no attribute 'fileformats'

# can call function correctly
>>> import iris.fileformats
>>> iris.fileformats.netcdf.save
<function save at 0x7f207981c9d0>
`

**Comment by trexfeathers** [comment]
Hi @NMC-DAVE, this was an explicit decision in #4714 - to improve performance. But we're aware it's controversial! You can read more here: https://github.com/SciTools/iris/issues/4868#issuecomment-1189106247

**Comment by NMC-DAVE** [comment]
Thanks very much.
