### ISSUE TITLE
Enable lazy evaluation in iris.analysis.cartography.rotate_winds

### ISSUE THREAD

**Issue by tinyendian** [SciTools/iris#4943]
### Discussed in https://github.com/SciTools/iris/discussions/4934

<div type='discussions-op-text'>

<sup>Originally posted by **tinyendian** August 26, 2022</sup>
Dear Iris developers,

I am currently working on enabling out-of-core computation in a file format conversion tool that uses Iris to load CF-netCDF data. Everything is working fine, including Iris regridding, but I noticed that the `rotate_winds` function in the cartography module is not currently lazy evaluation-enabled, so it will force wind field cube data to be loaded.

With a few straightforward modifications, I was able to enable lazy evaluation, including array masking. So I was wondering if there is any interest in this? I'd be happy to contribute an issue and pull request with the necessary changes. There seem to be more functions in the cartography module without lazy evaluation, though.</div>

As per @pp-mo's comment, a pull request with the required changes for enabling lazy evaluation would be welcome, so I'll create one soon.

**Comment by trexfeathers** [comment]
This was closed by #4972
