### ISSUE TITLE
Reinstate "CubeList._repr_html_" method.

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#4973]
## How To Reproduce
`CubeList([])._repr_html_()` ought to produce an html string, 
but instead fails with a simple
`AttributeError: 'CubeList' object has no attribute '_repr_html_'`

## Notes
Seems to be a bug introduced [in #4767](https://github.com/SciTools/iris/pull/4767#discussion_r974490539)

We already [test the behaviour of `CubeListRepresentation.repr_html()`](https://github.com/SciTools/iris/blob/main/lib/iris/tests/unit/experimental/representation/test_CubeListRepresentation.py#L56-L65)
But tests don't call `CubeList._repr_html_` itself.

Fix should include a test that `CubeList._repr_html_` 
  1. exists, 
  2. creates a `CubeListRepresentation`, and 
  3. calls its `repr_html`
(can be mock-ist)

**Comment by rcomer** [comment]
This was done at #4976 and merged back into `main` at #5004.
