### ISSUE TITLE
rotated pole data plots incorrectly for a grid_north_pole_longitude = 0

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#4978]
## 🐛 Bug Report
Rotated pole data with grid_north_pole_longitude=0 and a grid_north_pole_latitude=90 do not plot correctly

## How To Reproduce
Steps to reproduce the behaviour:

1. load the file at /data/users/fris/rpole_0_issue/failing.nc
2. plot data with pcolormesh
3. appears over New Zeland when the data is in fact for Africa
4. edit the file so that grid_north_pole_longitude=180 /data/users/fris/rpole_0_issue/ok.nc
5. plot data again - appears in the correct location

## Expected behaviour
I would expect that as the north pole latitude is 90N the pole longitude should be irrelevant. ncview get this correct

## Screenshots
3 plots:
1. ncview of failing.nc 
![image](https://user-images.githubusercontent.com/6161374/191688962-5a0e8f91-3069-47bc-b377-45e4a472c0e6.png)
2. iris quckplot.pcolormesh for failing,nc 
![image](https://user-images.githubusercontent.com/6161374/191689184-9e743bbc-f990-4a8d-af3e-f3d2552dd767.png)
3. iris quckplot.pcolormesh for ok.nc
![image](https://user-images.githubusercontent.com/6161374/191689233-4e3ad244-264d-42cb-86d2-216559c817b1.png)

## Environment 
 - VDI
 - reprducable for iris 2.4.0 and 3.2.1 (default/current)

## Additional context

<details>
<summary>Click to expand <b>this section...</b></summary>

```
import iris
import iris.quickplot as qplt
import matplotlib.pyplot as plt


for file in ['failing.nc', 'ok.nc']:
    data = iris.load_cube(file)
    qplt.pcolormesh(data[0,...],cmap='Blues')
    plt.gca().coastlines()
    plt.title(file)
    plt.show()
```
</details>

**Comment by nhsavage** [comment]
this looks to be a similar issue in a different tool https://code.mpimet.mpg.de/boards/1/topics/8564 

the explanation for panoply is "The data are on a rotated-pole projected grid, as defined by the attributes of the "rotated_pole" variable. That var indicates that the rotated north pole is at -180°E 90°N. This might look to the casual observer as if it means that there is no rotation of the pole at all. However, Panoply understands this to mean that the primary meridian is to be rotated 180° of longitude. "

I have to say I am confused by the CF definition here:

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_rotated_pole 

```
Rotated pole

grid_mapping_name = rotated_latitude_longitude

Map parameters:
        grid_north_pole_latitude
        grid_north_pole_longitude
        north_pole_grid_longitude - This parameter is optional (default is 0).
```

it does not explain what the difference between grid_north_pole_longitude and north_pole_grid_longitude  is...

**Comment by bsherratt** [comment]
> I have to say I am confused by the CF definition here:
> 
> http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_rotated_pole

I was confused too, but then discovered that the definitions for *all* grid mapping attributes are grouped together in a table, after the mappings themselves. The table doesn't have a header, so it isn't in the contents, and I can't even get a direct link to it!

Anyway, from an initial look, it seems like this may have something to do with CF having parameters for "true latitude/longitude of the north pole of the rotated grid", but [proj](https://proj.org/operations/projections/ob_tran.html#parameters) only having parameters for "latitude/longitude of the north pole of the unrotated source CRS, expressed in the rotated geographic CRS.

So [cartopy](https://github.com/SciTools/cartopy/blob/11987150a8350b0d66f9f18f7bee1dccc47e4ea0/lib/cartopy/crs.py#L1928-L1933) has to translate these in some way, and it's possible that the current solution may fall down in this edge case. I'm struggling to think it through though.

*However*... if you `plt.show()` those examples and mouse-over the map, to see the projected and unprojected coordinates, cartopy actually believes that your data covers exactly the same range in both cases. So it is somehow incorrectly projecting the coastlines, but correctly projecting the mouse position (?)

**Comment by rcomer** [comment]
Possibly same issue? https://github.com/SciTools/cartopy/issues/2091

**Comment by nhsavage** [comment]
> Possibly same issue? [SciTools/cartopy#2091](https://github.com/SciTools/cartopy/issues/2091)

looks like it. I assumed it was probably a cartopy issue not an Iris one as such, but I wanted to record this issue and didn't have time to dig into cartopy. If that can be fixed, it might close this.

**Comment by nhsavage** [comment]
Looking at the thread on [SciTools/cartopy#2091](https://github.com/SciTools/cartopy/issues/2091) it seems like that this is about the definition used in these files not actually matching the CF conventions. If that is the case, this is a not a bug. I'd welcome a chance to discuss further. But if we can agree this is the case, this ticket could be closed, and for ESMValTool where we have this problem, we should add a fixer into the pre-processors.

**Comment by bjlittle** [comment]
@SciTools/peloton Thanks @nhsavage for the update.

How did you want to proceed and who should be involved in the conversation?

**Comment by nhsavage** [comment]
I think that the first thing we need to do is close cartopy issue above by 
a. adding the promised extensions to the documentation in cartopy
b. contacting the CORDEX community to make them aware of these differences and implications for how they make netCDF files for the southern hemisphere domains

I also need to review those documents and then convince myself that this CORDEX file is wrong. If that is the case, then when using ESMValTool we should write a fixer for this specific dataset (and others with this problem)

**Comment by bjlittle** [comment]
> I also need to review those documents and then convince myself that this CORDEX file is wrong. If that is the case, then when using ESMValTool we should write a fixer for this specific dataset (and others with this problem)

@nhsavage Have you managed to find time to follow this though and understand if this is a CORDEX issue? Thanks 👍

**Comment by nhsavage** [comment]
I didn't have time to check. I find the CF definitions here very confusing. I also note thatjust make things even more interesting there is a difference between the defintition used in Grib files by WMO and CF.

**Comment by larsbarring** [comment]
Just a couple of quick comments:

@vsherratt [wrote](https://github.com/SciTools/iris/issues/4978#issuecomment-1263796852):
> I was confused too, but then discovered that the definitions for all grid mapping attributes are grouped together in a table, after the mappings themselves. The table doesn't have a header, so it isn't in the contents, and I can't even get a direct link to it!

In recent versions of the conventions there is a List of Tables (after the TOC) and here you can find a direct link to Table F.1. [Grid Mapping Attributes](https://cfconventions.org/cf-conventions/cf-conventions.html#table-grid-mapping-attributes).


Yes, I agree that the difference between the grib and CF way of representing the rotated pole easily cause confusion. But that is how things are (and have been since forever) . The way forward is to be specific in documentations and always specify whether it is the North or the South Pole. {ping @gnikulin and @larsbuntemeyer re. CORDEX domain specs.). As was noted earlier in this issue the problem was noted in the [Cartopy issue](https://github.com/SciTools/cartopy/issues/2091). 

I think that with rather small changes to documentation this confusion can easily be substantially reduced. 

I leave the possible need to improve the CF text on the subject for another time.

**Comment by nhsavage** [comment]
This is not really related to https://github.com/SciTools/cartopy/issues/2091 as such - although exploring those issues has helped me better understand what is happening here. 

It also has nothing to do with the Grib issue 

The correct definition for The Africa CORDEX rotated pole is RotPole (180.0; 90.0) https://cordex.org/domains/region-5-africa/ which is consistent with the pacthed /data/users/fris/rpole_0_issue/ok.nc 

The original data file has 
	char rotated_pole ;
		rotated_pole:long_name = "coordinates of the rotated North Pole" ;
		rotated_pole:grid_mapping_name = "rotated_latitude_longitude" ;
		rotated_pole:grid_north_pole_latitude = 90. ;
		rotated_pole:grid_north_pole_longitude = 0. ;

which is not consistent with the CORDEX Africa definition. 

My expectation that the value of the longitude of the rotated pole when when the latitude is zero is wrong, it controls where the meridian of the rotated pole grid is. 

The third optional piece of CF metadata: north_pole_grid_longitude adds more confusion here as it is effectively redundant in this case, but can be useful in some circumstances (although rarely used and defaults to zero if not set). 

I conclude that the problem is indeed with the metadata in the original file and I should now be able to close this issue but I will do some last tests first:

1. check that the fixed files'  2D lat and lon match the ones generated by cartopy from the grid information
2. see what happens in ncview if those 2D lat and lon are removed from the original file (I expect it will not be able to plot a map and it is in fact using the 2D lat and lon to do the plotting)
3. do plots of this domain with grid_north_pole_longitude  set to 0, 90, 180 and 270 to show the importance of this parameter

**Comment by nhsavage** [comment]
![Africa-270](https://github.com/SciTools/iris/assets/6161374/a4b3d19c-189f-4b47-ad4a-479a5c901f92)
![Africa-90](https://github.com/SciTools/iris/assets/6161374/75fbfa8f-a7f3-4eb7-b681-63018ff09b96)
![Africa-0](https://github.com/SciTools/iris/assets/6161374/399868f7-33b9-4360-8f0e-9542f56fe54e)
![Africa-180](https://github.com/SciTools/iris/assets/6161374/28a2ff4e-e195-4580-b1d7-fde71215c753)
 
Plots of Africa domain with all 4 values of grid_north_pole_longitude which shows the importance of this and that the correct value is 180

**Comment by nhsavage** [comment]
![Africa-270](https://github.com/SciTools/iris/assets/6161374/c67f9dff-80b5-45bb-958c-1138a77fee8f)
![Africa-90](https://github.com/SciTools/iris/assets/6161374/062d17e2-0c81-4391-b6f4-a6a2b3ee32f1)
![Africa-180](https://github.com/SciTools/iris/assets/6161374/795599aa-6b7f-4936-9527-3275b7df75b3)
![Africa-0](https://github.com/SciTools/iris/assets/6161374/40754f14-58fa-4f63-95ea-c8b02a6bf46c)
Images showing importance of grid_north_pole_longitude

**Comment by nhsavage** [comment]
testing the lat and lon from cartopy in the two files - failing.nc
```python
>>> glat = cube.coord('grid_latitude').points
>>> glon = cube.coord('grid_longitude').points
>>> x, y = np.meshgrid(glon, glat)
>>> cs = cube.coord_system()
>>> lons, lats = iris.analysis.cartography.unrotate_pole(x, y, cs.grid_north_pole_longitude, cs.grid_north_pole_latitude)
>>> lons[0,0]
155.25
>>> cube.coord('longitude').points[0,0]
-24.75
```

so the metadata and the 2D lons are inconsistent. Repeating for ok.nc:
```python
>>> lons[0,0]
-24.75000000000004
>>> cube.coord('longitude').points[0,0]
-24.75
>>> cube.coord('longitude').points[-1,-1]
60.38999938964844
>>> lons[-1,-1]
60.38999938964846
>>> 
```
so close enough. 

The problem is clearly with the metadata in the source file so closing this ticket

**Comment by trexfeathers** [comment]
Thanks so much for your hard work on this, @nhsavage 👍
