### ISSUE TITLE
Rethink "extra" user info sections

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#4990]
## 📚 Documentation
Since #4661, what were "Iris Technical Papers" ([were here](https://scitools-iris.readthedocs.io/en/v3.0.0/techpapers/index.html)), are now moved to be part of the "Developer docs" ([now here](https://scitools-iris.readthedocs.io/en/stable/techpapers/index.html))
The existing items here are :
  1. "Iris Handling of PP and Fieldsfiles", and
  2. "Missing Data Handling in Iris"

Meanwhile, with #3890, the User Guide has gained an extra "Further Topics" section, now containing:
  1. "Metadata"
  2. "Lenient Metadata"
  3. "Lenient Cube Maths", and 
  4. "Mesh Support"

I think the result is now a bit confused + inappropriate :  None of the above are really developer-specific information, and the information sections like "Metadata" and "Mesh Support" are if anything of _less_ general interest than the former "Technical Papers".

So I think these could usefully **_all_** go in the "Further Topics" section of the User Guide.  

**What does anyone else think of this ?**
@bjlittle @tkknight @trexfeathers

**Comment by pp-mo** [comment]
Some possible problems, though ?
  * the older "technical papers" might want some rewrite to unify the styles a bit
  * the "metata" sections look like they might usefully be grouped together.  But I don't know if sections + subsections are easily achievable here ?

**Comment by trexfeathers** [comment]
My personal instinct would be a dedicated heading for Further Topics and Technical Papers combined. But I'm not certain how that fits with the '4-quadrant' approach researched by @jamesp and @wjbenfold.

**Comment by wjbenfold** [comment]
I'm not about to completely redesign the docs (probably) but will happily opine on them a bit:

* Making a call about what's important for users and what's important for devs (can we use different words, given that users might consider themselves devs? Anyway...) seems sensible. I'd expect some users to benefit from an understanding of why choices have been made and the mental models behind them, so maybe there will be more in the user section than we'd expect. There could always be stubs in the dev bit that linked to the user bit?
* I think we'd ideally be using a 4-quadrant style of **tutorials**, **how-tos**, **reference** and **explanation** - to me I think further topics tends to fall into explanation (leaving api docs as the reference). Based on that, and based on a quick skim of the contents of both, I'd stick them all in a "explanation" or "background information" or something. There might be an argument for having explanations for users and explanations for devs, though it seems like they're all user-type ones?

**Comment by rcomer** [comment]
> can we use different words, given that users might consider themselves devs? 

I think there was talk at one point about rebranding the Developer’s Guide to the Contributor’s Guide.

**Comment by trexfeathers** [comment]
> My personal instinct would be a dedicated heading for Further Topics and Technical Papers combined. 

#5602 ✅
