### ISSUE TITLE
Attempting to collapse a scalar coordinate raises an exception

### ISSUE THREAD

**Issue by isedwards** [SciTools/iris#50]
Currently the user must perform an additional check to see whether the coordinate is scalar or dimensioned before attempting a collapse.

cubecol = cube.collapsed('time',iris.analysis.MEAN)

"... iris/cube.py",
line 1839, in collapsed
    raise iris.exceptions.CoordinateCollapseError('Cannot
collapse a dimension which does not describe any data.')

**Comment by dkillick** [comment]
This is...
 (a) old, and
 (b) not a problem, IMO.

Off it goes closed, then.
