### ISSUE TITLE
Cube subtraction duplicates coordinates

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#5065]
Hello, I found that when subtracting one cube from another, each with an auxiliary 'time' coordinate (not a dimension coordinate), that the 'time' coordinate on the resultant cube is duplicated. This causes an error if trying to use the 'time' coordinate later. I guess it may need to be removed from the resultant cube, though. Edit to add - I found this occurs in iris 3.3.1 and 3.0.4.

The use case is that I've computed a seasonal cycle from two datasets, with 'Month number' being the dimension coordinate and want to look at the difference. The calendars are different (one is 360 day and the other 365 day), which I think means the mean 'time' values for each month become slightly different and so the coordinates are unequal, which I guess has something to do with the coordinates being duplicated. 

I've given the code and attached a file with the starting cubes below. 

I actually also had the same problem with the 'month' aux coordinate in my case, but this isn't replicated in the example, the difference being that in my code the 'month' coordinate is added after loading the data with iris.coord_categorisation.add_month() for one cube and was included in the loaded data with the other - it seems that saving and reloading data including a particular aux coordinate can give it different properties to what it had before saving, and this means the coordinate is duplicated when doing subtraction with a cube where the coordinate has been added in the latter way (particularly, a unit of 'no_unit' is changed to 'unknown' in this case) - it would be ideal if saving and reloading didn't change the properties of aux coordinates.

[demo_seascyc.zip](https://github.com/SciTools/iris/files/10003669/demo_seascyc.zip)

```
import iris
seascyc_mean=iris.load_cube('demo_seascyc.nc')
seascyc_mean_ref=iris.load_cube('demo_seascyc_ref.nc')

print([coord.name() for coord in seascyc_mean.aux_coords])
print([coord.name() for coord in seascyc_mean_ref.aux_coords])
print([coord.name() for coord in (seascyc_mean-seascyc_mean_ref).aux_coords])
print()
print(seascyc_mean.coord('time'))
print()
print(seascyc_mean_ref.coord('time'))
```

The output I get is:
```
['latitude', 'longitude', 'month', 'time']
['latitude', 'longitude', 'month', 'time']
['latitude', 'longitude', 'month', 'time', 'time']

AuxCoord :  time / (days since 1840-12-01 00:00:00, 360_day calendar)
    points: [
        2000-01-16 00:00:00, 2000-02-16 00:00:00, 1999-09-16 00:00:00,
        1999-10-16 00:00:00, 1999-11-16 00:00:00, 1999-12-16 00:00:00,
        2000-01-16 00:00:00, 2000-02-16 00:00:00, 2000-03-16 00:00:00,
        2000-04-16 00:00:00, 2000-05-16 00:00:00, 1999-12-16 00:00:00]
    shape: (12,)
    dtype: float32
    standard_name: 'time'
    var_name: 'time'
AuxCoord :  time / (day since 1979-01-01, standard calendar)
    points: [
        2000-01-15 00:00:00, 2000-02-15 00:00:00, 1999-09-14 00:00:00,
        1999-10-15 00:00:00, 1999-11-14 00:00:00, 1999-12-15 00:00:00,
        2000-01-14 00:00:00, 2000-02-14 00:00:00, 2000-03-16 00:00:00,
        2000-04-15 00:00:00, 2000-05-16 00:00:00, 1999-12-15 00:00:00]
    shape: (12,)
    dtype: float64
    standard_name: 'time'
    var_name: 'time'
```

**Comment by trexfeathers** [comment]
Hi @PAGWatson, thanks for getting in touch. We believe this is the correct, expected behaviour. You are correct to focus on the differences in calendar between the two coordinates - Iris will never reconcile this because it needs human input to know the right answer, so instead it outputs both coordinates so that you can solve how you see fit (e.g. removing one/both).

You may be interested to read about [Lenient Cube Maths](https://scitools-iris.readthedocs.io/en/stable/further_topics/lenient_maths.html), which provides a number of tools to help reconcile such differences.

**Comment by trexfeathers** [comment]
>I actually also had the same problem with the 'month' aux coordinate in my case, but this isn't replicated in the example, the difference being that in my code the 'month' coordinate is added after loading the data with iris.coord_categorisation.add_month() for one cube and was included in the loaded data with the other - it seems that saving and reloading data including a particular aux coordinate can give it different properties to what it had before saving, and this means the coordinate is duplicated when doing subtraction with a cube where the coordinate has been added in the latter way (particularly, a unit of 'no_unit' is changed to 'unknown' in this case) - it would be ideal if saving and reloading didn't change the properties of aux coordinates.

If this is a problem for you, would you mind raising a separate issue as the discussions will go in two different directions. Thanks!

**Comment by PAGWatson** [comment]
Sorry for the delay in getting back here - I hit a busy period.

Re "it outputs both coordinates so that you can solve how you see fit (e.g. removing one/both)" - the duplicated time coord can't be removed it seems. If I do
```
diff=seascyc_mean-seascyc_mean_ref
diff.remove_coord('time')
```
then I get error
`CoordinateNotFoundError: 'Expected to find exactly 1 coordinate, but found 2. They were: time, time.'`

I feel that this shouldn't happen e.g. the time coords on `diff` should be given different names e.g. `time_source1` and `time_source2` ('source' referring to the source cubes).

**Comment by rcomer** [comment]
You could remove just one of those time coordinates from the diff cube by e.g.
```python
tcoord_360d = seascyc_mean.coord("time")
diff.remove_coord(tcoord_360d)
```
or remove both by
```python
for tcoord in diff.coords("time"):
    diff.remove_coord(tcoord)
```
or just remove either or both from the input cubes before you take the difference.

**Comment by PAGWatson** [comment]
Thanks for the response. I find needing to do this unintuitive and user-unfriendly, though - and I've been using iris for years, so I imagine it's much worse for newer users. Isn't the point of iris to remove the need for doing this sort of faff, so we can get on with doing science?

**Comment by trexfeathers** [comment]
@PAGWatson I appreciate the difficulty of removing the coordinate. I would suggest filtering through the `Cube`'s coordinates, identifying the coord-to-remove by checking the `calendar` attribute, then passing that `Coord` instance into `remove_coord()`.

>Isn't the point of iris to remove the need for doing this sort of faff, so we can get on with doing science?

Indeed. The trouble is that sophisticated conveniences risk just moving the "faff" onto someone else's workflow. We'd much prefer that users such as yourself make upstream changes to prevent this from happening, such as removing/modifying the offending coordinate(s).

If you activate Strictness (see [Lenient Cube Maths](https://scitools-iris.readthedocs.io/en/stable/further_topics/lenient_maths.html)), you can force Exceptions in circumstances like this - to avoid downstream confusion until the necessary upstream fixes have been made.

Out of interest: what would your ideal general solution to this problem look like?

**Comment by PAGWatson** [comment]
My idea was to keep both time coordinates and give them different names (see above) (it would make sense to raise a warning too). Well, I'll leave it up to you.
