### ISSUE TITLE
Improve regridding documentation (which regridder should I use?)

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#5093]
## 📚 Documentation

The existing documentation is good for giving an introduction to the basic ideas of regridding, but it is difficult to find out which regridding method is most suitable for a particular case.

There should be a page which goes through the pros and cons of different regridders and which types of data they are suitable for (it would also be worth mentioning iris-esmf-regrid here).

**Comment by trexfeathers** [comment]
Would be great to get feedback from a user as well as a developer
