### ISSUE TITLE
DOCS: Remove sphinx temporary maximum pin

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#5123]
## 📰 Custom Issue

Remove the temporary maximum `pip` pin `sphinx<5` introduced into the `setup.py` by #5122

**Comment by tkknight** [comment]
Tested an unpin of sphinx **09/11/23**.  

The docs built without error with sphinx 7.2.6 locally and on readthedocs (currently pinned to 5.3).  The only issue I have found is that the voted issues table (via [datatables.net](https://datatables.net/)) fails to render, pressing F12 in the web browser shows the errors:

![image](https://github.com/SciTools/iris/assets/2108488/226039fd-47d7-4f04-adbf-10c98c0a661b)

I am unable to fix this at present.  We can either wait a bit longer to see if a future update fixes this or we could look to remove the voted tables use of datatables and just link directly to github (which now allows sorting by reactions).
