### ISSUE TITLE
Enable ReadTheDocs build for each PR 

### ISSUE THREAD

**Issue by tkknight** [SciTools/iris#5124]
## 📚 Documentation

This topic has be raised a few times and now I think we should trial it.

This issue has been raised to track the change as it is a checkbox on the Read the Docs config panel:

![image](https://user-images.githubusercontent.com/2108488/210414331-c2b6eeaa-d45e-4e08-a3e1-a2e1529e8f94.png)

Once enabled any future **pull requests** (or updates to existing?) will have any extra check that shows the build status on ReadTheDocs.  This will help up catch any Iris doc build failures quickly.

I propose to enable this on **04/01/23**.  If there is any issues then we can easily just **uncheck** this feature on Read the Docs.

**Comment by tkknight** [comment]
Just enabled.  More info: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by trexfeathers** [comment]
This has already proved quite useful. Could we think about closing this issue?

**Comment by pp-mo** [comment]
💐 🥳
