### ISSUE TITLE
Re-licensing iris from LGPL to BSD-3

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#5148]
To enable wider adoption of Iris, we are working on re-licensing it to be the more flexible BSD-3 license. 

Before we can do this we need all previous contributors to sign the latest SciTools Contributors License Agreement (CLA) as this includes a clause stating that the SciTools libraries can be re-licensed to any other OSI approved license. 

If your username appears below, could you please sign the updated CLA (Google Form) which can be found here: https://scitools.org.uk/cla/v4/form 

- [ ] @andreas-h
- [x] @ajdawson 
- [x] @mir06 
- [x] @cvelascof 
- [x] @cbcunc 
- [x] @duncanwp 
- [x] @jswanljung 
- [x] @philippjfr 
- [x] @SimonPeatman 
- [ ] @shoyer 
- [x] @bascrezee 

This form is also linked from the SciTools Governance page: https://scitools.org.uk/organisation.html#governance
 
Once all contributors listed above have signed the new CLA we will re-license Iris to BSD-3.

**Comment by philippjfr** [comment]
Signed.

**Comment by mir06** [comment]
Signed.

**Comment by duncanwp** [comment]
Done!

**Comment by jswanljung** [comment]
Signed. I only contributed a small feature 7 years ago and am no longer in the field, but contributing to iris was very enjoyable. Everyone was so friendly and supportive and the process was so well thought out. Thanks!6 feb. 2023 kl. 09:57 skrev lbdreyer ***@***.***>:﻿
To enable wider adoption of Iris, we are working on re-licensing it to be the more flexible BSD-3 license.
Before we can do this we need all previous contributors to sign the latest SciTools Contributors License Agreement (CLA) as this includes a clause stating that the SciTools libraries can be re-licensed to any other OSI approved license.
If your username appears below, could you please sign the updated CLA (Google Form) which can be found here: https://scitools.org.uk/cla/v4/form

 @andreas-h
 @ajdawson
 @mir06
 @cvelascof
 @cbcunc
 @duncanwp
 @jswanljung
 @philippjfr
 @SimonPeatman
 @shoyer
 @bascrezee

This form is also linked from the SciTools Governance page: https://scitools.org.uk/organisation.html#governance
Once all contributors listed above have signed the new CLA we will re-license Iris to BSD-3.

**Comment by shoyer** [comment]
I would be happy to sign in my personal capacity, but I believe I previously signed this form on behalf of my former employer (climate.com). Feel free to reach out to me directly at shoyer@gmail.com if this is the case and I can see I can help find someone to authorize this.

**Comment by bascrezee** [comment]
Signed.

**Comment by lbdreyer** [comment]
> I would be happy to sign in my personal capacity, but I believe I previously signed this form on behalf of my former employer (climate.com). Feel free to reach out to me directly at [shoyer@gmail.com](mailto:shoyer@gmail.com) if this is the case and I can see I can help find someone to authorize this.

Yes, I think your former employer may be considered as the first owner of the copyright at least for anything you contributed as part of your employment so it may make sense to get authorisation from them. I will contact to you directly to discuss this further

**Comment by trexfeathers** [comment]
Important info regarding @andreas-h:

https://www.iup.uni-bremen.de/lamos/Andreas-Hilboll.html

**Comment by lbdreyer** [comment]
We are very close to being able to move Iris to the BSD-3 license!

There are a couple of contributors that have not yet signed the new CLA, so I am going to retry contacting those that are outstanding.

The plan is to **relicense Iris after Monday 16th October 2023** so you have until that date to get in touch! If we have not heard from you before that date we will assume that you are happy with the change, and will proceed with the relicensing.

Note that, as BSD-3 is an open source license so moving Iris from LGPL to BSD-3 still meets the open source objectives all past contributors originally agreed to. Nonetheless, if you have any queries regarding the re-licensing please let me know before **Monday 16th October 2023**
