### ISSUE TITLE
micromoles per kilogram is an invalid unit

### ISSUE THREAD

**Issue by uliw** [SciTools/iris#5157]
## How To Reproduce

1. cubes = iris.load("https://www.ncei.noaa.gov/data/oceans/woa/WOA18/DATA/phosphate/netcdf/all/1.00/woa18_all_p00_01.nc")  
2. will complain that "micromoles_per_kilogram" in an invalid unit

## Expected behavior
micromoles_per_kilogram (or, more generally, moles/kg) is a standard unit for oceanographic data; as such it would be great if it could be parsed correctly.

## Additional context
From other posts, I understand that this is likely a limitation in the unit parsing library.  I did not look into the code, so this may be naive, but would it be possible that users could provide a custom function for unit parsing that is passed as an argument to the load function? Or that a more general unit parsing library is being used (something along the line of e.g. pint which allows the user to add custom units to the unit registry)?

**Comment by trexfeathers** [comment]
Hi @uliw, thanks for getting in touch. `micromoles_per_kilogram` is indeed an invalid unit; there are many valid forms of this, the closest of which would be: `micromoles per kilogram`.

If you are unable to fix this within the file then you could use a callback during loading - [see here for examples](https://scitools-iris.readthedocs.io/en/latest/userguide/navigating_a_cube.html#adding-and-removing-metadata-to-the-cube-at-load-time).

**Comment by uliw** [comment]
Ah, I did not see this. So the call back takes care of the units, but the warning remains. Is there a way to avoid those warnings as well?

**Comment by uliw** [comment]
never mind, just found the warnings library

**Comment by trexfeathers** [comment]
> never mind, just found the warnings library

Glad to hear it. Iris generates many types of warnings, so we're hoping in future to improve user awareness of warning filters, as well as improving Iris to make this as easy as possible.

**Comment by bjlittle** [comment]
@uliw Thanks for raising this issue, we're going to close it now.

Please re-open if you have further concerns, cheers! :beers:
