### ISSUE TITLE
`HDF5-DIAG` warnings from libnetcdf `v4.9.1`

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#5187]
## 📰 Custom Issue

Since #5177, NetCDF loading is prompting verbose `HDF5-DIAG` warnings in some/all cases; [here is an example](https://github.com/SciTools/iris/actions/runs/4348704062/jobs/7597539846#step:12:618).

@pp-mo and I have done some testing and isolated this to the advancement of libnetcdf from `v4.8.1` to `v4.9.1`.

As far as we can tell this is probably innocuous, a view tentatively shared in pydata/xarray#7549. However it is going to start alarming developers and users alike, and will be a source of frustration given how verbose Iris' own warnings are as well. We've already had a case where it gets in the way of other print statements and thus makes ordinary work that much harder.

So far not sure what the next step is, but wanted to post this to forewarn everyone else.

**Comment by pp-mo** [comment]
> advancement of libnetcdf from v4.8.1 to v4.9.1

Again tentatively, from https://github.com/pydata/xarray/issues/7549 it looks like the actual problem may lie in hdf5 changes introduced with hdf5 v1.12.2 
That version of hdf5 has already been out for months, but we suspect the libnetcdf changes may have newly "exposed" the problem.

**Comment by pp-mo** [comment]
>  I don't think that caused any of the test failures there ... and pinning to libnetcdf=4.8 removed all the offending HDF5 warnings

However, I do now seem to have [python 3.10 specific failures](https://github.com/SciTools/iris/pull/5191#issuecomment-1464137637).
Which I think may indicate that pinning libnetcdf is not a panacea as it may introduce **actual errors** 😬

**Comment by pp-mo** [comment]
Ping !

Latest main-branch doctests are really full of the HDF5-DIAG warning messages
E.G. : https://pipelines.actions.githubusercontent.com/serviceHosts/85610251-844a-4a1d-8171-bd20e30f9c14/_apis/pipelines/1/runs/4455/signedlogcontent/6?urlExpires=2023-03-27T00%3A35%3A51.0247240Z&urlSigningMethod=HMACV1&urlSignature=9tcPZXK%2B%2Bov5smdX5IBtQ4z5s41u5Y%2BANwxBJcsfJOc%3D

Could this also be the basic reason we are getting benchmark regressions ?
We really need to seek a solution to this.

**Comment by trexfeathers** [comment]
Poll:

- https://github.com/SciTools/iris/discussions/5213

**Comment by trexfeathers** [comment]
Relevant: https://github.com/pydata/xarray/issues/7388#issuecomment-1511596653

**Comment by zklaus** [comment]
I resolved this in the conda-forge package for libnetcdf 4.9.2 in conda-forge/libnetcdf-feedstock#175. Would it be useful to have it for 4.9.1 as well? The backport would be easy enough, but it's always a little bit of a hassle to release older versions. Would pinning to `!=4.9.1` be an option?

**Comment by trexfeathers** [comment]
> I resolved this in the conda-forge package for libnetcdf 4.9.2 in [conda-forge/libnetcdf-feedstock#175](https://github.com/conda-forge/libnetcdf-feedstock/pull/175). Would it be useful to have it for 4.9.1 as well? The backport would be easy enough, but it's always a little bit of a hassle to release older versions. Would pinning to `!=4.9.1` be an option?

Thanks @zklaus!

That's definitely a sensible option.

We will take a look next week. Getting a lot of conflicts with different PR's updating dependencies today.

**Comment by trexfeathers** [comment]
I've tested this locally and it's looking good! In a meeting now so will push up in an hour or so.
