### ISSUE TITLE
Use of Grib level type = 1 ('surface')

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#519]
Originally the PR https://github.com/SciTools/iris/pull/482 proposed accepting input data with a levelType of 1, aka "ground or water surface" as having essentially _no_ associated vertical coordinate, and also to **assign this level-type on output**, for an output cube with no vertical coordinate.
Notes:
- This levelType=1 is distinct from types 102 (aka "Specific altitude above mean sea level", in units "m") and 103 (aka "Specified height level above ground", in units "m").
- As levelType=1 has no unit, and so no associated value, it seems _strictly_ to represent a value "at" the surface.
- This leveType therefore also presumably can have no second surface (though this is also not explicitly stated in the spec).
- We have no way of representing such a "surface level" concept within Iris itself (i.e. in CF terms), distinct from a stated "height=0" (which as noted above is a distinct representation within Grib).
- There is no obvious statement in the Grib spec about data with **no** stated vertical coordinate whatever.  But example data we have available (both Grib1 and Grib2) seems to indicate that such data tends to have levelType=1.  This includes parameters which actually seem incapable of being specified "at" a vertical level, such as cloud fractional areas ("total", "upper" and "lower"), and "height of cloudbase".

@bblay has pointed out that assigning this on output may be tantamount to "inventing" metadata.
(see discussions in https://github.com/SciTools/iris/pull/482).

On 2013-05-21, @marqh, @munslowa, @bblay and @pp-mo met to discuss this at length.

We considered and rejected an alternative approach of creating a non-CF "cube attribute" marker (e.g. "cube.attributes['grib_level_type'] = 1"), which would allow forcing the levelType on output.  This could work automatically for through-processing of Grib input to Grib output data, as required by the original usecase motivating the PR.  In other cases, it would require _explicit_ setting by the user to enable saving to Grib of 'ordinary' Iris cubes with no vertical coordinate.

The meeting concluded, after much discussion, that most pragmatic approach for now **is** to treat this as analagous to "no vertical coordinate" in Iris, and provide this for both input (Grib1 at least) and output (Grib2).

**Therefore, we will be following this up with a request for clarification to the Grib "community" and standards sub-committee, and will review the decision when when have a more authoritative position to implement.**

**Comment by pp-mo** [comment]
We are not using this, and there have been no further calls for it to be introduced, 
 -- Seven years later (!)
so I think this is now a dead issue.

**Comment by jkalkhof** [comment]
I ran into this same problem of not being able to save geopotential height at 500mb and used this solution for iris:
https://groups.google.com/g/scitools-iris/c/D2InfYESaUM
`cube.add_aux_coord(iris.coords.DimCoord(500, "height", units="m"))`
