### ISSUE TITLE
Using a miniforge environment, iris can load data from .nc file but with a lot of errors

### ISSUE THREAD

**Issue by penmaher** [SciTools/iris#5195]
## 📰 Custom Issue

I have found that miniforge is unable to load an iris cube without errors but interestingly miniconda can. I thought I would raise this as an issue, though it is not explicitly an iris code issue but a python environment/library dependency issue.

A minimum working example is as follows:

import iris
import glob
filename = iris.sample_data_path('ostia_monthly.nc')
f1 = glob.glob(filename) 
cube = iris.load_cube(f1)
var = cube.data

When the above code is run using a miniforge environment (see py3.10 env), the error attached in the txt file is generated
[error.txt](https://github.com/SciTools/iris/files/10958865/error.txt). But when I run the same code using a minconda environment (see py3.10conda env) the code executes without error.

For context, here is the python environments I have been working with (using the Ubuntu 22.04 OS).

1. Working in a miniforge environment at version 22.9.0-2 which was set up using the following:

   [ https://github.com/conda-forge/miniforge/releases/download/22.9.0-2/Miniforge-pypy3-Linux-x86_64.sh](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconda-forge%2Fminiforge%2Freleases%2Fdownload%2F22.9.0-2%2FMiniforge-pypy3-Linux-x86_64.sh&data=05%7C01%7Cp.maher%40exeter.ac.uk%7Ce3a6285d9fe1421432e008db1f30b83f%7C912a5d77fb984eeeaf321334d8f04a53%7C0%7C0%7C638138066332839380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b1cfYvwKD6FWRCNkmo%2Bl9tbhksiFNv9Gx6mYKu0WbAA%3D&reserved=0)

2. Created a python environment at version 3.10:

    conda create -n py3.10 python=3.10

    conda install cube_helper iris pandas

What did work, was using a miniconda environment instead:

1.  Working in a miniconda environment at version 23.1.0-1 which was set up using the following:

   [ https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Linux-x86_64.sh](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepo.anaconda.com%2Fminiconda%2FMiniconda3-py310_23.1.0-1-Linux-x86_64.sh&data=05%7C01%7Cp.maher%40exeter.ac.uk%7Ce3a6285d9fe1421432e008db1f30b83f%7C912a5d77fb984eeeaf321334d8f04a53%7C0%7C0%7C638138066332839380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JRR9vb0sgxXXX1EBn6vYwwWDJyyUEEaVvCLM0mpPVUU%3D&reserved=0)

 2. create a python environment at version 3.10

    conda create -n py3.10conda python=3.10

    conda install pandas

    conda install -c conda-forge cube_helper iris

**Comment by pp-mo** [comment]
For ref. the errors in the file look like this ...
```
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
 . . .
  ((and lots more similar))
```
