### ISSUE TITLE
Cartopy projection from a cube

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#5219]
## ✨ Feature Request

A convenience function to get an appropriate Cartopy projection from a cube.

## Motivation

When plotting a map to the current axes, `iris.plot` has [some logic](https://github.com/SciTools/iris/blob/2056703a0a84d1b9ee9f6e314e38c2156a8988b0/lib/iris/plot.py#L930-L965) that figures out the appropriate Cartopy projection and uses it to set up a Cartopy GeoAxes to plot onto (if the current axes isn't already a Cartopy one).  This is super convenient and I use it all the time.  However, it relies on Matplotlib's implicit API, which is [not really how Matplotlib recommends doing things these days](https://matplotlib.org/stable/users/explain/api_interfaces.html#why-be-explicit).

If this logic could be factored out into its own public function, then users who want to use the recommended explicit API could do so without losing too much convenience.

```python
cartopy_proj = shiny_new_function(cube)
ax = fig.add_subplot(projection=cartopy_proj)
iplt.contourf(cube, axes=ax)
```

## Additional context

I realise there isn't much to this logic, and I could just write my own convenience function for my own use.  However, I think it's worth Iris making it as easy as possible for users to follow the recommended practice.

**Comment by pp-mo** [comment]
Why can't you use `cube.coord_system().as_cartopy_crs()` or `cube.coord_system().as_cartopy_projection()` ??

**Comment by rcomer** [comment]
> Why can't you use `cube.coord_system().as_cartopy_crs()` or `cube.coord_system().as_cartopy_projection()` ??

I think that is illustrated in [the logic that `iris.plot` currently uses](https://github.com/SciTools/iris/blob/2056703a0a84d1b9ee9f6e314e38c2156a8988b0/lib/iris/plot.py#L930-L965): sometimes there isn't a coord system on the cube, in which case we default to `PlateCarree()`.  There are also some extra complications for `RotatedGeogCS`, though admittedly I've never knowingly used that.
