### ISSUE TITLE
Errors caused by times not convertible to datetime

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#5237]
## 🐛 Bug Report

Time coordinates can sometimes have units which will cause an error when you try and convert thier points to datetimes. For example, when the units are in "years since date" format. This causes an error when plotting against this time axis or when printing a cube with a scalar coordinate of this form. In such cases, it might be appropriate to represent the raw points (and raising a warning) rather than failing outright.

This could potentially by solved by adding try/except in places like here:
https://github.com/SciTools/iris/blob/b2b4e3ba89a745f851c4d724c137b3f4e4641f92/lib/iris/coords.py#L2166-L2169

**Comment by rcomer** [comment]
Think https://github.com/SciTools/cf-units/pull/279 may be relevant here.
