### ISSUE TITLE
grib follow-up

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#525]
Following on from #482, which was merged in a hurry without the finishing touches, implement the things that we didn't have time for:

switch
https://github.com/SciTools/iris/pull/482#issuecomment-18398670

255 vs -1 (note: -1 is necessary for longs, might be better to have a variable)
https://github.com/SciTools/iris/pull/482#commitcomment-3282025
https://github.com/SciTools/iris/pull/482#commitcomment-3282029
https://github.com/SciTools/iris/pull/482#commitcomment-3282082

misc
https://github.com/SciTools/iris/pull/482#discussion_r4380862
https://github.com/SciTools/iris/pull/482#discussion_r4380929
https://github.com/SciTools/iris/pull/482#discussion_r4381555
https://github.com/SciTools/iris/pull/482#discussion_r4381350

bigger issues
https://github.com/SciTools/iris/pull/482#issuecomment-18411883

**Comment by pelson** [comment]
Closing this as obsolete. Pretty much re-written as part of the new grib interface. Code now maintained in the scitools/iris-grib repository.
