### ISSUE TITLE
plot on map by default when only 2D lat/lon present

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#529]
this is an extension of #463

``` Python
import iris
import iris.tests as tests
import matplotlib.pyplot as plt
plt.switch_backend('TkAgg')
import iris.plot as iplt

filename = tests.get_data_path(('NetCDF', 'rotated', 'xy',
                                'rotPole_landAreaFraction.nc'))

cube = iris.load_cube(filename)

print cube

plt.subplot(311)
iplt.contourf(cube)

cube.remove_coord('grid_latitude')
cube.remove_coord('grid_longitude')
plt.subplot(312)
iplt.contourf(cube)

plt.subplot(313)
iplt.contourf(cube, coords=['longitude', 'latitude'])
plt.show()
```

![no_map](https://f.cloud.github.com/assets/2071643/591375/8ae0d09c-ca00-11e2-8f8f-45530736fc5a.png)

Currently its only plotted on a map when the coordinates are specified for the case that only a 2D lat/lon is present.

Assigned: cpelley

**Comment by rcomer** [comment]
Iris 2.4 gives me this, so I think this is done.
![test](https://user-images.githubusercontent.com/10599679/93493732-268a3a80-f904-11ea-8ff9-6407573d61db.png)
