### ISSUE TITLE
Tidying up old branches

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#5317]
I noticed we have accrued [quite a few branches](https://github.com/SciTools/iris/branches/all). 

While it can be helpful to keep release branches (e.g. v3.4.x) in case we need to put out a bug fix for that release, it is unlikely we will be doing so for such old releases.

Therefore, I propose we delete the following branches:
* v2.4.x
* v3.0.x
* v3.1.x
* v3.2.x
* pp-mo-patch-1

If you have an objection to this, **please respond by 22nd May 2023**, otherwise I will go ahead and delete the above branches.

**Comment by trexfeathers** [comment]
@lbdreyer pointed out in offline conversation that it would still be possible to bugfix older releases by branching off release commits. We certainly wouldn't expect the older release branches to have un-released commits, so I'm comfortable with this pattern.

**Comment by lbdreyer** [comment]
This has now been done, leaving us with 7 branches:

![image](https://github.com/SciTools/iris/assets/8101163/57cea1cb-13ce-49f6-8c55-8a9f805d1e2c)
