### ISSUE TITLE
Repopatch with numpy !=1.24.3 pin

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#5329]
Hey guys, it may be a good idea to do a repopatch with `numpy !=1.24.3` pin, one of our users got some really funky results )from the severe masking bug in 1.24.3) and caught a perfect storm: ESMValCore has the pin but we've not yet released a bugfix release to conda, and he caught iris=3.5 just shy of 3.6 (that now does, indeed, contain the pin) :+1: PS; I've just checked the numpy feedstock and there is not even a trace of a PR to up the version to 1.24.4 just yet

**Comment by bjlittle** [comment]
@valeriupredoi Fair call, thanks.

If it's causing pain, and clearly it is, then I'd agree that making a repo-patch would be helpful to the community in general.

On it 👍

**Comment by valeriupredoi** [comment]
@bjlittle great many thanks :beer: 90% of the times iris=3.6.0 will be picked up in an up to date env, but you never know what older deps with pins pepeople have that'll grab iris<3.6 :grin: Lemme know if I can help with this!

**Comment by bjlittle** [comment]
@valeriupredoi No bother.

Given the `numpy` dependencies and pinning history within `iris`, I may only patch 3.2.0 <= `iris` < 3.6.0.

That seems reasonable enough to me.

**Comment by valeriupredoi** [comment]
sounds like a good plan, Batman :bat:

**Comment by bjlittle** [comment]
Reference https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/455

**Comment by bjlittle** [comment]
@valeriupredoi I'm gonna close this issue since https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/455 is now merged.

Obviously, reopen if the patch didn't work.

Cheers! 👍
