### ISSUE TITLE
lenient intersetion_of_cubes()

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#5330]
## ✨ Feature Request
An LFRic eastward wind cube has a pressure coord with slightly more metadata than the UM one (see attached image). This causes `_dimensional_metadata_comparison()`, and therefore `intersection_of_cubes()`, to incorrectly think the coords different.

I can work around this but wanted to suggest that this could be improved by allowing `intersection_of_cubes()` to be [lenient](https://scitools-iris.readthedocs.io/en/stable/further_topics/lenient_metadata.html).

A quote from a scientist, as a second opinion: _"...one feature of Iris that bugs me a bit is how fussy it is with the meta data needing to be exactly the same"_.

<img width="352" alt="coord_metadata" src="https://github.com/SciTools/iris/assets/2048530/3c990876-02f6-4bf6-ab14-45ebb1668969">

**Comment by bjlittle** [comment]
Awesome, thanks @bblay for raising this issue :beers

**Comment by rcomer** [comment]
`intersection_of_cubes` is deprecated in favour of [the `extract_overlapping` method](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.cube.html#iris.cube.CubeList.extract_overlapping), which appears to only care about the coordinate names.  Is that better for your use-case @bblay?
