### ISSUE TITLE
Broken git links in developer guide

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#5336]
## 📚 Documentation

Our [Development Workflow](https://scitools-iris.readthedocs.io/en/latest/developers_guide/gitwash/development_workflow.html) page has various links to documentation for git commands.  Those links are defined here:

https://github.com/SciTools/iris/blob/299b335facde9525656a18b00a521ef5694da316/docs/src/developers_guide/gitwash/git_links.inc#L16-L28

http://schacon.github.com gives a 404.

It's ignored by the linkcheck

https://github.com/SciTools/iris/blob/299b335facde9525656a18b00a521ef5694da316/docs/src/conf.py#L379

**Comment by rcomer** [comment]
My original thought when I saw this was that we should update these links to point to equivalent documentation on another site.  But now I’m thinking maybe we should just remove them: git is a lot more mainstream than it was a decade ago, and I think we can reasonably expect contributors to google* those commands if they want more details.

*other search engines are available

**Comment by tkknight** [comment]
https://github.com/SciTools/iris/pull/5569 created to remove the broken git links.

**Comment by rcomer** [comment]
Closed by #5569.
