### ISSUE TITLE
Change the default version of the documentation to stable rather than latest on ReadTheDocs

### ISSUE THREAD

**Issue by jfrost-mo** [SciTools/iris#5373]
## 📚 Documentation

Currently the default version for the documentation on readthedocs is latest, which is the documentation for the next, unreleased version of Iris. This should be changed to the stable, which is the most recent release.

Because the unreleased documentation is the default, it is what is directed to when you visit the top of the domain ([scitools-iris.readthedocs.io](https://scitools-iris.readthedocs.io/)), as well as affecting the [canonical URL](https://docs.readthedocs.io/en/latest/canonical-urls.html#how-read-the-docs-generates-canonical-urls), which makes search engines point to the unreleased documentation over the stable docs.

The current behaviour is both confusing, and [not recommended](https://docs.readthedocs.io/en/latest/guides/best-practice/links.html#questionable-practice). Fortunately it can be changed fairly easily in the [ReadTheDocs web interface](https://readthedocs.org/projects/scitools-iris/). The [setting](https://docs.readthedocs.io/en/latest/config-file/v2.html#migrating-from-the-web-interface) is `Admin` > `Advanced settings` > `Default version`.

**Comment by pp-mo** [comment]
Thanks @jfrost-mo, I have thought the same on occasion -- I think this is a good idea !
And I think it's easily fixed in the RTD project settings, as you say.

**Does anyone have other views ?**
If not I shall switch it + we can see how it goes.

**Comment by pp-mo** [comment]
Ok, no anguished responses, so let's try it.
I fixed this in the RTD settings, and the link in top right of the GitHub repo.
@jfrost-mo I think that should do it -- **does that look better to you ?**

**Comment by jfrost-mo** [comment]
Yep, that looks good, redirecting properly to the stable docs. Search engines still point to the latest version, but that should hopefully change after a few days.
