### ISSUE TITLE
More calendars than just 'standard', '360-day' and '365-day'

### ISSUE THREAD

**Issue by HoWol76** [SciTools/iris#5378]
https://github.com/SciTools/iris/blob/5b42f47e71fbeb7861a9df59c8bd8c0be9a340e3/lib/iris/fileformats/pp_load_rules.py#L551

My code just fails as it tries to read in a file with a calendar type 'proleptic_gregorian'

`cf_units` has several calendars:
```
CALENDAR_STANDARD = "standard"
CALENDAR_GREGORIAN = "gregorian"
CALENDAR_PROLEPTIC_GREGORIAN = "proleptic_gregorian"
CALENDAR_NO_LEAP = "noleap"
CALENDAR_JULIAN = "julian"
CALENDAR_ALL_LEAP = "all_leap"
CALENDAR_365_DAY = "365_day"
CALENDAR_366_DAY = "366_day"
CALENDAR_360_DAY = "360_day"
```

I just have this issue when I try to load an orography file, which has set the year to 0.

**Comment by rcomer** [comment]
I think this might be part of the same problem as #3561, and I have an open pull request for that at #5138.  @HoWol76 are you able to try loading your file with my branch?  The original issue is rather old, so we have been unsure how to test my change in a real-world situation.

**Comment by trexfeathers** [comment]
From @SciTools/peloton:

@HoWol76 does it look to you like @rcomer's PR is indeed addressing the same problem?
