### ISSUE TITLE
Document NetCDF loading chunk control

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#5400]
Follow on from #5399?

- [ ] Add documentation (e.g. docstrings, user guide content) for work completed in #5399. **Target the same feature branch as that work**
- [ ] Merge the feature branch to `main`.

**Comment by ESadek-MO** [comment]
(WIP) 

- [ ] Add user guide sections of Chunk Control
- [ ] Fix docstring tests
- [ ] Double check all changes have good docstrings
