### ISSUE TITLE
CI Stale Bot for Dragons

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#5411]
## 📰 Custom Issue

The CI stale bot should recognise the dragon labels https://github.com/SciTools/iris/labels/Dragon%20%F0%9F%90%89 and https://github.com/SciTools/iris/labels/Dragon%20Sub-Task%20%F0%9F%A6%8E i.e., items tagged with these labels should not be labelled as stale

**Comment by trexfeathers** [comment]
For anyone that has the necessary 15 minutes:

https://github.com/SciTools/iris/blob/b5f43fbd4ce22c8ed708c3d9c5769a927f689d56/.github/workflows/stale.yml#L65-L71

**Comment by agriyakhetarpal** [comment]
Happy to take this!

**Comment by rcomer** [comment]
Thanks @agriyakhetarpal!  Please go ahead 😃
