### ISSUE TITLE
earth_radius for spherical earth

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#551]
A Cf NetCDF file with a grid mapping which only specifies

```
int simple_crs ;
    orca1_crs:grid_mapping_name = "latitude_longitude" ;
    orca1_crs:earth_radius = 6371229 ;
```

does not load, returning error:

```
return iris.coord_systems.GeogCS(major, minor, inverse_flattening)
File "/net/home/h04/itmh/scitools/iris/lib/iris/coord_systems.py", line 138, in __init__
raise ValueError("No ellipsoid specified") 
ValueError: No ellipsoid specified
```

this is a CF compliant specification of a spherical ellipsoid and should be loaded correctly

this looks like a bug in the CF pyke rules interpreter to me.

**Comment by pp-mo** [comment]
This was addressed -- closed by #763
The test [here](https://github.com/SciTools/iris/blob/077df3ec15530255df80c2fc330eb21998e24769/lib/iris/tests/test_netcdf.py#L528) shows that we do now accept an "earth_radius" property in place of the "semi_major" key.
