### ISSUE TITLE
Avoid numpy deprecation for scalar array comparison

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#5627]
A user finds that in some cases, saving to a netcdf file can cause the warning
```
/net/project/ukmo/scitools/opt_scitools/conda/deployments/default-2023_10_10/lib/python3.10/site-packages/iris/fileformats/netcdf/saver.py:307: 
FutureWarning: elementwise comparison failed; returning scalar instead, 
but in the future will perform elementwise comparison contains_value = arraylib.any(data == check_value)
```
I.E. [at this line](https://github.com/SciTools/iris/blob/v3.7.0/lib/iris/fileformats/netcdf/saver.py#L307) (occurring in Iris 3.7.0)

Worth fixing, but I expect the same problem may occur elsewhere

**Comment by trexfeathers** [comment]
#4374 returns 😅

**Comment by pp-mo** [comment]
False alarm, really !
This FutureWarning is well explained [here](https://stackoverflow.com/a/46721064/2615050)
But it was replaced by [changed behaviour in release 1.13](https://numpy.org/doc/stable/release/1.13.0-notes.html#futurewarning-to-changed-behavior)
