### ISSUE TITLE
iris grib2 loading not writting parameter codes to cube

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#563]
When there is no parameter translation available, iris is supposed to assign various grib parameter code information to the cube.

This means that one phenomena on the same grid can be differentiated from another.  A consequence of this is that iris may merge different phenomena together.

Data file is copyrighted, will create a suitable example ASAP

**requested tags; high priority, grib, bug**
**Assigned: cpelley**
_internal ref: WO49559_

**Comment by pp-mo** [comment]
This problem has gone, since we now create attributes to track the original file parameters, i.e. https://github.com/SciTools/iris-grib/pull/156
