### ISSUE TITLE
Add functionality to allow appending cubes to existing netcdf file

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#565]
Currently writing Iris data to netcdf creates a new file.    In the case where we are using Iris to process a large amount of data (in my case a 30 year global hindcast), we need to be able process timestep-by-timestep and append the processed result at each timestep to the existing netcdf file, as we don't have enough computer memory to hold all the timesteps at once.   An example of what we would like to do is here, using NetCDF4 to append, but we would like to be able to accomplish this with Iris.

http://nbviewer.ipython.org/5777643

The relevant code snippet is:

```

nc = netCDF4.Dataset('cfsr.nc','r+')
for i in range(10):
    url='http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/\
cmd_ocnh/2009/200905/200905%2.2d/ocnh01.gdas.200905%2.2d00.grb2' % (i+1,i+1)
    print url
    cubes = iris.load(url)
    t = cubes[4]
    slice=t.extract(iris.Constraint(longitude=lambda cell: -77.+360. < cell < -63.0+360.,latitude=lambda cell: 34. < cell < 46.0))
    nc.variables['Potential_temperature'][i,:,:,:]=slice.data
```

**Comment by arulalant** [comment]
Is this #565 open ? 

cubes = [temperature, pressure, humidity]
for cube in cubes:
    iris.save(cube, 'myfile.nc', append=True)

Still I couldn't append cubes (list of different variables) into nc file.

Thanks,
Arulalan.T

**Comment by rhattersley** [comment]
> Is this #565 still open ?

Yes, but I'm not aware of anyone working on a fix. Sorry!

**Comment by pp-mo** [comment]
I've been meaning for ages to respond to this.

I spent quite a while a few months back trying to implement an append, mostly focussed on @rhattersley case #1, 
i.e. **_specifically_** appending to all the relevant variables along an unlimited dimension.

It's a natural usecase, e.g. to open a file and add "today's data" to it, especially as the necessary operation exists in netcdf (without requiring you to read+re-write all the existing, even by streaming it).

I spent quite a while climbing the mountain of "decoupling the saving code from actual file operations", so it instead produces an abstract representation of the required (new) data, 
With this, I could then either create new variables or extend existing ones.
Working code ideas here : https://github.com/pp-mo/iris/pull/51

However, when I then sought to use this to define a file-append function, I hit big problems in unambiguously relating the "new data" to the existing content in a file, and **_especially_** in guaranteeing that the proposed append operation will be correct and safe
... which you **_really_** need, as we expect the existing dataset to typically be large and old, so when modifying it without first taking a copy, you really can't afford to fail halfway through !!

So, the resulting checking routine got awfully intricate, and I never completed the work.
Sample of WIP here : https://github.com/pp-mo/iris/pull/52
See especially these routines : 
 * https://github.com/pp-mo/iris/blob/a6e86dce88e721c084c96c4c43d13225fc5289fc/lib/iris/fileformats/netcdf.py#L2432
 * https://github.com/pp-mo/iris/blob/a6e86dce88e721c084c96c4c43d13225fc5289fc/lib/iris/fileformats/netcdf.py#L2452


So, I conclude that, if we really want this, it would far better be based on a lower-level append operation acting on general netcdf files, with no CF concepts involved.
  * E.G. I think there is append functionality in the CDO code.
  * .. or how about in xarray ?

But equally, I came to really doubt the wisdom of the whole idea...  
If it's really so hard to be sure you are not about to trash the existing precious file, maybe **_taking a copy just isn't so terrible_** ??

**Comment by pp-mo** [comment]
I'm going to finally close this, as I don't think we are going to do it.
We are currently intending to improve Iris/Xarray interoperability, 
we are planning to trial a much better lazy-data-preserving data-exchange 
so I expect that in future that will be the appropriate way to support incremental writes.
See for context : https://github.com/SciTools/iris/pull/4835#issuecomment-1172198937
