### ISSUE TITLE
DOCS: What's New in Iris link does not show the sidebar at all in latest.

### ISSUE THREAD

**Issue by tkknight** [SciTools/iris#5686]
## 📚 Documentation

From the [docs homepage](https://scitools-iris.readthedocs.io/en/latest/index.html), the [What's New in Iris](https://scitools-iris.readthedocs.io/en/latest/whatsnew/index.html#) link does not show the sidebar at all in latest.  Renders ok in v3.7.

## [Latest](https://scitools-iris.readthedocs.io/en/latest/whatsnew/index.html)

No sidebar on the left.
![image](https://github.com/SciTools/iris/assets/2108488/17d0231a-908a-4f07-b034-dcbf45bd334b)

## [Iris v3.7](https://scitools-iris.readthedocs.io/en/v3.7.0/whatsnew/index.html)

Sidebar with links on the left (intended behavciour).
![image](https://github.com/SciTools/iris/assets/2108488/c74c0291-e56c-4ef8-868a-06e33c751d37)

**Comment by tkknight** [comment]
Renders ok when building latest locally.  Only appears to an issue building and serving from reatthedocs?

**Comment by tkknight** [comment]
Iris v3.7 uses `pydata-sphinx-theme-0.13.3` https://github.com/SciTools/iris/blob/v3.7.0/requirements/locks/py311-linux-64.lock#L276

Iris latest uses `pydata-sphinx-theme-0.14.4` https://github.com/SciTools/iris/blob/main/requirements/locks/py311-linux-64.lock#L219C62-L219C62, **last updated 18/12/23**.

Local dev build uses `pydata-sphinx-theme-0.15.1`.

**Comment by tkknight** [comment]
This issue is also present in the [Developers Guide](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_getting_involved.html#)

**Comment by tkknight** [comment]
This maybe down to the behavior of the **toctree**  ``:hidden:`` option

**Comment by trexfeathers** [comment]
> **Iris v3.7** uses `pydata-sphinx-theme-0.13.3` https://github.com/SciTools/iris/blob/v3.7.0/requirements/locks/py311-linux-64.lock#L276
> 
> **Iris latest** uses `pydata-sphinx-theme-0.14.4` https://github.com/SciTools/iris/blob/main/requirements/locks/py311-linux-64.lock#L219C62-L219C62 **lock file last updated 18/12/23**.
> 
> **Local dev** build uses `pydata-sphinx-theme-0.15.1`.

Also of note is that Read the Docs cannot use a lock file, so is running Mamba against the YAML file. RTD is therefore often the 'canary in the coal mine', experiencing problems before any of our other CI. RTD is also getting `pydata-sphinx-theme-0.15.1` ([taken from this build](https://readthedocs.org/projects/scitools-iris/builds/23076227/)):

![image](https://github.com/SciTools/iris/assets/40734014/0d3de7cf-ad27-4883-b74d-b78a4c3350c4)

**Comment by tkknight** [comment]
Issue has resolved itself.
