### ISSUE TITLE
Document loss of attributes when using iris.analysis.maths

### ISSUE THREAD

**Issue by isedwards** [SciTools/iris#569]
ASSIGNED: **iedwards**

Update the API (and possibly user guide) to warn users that attributes will 
not be transferred when using the `iris.analysis.maths` methods.

e.g. the following attributes would all be removed when running the sample code below:

Attributes:
      STASH: m01s00i004
      source: Data from Met Office Unified Model 7.03

```
cube = iris.analysis.maths.exponentiate(cube, 2):
```

Also, change instances of:
   `Whether to add an entry into the resulting cube’s “history” coordinate.`
to:
   `Whether to add an entry into the resulting cube’s “history” attribute.`

**Comment by rcomer** [comment]
Looks like the recent changes to metadata handling have sorted this.  If I do

```python
import iris

cube = iris.cube.Cube(1)
cube.attributes = dict(foo='bar', baz=42)
print(iris.analysis.maths.exponentiate(cube, 2))
```
under Iris 2.4 I get
```
unknown / (unknown)                 (scalar cube)
```
but under Iris 3.0.dev0 I get
```
unknown / (unknown)                 (scalar cube)
     Attributes:
          baz: 42
          foo: bar
```
