### ISSUE TITLE
Should a cube be considered equal to itself?

### ISSUE THREAD

**Issue by bouweandela** [SciTools/iris#5705]
## Motivation

At the moment, a cube where the data contains a NaN is not considered equal to itself or to another cube with the same data. Conversely, coordinates/cell measures/ancillary variables with NaNs are equal to themselves. Maybe it would be nicer, and more consistent, to introduce the same behaviour for cubes.

See https://github.com/SciTools/iris/pull/5691#discussion_r1457455386 for some previous discussion.

**Comment by trexfeathers** [comment]
Xref: #4681

**Comment by bouweandela** [comment]
Thanks for getting back on this. I would be happy to make a PR.
