### ISSUE TITLE
Categorisation functions should make lazy coordinates

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#5729]
It looks like functions such as such as `iris.coord_categorisation.add_month` don't create lazy coords.
Worse, they may actually [realise the existing coords which they reference](https://github.com/SciTools/iris/blob/5e009719cbaccaa567c5699572905442dcfdcc6f/lib/iris/coord_categorisation.py#L69) ?

**Comment by acchamber** [comment]
I Think it does. All the builtins use the _pt_date function, which requires calling the 'cftime.num2date' function on every time point in the coord. each operation is indervidually a few milliseconds, vectorized with numpy, but you can't avoid getting the points realised before using num2date

**Comment by bouweandela** [comment]
I'm all data that I've seen so far, time is a DimCoord, so it already has realized data. Unless you have data with a very high temporal resolution, I don't expect much memory saving or performance gain from making this lazy. Or am I missing something?

**Comment by ESadek-MO** [comment]
@SciTools/peloton We can't remember why this was raised, and can't currently find a driver to do this. We'll close this issue, and if anyone objects, feel free to reopen.
