### ISSUE TITLE
Load GDAL compatible grids into Iris as Cubes

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#573]
Use GDAL behind the scenes to convert any of the GDAL Raster Formats to an Iris cube, giving Iris the ability to read GeoTIFF, ERDAS, ArcGIS, GMT, etc grids (full list at: http://www.gdal.org/formats_list.html)

**Comment by ajdawson** [comment]
@cpelley - This issue should be transferred to [Scitools-incubator/iris-raster](https://github.com/SciTools-incubator/iris-raster/issues), then closed here.

**Comment by pelson** [comment]
> @cpelley - This issue should be transferred to Scitools-incubator/iris-raster, then closed here.

Let's get ``iris-raster`` off the ground first (lift-and-shift), then add usecases once it has some content 😄 .

**Comment by trexfeathers** [comment]
@SciTools/peloton believe this need is now served by xarray/rasterio, so we're closing. Please comment if you'd like to see this re-opened.
