### ISSUE TITLE
Cube printout should not compute lazy scalar coordinates

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#5743]
To address #5723

We've accepted in the discussion there that we really don't want complex lazy calculations performed each time you print a cube.  
Nor would we like it to "realise" a scalar coordinate, so it only happens once, since you really wouldn't expect printing to _modify_ a cube.

It seems reasonable instead to just print something like "complex_scalarvalue_coord: \<lazy\>" in this case.
The user could of course realize it, if + when the value is actually _wanted_. 

Note: IMHO this is not a major change, and can just be done
  -- we have changed printout format before without considering it a breaking change.
Also relevant here : _most_ scalar coords, ones loaded from files, are not lazy, since #5229 
( so in many/most cases, adopting this _won't_ change the output )

**Comment by bouweandela** [comment]
Does this issue mean that there is consensus that this is the right approach? And if yes, is this is something @fnattino and I could help with implementing and/or reviewing?

**Comment by pp-mo** [comment]
> Does this issue mean that there is consensus that this is the right approach? And if yes, is this is something @fnattino and I could help with implementing and/or reviewing?

Yes, and Yes, I think!
I wrote this after last week's Peloton meeting, so we did get to generally discuss the options + this was our choice.

N.B. I just edited the comment as I realised the "\<lazy>" part didn't come out in markdown!

**Comment by ESadek-MO** [comment]
@SciTools/peloton Closed in #5896
