### ISSUE TITLE
Coverage upload is failing from forked repositories

### ISSUE THREAD

**Issue by bouweandela** [SciTools/iris#5915]
## 🐛 Bug Report

The coverage upload to codecov is failing with the following messages:
```
info - 2024-04-16 14:46:32,664 -- The PR is happening in a forked repo. Using tokenless upload.
info - 2024-04-16 14:46:32,899 -- Process Commit creating complete
error - 2024-04-16 14:46:32,899 -- Commit creating failed: {"detail":"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 749 seconds."}
```

see e.g. [here](https://github.com/SciTools/iris/actions/runs/8707590169/job/23882911444?pr=5801)

**Comment by trexfeathers** [comment]
You'll be interested to hear that it is coverage that makes testing the latest Python version twice as slow as the other Python versions. Can't tell if it is the coverage processing during testing, or the communication with the codecov service, but the proof is in these two GitHub actions:

- [`8525890403`](https://github.com/SciTools/iris/actions/runs/8525890403) - where 3.11 was the latest Python version
- [`8694666011`](https://github.com/SciTools/iris/actions/runs/8694666011) - where 3.12 was the latest Python version

**Comment by bouweandela** [comment]
Interesting, so it could be coverage collection then. The upload to codecov is a separate step in the workflow, so that is not the cause.

**Comment by bjlittle** [comment]
@SciTools/peloton Awaiting whether codecov backtrack or fix this issue for the community.

**Comment by trexfeathers** [comment]
Can we copy the format used in iris-grib?

```
      - name: "upload coverage report"
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

**Comment by bjlittle** [comment]
We can give it a try ... I'll push the change 👍

**Comment by pp-mo** [comment]
Ok @bouweandela, we think #5941 may address this.
Can you easily retry this ?

**Comment by bouweandela** [comment]
Unfortunately it is still failing: https://github.com/SciTools/iris/actions/runs/9091807310/job/24987143460?pr=5926

**Comment by bouweandela** [comment]
Looks like it worked https://github.com/SciTools/iris/pull/5926#issuecomment-2111879384 now that I pulled in these changes from `main` :partying_face:
