### ISSUE TITLE
Holding space for memory benchmarking issues

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#5967]
Since #5960, #5959 , #5950  and especially #5948 
We are likely to get a few change warnings from memory benchmarks.

Doubtless some sensitivity changes may be needed, perhaps we'll have to turn off most of the memory benchmarking again.  But possibly also, it will need to "settle down" after recent changes ?
I think we should just routinely close these for a while, and later review as a set.

Issues referencing this one will be visible below ...

**Comment by trexfeathers** [comment]
If we feel we might benefit from repetitions, we could try writing our own benchmark class - ASV is designed for this and they are not as complex as I feared.

- [Developing benchmarks - asv_runner 0.2.0 documentation](https://asv.readthedocs.io/projects/asv-runner/en/latest/development/benchmark_plugins.html)
- [`asv_bench_memray`](https://github.com/HaoZeke/asv_bench_memray/tree/main) - an example of a custom benchmark plugin.
- [`asv_runner.benchmarks.time.TimeBenchmark`](https://github.com/airspeed-velocity/asv_runner/blob/9b7a26f8d24d91a0cf040b367d1a37f680f01bbd/asv_runner/benchmarks/time.py#L10) - an example of how repeats could be implemented.
