### ISSUE TITLE
Configurable colorbar in `iris.quickplot`

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#5970]
## ✨ Feature Request

I would like to be able to configure colorbar creation via kwargs in `iris.quickplot` functions.

## Motivation

If I want to customise a plot using `iris.quickplot`, I can modify every element after creating the plot EXCEPT the colorbar (due to how Matplotlib works).

**Comment by rcomer** [comment]
I think the work here is:

1. Add a `colorbar_kwargs` keyword to the [`_label` function](https://github.com/SciTools/iris/blob/3e1e80ecdb3784f25f4f2bc03bc8e0dbb0a1afa0/lib/iris/quickplot.py#L51), which is a dictionary of keywords to use in the [`colorbar` call](https://github.com/SciTools/iris/blob/3e1e80ecdb3784f25f4f2bc03bc8e0dbb0a1afa0/lib/iris/quickplot.py#L60-L62).  If "orientation" or "drawedges" is in that dictionary, they should override the current choices.

2. Do the "plumbing" to expose `colorbar_kwargs` in every public plotting function that ultimately calls `_label`.

3. Add tests.

**Comment by pp-mo** [comment]
I'm not quite sure of the exact scope or intention here, but I would probably oppose any additions to the quickplot api.
IMHO iris.quickplot is a quick + simple one-stop shop.  If you need more control, you should simply be using iris.plot instead.
If there is still a need for additional controls _there_, to do things which can't be done otherwise, then I'd say that is appropriate.

**Comment by trexfeathers** [comment]
From @SciTools/peloton:

We prefer the simpler solution of 1 new parameter: `colorbar`, which defaults to `True`. If the user wants a customised colorbar then they should use `False` then add their own after creating the plot.

**Comment by rcomer** [comment]
I think the work here is:

1. Add the boolean `colorbar` keyword to the [`_label` function](https://github.com/SciTools/iris/blob/3e1e80ecdb3784f25f4f2bc03bc8e0dbb0a1afa0/lib/iris/quickplot.py#L51), which controls whether the colorbar is added.

2. Do the "plumbing" to expose `colorbar` in every public plotting function that ultimately calls `_label`.

3. Add tests.

**Comment by ukmo-ccbunney** [comment]
Just so I understand the problem, I assume it is not enough to have a handle to the `colorbar` instance so you can adjust stuff? E.g.:
```
cm = qplt.pcolormesh(cube)
cb = cm.colorbar

# change ticks:
cb.set_ticks( [ ... ] )

# change position:
cb.ax.set_position([ ... ])
```

**Comment by trexfeathers** [comment]
>Just so I understand the problem, I assume it is not enough to have a handle to the `colorbar` instance so you can adjust stuff?

I have been led to understand that the problem is that it is not possible (at least not easy) to gain access to a `colorbar` that has already been added to the plot.

**Comment by rcomer** [comment]
Note that this came from discussion #5964, where the user had a whole dictionary of colorbar keywords they wanted to specify.

**Comment by ukmo-ccbunney** [comment]
> Note that this came from discussion #5964, where the user had a whole dictionary of colorbar keywords they wanted to specify. Unfortunately `Colorbar` is one of few Matplotlib objects that is not an `Artist` subclass, so is missing the [set](https://matplotlib.org/stable/api/_as_gen/matplotlib.artist.Artist.set.html#matplotlib.artist.Artist.set) method.

Thanks for the context @rcomer - that makes sense.
#6169 raised to address this.
