### ISSUE TITLE
Remove `GeoAxes` patch at next Cartopy release

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#5977]
## 📰 Custom Issue

SciTools/cartopy#2390

https://github.com/SciTools/iris/blob/57096f29f6f2c5ff278d616df5e2da4d2bab95e2/lib/iris/plot.py#L46-L60

**Comment by rcomer** [comment]
Cartopy 0.24 is now out.

**Comment by schlunma** [comment]
Hi!

With the release of cartopy 0.24 the current iris 3.10.0 package on conda-forge will throw the following exception when trying to plot a map:

```bash
TypeError: _GeoAxesPatched._draw_preprocess() missing 1 required positional argument: 'renderer' 
```

I could trace back this error to the piece of code that you mention here (i.e., removing it solves this error).

MRE:

```py
import matplotlib.pyplot as plt

import iris
import iris.quickplot as qplt

fname = iris.sample_data_path("air_temp.pp")
temperature_cube = iris.load_cube(fname)

# Draw the contour with 25 levels.
qplt.contourf(temperature_cube, 25)

# Add coastlines to the map created by contourf.
plt.gca().coastlines()

plt.show()
```

**Comment by rcomer** [comment]
Ah, that would be my fault again 😬 .  _renderer_ wasn't getting used in `_draw_preprocess` so we removed that at https://github.com/SciTools/cartopy/pull/2424

**Comment by valeriupredoi** [comment]
cheers, guys! We're gonna pin ESMValTool's `cartopy<0.24` right now, and will release a new build with it :+1:

**Comment by trexfeathers** [comment]
@pp-mo I currently have no intention of removing the patch at the next Cartopy release. Could you explain the re-opening? You mentioned to me offline that in several years' time we will probably have a minimum pin `>0.23`, but that's a long way off and I wouldn't want to use an issue to track something like that.

**Comment by pp-mo** [comment]
> @trexfeathers I currently have no intention of removing the patch at the next Cartopy release. Could you explain the re-opening? You mentioned to me offline that in several years' time we will probably have a minimum pin `>0.23`, but that's a long way off and I wouldn't want to use an issue to track something like that.

OK I get it, we don't have a way of scheduling this, so let's just leave it ther
