### ISSUE TITLE
Support numpy 2

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#6043]
We currently blocked this #6039 
An initial check for test failures uncovers quite a lot : #6035 

So, I'm creating this and assigning provisionally to the 3.11 release

Known issues to address (just a list for now):
  * [ ] scalars printing changes (e.g. "1" --> "np.int32(1)" visible for scalar coords in doc-tests

**Comment by valeriupredoi** [comment]
does this still hold for 3.11 release, folks? [proceeding to biting all my nails and hoping this will indeed]

**Comment by ESadek-MO** [comment]
HI, yes, this is still planned for 3.11, which should come late October, Early November God willing.

**Comment by valeriupredoi** [comment]
cheers, Elias :crossed_fingers:
