### ISSUE TITLE
Cube merge loads NetCDF deferred auxiliary coordinates.

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#608]
Iris implements deferred loading of auxiliary coordinates payload via the NetCDF loader via a `LazyArray`.

This is in response to large multi-dimensional auxiliary coordinates causing a large memory footprint. Loading many such cubes can easily exhaust the available RAM for a process.

At the moment cube merge has no concept of such deferred auxiliary coordinates. As such, cube merge loads the payload of the deferred auxiliary coordinates, thus negating all benefit of such deferred loading.

The only workaround at the moment is to use `iris.load_raw` as this circumvents the merge process. This is a valid step to take in the majority of times, as NetCDF sourced cubes tend to be complete multi-dimensional entities i.e. non-mergeable.

We require to extend cube merge to recognise such deferred auxiliary coordinates and not realise the payload.

**Comment by pelson** [comment]
Pretty certain we have this capability now. Closing this out.
