### ISSUE TITLE
unexpected and undocumented behaviour in dim coord assoc.

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#609]
``` Python
        if not matches:
            matches = [(dim,) for coord_, dim in self._dim_coords_and_dims if
                       coord_.name() == coord.name()]

        # Search aux coords
        if not matches:
            matches = [dims for coord_, dims in self._aux_coords_and_dims if
                       coord_.name() == coord.name()]
```

https://github.com/SciTools/iris/blob/master/lib/iris/cube.py#L791

Currently we are looking at whether the given coord shares its name with a coordinate on the cube.  I really dont think this belongs in coord_dims at all and may result in unexpected results to users.

**Effected tests:**
test_contrived_differential1 (iris.tests.test_analysis_calculus.TestCalculusWKnownSolutions)
test_contrived_spherical_curl1 (iris.tests.test_analysis_calculus.TestCalculusWKnownSolutions)
test_contrived_sphrical_curl2 (iris.tests.test_analysis_calculus.TestCalculusWKnownSolutions)

Since this is not documented, I would at the very least label it as a **bug**, further more, the test failures based on its removal require investigation, determining why its necessary.

Happy to look into this myself when I have time.

**Comment by rcomer** [comment]
No idea when they were removed, but those name matching lines are no longer present.
