### ISSUE TITLE
issue with iris all shader not loading

### ISSUE THREAD

**Issue by StonesRus** [SciTools/iris#6221]
## How To Reproduce
Steps to reproduce the behaviour:

1. honestly not sure every person on this one server was having the same issue
2. 
3. 

## Expected behaviour
I expected the shaders to load after changing them and the system said iris issue with all shaders consecutively I tried to load.

## Screenshots
![2024-11-06_20 22 00](https://github.com/user-attachments/assets/53bf087c-a620-4c67-97a7-cb641d18e392)

## Environment 
no idea honestly sorry probably newest?
## Additional context
Shader compilation failed, see log for details
is what the info said to copy

```
Please add additional verbose information in this section e.g., code, output, tracebacks, screenshots etc
```
</details>

**Comment by rcomer** [comment]
Hi @StonesRus I think you might have the wrong Iris repo.  This one is a python package for analysing weather and climate data.  Perhaps you want https://github.com/IrisShaders/Iris instead?

**Comment by trexfeathers** [comment]
Our second ever Minecraft issue! 🎉

Also kudos for attempting to fit your bug report into our structure.
