### ISSUE TITLE
grib2 tables version 7

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#683]
Update GRIB2 saving to use a more recent tables version.

Ideally, in `grib_save_rules.run()`:

```
    # Use tables version 7 (May 2011), as found in api 1.9.16 (May 2012).
    # The default GRIB2 template uses version 4 (Nov 2007).
    gribapi.grib_set_long(grib, "tablesVersion", 7)
```

Note, this causes a grib api assertion failure.

**Comment by dkillick** [comment]
Ported to `iris-grib`, where this issue now best belongs.

**Comment by pp-mo** [comment]
> Ported to iris-grib,

https://github.com/SciTools/iris-grib/issues/118
