### ISSUE TITLE
coord_comparison bug

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#717]
```coord_comparison``` fails when the two input cubes share a coord.
Duplicating the coord stops the failure, but I think this is a bug and should be fixed.

```
altitude = DimCoord(...)
u.remove_coord("pressure")
v.remove_coord("pressure")
u.add_aux_coord(altitude, 1)
#v.add_aux_coord(altitude, 1)  # FAILS
v.add_aux_coord(altitude.copy(), 1)

result = iris.analysis.calculus.curl(u, v)
```

The above snippet fails is on [this line] (https://github.com/SciTools/iris/blob/master/lib/iris/analysis/calculus.py#L452) in _analysis.calculus.curl_:
```if bad_coords:```

I believe the problem is caused by [this line] (https://github.com/SciTools/iris/blob/master/lib/iris/analysis/__init__.py#L191) in _analysis.compare_coords_:
```if (id(other_coord) not in processed_coords```

**Comment by marqh** [comment]
an enhancement would be needed in order for coordiantes to be shared between cubes without this kind of consequence.

This would have to be driven by a particular need
