### ISSUE TITLE
Support for most commonly used Ocean Dimensionless Vertical Coordinates

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#762]
Now that there is a PR for  `ocean_sigma_z_coordinate`, it would be great to have support for the other commonly used Ocean Dimensionless Vertical Coordinates.  IMHO, these are `ocean_sigma`, `ocean_s_coordinate`, `ocean_s_coordinate_g1` and `ocean_s_coordinate_g2`.   Here are some example datasets for testing these:
### OPeNDAP DATA URLS (open these in Iris instead of local NetCDF file name)
- ocean_s_coordinate: http://geoport.whoi.edu/thredds/dodsC/examples/bora_feb.nc
- ocean_sigma:  http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/z_coord/ocean_sigma.nc
- ocean_s_coordinate: http://geoport.whoi.edu/thredds/dodsC/examples/bora_feb.nc
- ocean_s_coordinate_g1: http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/z_coord/ocean_s_coordinate_g1.nc
- ocean_s_coordinate_g2: http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/z_coord/ocean_s_coordinate_g2.nc

Thanks so much for the consideration!

**Comment by ocefpaf** [comment]
We added a workaround (https://github.com/SciTools/iris/pull/1485) many years ago for this. So I guess this one can be closed. Full support for staggered grids is still desirable though.

**Comment by ocefpaf** [comment]
For those who believe that bots will rule the world remember, it took it 5 years to catch up with my comment 😜

**Comment by rcomer** [comment]
It seems that in 5 years nobody has objected to 

>  I guess this one can be closed

So,,,
