### ISSUE TITLE
bbox extract

### ISSUE THREAD

**Issue by isedwards** [SciTools/iris#77]
This ticket proposes an enhancement to allow a region to be extracted by specifying a bounding box.

Currently, users may attempt to extract a region from a global dataset using constraints:

``` python
latc = iris.Constraint(latitude=lambda cell: minlat <= cell <= maxlat)
lonc = iris.Constraint(longitude=lambda cell: minlon <= cell <= maxlon)
region = cube.extract(latc & lonc)
```

However, the output will retain the circular property, which they would have to change manually:
`region.coord('longitude').circular = False`

**Comment by ajdawson** [comment]
The `Cube.intersection` method seems to cover the requirements set out here, closing.
