### ISSUE TITLE
Extending concatenate to handle dim coord of len 1 with others of len > 1

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#775]
Currently concatenate doesn't make any assumption for the case where we have a dimension coordinate of length 1 for one cube and a dimension coordinate of length > 1 for another.  Handling this has the following complexity (assume every other detail about these cubes are suitable for concatenation other than the order):

``` Python
cube1 / (unknown) (time: 1)
Time is neither an increasing or decreasing coordinate.

cube2 / (unknown) (time: 10)
Time is increasing

cube3 / (unknown) (time: 10)
Time is decreasing
```

Concatenating the three, which should cube1 be concatenated to? (rhetorical question) neither in this case, since we cannot know which the user intends.  However in some cases I believe we can make an assumption:

``` Python
cube1 / (unknown) (time: 1)
Time is neither an increasing or decreasing coordinate.

cube2 / (unknown) (time: 10)
Time is increasing
```

Clearly we can still concatenate cube1 with cube2 now (since there are only these two cubes).

Id like to work on this possible enhancement myself as I have already looked into concatenate to an extent in determining the above.

**Assigned: @cpelley**
_Internal ref: 54760_

**Comment by stephenworsley** [comment]
I believe this has already been fixed by #2022 so this can be closed.
