### ISSUE TITLE
save cube in TransverseMercator to grib2

### ISSUE THREAD

**Issue by wideblue** [SciTools/iris#819]
When trying to save cube in Transverse Mercator  coordinat system into grib2 I get the following error 

`Traceback (most recent call last):
  File "/home/damjan/testGribWrite.py", line 46, in <module>
    iris.fileformats.grib.save_grib2(cubes[0],'/home/damjan/Namizje/apr1km.grib2')
  File "/usr/local/lib/python2.7/dist-packages/Iris-1.5.1-py2.7-linux-i686.egg/iris/fileformats/grib/__init__.py", line 706, in save_grib2
    raise TranslationError("Did not find one (and only one) "
iris.exceptions.TranslationError: Did not find one (and only one) latitude or longitude coord`

It seems that save_grib2 expects lat/long coordinates and doesn't  realise that it should save Transverse Mercator  coordinat system. I'm not completely sure if this is an issue or saving a cube in TransverseMercator to grib2 is not supported or I have to set something up before saving.

**Comment by bjlittle** [comment]
We've scheduled to have an `iris-grib` development sprint quite soon, and this is one of the use cases that we know we need to address.

Ping @dkillick and @pp-mo.

**Comment by wideblue** [comment]
Ok, I saw no activiti on this and tought it would be best to close it.  It's good to know there are plans for this issue.

**Comment by dkillick** [comment]
We now have support for saving to Transverse Mercator in `iris-grib`: https://github.com/SciTools/iris-grib/blob/master/iris_grib/_save_rules.py#L500. This was actually added in Iris at #1477 (before we split the GRIB handling code out into its own library).

@wideblue would you mind checking if this now does indeed work for you? It would be good to tidy up this issue. Thanks!

**Comment by pp-mo** [comment]
No reply, so I guess this is done.
