### ISSUE TITLE
Stop concatenate using all memory

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#850]
Does iris.cube.CubeList.concatenate() need to load the data payload? If it can be changed so that it doesn't then this would be very useful. If not, then it would be good if a safeguard could be added to abort the concatenate when the memory usage is getting critically high. You don't know before you perform a cat if iris will swallow 100% of the memory, leading to a very messy and painful abort for the user.

**Comment by ajdawson** [comment]
This one is fixed in v1.8.0, `concatenate()` no longer loads the data payload.
