### ISSUE TITLE
nosetests ignoring _xxx test directories

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#938]
See https://github.com/SciTools/iris/pull/937 ...

There is a problem with testing at present, as nosetests (and therefore 'setup.py test') ignores any directories that start with underscores.

This doesn't play nicely with our unit-test naming scheme.

[This issue](http://code.google.com/p/python-nose/issues/detail?id=82) indicates that this was once hard-wired, but it should now be possible to get around it

I thought  --match key might help, from "nosetests -h"

```
-m REGEX, --match=REGEX, --testmatch=REGEX
                        Files, directories, function names, and class names that match this regular expression are considered
                        tests.  Default: (?:^|[\b_\./-])[Tt]est [NOSE_TESTMATCH]
```

**BUT** I can't see how that works, as test-module directories will _not_ have '[Tt]test' in the name ??

**Comment by marqh** [comment]
@rhattersley ping

**Comment by pelson** [comment]
We currently take the path of not having underscores in names in our test folders. Not pretty, but is pragmatic.
