### ISSUE TITLE
Iris cubes and coordinates are both mutable and hashable

### ISSUE THREAD

**Issue by shoyer** [SciTools/iris#962]
This break Python conventions and thus is likely to lead to unexpected behavior.

This is especially problematic because these objects also implement their own `__eq__` method, and thus hashes for equal objects are not necessary equal.

For an overview, read the answers on this StackOverflow question:
http://stackoverflow.com/questions/2671376/hashable-immutable

Since it's unlikely that cubes or coords can be made entirely immutable, my suggested fix is to add `__hash__ = None` to both `Coord` and `Cube`.

**Comment by rhattersley** [comment]
:+1:

**Comment by pelson** [comment]
Got done in #1772 I believe.

**Comment by djkirkham** [comment]
It's still an issue. For Coords, `__eq__` is based on mutable properties of the object, which implies they shouldn't be hash-able. Unless we make Coords immutable, we shouldn't really be using them in sets or as dictionary keys.
